### ISSUE TITLE
Change to stack size breaks some unittests.

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#100]
Summary: 16 MB stack limit makes 2 unittests fail. Rick has investigated this, and I am summarizing his conclusions here. 

Back in August, Dusan found that stack limit was causing a mips64 webkit test to fail on the simulator. After some discussion we changed the stack limit for all buildbot jobs from 'ulimit -s 8192' (8MB) to 16384 (16MB).

Slack discussion here.
https://v8m.slack.com/archives/buildbot/p1409321067000074

Per that discussion, it was not easy to change this limit for just the mips64 simulator. I had intended to discuss the possible side-effects of this change with Dusan, but I failed to do so.

I had a general concern that us testing differently than Google does might bite us. Well, yes it did.

These 2 tests fail with timeouts:

unittests/ConditionVariable.MultipleThreadsWithSeparateConditionVariables
unittests/ConditionVariable.MultipleThreadsWithSharedSeparateConditionVariables

They get locked on a mutex, but the underlying failure reason is a pthread_create() returns a failure, for lack of resources, presumably out of memory. If the stack limit is set to 8MB, the tests pass. I believe that setting to even 15MB the tests pass.

Rick, please fill in additional relevant details.

Also, please set the stack limit to 8MB, run the webkit tests in mips64-simulator, and identify the specific failing webkit tests in this issue.

**Comment by kwan0xfff** [comment]
I managed to copy a completed "Sim - MIPS64 - edge - webkit" build (1414) to a separate directory. It succeeded with 16 MB stack and failed with 8 MB stack ("ulimit -s <stacksize_k>").  All of them deal with "webkit/reentrant-caching".  Specific failures:
1. webkit/reentrant-caching
   Command: /export/rkwan-target/build/slave/v8-linux-mips64el-sim-edge-webkit/build/v8/out/Release/d8 --test --random-seed=506791341 --stress-opt --always-opt --nohard-abort --nodead-code-elimination --nofold-constants /export/rkwan-target/build/slave/v8-linux-mips64el-sim-edge-webkit/build/v8/test/webkit/resources/standalone-pre.js /export/rkwan-target/build/slave/v8-linux-mips64el-sim-edge-webkit/build/v8/test/webkit/reentrant-caching.js /export/rkwan-target/build/slave/v8-linux-mips64el-sim-edge-webkit/build/v8/test/webkit/resources/standalone-post.js
   exit code: -11 (crashed)
2. webkit/reentrant-caching:
   Command: /export/rkwan-target/build/slave/v8-linux-mips64el-sim-edge-webkit/build/v8/out/Release/d8 --test --random-seed=506791341 --nocrankshaft --nohard-abort --nodead-code-elimination --nofold-constants /export/rkwan-target/build/slave/v8-linux-mips64el-sim-edge-webkit/build/v8/test/webkit/resources/standalone-pre.js /export/rkwan-target/build/slave/v8-linux-mips64el-sim-edge-webkit/build/v8/test/webkit/reentrant-caching.js /export/rkwan-target/build/slave/v8-linux-mips64el-sim-edge-webkit/build/v8/test/webkit/resources/standalone-post.js
   exit code: -11 (crashed)
3. webkit/reentrant-caching:
   Command: /export/rkwan-target/build/slave/v8-linux-mips64el-sim-edge-webkit/build/v8/out/Release/d8 --test --random-seed=506791341 --turbo-asm --turbo-filter=\* --always-opt --nohard-abort --nodead-code-elimination --nofold-constants /export/rkwan-target/build/slave/v8-linux-mips64el-sim-edge-webkit/build/v8/test/webkit/resources/standalone-pre.js /export/rkwan-target/build/slave/v8-linux-mips64el-sim-edge-webkit/build/v8/test/webkit/reentrant-caching.js /export/rkwan-target/build/slave/v8-linux-mips64el-sim-edge-webkit/build/v8/test/webkit/resources/standalone-post.js
   exit code: -11 (crashed)
4. webkit/reentrant-caching:
   Command: /export/rkwan-target/build/slave/v8-linux-mips64el-sim-edge-webkit/build/v8/out/Release/d8 --test --random-seed=506791341 --nohard-abort --nodead-code-elimination --nofold-constants /export/rkwan-target/build/slave/v8-linux-mips64el-sim-edge-webkit/build/v8/test/webkit/resources/standalone-pre.js /export/rkwan-target/build/slave/v8-linux-mips64el-sim-edge-webkit/build/v8/test/webkit/reentrant-caching.js /export/rkwan-target/build/slave/v8-linux-mips64el-sim-edge-webkit/build/v8/test/webkit/resources/standalone-post.js
   exit code: -11 (crashed)

I'll see in next post about removing redundant paths.

**Comment by kwan0xfff** [comment]
I can reduce the first test above to:
$ cd <...path...>/build/v8
$ ./out/Release/d8 --test --random-seed=506791341 --stress-opt --always-opt --nohard-abort --nodead-code-elimination --nofold-constants ./test/webkit/resources/standalone-pre.js ./test/webkit/reentrant-caching.js ./test/webkit/resources/standalone-post.js

The test succeeds when "ulimit -s" is set to 16384, 12880, 10240.  But it fails at 9216.

If I run the original command at "ulimit -s 10240", the whole thing succeeds.  That is:
$ python tools/run-tests.py --verbose --buildbot --outdir=out --arch=mips64el --mode=Release webkit --timeout=1800

**Comment by kwan0xfff** [comment]
Target boards (not sims) in the farm have been set to use 10240K rather than 16384K. Hopefully, unittests start to work, and webkit doesn't start to fail.

**Comment by kwan0xfff** [comment]
Unittests seems to be succeeding, e.g.,
https://dmz-portal.mips.com/bbv8/builders/Target%20-%20edge/builds/2990/steps/Unittests/logs/stdio
although the "Target - edge" test later fails on Check step (separate issue). Similarly, webkit on simulators are still succeeding.
