### ISSUE TITLE
threading3 test fail on big-endian mips hw on google bot.

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#109]
On the google bots, the 2nd mips eb builder keeps failing threading3 test.
http://build.chromium.org/p/client.v8/builders/V8%20Mips%20-%20big%20endian%20-%20nosnap%20-%202/builds/38
http://build.chromium.org/p/client.v8/builders/V8%20Mips%20-%20big%20endian%20-%20nosnap%20-%202/builds/37
http://build.chromium.org/p/client.v8/builders/V8%20Mips%20-%20big%20endian%20-%20nosnap%20-%202/builds/36
http://build.chromium.org/p/client.v8/builders/V8%20Mips%20-%20big%20endian%20-%20nosnap%20-%202/builds/34
more ...

```
# Fatal error in ../test/cctest/test-api.cc, line 7602
# CHECK(object_a.flag) failed
```

I've not noticed this fail on our EB tester, maybe start by carefully checking the google bot to see if there is any mis-config.

**Comment by paul99** [comment]
Oops, also copy @dusmil, @petar-jovanovic

**Comment by svetozar-janjic** [comment]
I have tried to reproduce the Threding3 failure on our ER8-PRO and Cavium board, but Threading3 pass all both target, debug or release mode, also with static and shared library options. I didn't see that google bots use some different enviroment then usually.

**Comment by paul99** [comment]
Is your er8 board set up with kernel and rfs per the v8m-r wiki page for that board?

Are you running -j2?

Are you running without snapshots, as Google does?

Another thought - they are sharding tests across 2 boards. That would mean the rest running on the other cpu while threading3 runs would likely be different. And threading3 is a long running test, and the tester runs long running tests first, so it might always be the same test pair. (Yes, I am really reaching on this scenario! :)

No idea how to easily check this, though

**Comment by paul99** [comment]
I did put threading3 on skip list for test runner (https://github.com/paul99/v8mips/commit/4641d93f89a813859251a0202f767f424db64e1e), and that builder seems to always pass now.

**Comment by svetozar-janjic** [comment]
I got the information that we are using the kernel set up by wiki instructions, but rfs is changed. I will setup the board per wiki instructions and try once again.

Yes I was running with -j2, and without snapshots as Google does.

Currently we have only one er8pro board, so we can't run the tests with sharing option.

**Comment by svetozar-janjic** [comment]
Today, I have run the tests on er8pro board with RFS suggested on Wiki page, Threading3 test passed in release and debug mode, with -j1, -j2... -j5. Probably we will need another board and sharding scenario to reproduce the bug.

**Comment by paul99** [comment]
This issue is still valid, Threading3 is still on the skip list. We should reopen investigation, and re-test. Assigning to Ivica.

**Comment by mkaric** [comment]
I managed to get this test to fail on simulator for mips, mipsel and ia32 with the same error message. Logs are missing so I couldn't get the command used on bots but using this command I got the test to fail consistently:

```
out/mips.debug/cctest --nocrankshaft test-api/Threading3 --nobreak-on-abort --nodead-code-elimination --nofold-constants --enable-slow-asserts --debug-code --verify-heap --testing_serialization_file=out/.serdes/serdes_Threading3__nocrankshaft --gc-interval 50 --stress-compaction
```

It seems this failure is not specific to mips.

**Comment by ibogosavljevic** [comment]
Threading3 has been passing on the board for a very long time: https://build.chromium.org/p/client.v8.ports/builders/V8%20Mips%20-%20big%20endian%20-%20nosnap%20-%201/builds/5090/steps/Check/logs/stdio

Issue closed
