### ISSUE TITLE
Set up Debian chroot on Lemote 6100 

### ISSUE THREAD

**Issue by kisg** [v8mips/v8mips#112]
Please set up a Debian chroot on the 6100 and document the process in the wiki.

**Comment by paul99** [comment]
any update on this?

**Comment by kisg** [comment]
I have set up the root fs on our NFS server, but it looks like the lemote 6100 has frozen. I will restart it and finish setup tomorrow morning.

**Comment by paul99** [comment]
Any update here? Can we close this?

**Comment by paul99** [comment]
Closed due to no response, and that we have much alternative 64-bit platforms now.
