### ISSUE TITLE
sin-cos.js occasionally crashes in simulator

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#114]
I first saw this on build #1442 on Google's bot here: http://build.chromium.org/p/client.v8/builders/V8%20Linux%20-%20mips%20-%20sim

I built it locally, mipsel.release (all default build params) at commit 96143d19314 from Dec 24, and it will fail if run enough times:

```
 Iteration 9
============ Stress 1/5 ============
============ Stress 2/5 ============
============ Stress 3/5 ============
============ Stress 4/5 ============
============ Stress 5/5 ============
Memory write to bad address: 0x00000021, pc=0x25f4ef40
  0x25f4ef40  acc70007       sw      a3, 7(a2)
sim> 
```

So far, it has failed at iterations 23, 9, 200, and 792 when run in a loop. (so be patient :-)

@dusmil, @svetozar-janjic, can you guys please take a look at this one?

**Comment by dusmil** [comment]
I have been investigating the failure, and it look like it is GC related or we have classic register clobbering.
Svetozar is doing bisect to find out when the bug is introduced. In the meantime I am looking through the code and recent mips specific Cls
.

**Comment by svetozar-janjic** [comment]
The commit 76aab824fe257c422bd90273e241315400fc161c has introduced the bug. I have run sin-cos test, with previous commit 70eb456e731ce01c2aa2203d8a6ea459fa8b41ba, over 1000 times in loop and test passed every time.

So, I think that this hydrogen change side effects the cause of sin-cos failing.

**Comment by dusmil** [comment]
The issue has been resolved  recently in e1d878d1. I confirmed and verified the fix.
A bug in type tracking mechanism is dangerous thing.

Also we should pay attention to 028ff214, it might significant for mips64.

**Comment by paul99** [comment]
@dusmil - I do not think this is fixed. Please see today's builds on google bots, builds

http://build.chromium.org/p/client.v8/builders/V8%20Linux%20-%20mips%20-%20sim/builds/1585
http://build.chromium.org/p/client.v8/builders/V8%20Linux%20-%20mips%20-%20sim/builds/1592

failed for sin-cos error. It does seem to be a flake ....

**Comment by dusmil** [comment]
Yes, the bug  is back I checked top of tree. At commit e1d878d1 I could not reproduce it  few days ago.  Apparently, the root cause is something else, the bug is temporary  covered. Now it emerges again.

**Comment by dusmil** [comment]
Main cause of random crashes found and fixed.
https://codereview.chromium.org/865153002/
There is one more problem that is different issue, now occasionally we lose precision on sin().

**Comment by dusmil** [comment]
Failure rate of precision loss is dramatically low, less than 1%, Therefore I was forced to work on older version at commit number: 159b141 in order to have some chance to catch failure.
I have managed to get input values for which sin() losses precision. Interestingly failure occurs always on same input value.

```
x= -7.955449482895784
Math.sin = -0.9948565530496416
err_sin = 62320268.183210485
============ Stress 4/5 ============
test/mjsunit/mjsunit.js:178: Failure: expected <true> found <false>
    throw new MjsUnitAssertionError(message);
          ^
Error
    at new MjsUnitAssertionError (test/mjsunit/mjsunit.js:31:16)
    at fail (test/mjsunit/mjsunit.js:178:11)
    at assertEquals (test/mjsunit/mjsunit.js:248:7)
    at assertTrue (test/mjsunit/mjsunit.js:293:5)
    at assertEqualsDelta (test/mjsunit/mjsunit.js:256:43)
    at test/mjsunit/sin-cos.js:139:24

   # test iteration 110
```

I can only print one value at time, otherwise the failure does not happened
Err_sin value obtained by abs_error function which return absolute value of difference between referent sin() function in test and Math,sin().

The gathered data indicates that wrong value is returned by abs function or referent sin function for given x calculates wrong value considering Math.sin return correct value.
Still cannot make connection between losing precision and random behavior.

**Comment by dusmil** [comment]
One more thing the common sources of randomness as concurrent-recompilation concurrent-osr, code-aging, concurrent-sweeping are eliminated as cause.

**Comment by dusmil** [comment]
The bug is history.
Fixed in: https://codereview.chromium.org/885923004/

**Comment by paul99** [comment]
Nice find! I'd like to hear about the debug process that let you find this error. Closing.
