### ISSUE TITLE
RunFloat64Ceil, RunFloat64Floor and RunFloat64RoundTruncate failing on Popcorn Hour boards but not Edge Router Pro boards

### ISSUE THREAD

**Issue by MIPSbkirby** [v8mips/v8mips#115]
Initial bug letting people know that these tests are failing on the Popcorn Hour boards.  I'll be collecting more information and adding it to the bug as I get it.

**Comment by paul99** [comment]
Brendan, I suspect that the errors were introduced with 8c4b7d272ac7, December 22, 2014 at 9:37:20 AM PST, Cr-Commit-Position: refs/heads/master@{#25931}

Can you check the BB logs to see if that is when they first showed up?

As we discussed, er8 boards (no FPU, all kernel FPU emulator) do _not_ show any errors. Popcorn boards do show, but not consistently. Could this be the same bogus mthc1 failure as in https://github.com/paul99/v8m-rb/issues/102?

However, this code uses Mthc1() macro, which should emit only mtc1() instruction on this board in 32-bit FP mode.

Brendan, can you please test this on mipsswbrd030 which is single core with FPU? We should not have any possibility of FPU emulation there.

**Comment by paul99** [comment]
Also note that math-floor & math-ceil fail on popcorn board, presumably from the same change.

**Comment by MIPSbkirby** [comment]
### Notes on the failures

Looking at the results of these tests including the math-floor and math-ceil test failures on three different builds, I'm just seeing that they are all "CRASH" failures and exit with -4.  Also, the tests results are flaky.  They fail sometimes and pass other times.  There's usually no output from the tests and only math-floor and math-ceil have output.  The output usually looks something like:

> ============ Stress 1/5 ============
> ============ Stress 2/5 ============
> ============ Stress 3/5 ============
> ============ Stress 4/5 ============
> ============ Stress 5/5 ============
> ======== Full Deoptimization =======

### Example commands to run the tests

I've removed commands that the only difference was the number passed to the random-seed option.  

#### RunFloat64Ceil

```
out/Release/cctest --random-seed=1720039638 test-run-machops/RunFloat64Ceil --nohard-abort --nodead-code-elimination --nofold-constants --testing_serialization_file=out/.serdes/serdes_RunFloat64Ceil
out/Release/cctest --random-seed=1721302457 --nocrankshaft test-run-machops/RunFloat64Ceil --nohard-abort --nodead-code-elimination --nofold-constants --testing_serialization_file=out/.serdes/serdes_RunFloat64Ceil__nocrankshaft
out/Release/cctest --random-seed=83550798 --turbo-asm --turbo-filter=* --always-opt test-run-machops/RunFloat64Ceil --nohard-abort --nodead-code-elimination --nofold-constants --testing_serialization_file=out/.serdes/serdes_RunFloat64Ceil__turbo_asm__turbo_filter=*__always_opt
```

#### RunFloat64Floor

```
out/Release/cctest --random-seed=1720039638 test-run-machops/RunFloat64Floor --nohard-abort --nodead-code-elimination --nofold-constants --testing_serialization_file=out/.serdes/serdes_RunFloat64Floor
out/Release/cctest --random-seed=1720039638 --stress-opt --always-opt test-run-machops/RunFloat64Floor --nohard-abort --nodead-code-elimination --nofold-constants --testing_serialization_file=out/.serdes/serdes_RunFloat64Floor__stress_opt__always_opt
out/Release/cctest --random-seed=1721302457 --nocrankshaft test-run-machops/RunFloat64Floor --nohard-abort --nodead-code-elimination --nofold-constants --testing_serialization_file=out/.serdes/serdes_RunFloat64Floor__nocrankshaft
out/Release/cctest --random-seed=83550798 --turbo-asm --turbo-filter=* --always-opt test-run-machops/RunFloat64Floor --nohard-abort --nodead-code-elimination --nofold-constants --testing_serialization_file=out/.serdes/serdes_RunFloat64Floor__turbo_asm__turbo_filter=*__always_opt
```

#### RunFloat64RoundTruncate

```
out/Release/cctest --random-seed=1720039638 test-run-machops/RunFloat64RoundTruncate --nohard-abort --nodead-code-elimination --nofold-constants --testing_serialization_file=out/.serdes/serdes_RunFloat64RoundTruncate
out/Release/cctest --random-seed=1720039638 --stress-opt --always-opt test-run-machops/RunFloat64RoundTruncate --nohard-abort --nodead-code-elimination --nofold-constants --testing_serialization_file=out/.serdes/serdes_RunFloat64RoundTruncate__stress_opt__always_opt
out/Release/cctest --random-seed=1721302457 --nocrankshaft test-run-machops/RunFloat64RoundTruncate --nohard-abort --nodead-code-elimination --nofold-constants --testing_serialization_file=out/.serdes/serdes_RunFloat64RoundTruncate__nocrankshaft
```

#### math-ceil

```
out/Release/d8 --test --random-seed=1720039638 --stress-opt --always-opt --nohard-abort --nodead-code-elimination --nofold-constants test/mjsunit/mjsunit.js test/mjsunit/asm/math-ceil.js
out/Release/d8 --test --random-seed=83550798 --nohard-abort --nodead-code-elimination --nofold-constants test/mjsunit/mjsunit.js test/mjsunit/asm/math-ceil.js
```

#### math-floor

```
out/Release/d8 --test --random-seed=1720039638 --nocrankshaft --nohard-abort --nodead-code-elimination --nofold-constants test/mjsunit/mjsunit.js test/mjsunit/asm/math-floor.js
out/Release/d8 --test --random-seed=1721302457 --turbo-asm --turbo-filter=* --always-opt --nohard-abort --nodead-code-elimination --nofold-constants test/mjsunit/mjsunit.js test/mjsunit/asm/math-floor.js
out/Release/d8 --test --random-seed=83550798 --stress-opt --always-opt --nohard-abort --nodead-code-elimination --nofold-constants test/mjsunit/mjsunit.js test/mjsunit/asm/math-floor.js
out/Release/d8 --test --random-seed=83550798 --nohard-abort --nodead-code-elimination --nofold-constants test/mjsunit/mjsunit.js test/mjsunit/asm/math-floor.js
```

**Comment by MIPSbkirby** [comment]
Manually running the commands on Popcorn Hour board 3 (mipsswbrd013) shows that some of the commands failing with an `Illegal instruction` message.  The board currently has no load and no testing running.  All of the `cctest` commands fail with an `Illegal instruction` and most of the `d8` commands pass.  

Since this is probably related to floating point, the `taskset` command was used to force the test onto a specific core.  Doing this causes all the tests to pass if on a core with an FPU or FAIL if run on a core without one.  

Commands to cause all the tests to pass:

```
taskset 0x1 out/Release/cctest --random-seed=1720039638 test-run-machops/RunFloat64Ceil --nohard-abort --nodead-code-elimination --nofold-constants --testing_serialization_file=out/.serdes/serdes_RunFloat64Ceil
taskset 0x1 out/Release/cctest --random-seed=1721302457 --nocrankshaft test-run-machops/RunFloat64Ceil --nohard-abort --nodead-code-elimination --nofold-constants --testing_serialization_file=out/.serdes/serdes_RunFloat64Ceil__nocrankshaft
taskset 0x1 out/Release/cctest --random-seed=83550798 --turbo-asm --turbo-filter=* --always-opt test-run-machops/RunFloat64Ceil --nohard-abort --nodead-code-elimination --nofold-constants --testing_serialization_file=out/.serdes/serdes_RunFloat64Ceil__turbo_asm__turbo_filter=*__always_opt
taskset 0x1 out/Release/cctest --random-seed=1720039638 test-run-machops/RunFloat64Floor --nohard-abort --nodead-code-elimination --nofold-constants --testing_serialization_file=out/.serdes/serdes_RunFloat64Floor
taskset 0x1 out/Release/cctest --random-seed=1720039638 --stress-opt --always-opt test-run-machops/RunFloat64Floor --nohard-abort --nodead-code-elimination --nofold-constants --testing_serialization_file=out/.serdes/serdes_RunFloat64Floor__stress_opt__always_opt
taskset 0x1 out/Release/cctest --random-seed=1721302457 --nocrankshaft test-run-machops/RunFloat64Floor --nohard-abort --nodead-code-elimination --nofold-constants --testing_serialization_file=out/.serdes/serdes_RunFloat64Floor__nocrankshaft
taskset 0x1 out/Release/cctest --random-seed=83550798 --turbo-asm --turbo-filter=* --always-opt test-run-machops/RunFloat64Floor --nohard-abort --nodead-code-elimination --nofold-constants --testing_serialization_file=out/.serdes/serdes_RunFloat64Floor__turbo_asm__turbo_filter=*__always_opt
taskset 0x1 out/Release/cctest --random-seed=1720039638 test-run-machops/RunFloat64RoundTruncate --nohard-abort --nodead-code-elimination --nofold-constants --testing_serialization_file=out/.serdes/serdes_RunFloat64RoundTruncate
taskset 0x1 out/Release/cctest --random-seed=1720039638 --stress-opt --always-opt test-run-machops/RunFloat64RoundTruncate --nohard-abort --nodead-code-elimination --nofold-constants --testing_serialization_file=out/.serdes/serdes_RunFloat64RoundTruncate__stress_opt__always_opt
taskset 0x1 out/Release/cctest --random-seed=1721302457 --nocrankshaft test-run-machops/RunFloat64RoundTruncate --nohard-abort --nodead-code-elimination --nofold-constants --testing_serialization_file=out/.serdes/serdes_RunFloat64RoundTruncate__nocrankshaft
taskset 0x1 out/Release/d8 --test --random-seed=1720039638 --stress-opt --always-opt --nohard-abort --nodead-code-elimination --nofold-constants test/mjsunit/mjsunit.js test/mjsunit/asm/math-ceil.js
taskset 0x1 out/Release/d8 --test --random-seed=83550798 --nohard-abort --nodead-code-elimination --nofold-constants test/mjsunit/mjsunit.js test/mjsunit/asm/math-ceil.js
taskset 0x1 out/Release/d8 --test --random-seed=1720039638 --nocrankshaft --nohard-abort --nodead-code-elimination --nofold-constants test/mjsunit/mjsunit.js test/mjsunit/asm/math-floor.js
taskset 0x1 out/Release/d8 --test --random-seed=1721302457 --turbo-asm --turbo-filter=* --always-opt --nohard-abort --nodead-code-elimination --nofold-constants test/mjsunit/mjsunit.js test/mjsunit/asm/math-floor.js
taskset 0x1 out/Release/d8 --test --random-seed=83550798 --stress-opt --always-opt --nohard-abort --nodead-code-elimination --nofold-constants test/mjsunit/mjsunit.js test/mjsunit/asm/math-floor.js
taskset 0x1 out/Release/d8 --test --random-seed=83550798 --nohard-abort --nodead-code-elimination --nofold-constants test/mjsunit/mjsunit.js test/mjsunit/asm/math-floor.js
```

Commands to cause all the tests to fail:

```
taskset 0x2 out/Release/cctest --random-seed=1720039638 test-run-machops/RunFloat64Ceil --nohard-abort --nodead-code-elimination --nofold-constants --testing_serialization_file=out/.serdes/serdes_RunFloat64Ceil
taskset 0x2 out/Release/cctest --random-seed=1721302457 --nocrankshaft test-run-machops/RunFloat64Ceil --nohard-abort --nodead-code-elimination --nofold-constants --testing_serialization_file=out/.serdes/serdes_RunFloat64Ceil__nocrankshaft
taskset 0x2 out/Release/cctest --random-seed=83550798 --turbo-asm --turbo-filter=* --always-opt test-run-machops/RunFloat64Ceil --nohard-abort --nodead-code-elimination --nofold-constants --testing_serialization_file=out/.serdes/serdes_RunFloat64Ceil__turbo_asm__turbo_filter=*__always_opt
taskset 0x2 out/Release/cctest --random-seed=1720039638 test-run-machops/RunFloat64Floor --nohard-abort --nodead-code-elimination --nofold-constants --testing_serialization_file=out/.serdes/serdes_RunFloat64Floor
taskset 0x2 out/Release/cctest --random-seed=1720039638 --stress-opt --always-opt test-run-machops/RunFloat64Floor --nohard-abort --nodead-code-elimination --nofold-constants --testing_serialization_file=out/.serdes/serdes_RunFloat64Floor__stress_opt__always_opt
taskset 0x2 out/Release/cctest --random-seed=1721302457 --nocrankshaft test-run-machops/RunFloat64Floor --nohard-abort --nodead-code-elimination --nofold-constants --testing_serialization_file=out/.serdes/serdes_RunFloat64Floor__nocrankshaft
taskset 0x2 out/Release/cctest --random-seed=83550798 --turbo-asm --turbo-filter=* --always-opt test-run-machops/RunFloat64Floor --nohard-abort --nodead-code-elimination --nofold-constants --testing_serialization_file=out/.serdes/serdes_RunFloat64Floor__turbo_asm__turbo_filter=*__always_opt
taskset 0x2 out/Release/cctest --random-seed=1720039638 test-run-machops/RunFloat64RoundTruncate --nohard-abort --nodead-code-elimination --nofold-constants --testing_serialization_file=out/.serdes/serdes_RunFloat64RoundTruncate
taskset 0x2 out/Release/cctest --random-seed=1720039638 --stress-opt --always-opt test-run-machops/RunFloat64RoundTruncate --nohard-abort --nodead-code-elimination --nofold-constants --testing_serialization_file=out/.serdes/serdes_RunFloat64RoundTruncate__stress_opt__always_opt
taskset 0x2 out/Release/cctest --random-seed=1721302457 --nocrankshaft test-run-machops/RunFloat64RoundTruncate --nohard-abort --nodead-code-elimination --nofold-constants --testing_serialization_file=out/.serdes/serdes_RunFloat64RoundTruncate__nocrankshaft
taskset 0x2 out/Release/d8 --test --random-seed=1720039638 --stress-opt --always-opt --nohard-abort --nodead-code-elimination --nofold-constants test/mjsunit/mjsunit.js test/mjsunit/asm/math-ceil.js
taskset 0x2 out/Release/d8 --test --random-seed=83550798 --nohard-abort --nodead-code-elimination --nofold-constants test/mjsunit/mjsunit.js test/mjsunit/asm/math-ceil.js
taskset 0x2 out/Release/d8 --test --random-seed=1720039638 --nocrankshaft --nohard-abort --nodead-code-elimination --nofold-constants test/mjsunit/mjsunit.js test/mjsunit/asm/math-floor.js
taskset 0x2 out/Release/d8 --test --random-seed=1721302457 --turbo-asm --turbo-filter=* --always-opt --nohard-abort --nodead-code-elimination --nofold-constants test/mjsunit/mjsunit.js test/mjsunit/asm/math-floor.js
taskset 0x2 out/Release/d8 --test --random-seed=83550798 --stress-opt --always-opt --nohard-abort --nodead-code-elimination --nofold-constants test/mjsunit/mjsunit.js test/mjsunit/asm/math-floor.js
taskset 0x2 out/Release/d8 --test --random-seed=83550798 --nohard-abort --nodead-code-elimination --nofold-constants test/mjsunit/mjsunit.js test/mjsunit/asm/math-floor.js
```

**Comment by MIPSbkirby** [comment]
Running GDB to find the illegal instruction for `RunFloat64Ceil` test:

```
-> taskset 0x2 gdb --args out/Release/cctest --random-seed=1720039638 test-run-machops/RunFloat64Ceil --nohard-abort --nodead-code-elimination --nofold-constants --testing_serialization_file=out/.serdes/serdes_RunFloat64Ceil
GNU gdb (GDB) 7.4.1-debian
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "mipsel-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /bbv8-slaves/popcorn-hour-board-3/tmp/v8/out/Release/cctest...(no debugging symbols found)...done.
(gdb) run
Starting program: /bbv8-slaves/popcorn-hour-board-3/tmp/v8/out/Release/cctest --random-seed=1720039638 test-run-machops/RunFloat64Ceil --nohard-abort --nodead-code-elimination --nofold-constants --testing_serialization_file=out/.serdes/serdes_RunFloat64Ceil
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/mipsel-linux-gnu/libthread_db.so.1".
[New Thread 0x77c1d4a0 (LWP 20895)]
[New Thread 0x7741d4a0 (LWP 20896)]
[New Thread 0x76c1d4a0 (LWP 20897)]
[New Thread 0x7641d4a0 (LWP 20898)]
[New Thread 0x75c1d4a0 (LWP 20899)]

Program received signal SIGILL, Illegal instruction.
0x3c08b298 in ?? ()
(gdb) disassemble 
No function contains program counter for selected frame.
(gdb) x/4i 0x3c08b290 
   0x3c08b290:  beqz    at,0x3c08b2b0
   0x3c08b294:  mov.d   $f0,$f0
=> 0x3c08b298:  ceil.l.d        $f0,$f0
   0x3c08b29c:  mfc1    at,$f0
```

Running GDB to see the illegal instruction for the `RunFloat64Floor` test:

```
-> taskset 0x2 gdb --args out/Release/cctest --random-seed=1720039638 test-run-machops/RunFloat64Floor --nohard-abort --nodead-code-elimination --nofold-constants --testing_serialization_file=out/.serdes/serdes_RunFloat64Floor
GNU gdb (GDB) 7.4.1-debian
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "mipsel-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /bbv8-slaves/popcorn-hour-board-3/tmp/v8/out/Release/cctest...(no debugging symbols found)...done.
(gdb) run
Starting program: /bbv8-slaves/popcorn-hour-board-3/tmp/v8/out/Release/cctest --random-seed=1720039638 test-run-machops/RunFloat64Floor --nohard-abort --nodead-code-elimination --nofold-constants --testing_serialization_file=out/.serdes/serdes_RunFloat64Floor
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/mipsel-linux-gnu/libthread_db.so.1".
[New Thread 0x77c1d4a0 (LWP 20925)]
[New Thread 0x7741d4a0 (LWP 20926)]
[New Thread 0x76c1d4a0 (LWP 20927)]
[New Thread 0x7641d4a0 (LWP 20928)]
[New Thread 0x75c1d4a0 (LWP 20929)]

Program received signal SIGILL, Illegal instruction.
0x3c08b298 in ?? ()
(gdb) disassemble
No function contains program counter for selected frame.
(gdb) x/4i 0x3c08b290
   0x3c08b290:  beqz    at,0x3c08b2b0
   0x3c08b294:  mov.d   $f0,$f0
=> 0x3c08b298:  floor.l.d       $f0,$f0
   0x3c08b29c:  mfc1    at,$f0
```

**Comment by paul99** [comment]
Thanks Brendan. The root problem is that these mips32r2 instructions used (for example) here: https://github.com/paul99/v8mips/commit/8c4b7d272ac7#diff-bbd46afc82cb68a7e9ad16856f518f55R476 are _not_ legal for fp32 mode.

The line in the mips32r2 users guide says `The result of this instruction is UNPREDICTABLE if the processor is executing in 16 FP registers mode.`

So this CL needs to be refactored.

However it seems that what we see here is the actual FPU in the popcorn board, _AND_ the kernel FPU emulator in the ubiquiti ERpro-8 board executes this instruction flawlessly. Only the kernel FPU emulator in the _old_ sigma 3.2.x kernel has a problem with this. Since the kernel knows that we are in fp32 mode, it does seem that it should generate an error in this case.

Finally, it seems that there is no provision in the code for mips32r1 CPUs, and these long <-->double conversions are mips32r2 only.

Assigning to Dusan.

**Comment by paul99** [comment]
Another thing I do not understand, these instruction are used in TF code, but show errors in regular mjsunit tests, without --turbo flags. How is this happening?

```
out/Release/d8 --test --random-seed=1720039638 --stress-opt --always-opt --nohard-abort --nodead-code-elimination --nofold-constants test/mjsunit/mjsunit.js test/mjsunit/asm/math-ceil.js
```

**Comment by dusmil** [comment]
Nice find guys. You found problematic combination. The problem here is  executing code in FP32 mode on HW with 32-bit FPU unit implementation. Other 32-bit boards on which we were testing this CL have 64-bit FPU implementation but they were working in FP32 mode. This also means setting FP64 mode on them is possible.

I do not think we should disable rounding optimization for MIPS32 in fp32 mode although it is obvious short term solution. The Popcorn indeed is mips32r2 but with 32-bit FPU only, considering this the kernel behavior is expected as described above in this thread.

The long term is solution is to check FPU hardware capability if possible and include it in patch.

**Comment by dusmil** [comment]
I did some research and it seems we should check "long fixed point" capability (bit 21 in FIR reg) instead of  64-bit FPU capability. This is based on the fact that on ci20 board tests run flawlessly with optimization and the FIR checking shows 32-bit FPU implementation only but it also shows long fixed point implementation is present.  I am sure cvt.l.d and similar instructions are not kernel emulated on this board.

I used this code snippet for FIR checking:

```
#include<stdio.h>
int main(void) {

  unsigned int result = 0;
  __asm__ volatile(
      "cfc1 %0, $zero\n\t"
      : "=r"(result)
      :
      : );

  unsigned int  isLongWordImpl =    !(!(result & (1 << 21)));
  unsigned int  isFPU64Bit =    !(!(result & (1 << 22)));
  printf("result: %lx isLongWordImpl: %lx isFPU64Bit: %lx\n",
          result, isLongWordImpl, isFPU64Bit);
  return 0;
}
```

@Brendan, @Paul: Could you run this snippet on PopCorn board and post the result?
If the result matches expectation, I will create the patch for this issue.

**Comment by paul99** [comment]
Hey Dusan - I expect that the code snip will pass. This comment https://github.com/paul99/v8m-rb/issues/115#issuecomment-69671640 shows that the test passes when run on core 0, presumably with hardware FPU, and fails on core 1, presumably when using kernel FP emulator.

We need to check when the floor.l.d and friends were added to the kernel FP emu, but I am guessing the old sigma kernel (3.2.x)  does not have it.

@MIPSbkirby, can you also check Dusan's test code on board 030 (sigma 8646) and on both core 0 & 1 of the popcorn (using taskset). We also need to check on Broadcom (r1), where it should return 0 in both cases.

**Comment by MIPSbkirby** [comment]
I've compiled the code for MIPS32r2 and run it on a few boards.  I was not able to compile it from MIPS32r1, but the MIPS32r2 code did run on the Broadcom board.  Here is my MIPS32r2 compile command:

```
/mips/arch/overflow/codesourcery/mips-linux-gnu/lite/release/2013.05-36/Linux/bin/mips-linux-gnu-gcc -EL -mips32r2 testing-FPU.c -o testing-FPU
```

And here is the MIPS32r1 compile command:

```
/mips/proj/build-compiler/stable-nightly-gcc/install-mips-mti-linux-gnu/bin/mips-mti-linux-gnu-gcc -mips32 -EL testing-FPU.c -o testing-FPU-r1
```

The compile errors for MIPS32r1 were:

> /tmp/cc9ZMTYR.s: Assembler messages:
> /tmp/cc9ZMTYR.s:30: Error: invalid operands `cfc1 $2,$zero'

### Results when running binary on the boards

#### Popcorn Hour board (mipsswbrd013) using a CPU with an FPU (kernel version: 3.2.5.1-mmc+)

Command:

```
taskset -c 0 testing-FPU
```

Results:

> result: 1739300 isLongWordImpl: 1 isFPU64Bit: 1

**Note** due to load on the board, I couldn't verify the trap and emulate count as in debugfs it was constantly increasing.  Howerver, `-c` option to `taskset` forces the process onto a processor number based on what is in /proc/cpuinfo.  So, according to /proc/cpuinfo, processor 0 has an FPU and processor 1 doesn't.

#### Popcorn Hour board (mipsswbrd013) using a CPU with no FPU (kernel version: 3.2.5.1-mmc+)

Command:

```
taskset -c 1 testing-FPU
```

Results:

> result: 0 isLongWordImpl: 0 isFPU64Bit: 0

#### Sigma 8646 board (mipsswbrd030) (kernel version: 2.6.35.9-12-sigma)

Command:

```
./testing-FPU
```

Results:

> result: 1739300 isLongWordImpl: 1 isFPU64Bit: 1

#### Broadcom board (mipsswbrd025) (kernel version: 3.3.8-3.1)

Command:

```
./testing-FPU
```

Results:

> result: 130001 isLongWordImpl: 0 isFPU64Bit: 0

#### Edge Router Pro board (mipsswbrd026) (kernel version: 3.14.12-00013-g2721956-dirty)

Command:

```
./testing-FPU
```

Results:

> result: 0 isLongWordImpl: 0 isFPU64Bit: 0

**Comment by dusmil** [comment]
Thank you for detailed results, they are really helpful to make a decision.

According to the results it turns out the capability of  double to fixed long conversion depends on kernel emulation as Paul already mentioned, On popcorn boards there is inconsistency between FPU real features on two cores and emulated FPU features in kernel. Also even if we implement detection based on FIR reg, it will be useless on board with emulated FPU as it can be seen in last example of EDGE ROUTER PRO  kernel does not set corresponding bits in FIR reg although it supports cvt.l.d and similar instructions.

Overall, we do not have real problem in v8 here. Either we chose to rely on support in kernel FPU emulation  for conversion instructions or we simply disable optimization for mips32r2 and conform with the spec. Choosing later options we ensure the code will work for all boards but lose optimization on other mips32r2 boards.

**Comment by paul99** [comment]
Responding to https://github.com/paul99/v8m-rb/issues/115#issuecomment-69934701, the code for this was added to the kernel years ago, but _only_ for mips64. That explains why it fails on popcorn kernel FP emulator, but works on er8 kernel FP emulator.

From arch/mips/math-emu/cp1emu.c, line 1712:

```
#if defined(__mips64)
        case fcvtl_op:{
            ieee754sp fs;

            SPFROMREG(fs, MIPSInst_FS(ir));
            rv.l = ieee754sp_tlong(fs);
            rfmt = l_fmt;
            goto copcsr;
        }

        case froundl_op:
        case ftruncl_op:
        case fceill_op:
        case ffloorl_op:{
            unsigned int oldrm = ieee754_csr.rm;
            ieee754sp fs;

            SPFROMREG(fs, MIPSInst_FS(ir));
            ieee754_csr.rm = ieee_rm[modeindex(MIPSInst_FUNC(ir))];
            rv.l = ieee754sp_tlong(fs);
            ieee754_csr.rm = oldrm;
            rfmt = l_fmt;
            goto copcsr;
        }
#endif /* defined(__mips64) */
```

**Comment by paul99** [comment]
Also @dusmil, what do you think about https://github.com/paul99/v8m-rb/issues/115#issuecomment-69678335 ?  This seems to fail non-TF specific tests. Why?

**Comment by dusmil** [comment]
@paul99:  It is TF specific after all, the test belongs to asm.js group and all asm.js code is turbofan compiled.

**Comment by paul99** [comment]
There is weirdness to the failure -- the test that @palfia pasted to slack (https://v8m.slack.com/archives/bugs/p1430423405000160) shows illegal instruction, even on core 0, which has dedicated FPU, presumably. Either something is terribly broken on this board, or possibly a data dependency causes the FP emulator code to get called.

Regardless, the manual says we must not use these instructions in fp32 mode, and I think we need to obey that. Let's land https://codereview.chromium.org/1116073002/, and take the perf hit, and then once we have correctness, we can further discuss the options available to improve this situation.

**Comment by paul99** [comment]
Disabled in fp32 per: https://chromium.googlesource.com/v8/v8/+/900bc7937c28219b39fcc5776ce945cf6fda367e

**Comment by paul99** [comment]
Issue resolved, should have been closed with the previous comment. Thx for fix Ákos.
