### ISSUE TITLE
Improve the fix for MIPS: split api call stubs into accessor and function call stubs.

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#117]
Ákos committed Balázs patch for 6950ead0b0a (The Dan Carney CL on accessors) https://codereview.chromium.org/853323002/

That had some bugs, and we figured out that it was this strange construct:

```
+    lw(s0, *stack_space_operand);
```

where `*stack_space_operand` is actually a `MemOperand(sp, 4 * kPointerSize);` constructed earlier. [1]

The problem is that it is used _after_ the `DirectCFunctionCall()`, which pushes 4 mips argument slots onto the stack, but before those arg slots are popped off in `__ LeaveExitFrame().`

Our quick fix is to add in the arg slots: `MemOperand(sp, 4 * kPointerSize + kCArgsSlotsSize);`
See https://codereview.chromium.org/855183003/

But that is spreading the ugliness to parts of the code that should not have to know.

At the very least we should add a detailed comment to our future selves who won't remember any of this. 

But it would be better to factor this differently for mips32. I don't think we need to follow the arm port super closely here if we can make this cleaner.

Note that mips64 does not have argument slots, and does not need this.

I'll assign this to Ákos for now, since he and I have been thinking about this, but I'd be happy to hear feedback & ideas from @kilvadyb or @dusmil 

[1] With git transition, and the new "Gitiles" interface to commits, we don't seem to be able to send line# links to code, like we could in the old SVN system. I could do that on the GH v8 mirror, but these CL's have not landed there yet. So you get plain text pasted in. Sorry.

**Comment by kilvadyb** [comment]
My proposal fix-improvement:

```
commit 4465e4a3a422c612b61299d73d45a57a0f775faf
Author: Balazs Kilvady <balazs.kilvady@imgtec.com>
Date:   Mon Jan 19 13:03:05 2015 +0100

    MIPS: Fix after 'Fix after 'MIPS: split api call stubs into accessor and function call stubs'.'.

diff --git a/src/mips/code-stubs-mips.cc b/src/mips/code-stubs-mips.cc
index 894747f..d0fcf34 100644
--- a/src/mips/code-stubs-mips.cc
+++ b/src/mips/code-stubs-mips.cc
@@ -4940,15 +4940,13 @@ static void CallApiFunctionStubHelper(MacroAssembler* masm,
   }
   MemOperand return_value_operand(fp, return_value_offset * kPointerSize);
   int stack_space = 0;
-  MemOperand is_construct_call_operand =
-      MemOperand(sp, 4 * kPointerSize + kCArgsSlotsSize);
-  MemOperand* stack_space_operand = &is_construct_call_operand;
+  int32_t stack_space_offset = 4 * kPointerSize;
   if (argc.is_immediate()) {
     stack_space = argc.immediate() + FCA::kArgsLength + 1;
-    stack_space_operand = NULL;
+    stack_space_offset = kInvalidStackOffset;
   }
   __ CallApiFunctionAndReturn(api_function_address, thunk_ref, stack_space,
-                              stack_space_operand, return_value_operand,
+                              stack_space_offset, return_value_operand,
                               &context_restore_operand);
 }

@@ -4997,7 +4995,7 @@ void CallApiGetterStub::Generate(MacroAssembler* masm) {
   ExternalReference thunk_ref =
       ExternalReference::invoke_accessor_getter_callback(isolate());
   __ CallApiFunctionAndReturn(api_function_address, thunk_ref,
-                              kStackUnwindSpace, NULL,
+                              kStackUnwindSpace, kInvalidStackOffset,
                               MemOperand(fp, 6 * kPointerSize), NULL);
 }

diff --git a/src/mips/code-stubs-mips.h b/src/mips/code-stubs-mips.h
index 9796fd4..699d335 100644
--- a/src/mips/code-stubs-mips.h
+++ b/src/mips/code-stubs-mips.h
@@ -285,6 +285,8 @@ class DirectCEntryStub: public PlatformCodeStub {
   explicit DirectCEntryStub(Isolate* isolate) : PlatformCodeStub(isolate) {}
   void GenerateCall(MacroAssembler* masm, Register target);

+  static const int kSlotSize = kCArgsSlotsSize;
+
  private:
   bool NeedsImmovableCode() OVERRIDE { return true; }

diff --git a/src/mips/constants-mips.h b/src/mips/constants-mips.h
index 668481e..22c3e6c 100644
--- a/src/mips/constants-mips.h
+++ b/src/mips/constants-mips.h
@@ -924,6 +924,7 @@ class Instruction {
 // C/C++ argument slots size.
 const int kCArgSlotCount = 4;
 const int kCArgsSlotsSize = kCArgSlotCount * Instruction::kInstrSize;
+const int kInvalidStackOffset = -1;
 // JS argument slots size.
 const int kJSArgsSlotsSize = 0 * Instruction::kInstrSize;
 // Assembly builtins argument slots size.
diff --git a/src/mips/macro-assembler-mips.cc b/src/mips/macro-assembler-mips.cc
index cf42c13..a55c1d0 100644
--- a/src/mips/macro-assembler-mips.cc
+++ b/src/mips/macro-assembler-mips.cc
@@ -4420,7 +4420,7 @@ static int AddressOffset(ExternalReference ref0, ExternalReference ref1) {

 void MacroAssembler::CallApiFunctionAndReturn(
     Register function_address, ExternalReference thunk_ref, int stack_space,
-    MemOperand* stack_space_operand, MemOperand return_value_operand,
+    int32_t stack_space_offset, MemOperand return_value_operand,
     MemOperand* context_restore_operand) {
   ExternalReference next_address =
       ExternalReference::handle_scope_next_address(isolate());
@@ -4514,13 +4514,13 @@ void MacroAssembler::CallApiFunctionAndReturn(
   if (restore_context) {
     lw(cp, *context_restore_operand);
   }
-  if (stack_space_operand != NULL) {
-    lw(s0, *stack_space_operand);
+  if (stack_space_offset != kInvalidStackOffset) {
+    lw(s0, MemOperand(sp, stack_space_offset + DirectCEntryStub::kSlotSize));
   } else {
     li(s0, Operand(stack_space));
   }
   LeaveExitFrame(false, s0, !restore_context, EMIT_RETURN,
-                 stack_space_operand != NULL);
+                 stack_space_offset != kInvalidStackOffset);

   bind(&promote_scheduled_exception);
   {
diff --git a/src/mips/macro-assembler-mips.h b/src/mips/macro-assembler-mips.h
index 1fb2aa2..7dbfc3f 100644
--- a/src/mips/macro-assembler-mips.h
+++ b/src/mips/macro-assembler-mips.h
@@ -1291,7 +1291,7 @@ const Operand& rt = Operand(zero_reg), BranchDelaySlot bd = PROTECT
   // the additional space allocated for the fast call).
   void CallApiFunctionAndReturn(Register function_address,
                                 ExternalReference thunk_ref, int stack_space,
-                                MemOperand* stack_space_operand,
+                                int32_t stack_space_offset,
                                 MemOperand return_value_operand,
                                 MemOperand* context_restore_operand);

```

**Comment by dusmil** [comment]
This is a way better solution. Passing stack offset than pointer to MemOperand is cleaner and nicer.
I agree with the improvement.

**Comment by kilvadyb** [comment]
Thank you for reviewing. Also adding the slotSize const moved to MacroAssembler::CallApiFunctionAndReturn() so the  CallApiFunctionStubHelper() of code-stub-mips.cc does not have to know about it. The same code-stub logic works on mips and mips64. I do no think that the `static const int kSlotSize = kCArgsSlotsSize;` of `DirectCEntryStub` is acceptable but `DirectCEntryStub` adds the slot size space to sp so maintaining/holding the size of the slot space should be the responsibility of `DirectCEntryStub`. This const would be 0 on mips64.

**Comment by dusmil** [comment]
Yes, making static variable in DirectCEntryStub which is alias of kCArgsSlotsSize is not good idea. Maybe we can use kCArgsSlotsSize  directly in mips specific macro-assembler methods.

**Comment by kilvadyb** [comment]
Yes, kCArgsSlotsSize works fine also. I just wanted to show that adding the Slot Size offset to sp happens in DirectCEntryStub::Generate() and the offset is 16 bytes == kCArgsSlotsSize on mips32r2.  Let's wait what Paul will say :) If otherwise the patch is OK then I would switch to kCArgsSlotsSize and add the patch to the mips64 code also to unify codes.

**Comment by kilvadyb** [comment]
CallApiFunctionAndReturn() moved to code-stub...cc from macro-asm...cc so the moving "logic from to" does not true fully any more.

**Comment by paul99** [comment]
Sorry for delay in responding. I think your change is an improvement for sure. But the original code has some naming issues that make it hard to understand: `stack_space` and `stack_space_operand` where stack_space is a argument count, and stack_space_operand represents a length in bytes. So unless we re-factor this a lot, which will make it hard to stay in sync with changes in the other ports, I would argue for minimal change, and a comment or two to remind us what is going on.

So, let's use your basic idea. I really like getting the `+ kCArgsSlotsSize` out of `CallApiFunctionStubHelper()`, which you have done.

As both you guys agreed above, let's **not** add a new name into `DirectCEntryStub`.

So then in `CallApiFunctionAndReturn()`, how about something like:

```
if (stack_space_offset != kInvalidStackOffset) {
    // The DirectCEntryStub call has pushed the four MIPS argument slots onto
    // the ExitFrame, which will be cleaned up when we leave the frame below.
    // We must account for this when accessing the stack_space argument.
    lw(s0, MemOperand(sp, stack_space_offset + kCArgsSlotsSize));
} else {
```

I'm sure you can figure out how to say this clearly, in less words than I used :)

I'm open to inputs on mips64 port, but I think that since it does not have argument slots, let's not drag `kCArgsSlotsSize` and these comments into it. However, it might be worth changing to this `stack_space_offset`, just to make the two ports look similar. What do you think?

Please create a CL and we can discuss it more there, if needed.

**Comment by kilvadyb** [comment]
I uploaded the CL: https://codereview.chromium.org/867183003
The 64 bit part is not exactly clear for me because of these lines of constans-mips64.h:

```
const int kCArgSlotCount = (kMipsAbi == kN64) ? 0 : 4;

// TODO(plind): below should be based on kPointerSize
// TODO(plind): find all usages and remove the needless instructions for n64.
const int kCArgsSlotsSize = kCArgSlotCount * Instruction::kInstrSize * 2;
```

So I left `+ kCArgsSlotsSize`in the code but added a DCHECK to ensure it always 0. It is not a solution to land :)

**Comment by paul99** [comment]
We discussed the issues raised above in Balázs CL https://codereview.chromium.org/867183003 which was landed as https://crrev.com/0e7379e001a4d1adbc56da264316bfcddb8281a6

Thanks. Closing.
