### ISSUE TITLE
More NaN stuff

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#119]
I finished the port from Balázs on NaN's, which fixes the build and passes most of the NaN-related tests.

However, there are unfinished issues to resolve:

**One.** On linux, my mips64el.debug simulator build fails test/mjsunit/regress/regress-undefined-nan2.js
    `Failure: expected <undefined> found <NaN>`

That test was created by Benedikt in ee86227600  [arm] Fix sNaN quietening in the ARM simulator on IA-32. I did _not_ look closely at the mips64-sim to see if it fits into the problem areas he fixed here, however we did _not_ need this CL ported for the mips32 simulator.

This test passes on my mac, and fails on Linux. I seem to remember some log ago issue about Linux running the FP code in some different or weird mode, even on x64.

**Two.** The mips32 hardware on sigma 8646 with FPU fails test/mjsunit/regress/regress-undefined-nan.js

```
Fatal error in ../src/objects-debug.cc, line 395
CHECK((value & V8_UINT64_C(0x7FF8000000000000)) != V8_UINT64_C(0x7FF0000000000000) || (value & V8_UINT64_C(0x0007FFFFFFFFFFFF)) == V8_UINT64_C(0)) failed
```

That definition does not take into account MIPS NaN value, I think. I suspect we will need a ifdef MIPS there.

**Three.** I did _not_ yet test big-endian for any of these changes. Balázs, can you do that as early as possible tommorrow, and report back any problems on this issue. You are welcome to fix them too ;-)

**Four.** I think I did not do enough hardware testing, even on little-endian.

Assigning to Balázs for now, but I would appreciate help & advice from @dusmil (especially on item 2) and @palfia who have been thru some of these NaN issues a few times already.

**Comment by dusmil** [comment]
First look and  I  think we missed a point here. They introduced  sNaN for hole Nan in order to remove or greatly reduce Nan changes  to canonical NaN. Therefore, the portion of code is removed for instance from StoreNumberToDoubleElement for x86. I do not see we did the same thing. Also, this is not done for arm32 for some reason. Probably they will port this later. They rely on the fact that x86 FPU can quiet the SNaN. We should check if mips can do the same.

Second, since mips32 prior r5 uses inverted encoding  for SNaN and QNaN , this CL can be troublesome for us, We should ensure we use mips SNaN encoding for mips32r2 which is QNan for x86 and arm. The mips32r6 uses the same Nan encoding as the rest of the known mainstream world, so we should handle this as well.

I have an impression that more work should be spent on this CL.

**Comment by kilvadyb** [comment]
Big-endian sim is fine. mipsel sim also. I found some strange failures on mips64el sim - will check them. I started mipsel and mips tests on boards. I report the results soon. I run test on build before rev 0381acf which bring is a new test with hard-coded nan values.

**Comment by dusmil** [comment]
Sorry, how do you mean big-endian sim is fine?  If you have built mips.release for sim it is equivalent with mipsel.release build for sim. Another words there is no mips sim (big-endian) on little endian host.

The BE layout can be only checked on  BE mips targets or BE hosts as PowerPC.

**Comment by kilvadyb** [comment]
You are right, I forgot about BE sim <-> qemu trick. So when I can access the broadcom board I start the tests on it. On mips64el sim I got 36 failures while before nan changes ( == rev 3175d30) I got only 3. Most of the new failures are releated to NaN. I try to investigate them.

**Comment by paul99** [comment]
Probably obvious, but tests need to be run in debug mode. Most fails I saw yesterday only failed on debug.

**Comment by dusmil** [comment]
It appears MIPS can also quiets SNan (mips snan), I checked this on ci20 boards with code snippet.  The  addition of 1.0 and SNan  produces QNan..

The only question is now has it been done by trapping or it has been done by actual FPU. What settings we need in FCSR to ensure desired behavior?

Overall, the goal is to use sNan for holes in fixed double arrays and utilize sNan to qNan conversion through fpu. Doing so we will remove unnecessary checks and load as it is done for x86 which will result in performance increase.

**Comment by paul99** [comment]
Excellent, thanks for looking into this. 

If your CI-20 kernel has debugfs (CONFIG_DEBUG_FS=y), you can mount that (mount -t debugfs none /sys/kernel/debug) and in dir /sys/kernel/debug/mips/fpuemustats look at the counts in pseudo-files cp1ops and emulated. (I am not sure of the precise difference between these, I will try to determine.) On my sigma 8646 (with HW FPU), the two files return the same count.

Can you send me your code snip via slack, and I will try on this board.

We should also test this behavior works on pure emulated FPU, like in er8.

**Comment by kilvadyb** [comment]
Finally I managed to start tests on er8 in bigendian mode. Unfortunately I lost the connection to the board (broken pipe) at 9% - 45 mins. No nan error so far.

**Comment by dusmil** [comment]
Checked on CI-20 board, and FPU operation with sNan is not emulated. The counter for emulated fpu instructions is zero. The behavior on boards (Cavium and Er8-pro) is the same. The  snan 0x7ff80000 ... is converted to 0x7ff7fffff .... All checks are done with  the snippet uploaded on slack.

One note: The arm32 code has already used VFPU quieting feature to canonicalize  Nans which was introduced in 5c6b09e6.

**Comment by paul99** [comment]
I previously thought we had a simulator x87 NaN-conversion issue, but with limited testing in the regress-undefined-\* tests, I see **no** evidence for that.

I fixed one bug, due to the sign value of the updated `kHoleNanUpper32` we need this:

```
diff --git a/src/mips64/lithium-codegen-mips64.cc b/src/mips64/lithium-codegen-mips64.cc
index f51822d..bbe7e4d 100644
--- a/src/mips64/lithium-codegen-mips64.cc
+++ b/src/mips64/lithium-codegen-mips64.cc
@@ -3248,7 +3248,7 @@ void LCodeGen::DoLoadKeyedFixedDoubleArray(LLoadKeyed* instr) {
   __ ldc1(result, MemOperand(scratch));

   if (instr->hydrogen()->RequiresHoleCheck()) {
-    __ lw(scratch, MemOperand(scratch, sizeof(kHoleNanLower32)));
+    __ lwu(scratch, MemOperand(scratch, sizeof(kHoleNanLower32)));
     DeoptimizeIf(eq, instr, "hole", scratch, Operand(kHoleNanUpper32));
   }
 }
```

With that, mac sim, Linux sim, and er8 hardware show the same 2 test fails out of the 14 regress-undefined-\* tests. I've not run full test suite yet. Here is the remaining error:

Release: `Failure: expected <true> found <false>`
at test/mjsunit/regress/regress-undefined-nan3.js:32:19

Debug: 

```
#
# Fatal error in ../src/mips64/lithium-codegen-mips64.cc, line 4186
# CHECK(!instr->hydrogen()->has_transition()) failed
#

==== C stack trace ===============================

 1: V8_Fatal
 2: v8::internal::LCodeGen::DoStoreNamedField(v8::internal::LStoreNamedField*)
 3: v8::internal::LStoreNamedField::CompileToNative(v8::internal::LCodeGen*)
 4: v8::internal::LCodeGenBase::GenerateBody()
 5: v8::internal::LCodeGen::GenerateCode()
 6: v8::internal::LChunk::Codegen()
 ....
```

There is also the assertion for signalling NaN bit pattern in objects-debug.cc `FixedDoubleArray::FixedDoubleArrayVerify()` line 289.

**Comment by paul99** [comment]
These fails are clearly nan related: mjsunit/elements-transition, mjsunit/generated-transition-stub, mjsunit/regress/regress-convert-hole2, mjsunit/regress/regress-undefined-nan3

These I'm not sure:
mjsunit/tools/profviz, mjsunit/regress/regress-91008, mjsunit/regress/regress-123919

**Comment by paul99** [comment]
Found a 2nd sign-extension problem. This fixes several more tests, but a few still remain.

```
diff --git a/src/mips64/lithium-codegen-mips64.cc b/src/mips64/lithium-codegen-mips64.cc
index f51822d..4d4ab93 100644
--- a/src/mips64/lithium-codegen-mips64.cc
+++ b/src/mips64/lithium-codegen-mips64.cc
@@ -2337,6 +2337,8 @@ void LCodeGen::DoCmpHoleAndBranch(LCmpHoleAndBranch* instr) {

   Register scratch = scratch0();
   __ FmoveHigh(scratch, input_reg);
+  __ dsll32(scratch, scratch, 0);  // FmoveHigh (mfhc1) sign-extends.
+  __ dsrl32(scratch, scratch, 0);  // Use only low 32-bits.
   EmitBranch(instr, eq, scratch, Operand(kHoleNanUpper32));
 }

@@ -3248,7 +3250,7 @@ void LCodeGen::DoLoadKeyedFixedDoubleArray(LLoadKeyed* instr) {
   __ ldc1(result, MemOperand(scratch));

   if (instr->hydrogen()->RequiresHoleCheck()) {
-    __ lw(scratch, MemOperand(scratch, sizeof(kHoleNanLower32)));
+    __ lwu(scratch, MemOperand(scratch, sizeof(kHoleNanLower32)));
     DeoptimizeIf(eq, instr, "hole", scratch, Operand(kHoleNanUpper32));
   }
 }
```

**Comment by paul99** [comment]
The remaining failures in mips64el simulator were due to a bug in `LCodeGen::DoStoreNamedField()`.

The fix for all 3 issues is now landed in https://chromium.googlesource.com/v8/v8/+/1ea1141c81caf3f33d72f2f7f07c6d1719ef7d51

The MIPS buildbots still show a few errors, but I think they are all timeouts. My local testing of release and opt debug was clean.

I will emphasize that this is _simulator_ testing only, to fix the bugs that showed up from changing HoleNan value. 

We know there are still MIPS platform errors with sNaN and qNaN. And this does also not address the optimization in `LCodeGen::DoStoreKeyedFixedDoubleArray()` which started this whole thing.

I will likely close this issue tomorrow, and open specific new ones for the above two issues.

**Comment by paul99** [comment]
Further work tracked in https://github.com/paul99/v8m-rb/issues/125 and https://github.com/paul99/v8m-rb/issues/126.

Closing this one.
