### ISSUE TITLE
Internal ABI register usage - a0 vs v0

### ISSUE THREAD

**Issue by kalmard** [v8mips/v8mips#12]
Is there really a need to use v0 internally? I'm not talking about calling C code, but strictly our internal mechanics of calling code stubs and lithium functions.

We've had a lot of problems caused by differences from the ARM code - using v0 is one of them. We rarely gain anything by returning the result in v0 (and v1), because we otherwise follow ARM and don't re-use a0.

Getting rid of this would make porting ARM code easier and less error-prone.

v0 and v1 could be used as crankshaft or generic temporaries. The possible benefit of this needs to be investigated.

**Comment by paul99** [comment]
My initial thoughts: In hindsight, it was likely the wrong choice to follow mips abi here. Would have saved a lot of bugs had we not done this.

Question is how much effort would it take to try it the other way? And how would it help? Basic cost/benefit analysis.

It would make things a little faster, but I really doubt it would be measurable on benchmarks. So the benefit would likely be in a further reduction of bugs from porting new code, and maybe easier porting.

If this was really easy to try, I'd say go for it. But I think it is more than just a search/replace kind of thing. Maybe someone could prototype it in a week more or less? One good thing is it would not touch arch-indep code.

Is there anyplace where we end up calling C code, and do not have the ability to move result back to a0?  Mostly we do it thru wrappers, which we can fix.

Curious what others on the team think?

**Comment by paul99** [comment]
I am leaving this open for now, though it is quite old. I'm not really seeing a possible performance payoff here. it seems that it would only be something to reduce future bugs issue. And there, we still have to deal with CallRuntime() which will definitely follow the MIPS ABI.

Per this comment in v8-dev (https://groups.google.com/d/msg/v8-dev/-hJfRQWuyrw/PFFBuGCoAQAJ), it seems that the v8 plan is still to deprecate full-codegen and crankshaft, sos maybe when those are gone, we go thru TF,  code-stubs, and remaining code, and clean this up a bit.

**Comment by kisg** [comment]
I disagree with inventing a new custom API. It would needlessly make the already steep learning curve even more difficult for questionable performance benefits. Closing for now.
