### ISSUE TITLE
Big-endian failure: cctest/test-api/Threading2

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#121]
See google builders here: http://build.chromium.org/p/client.v8/builders/V8%20Mips%20-%20big%20endian%20-%20nosnap%20-%201

Failed since build 558. A quick look at the CL's involved show nothing obvious to me.

Note that the little-endian hardware builds at mips are down right now, so this might affect ALL mips hw.

Svetozar, can you please investigate this first thing Monday?

**Comment by paul99** [comment]
This bug disappeared after seemingly unrelated change https://codereview.chromium.org/942963004 was landed. Ákos is still investigating so that we understand root cause.

There were some interesting comments in https://codereview.chromium.org/942963004#msg3 , 4, and 5, and I think we should experiment with these specific changes, rather than the entire CL to help isolate this.

@palfia you posted a lot of interesting and useful debug info to slack. Can you please paste the summaries here, as well as your conclusion when you reach one. I want to have the relevant bug history captured in this issue.

**Comment by paul99** [comment]
This bug is back. It first showed up today on google BB: http://build.chromium.org/p/client.v8/builders/V8%20Mips%20-%20big%20endian%20-%20nosnap%20-%201/builds/1057  -- That has 4 commits since the previous build (which was fine)

```
36f17ed0 Deprecate 3-args ResourceConstraints::ConfigureDefaults
53cc6486 Remove support for externally backed elements from the API
f66a3128 Wrap array implementation in a function.
8cf289ca Throw when attaching a stack trace to an object fails.
```

I have not traced which one causes it, but at rev 42415bf9b, it was easily reproducible on erpro8 board, mips32el, no-snap.

@palfia: could you _please_ copy/paste the previous good info you have in slack regarding this bug to this issue.

**Comment by palfia** [comment]
I summarized my earlier findings in the next few points. Most of these observations applies to big-endian testing on the ER8 board with snapshot mode off (as the Google BB runs the tests).
- The Threading2 test starts many API test and at some point it fails at a CHECK in the InternalFieldCallback test. This test creates a 'Trivial' object which has a field and a getter/setter to this field. As the first step the test sets the internal field value to 42, then sets a phantom callback on this object and this callback is invoked during GC. The callback itself just gets the 'Trivial' object and sets it's internal field to 1729. After that the test calls the GC and checks if the Trivial's field value is 1729 or not. The 'InternalFieldCallback' test is executed twice by the Threading2, at first run it only calls the GC for the new space and second time it does a global GC. The first test with new space GC works fine, the registered 'CheckInternalFields' callback is invoked correctly by the GC and the test result is OK. However, the second time the 'InternalFieldCallback' test does a global GC, but the 'CheckInternalFields' callback is never invoked by the GC and thus the fields of t1 and t2 don't get updated and the CHECK aborts the test. It seems the GlobalHandles::pending_phantom_callbacks_ List should contain the registered Callback, but in the second case, the callback is missing from this list.
- Another observation is that the set of the executed API tests and these execution order is different on MIPS and on ARM. Each API test has a global constructor and in this constructor the test adds itself to a linked-list. So, actually the order of the tests in the list is determined by the calling order of the global constructors. On MIPS I use the GCC compiler to create a target build and therefore these global constructors are called by the "__static_initialization_and_destruction_0". But on ARM, I run this test on simulator which is built by clang and it seems the global constructor calling strategy (performed by "__cxx_global_var_init6") is different with clang.
  
  I tested the API test order on many archs:
  ARM sim debug clang: correct order
  ARM sim debug gcc: correct order
  ARM target gcc: correct order
  MIPS target gcc (CS-2013.11): WRONG order and InternalFieldsCallback fails!
  MIPSEL sim debug clang: correct order
  MIPSEL sim debug gcc: correct order
  MIPSEL target debug gcc (CS-2013.11): WRONG order!
  
  Either way, even though the execution order and test set is different on MIPS the Threading2 test should pass correctly.
- When I remove a (few) test from the test-api.cc then sometimes the Threading2 test passes. For example, the https://codereview.chromium.org/942963004 CL removed many tests and after that change the Threading2 tests suddenly started to work.
- Also interesting that when I modify the test that runs just before the InternalFieldCallback - which is CheckForCrossContextObjectLiterals - then the InternalFieldCallback sometimes gets fixed. For example, if I change the
  
  const char\* sources[nof] = {
    "try { [ 2, 3, 4 ].forEach(5); } catch(e) { e.toString(); }",
    "Object()"
  };
  
  array to
  
  const char\* sources[nof] = {
    "Object()",
    "Object()"
  };
  
  then the subsequent InternalFieldCallback magically runs correctly, it invokes the callback correctly and produces the correct result. So, it seems the prev test has an intense affect on InternalFieldCallback.
- My latest finding is that when I enable the snapshot mode in big endian mode then the Threading2 test works fine and there's no CHECK failure.

**Comment by palfia** [comment]
Final conclusions:

On MIPS the Threading2 test order is different then other on arches due to the toolchain static constructor initialization differences. Therefore MIPS runs more memory hungry tests then other archs and when the thread runner reaches to the InternalFieldCallback test then at that point it uses so much memory that the incremental marking algorithm gets activated. The InternalFieldCallback test is invoked twice, at first it calls the scavenge GC on new space, then at the second run it tries to do a full GC (with mark-compactor), but due to a bug in the GC it cannot perform a full GC when the incremental marker is running (instead it calls the scavenge GC), however the test requires a full GC cycle to pass the test.

This bug in the GC was fixed by the Google Team in this CL: https://codereview.chromium.org/1099783003

This CL fixes the Threading2 bug on MIPS, so we can safely close this ticket now.
