### ISSUE TITLE
21 unique tests failing when compiling with Codescape SDK and testing with Codescape SDK libraries

### ISSUE THREAD

**Issue by MIPSbkirby** [v8mips/v8mips#122]
I tried building V8 using the 2015.01-4 Codescape SDK compiler.  I can build V8 with the release version but not the optdebug version as noted in issue #118.  I was able to embed the dynamic linker and rpath into the binary by setting the LDFLAGS environment variable like this:

```
 export LDFLAGS="-Wl,-rpath,${RPATH} -Wl,--dynamic-linker=${LDSO}"
```

(the above assumes that RPATH is set to the Codescape SDK rpath and LDSO is set to the Codescape SDK dynamic linker) Since this might completely override the linker flags, this might be why the tests are failing.  So, the solution could be to add the LDSO_PATH and LD_R_PATH to the mips32r2 gyp configs.  

After getting V8 to build, I ran the test suite to see if tests are passing or not.  Here is how I ran the testing:

```
 python tools/run-tests.py --verbose --no-presubmit --outdir=out --arch=mipsel --mode=release --time default  --timeout=600 --flaky-tests skip --rerun-failures-count=2 --json-test-results ../mips32r2-with-Codescape-and-LDFALGS-on-erpro8-board-8.json
```

I'm seeing 180 failing tests failing that narrows down 21 unique failing tests.   Here are the unique failing tests and the number of times they fail:

| Failures | Test name |
| --- | --- |
| 3 | cctest/test-heap-profiler/ManyLocalsInSharedContext |
| 3 | mjsunit/big-object-literal |
| 6 | mjsunit/asm/embenchen/box2d |
| 6 | mjsunit/asm/embenchen/fannkuch |
| 6 | mjsunit/asm/embenchen/fasta |
| 6 | mjsunit/asm/embenchen/memops |
| 6 | mjsunit/asm/embenchen/zlib |
| 6 | mjsunit/numops-fuzz-part1 |
| 6 | mjsunit/numops-fuzz-part2 |
| 6 | mjsunit/numops-fuzz-part3 |
| 6 | mjsunit/numops-fuzz-part4 |
| 12 | cctest/test-heap/TestSizeOfRegExpCode |
| 12 | cctest/test-serialize/SerializeToplevelLargeCodeObject |
| 12 | cctest/test-simplified-lowering/RunNumberMultiply_TruncatingToUint32 |
| 12 | mjsunit/regexp-captures |
| 12 | mjsunit/regress/regress-1200351 |
| 12 | mjsunit/regress/regress-crbug-178790 |
| 12 | mjsunit/regress/regress-regexp-construct-result |
| 12 | mjsunit/string-slices-regexp |
| 12 | mjsunit/switch |
| 12 | mjsunit/third_party/regexp-pcre |

And, here the test names and an example command to make it fail:

| Test name | Example command |
| --- | --- |
| cctest/test-heap-profiler/ManyLocalsInSharedContext | out/mipsel.release/cctest --random-seed=1417975431 test-heap-profiler/ManyLocalsInSharedContext --nohard-abort --nodead-code-elimination --nofold-constants --testing_serialization_file=out/.serdes/serdes_ManyLocalsInSharedContext |
| cctest/test-heap/TestSizeOfRegExpCode | out/mipsel.release/cctest --random-seed=1417975431 test-heap/TestSizeOfRegExpCode --nohard-abort --nodead-code-elimination --nofold-constants --testing_serialization_file=out/.serdes/serdes_TestSizeOfRegExpCode |
| cctest/test-serialize/SerializeToplevelLargeCodeObject | out/mipsel.release/cctest --random-seed=1417975431 test-serialize/SerializeToplevelLargeCodeObject --nohard-abort --nodead-code-elimination --nofold-constants --testing_serialization_file=out/.serdes/serdes_SerializeToplevelLargeCodeObject |
| cctest/test-simplified-lowering/RunNumberMultiply_TruncatingToUint32 | out/mipsel.release/cctest --random-seed=1417975431 test-simplified-lowering/RunNumberMultiply_TruncatingToUint32 --nohard-abort --nodead-code-elimination --nofold-constants --testing_serialization_file=out/.serdes/serdes_RunNumberMultiply_TruncatingToUint32 |
| mjsunit/asm/embenchen/box2d | out/mipsel.release/d8 --test --random-seed=1417975431 --nohard-abort --nodead-code-elimination --nofold-constants test/mjsunit/mjsunit.js test/mjsunit/asm/embenchen/box2d.js |
| mjsunit/asm/embenchen/fannkuch | out/mipsel.release/d8 --test --random-seed=1417975431 --nohard-abort --nodead-code-elimination --nofold-constants test/mjsunit/mjsunit.js test/mjsunit/asm/embenchen/fannkuch.js |
| mjsunit/asm/embenchen/fasta | out/mipsel.release/d8 --test --random-seed=1417975431 --nohard-abort --nodead-code-elimination --nofold-constants test/mjsunit/mjsunit.js test/mjsunit/asm/embenchen/fasta.js |
| mjsunit/asm/embenchen/memops | out/mipsel.release/d8 --test --random-seed=1417975431 --nohard-abort --nodead-code-elimination --nofold-constants test/mjsunit/mjsunit.js test/mjsunit/asm/embenchen/memops.js |
| mjsunit/asm/embenchen/zlib | out/mipsel.release/d8 --test --random-seed=1417975431 --nohard-abort --nodead-code-elimination --nofold-constants test/mjsunit/mjsunit.js test/mjsunit/asm/embenchen/zlib.js |
| mjsunit/big-object-literal | out/mipsel.release/d8 --test --random-seed=1417975431 --nohard-abort --nodead-code-elimination --nofold-constants test/mjsunit/mjsunit.js test/mjsunit/big-object-literal.js |
| mjsunit/numops-fuzz-part1 | out/mipsel.release/d8 --test --random-seed=1417975431 --stress-opt --always-opt --nohard-abort --nodead-code-elimination --nofold-constants test/mjsunit/mjsunit.js test/mjsunit/numops-fuzz-part1.js |
| mjsunit/numops-fuzz-part2 | out/mipsel.release/d8 --test --random-seed=1417975431 --stress-opt --always-opt --nohard-abort --nodead-code-elimination --nofold-constants test/mjsunit/mjsunit.js test/mjsunit/numops-fuzz-part2.js |
| mjsunit/numops-fuzz-part3 | out/mipsel.release/d8 --test --random-seed=1417975431 --stress-opt --always-opt --nohard-abort --nodead-code-elimination --nofold-constants test/mjsunit/mjsunit.js test/mjsunit/numops-fuzz-part3.js |
| mjsunit/numops-fuzz-part4 | out/mipsel.release/d8 --test --random-seed=1417975431 --stress-opt --always-opt --nohard-abort --nodead-code-elimination --nofold-constants test/mjsunit/mjsunit.js test/mjsunit/numops-fuzz-part4.js |
| mjsunit/regexp-captures | out/mipsel.release/d8 --test --random-seed=1417975431 --nohard-abort --nodead-code-elimination --nofold-constants test/mjsunit/mjsunit.js test/mjsunit/regexp-captures.js |
| mjsunit/regress/regress-1200351 | out/mipsel.release/d8 --test --random-seed=1417975431 --nohard-abort --nodead-code-elimination --nofold-constants test/mjsunit/mjsunit.js test/mjsunit/regress/regress-1200351.js |
| mjsunit/regress/regress-crbug-178790 | out/mipsel.release/d8 --test --random-seed=1417975431 --nohard-abort --nodead-code-elimination --nofold-constants test/mjsunit/mjsunit.js test/mjsunit/regress/regress-crbug-178790.js |
| mjsunit/regress/regress-regexp-construct-result | out/mipsel.release/d8 --test --random-seed=1417975431 --nohard-abort --nodead-code-elimination --nofold-constants test/mjsunit/mjsunit.js test/mjsunit/regress/regress-regexp-construct-result.js |
| mjsunit/string-slices-regexp | out/mipsel.release/d8 --test --random-seed=1417975431 --nohard-abort --nodead-code-elimination --nofold-constants test/mjsunit/mjsunit.js test/mjsunit/string-slices-regexp.js |
| mjsunit/switch | out/mipsel.release/d8 --test --random-seed=1417975431 --nohard-abort --nodead-code-elimination --nofold-constants --allow-natives-syntax test/mjsunit/mjsunit.js test/mjsunit/switch.js |
| mjsunit/third_party/regexp-pcre | out/mipsel.release/d8 --test --random-seed=1417975431 --nohard-abort --nodead-code-elimination --nofold-constants test/mjsunit/mjsunit.js test/mjsunit/third_party/regexp-pcre.js |

**Comment by paul99** [comment]
@MIPSbkirby I think this can be closed, we have been been building with this toolchain (and your no-format-pedantic patch for a long time. I don't recall any of these tests failing recently. If this is really outdated, please close it.

**Comment by MIPSbkirby** [comment]
We have been building and testing with the Codescape 2015.01-5 since sometime in April.  So, this issue is resolved.
