### ISSUE TITLE
FPU related flags in gyp

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#123]
Why do we have the flags `v8_use_mips_abi_hardfloat` and `v8_can_use_fpu_instructions` ?

They are true by default, and I always use defaults, and produce working builds even for boards without FPU like ERpro-8.

This topic was raised on https://groups.google.com/forum/#!topic/v8-users/tyITy6OWwqI -- as I think we used to use those flags in pre-3.18 builds where we had soft-float.

I do remember that Dusan said there was still use for these, but if so, can you please document it here. If not, let's remove them.

**Comment by dusmil** [comment]
We need `v8_use_mips_abi_hardfloat` to chose ABI with regards to calling convention especially on soft-float system like OpenWRT although the v8 emit FPU instruction which are emulate in kernel.
The `v8_can_use_fpu_instructions` is here for historical reasons which forces usage of FPU instruction and tells v8 engine FPU is supported. This variable determines whether crankshaft is used on soft-float systems or not.

**Comment by paul99** [comment]
The answer is correct, and no further action is needed. Closing.
