### ISSUE TITLE
Label->pos() size on mips64

### ISSUE THREAD

**Issue by kilvadyb** [v8mips/v8mips#127]
In the function Assembler::bind_to() we use strict 32 bit label positions:

```
...
while (L->is_linked()) {
   int32_t fixup_pos = L->pos();
   int32_t dist = pos - fixup_pos;
...
```

While the Assembler::target_at functions got 64 bit arguments:

```
  // Decode branch instruction at pos and return branch target pos.
  int64_t target_at(int64_t pos, bool is_internal);

  // Patch branch instruction at pos to branch to given branch target pos.
  void target_at_put(int64_t pos, int64_t target_pos, bool is_internal);
```

And class Label uses int type positions:

```
class Label {
 public:
  int pos() const;

 private:
int pos_;
```

It looks like we should use int32_t or int type everywhere.

**Comment by kilvadyb** [comment]
Arm64 and x64 uses only int types.

**Comment by paul99** [comment]
But `int' is probably`int64_t`on these arch's. I do agree that we should be consistent, and if that is going to`int`, fine....

**Comment by kilvadyb** [comment]
In C standard definition the int type is compiler dependent (in sizes: short <= int <= long <= long long). sizeof(int) == 32 with gcc and llvm/clang as well on 64 bit archs. And anyway class Label is defined in src/assembler.h so Label::pos_ is int for all the archs. I plan to create a simple CL to use int type for label positions everywhere to see if it works or not, but it must work.

**Comment by paul99** [comment]
I believe the fix was landed in https://crrev.com/39f58c2451e087dcdece0916d750ae5719483234

@kilvadyb if there is no more work to do here, can you please close this issue?
