### ISSUE TITLE
Add support for rounding modes wrt FCSR in simulator.

### ISSUE THREAD

**Issue by dusmil** [v8mips/v8mips#132]
Add support for rounding modes in simulator according to values in FCSR register and
write corresponding tests for conversion instructions.  
Additionally, implement RINT instruction for r6  in assembler, disassembler and simulator for mips32, mips64, and write appropriate assembler, disassemble test.

**Comment by djpesic** [comment]
I have finished commit for this issue. Please take a look at the following link: https://codereview.chromium.org/1108583003

**Comment by paul99** [comment]
This is completed, reviewed, and ready to land. Please close this issue once the code lands, and has passed BB testing.

**Comment by djpesic** [comment]
I have finished first part of patch for this issue. Please, take a look at https://codereview.chromium.org/1119203003
