### ISSUE TITLE
Add test coverage for float32 instructions.

### ISSUE THREAD

**Issue by dusmil** [v8mips/v8mips#133]
Implement assembler, disassembler tests for all float instructions for mips32 and mips64.

Additionally, add missing single precision float instructions for r2 and r6 architecture variants in assembler, simulator and disassembler with corresponding tests.

**Comment by kilvadyb** [comment]
A lot of single precision float instructions was added in the following ports, CLs:
https://codereview.chromium.org/1046953004
https://codereview.chromium.org/1045203003
https://codereview.chromium.org/1047213002
Port of https://codereview.chromium.org/1066393002

**Comment by dusmil** [comment]
I am aware of that, so I particularly stated missing instruction in the issue and defined this issue as test coverage improvement.

**Comment by kilvadyb** [comment]
I see. It will be really useful if testing and missing stuff is added. I hoped it is easier to find missing things after checking these CLs.

**Comment by dusmil** [comment]
Right, thank you for updating the issue.

**Comment by djpesic** [comment]
Code for this issue has been finished. First part: https://codereview.chromium.org/1147493002/. Second part: https://codereview.chromium.org/1145223002/.
