### ISSUE TITLE
force-long-branches mode is broken.

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#135]
We can no longer use force-long-branches flag, the shell will not start up. The failure is in deoptimizer, in code from 9f37a8af. However, once reverting that CL, it fails elsewhere in deoptimizer. I found this in mips64el, and also tested mipsel briefly.

Dusan, can you take a look? Once this is fixed, we will add to to the bots, so we don't break it again.

**Comment by dusmil** [comment]
Fixed in: https://codereview.chromium.org/1120753010/
Closing issue.
