### ISSUE TITLE
Basic automatic optimization of generated code

### ISSUE THREAD

**Issue by kalmard** [v8mips/v8mips#14]
While complex optimizations could make code generation too slow, there are some cases where the optimization is obvious.

One example that comes to mind is pusing several values on the stack after each other. Yes, we have Push macros with several argument counts and MultiPush, but I remember seeing a lot of cases when neither of these were used for one reason or another (branches in cpp code, not enough args for Push, etc.).

The following code:
push(a0);
push(a1);
push(a2);

generates:
addiu sp, sp, -4
sw a0, sp + 0
addiu sp, sp, -4
sw a1, sp + 0
addiu sp, sp, -4
sw a2, sp + 0

Modifying push and pop (and the other variants) to check for consecutive sp adjustments should be almost trivial, however this is actually very rare in the code.
There is a slightly more complicated (but more common) case when a register is modified between two sp adjustments. Detecting and optimizing these cases may be a little more complicated, but probably still fairly easy.

Also, a note from Paul:
"there used to be a peephole optimzation for some constructs, I think it was removed long ago. (it was in assembler.cc if I remember right (all arch, not just mips)"

**Comment by paul99** [comment]
Closing this, as it applies to older code-gens. it might be useful to think of this kind of thing in the context of the new TF instruction-scheduler, however.
