### ISSUE TITLE
Implement r6 compact-branch forbidden-slot support.

### ISSUE THREAD

**Issue by dusmil** [v8mips/v8mips#140]
Implement compact branch forbidden-slot guards in simulator and assembler for r6

Find the most suitable way to implement it.

**Comment by paul99** [comment]
Delay slots on old branches must be protected by default (by adding a nop) and allowed only in the very limited cases where we know we are putting valid instruction there.

Forbidden slots are the opposite, in that most instructions are perfectly legal, and we must only protect the forbidden slot (by adding a nop) if we know that the following instruction will be a control-transfer-instruction.

My (very likely oversimplified) approach would be to keep some 'state' in the assembler that a compact branch was just emitted as previous instruction, and if the current instruction was a CTI, then the emit() function would automatically add the required nop(), before emitting the CTI instruction.

**Comment by paul99** [comment]
This has been implemented by Balázs, along with mips32 r6 compact branch support in https://codereview.chromium.org/1396133002

I think we are quite close to landing this. See the perf improvement numbers in slack #benchmarking

**Comment by paul99** [comment]
This has been implemented by Balázs in 3573d3cb MIPS: r6 compact branch optimization.

Unfortunately, there is a related bug in https://v8.mips.com/bbv8/builders/Target%20-%20MIPS64%20-%20Debug%20-%20edge%20-%20benchmarks/builds/1082, regexp test.

Also there is https://code.google.com/p/chromium/issues/detail?id=555543 from the Chromium fuzzer tests.

I think that @kilvadyb has a fix just about ready....

**Comment by kisg** [comment]
Implementation done, open new issue if necessary.
