### ISSUE TITLE
Fix unaligned double access in: Unify decoding of deoptimization translations.

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#143]
Commit `9127d4ee Unify decoding of deoptimization translations.` introduces some new use of pointers to doubles that are unaligned, and crash.

Kudo's to Rick who spotted this on the buildbot, and got to the root cause. 

TEST: mjsunit/debug-backtrace.js  with --turbo --always-opt

```
out/mipsel.release/d8 --test --random-seed=591134838 --turbo --always-opt --nohard-abort --nodead-code-elimination --nofold-constants --expose-debug-as debug test/mjsunit/mjsunit.js test/mjsunit/debug-backtrace.js
```

The problem is in new function TranslatedState::CreateNextTranslatedValue()  (https://chromium.googlesource.com/v8/v8/+/9127d4eef4248c6a5266c6ed9e9a32a4ce2423eb/src/deoptimizer.cc, line 2935). 

I'd strongly suspect case Translation::DOUBLE_REGISTER: , and the line registers->GetDoubleRegister(input_reg);, but I've not actually traced it that far.

It is clearly accessing a double from unaligned address, and gets a trap. I used the codescape 4.9.2 toolchain, built for mips32, and ran on Octeon-III board. I suspect any board with kernel alignment fixups _disabled_ will show this problem.

We will need a C workaround for doubles accesses, like we have in objects-inl.h. 

Balázs, can you please take a look at this? 

(It's possible that there are more access problems after we fix this one.)

**Comment by paul99** [comment]
Please note that this issue was the cause of my incoherent babbling during the group meeting, about DSP instruction sets and LDXC1, etc. Sorry about the misinformation.

This failure does raise a SIGILL on the Octeon-III board as Rick documented here: https://v8m.slack.com/files/rick/F0653Q74M/gdb_on_mjsunit_debug-backtrace.sh and in the comments that follow, and in other comments on the _octeon3_ channel.

The real reason for SIGILL is that this real and valid instruction LDXC1 gets an unaligned access trap. The kernel then goes to the fp emulator code to try and fix this, and this board has a kernel missing a key patch required for supporting LDXC1. So the fp-emulator code thinks it is an illegal instruction. But it is just an alignment problem.

I do think any board without kernel alignment fixups will exhibit the problem.

**Comment by kilvadyb** [comment]
The problem is in the function TranslatedState::CreateNextTranslatedValue() as Paul expected but in the Translation::DOUBLE_STACK_SLOT case of the switch. With the following patch I printed out the values:

```
@@ -3084,7 +3085,9 @@ TranslatedValue TranslatedState::CreateNextTranslatedValue(

     case Translation::DOUBLE_STACK_SLOT: {
       int slot_offset = SlotOffsetFp(iterator->Next());
+      fprintf(stderr, "address: %p, slot offset: %d\n", fp, slot_offset);
       double value = *(reinterpret_cast<double*>(fp + slot_offset));

```

The printed address and offset match to the values of v0, v1 registers of ldxc1 in the debugger when the SIGILL is caught:

```
   0x004b5358 <+308>:   lw  v1,248(sp)
   0x004b535c <+312>:   sll v0,v0,0x2
=> 0x004b5360 <+316>:   beqz    s2,0x4b5394 <_ZN2v88internal15Translated...>
   0x004b5364 <+320>:   ldxc1   $f20,v1(v0)
```

In the C++ code fp holds the base address and is not 8 byte aligned. The easiest fix would be to use READ_DOUBLE_FIELD() macro from object-inl.h.

**Comment by kilvadyb** [comment]
quick fix:

```
diff --git a/src/deoptimizer.cc b/src/deoptimizer.cc
index 2921d89..935f869 100644
--- a/src/deoptimizer.cc
+++ b/src/deoptimizer.cc
@@ -12,6 +12,7 @@
 #include "src/full-codegen.h"
 #include "src/global-handles.h"
 #include "src/macro-assembler.h"
+#include "src/objects-inl.h"
 #include "src/prettyprinter.h"


@@ -3084,7 +3085,7 @@ TranslatedValue TranslatedState::CreateNextTranslatedValue(

     case Translation::DOUBLE_STACK_SLOT: {
       int slot_offset = SlotOffsetFp(iterator->Next());
-      double value = *(reinterpret_cast<double*>(fp + slot_offset));
+      double value = READ_DOUBLE_FIELD(fp, slot_offset);
       if (trace_file != nullptr) {
         PrintF(trace_file, "%e ; (double) [fp %c %d] ", value,
                slot_offset < 0 ? '-' : '+', std::abs(slot_offset));
diff --git a/src/objects-inl.h b/src/objects-inl.h
index 700ae04..79c0477 100644
--- a/src/objects-inl.h
+++ b/src/objects-inl.h
@@ -1245,7 +1245,7 @@ MaybeHandle<Object> JSProxy::SetElementWithHandler(Handle<JSProxy> proxy,
     heap->RecordWrite(object->address(), offset);                       \
   }

-#define CONDITIONAL_WRITE_BARRIER(heap, object, offset, value, mode) \
+#define CONDITIONAL_WRITE_BARRIER(heap, object, offset, value,  mode) \
   if (mode != SKIP_WRITE_BARRIER) {                                  \
     if (mode == UPDATE_WRITE_BARRIER) {                              \
       heap->incremental_marking()->RecordWrite(                      \
@@ -7348,7 +7348,7 @@ String::SubStringRange::iterator String::SubStringRange::end() {
 #undef NOBARRIER_WRITE_FIELD
 #undef WRITE_BARRIER
 #undef CONDITIONAL_WRITE_BARRIER
-#undef READ_DOUBLE_FIELD
+//#undef READ_DOUBLE_FIELD
 #undef WRITE_DOUBLE_FIELD
 #undef READ_INT_FIELD
 #undef WRITE_INT_FIELD
```

**Comment by paul99** [comment]
OK, I can clearly see that case DOUBLE_STACK_SLOT is problematic, since fp will have 4-byte alignment. 

But is DOUBLE_REGISTER guaranteed to be safe, or did we get 'lucky' for now? (Is the `RegisterValues* registers` guaranteed to be 8-byte aligned?)

And I'm not sure we can add the include and drop the undef at the end. Do you think they will take this, or do we need to duplicate the READ_DOUBLE_FIELD here?

**Comment by kilvadyb** [comment]
I don't think removing the #undef would be accepted. If we can create a HeapNumber from the address and offset for example then using HeapNumber::value() would be a clean solution:

```
double HeapNumber::value() const {
  return READ_DOUBLE_FIELD(this, kValueOffset);
}
```

I try to find a clean way to use READ_DOUBLE_FIELD(). Would be nice to avoid duplication.

I am not sure about DOUBLE_REGISTER case of the switch. RegisterValues class has 2 data members where kNumRegisters is 32 on mips so the base address of double_registers_ is 'this' + 32 \* 4 on 32 bits. So if we can trust in 'this' is 8 byte aligned then double_registers_ also.:

```
class RegisterValues {
...
  intptr_t registers_[Register::kNumRegisters];
  double double_registers_[DoubleRegister::kMaxNumRegisters];
};
```

A #pragma pack could be used. Can we trust in 'this' of instances of RegisterValues?

**Comment by kilvadyb** [comment]
Strange that in debug mode I got an other SIGILL:

```
   0x77e23578 <+184>:   mfc1    a2,$f0
=> 0x77e2357c <+188>:   mfhc1   a3,$f0
   0x77e23580 <+192>:   sw  a2,8(sp)
   0x77e23584 <+196>:   sw  a3,12(sp)
```

**Comment by kilvadyb** [comment]
The debug failure must be core/FP problem. With `taskset -c 0 ...` the test passed with `taskset -c 1 ...` I got the SIGILL crash.

**Comment by paul99** [comment]
Yup, was just looking up older issue https://github.com/paul99/v8m-rb/issues/102 -- that's exactly it

**Comment by paul99** [comment]
Balázs fixed this in https://codereview.chromium.org/1193433002  https://crrev.com/0acc511e62fbd717e335c700012de47827fe0630

Generic double ReadDoubleValue(const void\* p) & WriteDoubleValue(void\* p, double value) were moved to utils.h so they can be accessed from (almost) anywhere.
