### ISSUE TITLE
Mozilla debug fails, related to j, maybe to code-range changes

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#149]
This is a DCHECK in mips64 on 'j' instruction, most likely from long-branch usage, debug Mozilla. 

Test: mozilla/js1_5/Regress/regress-80981

```
# Fatal error in ../src/mips64/assembler-mips64.cc, line 1414
# Check failed: in_range && ((target & 3) == 0).
```

https://v8.mips.com/bbv8/builders/Sim%20-%20MIPS64%20-%20Debug%20-%20edge%20-%20mozilla/builds/3911

https://v8.mips.com/bbv8/builders/Sim%20-%20MIPS64%20-%20Debug%20-%20edge%20-%20mozilla/builds/3911/steps/Mozilla%20%28flakes%29/logs/regress-80981

This is not repeatable but the mips64 builder has suspicious fails at these builds also:

https://v8.mips.com/bbv8/builders/Sim%20-%20MIPS64%20-%20Debug%20-%20edge%20-%20mozilla/builds/3912
https://v8.mips.com/bbv8/builders/Sim%20-%20MIPS64%20-%20Debug%20-%20edge%20-%20mozilla/builds/3914

Can you PTAL, Dusan?

**Comment by dusmil** [comment]
It was subtle bug after all, thank you for reporting.
Fixed in:https://codereview.chromium.org/1216823003/
We will watch buildbot for verification since it is very hard to reproduce.

**Comment by paul99** [comment]
The change in https://codereview.chromium.org/1216823003/ had an issue (in comments), and was never landed. So this issue is still open.

**Comment by paul99** [comment]
Dusan updated https://codereview.chromium.org/1216823003/ just before he left. I have not reviewed it yet. I will try to do so tomorrow. Ákos, can you also review this one. I am assigning it to you now.

Even if this passes our reviews tomorrow, I want to wait and land this only _after_ the tree is opened, and we have a day or so of testing history. 

Right now we have a lot in the CQ, and I'm sure Google does also. There's gonna be a flood of new things landing, and I want to see some stability on the BB before we land this.

**Comment by paul99** [comment]
Dusan's CL  https://codereview.chromium.org/1216823003/ fixed this issue, but had a typo that caused a diff failure in `mjsunit/regexp-captures`, `mjsunit/string-slices-regexp`, `mjsunit/regress/regress-crbug-178790`. 

I approved his CL, and fixed the small j->jal issue on landing. 

https://crrev.com/38501327599ae6ac7c255205c61c00aeed09da13

Verfiied on the bots, closing.
