### ISSUE TITLE
mips64 fails test-spaces/SizeOfFirstPageIsLargeEnough

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#150]
This test started failing consistently after https://codereview.chromium.org/1199113003 - https://crrev.com/325fbd0e243f6d43c977452651cf4be9a0dad727

BB test for that CL: https://v8.mips.com/bbv8/builders/Sim%20-%20MIPS64%20-%20edge/builds/3867

Balázs, can you PTAL?

**Comment by kilvadyb** [comment]
I tried to find out how to increase the size of the (first) page but no working patch yet. But the CL where the bug raised contains a special config for arm64 in cctest.status:
   # BUG(v8:4200).
 159   'test-spaces/SizeOfFirstPageIsLargeEnough': [PASS, FAIL],

**Comment by paul99** [comment]
Can you test this on arm64 sim?

**Comment by paul99** [comment]
I tested on arm64 sim, and it does fail. I did add a comment about mips64 to v8:4200
https://code.google.com/p/v8/issues/detail?id=4200

**Comment by paul99** [comment]
This was put on the skip list by Dan Ehrenberg at Google, per issue https://code.google.com/p/v8/issues/detail?id=4200 - CL https://codereview.chromium.org/1212963004/

Will leave this issue open until this is resolved. It may be resolved by Google, or we might need to take a look. I will drop it to pri-3 for now.

**Comment by kisg** [comment]
According to https://codereview.chromium.org/1507363002/ this issue was fixed for arm, need to check if it is fixed for MIPS as well and remove the test from the skip list.

**Comment by ibogosavljevic** [comment]
Issue is fixed, see https://v8.mips.com/bbv8/builders/Sim%20-%20MIPS64%20-%20edge/builds/6662/steps/Check/logs/stdio
