### ISSUE TITLE
Check float min/max on mipsr6

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#151]
Balázs mentioned this in https://v8m.slack.com/archives/porting/p1435065563000085

This CL & Issue show that Float64Min() is different on arm64 from x64, and the x64 behavior is correct. In arm they have quit supporting these min/max ops for now.

Statement from Jacob B. was that mips-r6 was like arm64.

https://codereview.chromium.org/1200123004
https://code.google.com/p/v8/issues/detail?id=4206

We need to investigate, avoid use for now, and find a fix (Arm may have a solution using other instructions).

**Comment by kilvadyb** [comment]
The CL contains a new test: mjsunit/compiler/regress-4206. This test passes on mips64elR6 sim but fails on qemu-mips64elR6 in the turbo test:

```
=== mjsunit/compiler/regress-4206 ===                    
/data/kilvadyb/v8-hw/v8/test/mjsunit/mjsunit.js:178: Failure: expected <0> found <-0>
    throw new MjsUnitAssertionError(message);
    ^
Error
    at new MjsUnitAssertionError (/data/kilvadyb/v8-hw/v8/test/mjsunit/mjsunit.js:31:16)
    at fail (/data/kilvadyb/v8-hw/v8/test/mjsunit/mjsunit.js:178:11)
    at assertEquals (/data/kilvadyb/v8-hw/v8/test/mjsunit/mjsunit.js:248:7)
    at /data/kilvadyb/v8-hw/v8/test/mjsunit/compiler/regress-4206.js:23:19
Command: qemu-mips64el -R 2147483648 -cpu I6400 /data/kilvadyb/v8-hw/v8/out/mips64el.release/d8 --test --random-seed=1287609924 --turbo --always-opt --nohard-abort --nodead-code-elimination --nofold-constants /data/kilvadyb/v8-hw/v8/test/mjsunit/mjsunit.js /data/kilvadyb/v8-hw/v8/test/mjsunit/compiler/regress-4206.js
```

I will create a CL to turn min/max to `{ UNREACHABLE(); }` while there is no better solution.

**Comment by dusmil** [comment]
Right, go ahead.

**Comment by kilvadyb** [comment]
I tried to test mips32re LE with quemu if the min/max test fails but I could not make a 32 bits r6 build which is good for qemu. So I decided to make a CL to remove min/max from 32 and 64 bits. The 64 bits build caused many round and truncate failures. The CL is extremely simple so I am surprised and will investigate it.

**Comment by paul99** [comment]
Balázs, I know your CL to remove it landed long ago: https://codereview.chromium.org/1204903004

Is there something else that must be done here with qemu? 

I think the instructions on the wiki for building for qemu might have been updated in this timeframe. Maybe you should try that again, as we have several r6 bugs to chase. But that work does not need to be done under this issue. You can probably close this as complete.

**Comment by kilvadyb** [comment]
I hoped that arm guys found a solution quickly but VisitFloat*[Max|Max]() functions are still UNREACHABLE() on arm64 so I close this issue.
