### ISSUE TITLE
mjsunit/asm/int32div fail on mips64, erpro8

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#154]
It's failing consistently on the bots, only --stress-opt --always-opt:
https://v8.mips.com/bbv8/builders/Target%20-%20MIPS64%20-%20edge/builds/1594

Cryptic error message: `Failure: expected <-2147483648> found <-2147483648>`

I just tried it on a Cavium Octeon-III board (with FPU) and it _does not fail_.

So I suspect some problem with the kernel FPU emulator, possibly with a negative-0 problem.

We do need to track this down.

It started failing at https://v8.mips.com/bbv8/builders/Target%20-%20MIPS64%20-%20edge/builds/1442

Build 1441 and earlier look clean for this bug (I did not check every single build).

Assigning to Ákos.

**Comment by paul99** [comment]
I was apparently mistaken about erpro-8 statement, this _does_ fail on Octeon-III board with FPU also.

Same failure message, and only on the `--stress-opt --always-opt` variant.

**Comment by paul99** [comment]
This is fixed by Ákos https://codereview.chromium.org/1265603002/ , which is stuck in the CQ right now. Let's leave this open until it lands and we see it working on the bots.

**Comment by paul99** [comment]
Replaces the 64-bit div instruction with 32-bit division in DivI.
Also fixes the Ddiv implementation in the simulator.
TEST=mjsunit/asm/int32div

Landed today https://crrev.com/437c789a26960e6902fe7f905c6b7dc5784c8c9b
Verified on the bots. Closing.

**Comment by paul99** [comment]
Miran sent me a slack message about this fix, and his suspicion that it should be fixed same way in FlooringDiv. @palfia, can you please take a another look? @mkaric can you see if you can adapt the (previously failing) test to provoke a failure on either boards or sim?

> Hello, Paul. I have a comment related to issue #154, which is closed, but as you may know I've been preparing to start working on v8 before I was in the team officially, so I was looking at this issue while it was still unresolved. It was fixed by changing the line:

```
__ Ddiv(result, dividend, divisor);
```

> into:

```
__ Div(result, dividend, divisor);
```

> in lithium-codegen-mips64.cc in function void LCodeGen::DoDivI(LDivI\* instr);
> 
> There is another function, void LCodeGen::DoFlooringDivI(LFlooringDivI\* instr) in lithium-codegen-mips64.cc where I believe the same correction should be done (it has the same line __ Ddiv(result, dividend, divisor);). I've been trying to run tests on our board with and without this change but the board keeps crashing. From what I did manage to run it seems this change doesn't make new failures. I wanted to ask you to have a look. It is probably something that would cause errors in the future.

**Comment by palfia** [comment]
Yes, Miran's right. Thanks for calling our attention. The FlooringDivI should also be corrected to use Div instead of Ddiv. The arm64 port uses Sdiv with 'w' registers, so they also do a 32-bit divide here.

**Comment by mkaric** [comment]
I modified int32div.js test to execute DoFlooringDivI function instead of DoDivI in v8, but the test passes. It also passes with the correction.

**Comment by mkaric** [comment]
hdiv->CheckFlag(HValue::kAllUsesTruncatingToInt32) returns false in DoFlooringDivI, and true in DoDivI. This causes the check:

```
// Check for (kMinInt / -1).
if (hdiv->CheckFlag(HValue::kCanOverflow) &&
    !hdiv->CheckFlag(HValue::kAllUsesTruncatingToInt32)) {
  Label left_not_min_int;
  __ Branch(&left_not_min_int, ne, dividend, Operand(kMinInt));
  DeoptimizeIf(eq, instr, Deoptimizer::kOverflow, divisor, Operand(-1));
  __ bind(&left_not_min_int);
}
```

to deoptimize in DoFlooringDivI and not in DoDivI, and that is why the test never fails in DoFlooringDivI and fails in DoDivI. If I comment out this check in DoFlooringDivI, the test fails.

**Comment by paul99** [comment]
OK, so is that then the final proof that we do need to fix the FlooringDiv as we did with the DoDiv()? If so, please prepare a CL for this.

**Comment by mkaric** [comment]
Not a proof because as I said DoFlooringDivI will deoptimize. I think the question is why DoDivI doesn't. Both functions do the same thing, only DoFlooringDivI substracts 1 from the result if the remainder is not 0 and result negative. I looked at DoMathAbs, the same case of kMinInt/-1 (actually 0-kMinInt) is covered here and we still deoptimize if the result is kMinInt. I think DoDivI should also deoptimize then in the case of kMinInt/-1.

**Comment by paul99** [comment]
Since we cannot repro a failure in DoFlooringDivI, let's just put this on hold for now. We have more important issues to work on. I've assigned this to Miran (who's done most of the recent work), but it is on hold, so we will come back to it later.

**Comment by mkaric** [comment]
My conclusion is that there will be no difference if Ddiv or Div is used in DoFlooringDivI function. We can make the change if we want to make the code analogous to arm64. If not the issue can be closed.
