### ISSUE TITLE
TEST(sqrt_rsqrt_recip) fails on mips32r1

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#155]
The rsqrt.fmt and recip.fmt instructions are mips32r2 (and later) only. So this test fails on mips32r1.

Test was introduced in https://codereview.chromium.org/1147493002.

Can you either exclude the entire test for r1 platforms, or maybe continue to test sqrt.fmt, but not test the other two?

**Comment by djpesic** [comment]
Fix for issue is at https://codereview.chromium.org/1221663006. PTAL.

**Comment by paul99** [comment]
Landed as https://crrev.com/2604c75eeda875e3e95e957cd886b481c55e1d62.
Fixed the bots. Thanks!
Closing.
