### ISSUE TITLE
back-merge MIPS: Fix Assembler::dd(Label*) implementation. to 4.3 branch

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#159]
Ákos, please back-merge this to 4.3. I am pretty sure this fix was done in the 4.4 timeframe, so it won't need anything there.

https://codereview.chromium.org/1127393003
https://crrev.com/3f7b797c1e066cd2a86508a051599624134f597a

**Comment by palfia** [comment]
Closing, merged: https://codereview.chromium.org/1224623018/
https://chromium.googlesource.com/v8/v8/+/8c28e488ea8774dc5a09d689c2731467b0a685f5
