### ISSUE TITLE
New commit ad7f35c49 breaks TF box2d

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#160]
https://codereview.chromium.org/1235663002
 https://crrev.com/ad7f35c49aa94b2bc625fe59a5e9251ef2645889 breaks mips embenchen box2d. 

We now take some unimplemented code paths.

http://build.chromium.org/p/client.v8/builders/V8%20Linux%20-%20mipsel%20-%20sim/builds/1694

**Comment by dusmil** [comment]
Fixed in: https://codereview.chromium.org/1234533004/

**Comment by paul99** [comment]
Landed as https://crrev.com/686e3abf66bd0bbb1d2419d0149992e042fea153. Closing.
