### ISSUE TITLE
mips64 string errors after 'c63e50ed Reland Update V8 DEPS.'

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#161]
Lots of string errors (27 check, 30 webkit, 10 test262) on hardware and sim.

It has nothing to do with the clang roll, but it is this simple change in StringCharFromCodeGenerator::GenerateFast(), to get past a clang warning:

```
-  DCHECK(base::bits::IsPowerOfTwo32(String::kMaxOneByteCharCode + 1));
-  __ And(a4,
-         code_,
-         Operand(kSmiTagMask |
-                 ((~String::kMaxOneByteCharCode) << kSmiTagSize)));
+  DCHECK(base::bits::IsPowerOfTwo32(String::kMaxOneByteCharCodeU + 1));
+  __ And(a4, code_, Operand(kSmiTagMask |
+                            ((~String::kMaxOneByteCharCodeU) << kSmiTagSize)));
```

The code in this function was broken, improperly ported from mips32, not doing Smi handling correctly.

The old signed `kMaxOneByteCharCode` caused the test for fast-path to always fail, and the code always went slow path thru runtime, and _worked_.

With the unsigned `kMaxOneByteCharCodeU`, the sign-extension does not happen -- and that results in code that erroneously goes to fast-path all the time, whether it should or not. And that is _broken_.

I've fixed this, so it only goes fast-path on 1-byte chars -- but it is _still broken_. 

I suspect that other code that handles the `SingleCharacterStringCache` must be bad.

Here's my (partial) fix:

```
diff --git a/src/mips64/code-stubs-mips64.cc b/src/mips64/code-stubs-mips64.cc
index b8204b3..0341456 100644
--- a/src/mips64/code-stubs-mips64.cc
+++ b/src/mips64/code-stubs-mips64.cc
@@ -3204,21 +3204,17 @@ void StringCharFromCodeGenerator::GenerateFast(MacroAssembler* masm) {
   DCHECK(!a4.is(result_));
   DCHECK(!a4.is(code_));

-  STATIC_ASSERT(kSmiTag == 0);
-  DCHECK(base::bits::IsPowerOfTwo32(String::kMaxOneByteCharCodeU + 1));
-  __ And(a4, code_, Operand(kSmiTagMask |
-                            ((~String::kMaxOneByteCharCodeU) << kSmiTagSize)));
-  __ Branch(&slow_case_, ne, a4, Operand(zero_reg));
-
+  __ JumpIfNotSmi(code_, &slow_case_);
+  __ Branch(&slow_case_, hi, code_,
+            Operand(Smi::FromInt(String::kMaxOneByteCharCode)));

   __ LoadRoot(result_, Heap::kSingleCharacterStringCacheRootIndex);
   // At this point code register contains smi tagged one_byte char code.
```

**Comment by paul99** [comment]
I got rid of a4 register use but that made no improvement (current patch below).

I ran this a cut-down mjsunit/string-replace.js, and the fast path was taken only 4 times. The ones I examined looked correct. We returned cached strings of '9', ';', ';', ';', .

I verified on the last instance, that the char code was a 0x3b (as 64-bit Smi), and semi-colon is the correct string to return. Guessing there's a problem somewhere else, but I'm not seeing it yet.

```
diff --git a/src/mips64/code-stubs-mips64.cc b/src/mips64/code-stubs-mips64.cc
index b8204b3..b94c5a9 100644
--- a/src/mips64/code-stubs-mips64.cc
+++ b/src/mips64/code-stubs-mips64.cc
@@ -3200,25 +3200,17 @@ void StringCharCodeAtGenerator::GenerateSlow(

 void StringCharFromCodeGenerator::GenerateFast(MacroAssembler* masm) {
   // Fast case of Heap::LookupSingleCharacterStringFromCode.
-
-  DCHECK(!a4.is(result_));
-  DCHECK(!a4.is(code_));
-
-  STATIC_ASSERT(kSmiTag == 0);
-  DCHECK(base::bits::IsPowerOfTwo32(String::kMaxOneByteCharCodeU + 1));
-  __ And(a4, code_, Operand(kSmiTagMask |
-                            ((~String::kMaxOneByteCharCodeU) << kSmiTagSize)));
-  __ Branch(&slow_case_, ne, a4, Operand(zero_reg));
-
+  __ JumpIfNotSmi(code_, &slow_case_);
+  __ Branch(&slow_case_, hi, code_,
+            Operand(Smi::FromInt(String::kMaxOneByteCharCode)));

   __ LoadRoot(result_, Heap::kSingleCharacterStringCacheRootIndex);
   // At this point code register contains smi tagged one_byte char code.
-  STATIC_ASSERT(kSmiTag == 0);
-  __ SmiScale(a4, code_, kPointerSizeLog2);
-  __ Daddu(result_, result_, a4);
+  __ SmiScale(at, code_, kPointerSizeLog2);
+  __ Daddu(result_, result_, at);
   __ ld(result_, FieldMemOperand(result_, FixedArray::kHeaderSize));
-  __ LoadRoot(a4, Heap::kUndefinedValueRootIndex);
-  __ Branch(&slow_case_, eq, result_, Operand(a4));
+  __ LoadRoot(at, Heap::kUndefinedValueRootIndex);
+  __ Branch(&slow_case_, eq, result_, Operand(at));
   __ bind(&exit_);
 }
```

**Comment by kilvadyb** [comment]
I created a test script:

```
ar a = new String('foobar');
for (var i = 0; i < a.length; i++) {
  print("#" + i + ": " + a.substring(i, i+1) + "\n");
}
```

`StringCharCodeAtGenerator::GenerateFast()` is called at index 0 and 2. It expects the char (ASCII) code in a2 (StringCharCodeAtGenerator::code_) as an smi value but a2 is SmiFromInt(102) (== 'f') in all calls. Looks like the caller (maybe `RUNTIME_FUNCTION(Runtime_SubStringRT)`) of the generated code from `StringCharCodeAtGenerator::GenerateFast()` should be fixed to use/set a2.

**Comment by paul99** [comment]
Fixed in https://codereview.chromium.org/1233903003/. I'll leave it open until it lands and survives the bots.

2nd problem was missing SmiTag() at end of SubStringStub,

**Comment by paul99** [comment]
Landed as https://crrev.com/88214f1bf8429311d26d8f85f2a1e4759cb3fe7e. Fixes issue. Closing.
