### ISSUE TITLE
Multiple r6 failures to fix

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#167]
This is a tracking issue for a variety of fails on r6. Builders for r6 running on Qemu have been recently enabled on the bots, and we have many issues to track down and fix.

I will create some specific bug issues, but in general, I would ask that those working on this activity look at the bots, pick an issue to investigate, create a specific github issue for it, and then fix and update the issue. As we fix issues, we can paste issue number and new failure counts into this tracking issue.

I suspect we have fewer real bugs than test failures, and each fix will likely fix more than a single test. The specific fixed tests should be clearly stated in the individual issues, and summarized here.

Please see https://github.com/paul99/v8m-rb/wiki/Running-tests-with-qemu-user-mode-for-R6 for building qemu and v8 for r6. (I think the cpu target for mipsel-linux-user is `mips32r6-generic`)

I'd like to suggest that Ákos and Balázs take the lead on this (Balazs, porting and port-reviews take priority over this, and try to make some progress on the sim refactoring as well -- we can talk via slack if there is any time left for this).

Here are the URLs of the builders, for mips32 & 64, release and debug:

https://v8.mips.com/bbv8/builders/Target%20-%20edge%20-%20mipsr6%2Cunder%20qemu
https://v8.mips.com/bbv8/builders/Target%20-%20MIPS64%20-%20edge%20-%20mipsr6%2Cunder%20qemu
https://v8.mips.com/bbv8/builders/Target%20-%20Debug%20-%20edge%20-%20mipsr6%2Cunder%20qemu%2Cquick
https://v8.mips.com/bbv8/builders/Target%20-%20MIPS64%20-%20Debug%20-%20edge%20-%20mipsr6%2Cunder%20qemu%2Cquick

Here are the tests failing on mips43r6 release (27 fails total in these tests):

```
ConvertDToI
QuietSignalingNaNs
Threading1
class_fmt
float64array-negative..
float64array-outofbou..
lua_binarytrees
min_max
mov
poppler
```

Note that `Threading1 is an artifact of at least the`QuietSignalingNaNs` test, and will go away once we fix all the rest of the cctests.

Mips64r6 release test fails:

```
BranchCombineInt32CmpI
BranchCombineInt32CmpP
DebuggerClearMessageH..
ExtensionsRegistration
NativeMethodMonomorph..
RunLoadElementFromUnt..
SetJitCodeEventHandler
TestSizeOfRegExpCode (not r6 specific, fails on mips64r2 now also)
regress-crbug-465564
```

**Comment by kisg** [comment]
These issues were already fixed.
