### ISSUE TITLE
mips32r6 QuietSignalingNaNs fail.

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#168]
This is an easy one. test-api.cc : 15819 & 15840 have lines like this:

```
#if (defined(V8_TARGET_ARCH_MIPS) || defined(V8_TARGET_ARCH_MIPS64)) && \
    !defined(_MIPS_ARCH_MIPS64R6) && !defined(USE_SIMULATOR)
```

Thes should have exclusion mips32r6, but do not. Ákos, can you please do a fix? This will have to get reviewed by Jakob or other v8-team member.

You might also look to see if there are NaN differences anywhere else:

For instance, cctest/test-assembler-mips/class_fmt fails like this:

```
# Fatal error in ../test/cctest/test-assembler-mips.cc, line 3383
# Check failed: bit_cast<int64_t>(t.dSignalingNan) == 0x001 (2 vs. 1).
```

**Comment by palfia** [comment]
Closing issue, the fix is landed: https://codereview.chromium.org/1311473007/
