### ISSUE TITLE
Qemu r6 failure: ConvertDToI

### ISSUE THREAD

**Issue by palfia** [v8mips/v8mips#169]
This test fails with the following output:

Test: cctest/test-code-stubs-mips/ConvertDToI
Flags: --nocrankshaft
Command: /mips/tools/mips/swpkgs/bin/qemu-mipsel-V8-prpl-i6400-mips64r6-PRIP4-32399a2 -R 2147483648 -cpu mips32r6-generic out/Release/cctest --random-seed=772700394 --nocrankshaft test-code-stubs-mips/ConvertDToI --nohard-abort --nodead-code-elimination --nofold-constants --testing_serialization_file=out/.serdes/serdes_ConvertDToI__nocrankshaft

Run #1
Exit code: -11
Result: CRASH
Expected outcomes: PASS
Duration: 00:00:326

Stderr:
qemu: uncaught target signal 11 (Segmentation fault) - core dumped

**Comment by paul99** [comment]
@palfia: DoubleToIStub() uses `DoubleRegister double_scratch = kLithiumScratchDouble;` and `kLithiumScratchDouble` is `f30`, which is a callee-saved double. 

(It's possible that I have https://github.com/paul99/v8m-rb/issues/171 too much on my mind now, but please try this...)

Suggest you add save/restore of FPU regs to the MakeConvertDToIFuncTrampoline(), as is done in JSEntryStub()  [example for save only, but obviously we need both]:

```
// Save callee saved registers on the stack.
__ MultiPush(kCalleeSaved | ra.bit());

// Save callee-saved FPU registers.
__ MultiPushFPU(kCalleeSavedFPU);
```

I don't think you need to init kDoubleRegZero, but it would not hurt.

**Comment by palfia** [comment]
Yes, indeed the JIT code overwrites the callee-saved f30 register which breaks the C code, it bites us again.. I've added the save/restore code and the test works fine. Thanks @ilijapavlovic, nice investigation!

I've uploaded a CL, PTAL: https://codereview.chromium.org/1337023002

**Comment by paul99** [comment]
This was fixed by above CL, landed as https://crrev.com/a795aa350f4d62ccbd8ea2ec297e1d844229ba4a. Verified fix on the bots. closing.
