### ISSUE TITLE
Qemu mipr32r6 and mips64r6 failure: min_max and mina_maxa

### ISSUE THREAD

**Issue by djpesic** [v8mips/v8mips#172]
cctest/test-assembler-mips/min_max fails in debug and release mode with:
Fatal error in ../test/cctest/test-assembler-mips64.cc, line 1607
 Check failed: test.c == outputsdmin[i](nan vs. 3).

Command:
 tools/run-tests.py -j8 --arch=mips64el --mode=debug  --timeout=20000   --no-presubmit  --command-prefix="qemu-mips64el -R 2147483648 -cpu mips64r6-generic" test-assembler-mips  'cctest/test-assembler-mips64/min_max'
All 4 variants fails.

**Comment by djpesic** [comment]
cctest/test-assembler-mips/mina_maxa fails in debug and release mode with:
Fatal error in ../test/cctest/test-assembler-mips.cc, line 1898
Check failed: test.resd == resd[i](-9.8 vs. 9.8).

Command:
tools/run-tests.py -j8 --arch=mipsel --mode=debug  --timeout=20000   --no-presubmit  --command-prefix="qemu-mipsel -R 2147483648 -cpu mips32r6-generic" test-assembler-mips  'cctest/test-assembler-mips/mina_maxa'
All 4 variants fails

**Comment by djpesic** [comment]
After some investigation, I suspect on wrong qemu behavior in following situation: when the first argument is NaN and the second argument is number (same for opposite) result is NaN, instead of number. For example: min NaN, 3.0 produces NaN, result should be 3.0. There are one more error in mina_maxa test, due to  misunderstanding of manual: mina result when absolute values of arguments are the same, but signs are the opposite. According to IEEE2008, result is negative number, not positive. This will be fixed. I also wrote C tests which proves wrong qemu behavior.
https://gist.github.com/djpesic/8cc5e33f9443e17ac4f6
When I insert patch from #170 in qemu, this problem does'n exist any more.

**Comment by djpesic** [comment]
Fix for an error in mina and new test cases.
https://codereview.chromium.org/1276813004/
PTAL

**Comment by paul99** [comment]
Landed: https://crrev.com/46fafcd706c0c161013c4904b69af0061d983d6f

Closing.
