### ISSUE TITLE
Add DCHECK for reg 'at' to macro-asm Branch()

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#180]
The BranchShort() macros trash the `at` register in some circumstances, but not in others. 

This usage is OK:

```
__ Branch(false_label, lt, at, Operand(FIRST_SPEC_OBJECT_TYPE));
```

These would not be:

```
__ Branch(false_label, eq, at, Operand(FIRST_SPEC_OBJECT_TYPE));
__ Branch(false_label, lt, at, Operand(123456));  // Operand > int_16
```

The differences are subtle, and therefore fragile. The use of `at` as `Register rs` in Branch() macros should be disallowed by adding an assertion: `DCHECK(!rs.is(at))`

I won't be surprised if we have to fix some existing usages after adding this, so please run ALL test suites after adding this, and fix any issues.

Assigning to Ilija.

**Comment by ilijapavlovic** [comment]
If `at` is allowed to use only in the class `MacroAssembler` (macro-assembler-mips[64].cc), does it mean that using `at` when `Branch()` is called from another files, is not allowed?
For example, in lithium-codegen-mips.cc register `at` is very often used. Is it allowed here to substitute `at` with `t8`?

**Comment by ilijapavlovic** [comment]
Also, it would be good to get additional details about this task.

**Comment by paul99** [comment]
Sorry, I did not define this task well. On further review, I see that most (all??) of the DCHECK()'s I thought were missing are actually here. I want to review this code in detail again. Assigning back to me.

**Comment by paul99** [comment]
So the issue that confused me here was that there are two versions of the BranchShort() macro:

```
MacroAssembler::BranchShort(int16_t offset, ... )
MacroAssembler::BranchShort(Label* L, ... )
```

When I was looking for the DCHECK()'s for 'at' register usage, I mistakenly looked in the first one, and they do not exist there. But `BranchShort(int16_t offset, ... )` is not used much, almost all usages are the Label version `BranchShort(Label\* L, ...) and that one does have the checks we need!

However, looking at this code, we have a huge function repeated twice, almost the same. This should be refactored, so that only one version is used, and does have the DCHECKS. 

@kilvadyb is working on such a refactor now, as part of the r6-compact branch usage. Assigning this to him.

**Comment by ilijapavlovic** [comment]
Certain reducing lines of code can be done with following macro-definitions:
```
#define CREATE_OFFSET(offset_size) \
  bits = offset_size; \
  if (!is_near(L, bits)) return false; \
  offset = GetOffset(offset, L, bits)

#define CREATE_SCRATCH_AND_OFFSET(offset_size) \
  bits = offset_size; \
  if (!is_near(L, bits)) return false; \
  scratch = GetRtAsRegisterHelper(rt, scratch); \
  offset = GetOffset(offset, L, bits)
```

**Comment by ilijapavlovic** [comment]
CL uploaded and ready for review:
 https://chromium-review.googlesource.com/574229

**Comment by ilijapavlovic** [comment]
Instead macro-definitions, function `CalculateOffset()` is introduced.

**Comment by ilijapavlovic** [comment]
CL landed:
https://chromium.googlesource.com/v8/v8/+/c32b128102c5c9c1e1b14ab86a75195153e78381
