### ISSUE TITLE
Understand/fix V8_ALIGNED() macro for Windows

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#181]
Regarding the mips64 alignment issue that BenT requested (and I think you were all copied on):

In https://codereview.chromium.org/1323663003/ patchset 3, I _thought_ I had a solution using V8_ALIGNED() that would work on all arch's, but you can see from the trybots that all the windows builders fail.

Example: http://build.chromium.org/p/tryserver.v8/builders/v8_win_compile_dbg/builds/7165/steps/compile/logs/stdio

```
FAILED: ninja -t msvc -e environment.x86 -- "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\amd64_x86\cl.exe" /nologo /showIncludes /FC @obj\test\cctest\compiler\cctest.test-run-native-calls.obj.rsp /c ..\..\test\cctest\compiler\test-run-native-calls.cc /Foobj\test\cctest\compiler\cctest.test-run-native-calls.obj /Fdobj\test\cctest\cctest.cc.pdb e:\b\build\slave\win\build\v8\test\cctest\compiler\test-run-native-calls.cc(1045) : error C2059: syntax error : 'identifier'
```

I'm hoping that one or more of you on the team have access to a Windows PC with Visual Studio and can investigate this as early as possible Monday. @ibogosavljevic , can you please coordinate the effort on this? 

To be clear, we don't care about alignment on x86 builds for Windows, but we do want a solution that works on mips64 Linux, and will compile on all arch's. (In a worst-case scenario, we could use #ifdef for MIPS64, but I really do not want to do this.)

It sure looks to me like the `V8_ALIGNED()` macro from `v8config.h` should work, and has a case for using `__declspec(align(n))` which seems to be the windows method of alignment, per https://msdn.microsoft.com/en-us/library/83ythb65.aspx and other references I have seen online.

Can you figure out: (a) am I calling this wrong, and how should I fix my CL? Or (b), is the V8_ALIGNED() macro really broken for windows (or some versions of windows), and how should it be fixed?

I did test the mips64 case carefully on my Linux machine, and it does fix the problem exposed on mips64-sim build, created in DEBUG mode, with clang. (see my email to v8-mips-ports, and some slack discussion with @palfia in #porting_requests.

**Comment by ibogosavljevic** [comment]
There is a problem with `__declspec(align(n))` directive. The parameter of alignment can only be a compile time constant expression, whereas in our case we provide `const int kDoubleSize    = sizeof(double)` as a parameter of alignment.  This is a known issue, see here http://computer-programming-forum.com/7-vc.net/fbdd26987ff6f71e.htm

Visual Studio 2015 supports standard C++ way of defining alignment using alignas directive, but this doesn't work for us if we want to support earlier versions as well.
There is a possibility to replace `const int kDoubleSize    = sizeof(double)` with `#define kDoubleSize 8`. It seems that there is no nice and easy way to do this.

**Comment by paul99** [comment]
Can I  use 'sizeof(double)' ?

If not, I will just use 8.

**Comment by ibogosavljevic** [comment]
sizeof(double) is unknown at compile time :(

**Comment by paul99** [comment]
Thanks! I hard-coded to 8. Closing.
