### ISSUE TITLE
Move Assembler::ldc1/sdc1to macro-assembler

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#182]
These 2 functions used to be quite simple in mips32, and we justified emitting them directly in assembler.

Now they are silly complicated, and we should move them to the macro-assembler as Ldc1() and Sdc1() and fix all usages.

There is some room for argument about what should be done with mips64. _All_ the load/store ops now include this usage of `LoadRegPlusOffsetToAt()`, which causes the emit of multiple instructions in the case there the offset is > int16.

```
void Assembler::lw(Register rd, const MemOperand& rs) {
  if (is_int16(rs.offset_)) {
    GenInstrImmediate(LW, rs.rm(), rd, rs.offset_);
  } else {  // Offset > 16 bits, use multiple instructions to load.
    LoadRegPlusOffsetToAt(rs);
    GenInstrImmediate(LW, at, rd, 0);  // Equiv to lw(rd, MemOperand(at, 0));
  }
}
```

I'd be open to input from the rest of the team, I could see leaving them in the assembler with all the rest, but I can also see the simple argument that: "multiple instructions means macro-assembler". Which means that all load/store ops would have to be moved & renamed.

This is low priority. Let's worry about it when the r6 and clang bugs are fixed. I am not assigning it yet, were can decide that later.

**Comment by ilijapavlovic** [comment]
Instructions `ldc1` and `sdc1` moved into macro-assembler.
CL:  https://codereview.chromium.org/2751973002/

**Comment by ilijapavlovic** [comment]
CL for MIPS32 is landed as: https://chromium.googlesource.com/v8/v8/+/47da8de250ca2b9ba37f69d7520bbf9df1ab127d

**Comment by ilijapavlovic** [comment]
CL for MIPS64: https://codereview.chromium.org/2829073002/

**Comment by ilijapavlovic** [comment]
Landed as https://chromium.googlesource.com/v8/v8/+/cc797ac06cad5e6e2ec2735f4648004c87066c83

**Comment by ilijapavlovic** [comment]
The tests on build-bots are successful.
