### ISSUE TITLE
Benchmark branch-delay-slot performance

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#188]
**_Background:**_

When we start optimizing for r6, we will want to use compact-branches wherever possible. 

Mostly likely we will refactor the Branch() macro-assembler instruction to use compact branches when we are building for r6, and existing branches when building for r2.

One problem with this approach is we have delay-slot usage distributed throughout our source code, by the _callers_ of the __ Branch() instruction. Example:

```
__ Branch(USE_DELAY_SLOT, &loop, ne, object_prototype, Operand(null));
__ lw(object_map, FieldMemOperand(object_prototype, HeapObject::kMapOffset));
```

Compact branches do not support the `delay-slot`, in fact that is a major advantage as we do a very poor job of filling delay slots on average, so it's much better for the CPU to not utilize that slot. (I'll skip a possible digression about delay slot filling optimizations).

So please note that to use a r6 branch (likely `BNEQC` in this case) we would _logically_ want to do this:

```
__ lw(object_map, FieldMemOperand(object_prototype, HeapObject::kMapOffset));
__ Branch(&loop, ne, object_prototype, Operand(null));
```

While we could figure out some complicated _"delayed-macro-assembler"_ to somehow automatically re-order these instructions for us in the r6, that would be complex.

**_The actual request:**_

Let's start by figuring out exactly what performance advantage we get in r2 by the _current_ delay-slot usage.

If the perf difference is small (as I expect), we could just abandon this optimization for 'r2' in order to make 'r6' easier. If it is large, then we will examine the more complex solutions.

Note that we do _not_ have to abandon `Ret(USE_DELAY_SLOT)` - we can keep that for r2 and r6. In r6 we can still use `jr(ra); delay_slot_instr();`, the same as in r2. But in the case without delay-slot (`Ret();`), for r6 we can use `jic(ra, 0);` to do a single-instruction return.

I'd like to run a benchmark with Octane, Kraken, Sunspider on several boards. We must include the Cavium Octeon-II and Octeon-III in this test. We should also include CI-20. I'd prefer to do both mips32 and mips64, but let's start with mips32 only.

I'd like to have the source patched to "undo" all the delay-slot usage on branches, and benchmark before and after. Please push the code to github/v8mips so we have the test-source (and the baseline rev), and can do further experiments in the future.

A quick grep shows there are only 116 instances of `Branch(USE_DELAY_SLOT, ...)` in the code for both mips32 and mips64. So we can just 'undo' these manually in an editor. (there are 102 `Ret(USE_DELAY_SLOT);` which we leave as is). We should also undo the `BranchF()` variants for this test.

There are a couple other variants, like `JumpIfSmi(src, smi_case, at, USE_DELAY_SLOT);`. Please figure out the sensible thing there.

**Comment by paul99** [comment]
I over complicated this. Easy to keep delay slot Branch() usage in r6 - just use existing r2 branches in those  cases. No reordering of instr needed. 

Measurement would still be very interesting, but let's hold off for now if you've not done it already.

**Comment by ibogosavljevic** [comment]
Agreed, I am stopping the investigation. Just as a sidenote, removing instructions from the delay slot is a non-trivial task, e.g. if the register value which is used in the branch is modified directly in the delay slot or at register is used in the delay slot; in these cases we cannot move the instruction from the delay slot before the branch

**Comment by paul99** [comment]
I think this was un-necessary. I am closing.
