### ISSUE TITLE
test262 return-normalized-string fails on mips32eb

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#194]
The single test `test262/built-ins/String/prototype/normalize/return-normalized-string`  has been failing for quite some time on big-endian mips32 build. We don't test test262 on mips64eb, so I don't know if it fails there as well. That should be checked.

It worked on build https://v8.mips.com/bbv8/builders/Target%20-%20big%20-%20edge%20-%20test262%20-%20no%20i18n/builds/4453

It started failing on next build 4454, and still fails now on build 4606.

Ivica, can you take a look, or assign one of the other guys to this?

**Comment by mkaric** [comment]
The problem here is missing i18n support for big endian targets. For BE targets we compile with i18nsupport=off. When I compiled v8 for mipsel with i18nsupport=off the test failed with the same message. i18n is needed to perform normalizations executed in this test.

**Comment by paul99** [comment]
@mkaric was that test added, or revised in the revision range when we started getting this failure?

The test runner has --no-i18n option, which is supposed to remove all tests that require i18n support. These tests are all in test/intl dir. 

My proposal is that we suggest moving this test to that dir. If you can answer the questions above about the history, I can suggest moving this test to 'intl' to the Google infrastructure guys. 

If you have a better idea, please let me know.

Related: https://github.com/paul99/v8m-rb/issues/197

**Comment by mkaric** [comment]
The commit that started the failure says it copied test262-es6 into test262. I checked now and problematic tests were in test262-es6 so they started executing at this point. These tests in test/test262/data/test/built-ins/String/prototype/normalize fail:
return-normalized-string.js
return-normalized-string-from-coerced-form.js
return-normalized-string-using-default-parameter.js
so all three should then be moved to intl dir.

**Comment by paul99** [comment]
On 2015-10-18 @mkaric said this in slack:

> I checked the status file and those three problematic tests are already skipped for no_i18n and debug mode only.

```
['no_i18n == True and mode == debug', {
  # BUG(v8:4437).
  'built-ins/String/prototype/normalize/return-normalized-string': [SKIP],
  'built-ins/String/prototype/normalize/return-normalized-string-from-coerced-form': [SKIP],
  'built-ins/String/prototype/normalize/return-normalized-string-using-default-parameter': [SKIP],
}],  # no_i18n == True and mode == debug
```

I was probably wrong above, I don't think we can move tests from test262 to intl.

So, we should either add the release & opt debug modes (actually, just remove the `mode` clause and always skip when `no_i18n == True`.)

But let's hold until we figure out https://github.com/paul99/v8m-rb/issues/197

**Comment by paul99** [comment]
I added a patch to the big-endian test-262 builder to skip those 3 tests for all modes (I removed the 'and mode == debug' part of the condition). This should get that build green again, until we get proper i18n support.

**Comment by mkaric** [comment]
With i18n support for big endian added, it is now safe to enable the 3 test262 tests that require i18n support, I will prepare a CL.

**Comment by mkaric** [comment]
The 3 tests were actually skipped using a patch on big endian test262 builder, with patch removed they are executed and pass, closing.
