### ISSUE TITLE
mips64r6 test fails on simulator

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#198]
As discussed on slack, we have a bunch of test failing on v8-simulator for r6. For reasons I do not understand, they do not all show up on buildbot.

Here is a run based on commit https://chromium.googlesource.com/v8/v8/+/fa4f5553736af3c23e72a95884ad7d24ad9aee31

```
38 failed in file 1026a-check-od-64r6.log:
mjsunit/asm/embenchen/corrections
mjsunit/asm/embenchen/corrections
mjsunit/asm/embenchen/fasta
mjsunit/asm/embenchen/fasta
mjsunit/asm/embenchen/zlib
mjsunit/asm/embenchen/zlib
mjsunit/asm/uint32div
mjsunit/asm/uint32mod
mjsunit/asm/uint32div
mjsunit/asm/uint32mod-constant
mjsunit/asm/uint32mod
mjsunit/asm/uint32mod-constant
mjsunit/asm/int32-udiv
mjsunit/asm/uint32mod
mjsunit/asm/uint32mod-constant
mjsunit/asm/uint32div
cctest/test-run-machops/RunUint32ModP
cctest/test-simplified-lowering/RunNumberDivide_2_TruncatingToUint32
cctest/test-simplified-lowering/RunNumberDivide_TruncatingToUint32
cctest/test-run-machops/RunUint32MulHighP
cctest/test-run-machops/RunUint32DivP
cctest/test-simplified-lowering/RunNumberModulus_TruncatingToUint32
mjsunit/asm/int32-udiv
mjsunit/asm/int32-udiv
cctest/test-run-machops/RunUint32DivP
cctest/test-run-machops/RunUint32ModP
cctest/test-run-machops/RunUint32DivP
cctest/test-run-machops/RunUint32ModP
cctest/test-run-machops/RunUint32MulHighP
cctest/test-simplified-lowering/RunNumberDivide_TruncatingToUint32
cctest/test-simplified-lowering/RunNumberDivide_TruncatingToUint32
cctest/test-run-machops/RunUint32MulHighP
cctest/test-simplified-lowering/RunNumberDivide_2_TruncatingToUint32
cctest/test-simplified-lowering/RunNumberModulus_TruncatingToUint32
cctest/test-simplified-lowering/RunNumberModulus_TruncatingToUint32
cctest/test-simplified-lowering/RunNumberDivide_2_TruncatingToUint32
mjsunit/asm/poppler/poppler
mjsunit/asm/poppler/poppler
```

Ákos has been looking at one of the RunNumberDivide_2_TruncatingToUint32.

If there is extra time on the RTRK team, why don't one of you start looking at one of the other tests in parallel. I believe that these tests all pass on qemu and hw, but verifying that might be a good place to start.

the log file is in Dropbox/mips/logs/1026a-check-od-64r6.log

**Comment by ibogosavljevic** [comment]
Djordje is looking at mjsunit/asm/uint32div and Ilija is looking at cctest/test-run-machops/RunUint32ModP

**Comment by paul99** [comment]
Fixed in sim by Dusan. We were missing some r6 instructions, so the sim was erroneously executing DIVU,MODU,MULU,MUHU using r2 instructions.

https://codereview.chromium.org/1425003003/
Landed as https://crrev.com/4cd3c1696700e561f2fb6b78a97c31d8857e783c

Fixes all r6 sim fails, except for reg-exa size problems on release build. (I will sometime later put these on skip list via local patch on BB)

Thanks Dusan! Closing.
