### ISSUE TITLE
GYP compile release for loongson3A and run benchmark error

### ISSUE THREAD

**Issue by loongson817** [v8mips/v8mips#20]
Hi,
  I get the source code "git clone git://github.com/paul99/v8m-rb.git " , on loongson3A(mips64),linux. use "make mipsel.release", then I run the benchmark by ">v8mipsel/benchmark# ../out/mipsel.release/shell  run.js"
    errors come:
   "  Richards: Error: Error during execution: queueCount = 149, holdCount = 59.
     DeltaBlue: ReferenceError: alert is not defined
     Crypto: TypeError: Object 0,2,129,.. ,46 has no method 'charCodeAt'
     RayTrace: Error: Scene rendered incorrectly
     EarleyBoyer: Error: Earley or Boyer did incorrect number of rewrites
     RegExp: illegal access
     Splay: RangeError: Maximum call stack size exceeded"
  but when i compile debug use "make mipsel.debug",then run benchmark.all ok. I don't know why,  can anybody tell me?
thanks.

**Comment by dusmil** [comment]
Hi,

The answer is simple,  you did not compile v8 properly for loongson.

Just export variable as follows before compiling:

export GYPFLAGS="-Dmips_arch_variant=loongson"

Then you can do: make mipsel.release

I hope I help you.

**Comment by loongson817** [comment]
Thank you dusmil。it works now, I am doing some improvement on loongson3A .

**Comment by paul99** [comment]
This was completed, closing.
