### ISSUE TITLE
Replace jalr/jr with jialc/jic for r6

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#200]
Create optimization to (conditionally) replace normal jalr() and jr() which have delay-slots, with the new r6 compact jump instructions jialc() and jic(). 

This should great benefit Call(), Jump() and Ret() operations. Most of those currently do not fill their delay-slots, so we waste an instruction slot with a nop().

Please do note that jialc() and jic() do _not_ have forbidden slots either, so no special guards are necessary.

Here are a few more implementation notes, I'm sure I will add more later:
- Many Ret() functions _do_ use an instruction in delay slot: `__ Ret(USE_DELAY_SLOT);`
  - In this case just use the older form of instruction with `jr(ra)`
- Take a close look at the multiple versions of `MacroAssembler::Call()` (and corresponding `MacroAssembler::CallSize())`, and `MacroAssembler::Jump()`
- There are also `MacroAssembler::Jalr()` and `MacroAssembler::Jr()` to labels. (probably these names should be generalized).
- I am pretty sure there are spots where we patch sequences with jalr() or jr(). These need to found and fixed. However may decide to defer implementation on some if the cases are really tricky.

**Comment by paul99** [comment]
I would like to simplify this issue a bit, by breaking out two tasks mentioned above to separate issues/CLs. We can then develop them independently, and by independent people. So let's separate out:
- Ret() function - currently implemented as `jr ra`, with optional instruction in delay slot.
- `MacroAssembler::Jalr()` and `MacroAssembler::Jr()` to labels. 

So the remaining task is the `Call()` and `Jump()` functions which come in many variations.

They are used a lot with the macro-assembler, for example `CallRuntime()`.

While `DirectCEntryStub()` uses `Call()`, the `CEntryStub()` uses a `jalr t9` with an instruction in the delay slot. We can debate or measure to see if that is worth changing.

It's probably good to do this first for mips32, and get the CL done/tested/landed, and then do mips64 separately. Assigning to Djordje.

**Comment by paul99** [comment]
Looking at current implementation of `Ret()`, it is calling `Jump()`, so it does _not_ make sense to break it out separately from `Call()`/`Jump()`, as I had requested in previous comment. Let's include `Ret()` in this issue.

**Comment by djpesic** [comment]
Here is what i did until now. I made optimization of lui-ori-jal/jalr sequences to lui-jic/jialc. Also modifided code patching. Final effect is that some mjsunit tests fails. Failures are weird. Diff file:
https://gist.github.com/53ed5158b0cb56cd4da0.git

Failures: https://gist.github.com/4f4671bf054ce574c7e8.git
Failures are on simulator, qemu and hw, except:  div-mod.js doesn't fail on hw.

**Comment by paul99** [comment]
The gist's above do not open for me. I am logged into github in this browser. Sorry I did not notice sooner,  I only had time to look into this now. Can you upload code as CL, or as a branch on github? Maybe text listing of the fails here in the issue? (also, regardless of gist, diff, or CL, please let me know what git revision this builds on top of (e.g., what rev you tested))

**Comment by djpesic** [comment]
CL: https://codereview.chromium.org/1476143003

Revision: 05449f741bf2f7f1c12891cd88b275b4dc983cf2

Failures:

```
>>> Running tests for mipsel.optdebug
No connection to distribution server; running tests locally.
=== mjsunit/es6/debug-blockscopes ===                    
Warning: unknown flag --enable-slow-asserts.
Try --help for options
============ Stress 1/2 ============
============ Stress 2/2 ============
Names found in scope:
/home/rtrk/Documents/software/v8/test/mjsunit/mjsunit.js:179: Failure (For loop 2): expected <null> found <MjsUnitAssertionError()>

Stack: Error
    at new MjsUnitAssertionError (/home/rtrk/Documents/software/v8/test/mjsunit/mjsunit.js:31:16)
    at fail (/home/rtrk/Documents/software/v8/test/mjsunit/mjsunit.js:179:11)
    at assertNull (/home/rtrk/Documents/software/v8/test/mjsunit/mjsunit.js:304:7)
    at EndTest (/home/rtrk/Documents/software/v8/test/mjsunit/es6/debug-blockscopes.js:76:3)
    at /home/rtrk/Documents/software/v8/test/mjsunit/es6/debug-blockscopes.js:425:1
    throw new MjsUnitAssertionError(message);
    ^
Error
    at new MjsUnitAssertionError (/home/rtrk/Documents/software/v8/test/mjsunit/mjsunit.js:31:16)
    at fail (/home/rtrk/Documents/software/v8/test/mjsunit/mjsunit.js:179:11)
    at assertNull (/home/rtrk/Documents/software/v8/test/mjsunit/mjsunit.js:304:7)
    at EndTest (/home/rtrk/Documents/software/v8/test/mjsunit/es6/debug-blockscopes.js:76:3)
    at /home/rtrk/Documents/software/v8/test/mjsunit/es6/debug-blockscopes.js:425:1
Command: /home/rtrk/Documents/software/v8/out/mipsel.optdebug/d8 --test --random-seed=-363950349 --stress-opt --always-opt --nohard-abort --nodead-code-elimination --nofold-constants --enable-slow-asserts --debug-code --verify-heap --expose-debug-as debug --allow-natives-syntax /home/rtrk/Documents/software/v8/test/mjsunit/mjsunit.js /home/rtrk/Documents/software/v8/test/mjsunit/es6/debug-blockscopes.js

=== mjsunit/debug-scopes ===                                    
Warning: unknown flag --enable-slow-asserts.
Try --help for options
============ Stress 1/2 ============
============ Stress 2/2 ============
/home/rtrk/Documents/software/v8/test/mjsunit/mjsunit.js:179: Failure (With 2 / Failure: expected <2> found <2>

Stack: Error
    at new MjsUnitAssertionError (/home/rtrk/Documents/software/v8/test/mjsunit/mjsunit.js:31:16)
    at fail (/home/rtrk/Documents/software/v8/test/mjsunit/mjsunit.js:179:11)
    at assertEquals (/home/rtrk/Documents/software/v8/test/mjsunit/mjsunit.js:249:7)
    at CheckScopeContent (/home/rtrk/Documents/software/v8/test/mjsunit/debug-scopes.js:210:3)
    at listener_delegate (/home/rtrk/Documents/software/v8/test/mjsunit/debug-scopes.js:394:3)
    at listener (/home/rtrk/Documents/software/v8/test/mjsunit/debug-scopes.js:50:7)
    at with_2 (/home/rtrk/Documents/software/v8/test/mjsunit/debug-scopes.js:382:7)
    at /home/rtrk/Documents/software/v8/test/mjsunit/debug-scopes.js:396:1): expected <null> found <MjsUnitAssertionError()>

Stack: Error
    at new MjsUnitAssertionError (/home/rtrk/Documents/software/v8/test/mjsunit/mjsunit.js:31:16)
    at fail (/home/rtrk/Documents/software/v8/test/mjsunit/mjsunit.js:179:11)
    at assertNull (/home/rtrk/Documents/software/v8/test/mjsunit/mjsunit.js:304:7)
    at EndTest (/home/rtrk/Documents/software/v8/test/mjsunit/debug-scopes.js:74:3)
    at /home/rtrk/Documents/software/v8/test/mjsunit/debug-scopes.js:397:1
    throw new MjsUnitAssertionError(message);
    ^
Error
    at new MjsUnitAssertionError (/home/rtrk/Documents/software/v8/test/mjsunit/mjsunit.js:31:16)
    at fail (/home/rtrk/Documents/software/v8/test/mjsunit/mjsunit.js:179:11)
    at assertNull (/home/rtrk/Documents/software/v8/test/mjsunit/mjsunit.js:304:7)
    at EndTest (/home/rtrk/Documents/software/v8/test/mjsunit/debug-scopes.js:74:3)
    at /home/rtrk/Documents/software/v8/test/mjsunit/debug-scopes.js:397:1
Command: /home/rtrk/Documents/software/v8/out/mipsel.optdebug/d8 --test --random-seed=-363950349 --stress-opt --always-opt --nohard-abort --nodead-code-elimination --nofold-constants --enable-slow-asserts --debug-code --verify-heap --expose-debug-as debug --allow-natives-syntax /home/rtrk/Documents/software/v8/test/mjsunit/mjsunit.js /home/rtrk/Documents/software/v8/test/mjsunit/debug-scopes.js

=== mjsunit/div-mod ===                                        
Warning: unknown flag --enable-slow-asserts.
Try --help for options
============ Stress 1/2 ============
(function(left) { return left / 3; })
(function(left) { return left / 4; })
(function(left) { return left / 5; })
(function(left) { return left / 6; })
(function(left) { return left / 7; })
(function(left) { return left / 8; })
(function(left) { return left / 9; })
(function(left) { return left / 10; })
(function(left) { return left / 16777216; })
(function(left) { return left / 1073741824; })
(function(left) { return left / 12; })
(function(left) { return left / 60; })
(function(left) { return left / 100; })
(function(left) { return left / 86400000; })
============ Stress 2/2 ============
(function(left) { return left / 3; })
(function(left) { return left / 4; })
(function(left) { return left / 5; })
(function(left) { return left / 6; })
(function(left) { return left / 7; })
(function(left) { return left / 8; })
(function(left) { return left / 9; })
(function(left) { return left / 10; })
(function(left) { return left / 16777216; })
(function(left) { return left / 1073741824; })
(function(left) { return left / 12; })
(function(left) { return left / 60; })
(function(left) { return left / 100; })
/home/rtrk/Documents/software/v8/test/mjsunit/mjsunit.js:179: Failure (-0%100): expected <-0> found <-0>

Stack: Error
    at new MjsUnitAssertionError (/home/rtrk/Documents/software/v8/test/mjsunit/mjsunit.js:31:16)
    at fail (/home/rtrk/Documents/software/v8/test/mjsunit/mjsunit.js:179:11)
    at assertEquals (/home/rtrk/Documents/software/v8/test/mjsunit/mjsunit.js:249:7)
    at divmod (/home/rtrk/Documents/software/v8/test/mjsunit/div-mod.js:40:3)
    at run_tests_for (/home/rtrk/Documents/software/v8/test/mjsunit/div-mod.js:62:5)
    at /home/rtrk/Documents/software/v8/test/mjsunit/div-mod.js:90:3
    throw new MjsUnitAssertionError(message);
    ^
Error
    at new MjsUnitAssertionError (/home/rtrk/Documents/software/v8/test/mjsunit/mjsunit.js:31:16)
    at fail (/home/rtrk/Documents/software/v8/test/mjsunit/mjsunit.js:179:11)
    at assertEquals (/home/rtrk/Documents/software/v8/test/mjsunit/mjsunit.js:249:7)
    at divmod (/home/rtrk/Documents/software/v8/test/mjsunit/div-mod.js:40:3)
    at run_tests_for (/home/rtrk/Documents/software/v8/test/mjsunit/div-mod.js:62:5)
    at /home/rtrk/Documents/software/v8/test/mjsunit/div-mod.js:90:3
Command: /home/rtrk/Documents/software/v8/out/mipsel.optdebug/d8 --test --random-seed=-363950349 --stress-opt --always-opt --nohard-abort --nodead-code-elimination --nofold-constants --enable-slow-asserts --debug-code --verify-heap --allow-natives-syntax /home/rtrk/Documents/software/v8/test/mjsunit/mjsunit.js /home/rtrk/Documents/software/v8/test/mjsunit/div-mod.js

=== mjsunit/harmony/array-concat ===                                        
Warning: unknown flag --enable-slow-asserts.
Try --help for options
============ Stress 1/2 ============
============ Stress 2/2 ============
/home/rtrk/Documents/software/v8/test/mjsunit/mjsunit.js:179: Failure: expected <140> found <140>

Stack: Error
    at new MjsUnitAssertionError (/home/rtrk/Documents/software/v8/test/mjsunit/mjsunit.js:31:16)
    at fail (/home/rtrk/Documents/software/v8/test/mjsunit/mjsunit.js:179:11)
    at assertEquals (/home/rtrk/Documents/software/v8/test/mjsunit/mjsunit.js:249:7)
    at testArrayConcatES5 (/home/rtrk/Documents/software/v8/test/mjsunit/harmony/array-concat.js:579:5)
    at /home/rtrk/Documents/software/v8/test/mjsunit/harmony/array-concat.js:708:3
    throw new MjsUnitAssertionError(message);
    ^
Error
    at new MjsUnitAssertionError (/home/rtrk/Documents/software/v8/test/mjsunit/mjsunit.js:31:16)
    at fail (/home/rtrk/Documents/software/v8/test/mjsunit/mjsunit.js:179:11)
    at assertEquals (/home/rtrk/Documents/software/v8/test/mjsunit/mjsunit.js:249:7)
    at testArrayConcatES5 (/home/rtrk/Documents/software/v8/test/mjsunit/harmony/array-concat.js:579:5)
    at /home/rtrk/Documents/software/v8/test/mjsunit/harmony/array-concat.js:708:3
Command: /home/rtrk/Documents/software/v8/out/mipsel.optdebug/d8 --test --random-seed=-363950349 --stress-opt --always-opt --nohard-abort --nodead-code-elimination --nofold-constants --enable-slow-asserts --debug-code --verify-heap --harmony-concat-spreadable /home/rtrk/Documents/software/v8/test/mjsunit/mjsunit.js /home/rtrk/Documents/software/v8/test/mjsunit/harmony/array-concat.js

=== mjsunit/es6/typedarray ===                                                 
Warning: unknown flag --enable-slow-asserts.
Try --help for options
============ Stress 1/2 ============
============ Stress 2/2 ============
/home/rtrk/Documents/software/v8/test/mjsunit/mjsunit.js:179: Failure: expected <1> found <1>

Stack: Error
    at new MjsUnitAssertionError (/home/rtrk/Documents/software/v8/test/mjsunit/mjsunit.js:31:16)
    at fail (/home/rtrk/Documents/software/v8/test/mjsunit/mjsunit.js:179:11)
    at assertEquals (/home/rtrk/Documents/software/v8/test/mjsunit/mjsunit.js:249:7)
    at TestTypedArray (/home/rtrk/Documents/software/v8/test/mjsunit/es6/typedarray.js:315:3)
    at /home/rtrk/Documents/software/v8/test/mjsunit/es6/typedarray.js:318:1
    throw new MjsUnitAssertionError(message);
    ^
Error
    at new MjsUnitAssertionError (/home/rtrk/Documents/software/v8/test/mjsunit/mjsunit.js:31:16)
    at fail (/home/rtrk/Documents/software/v8/test/mjsunit/mjsunit.js:179:11)
    at assertEquals (/home/rtrk/Documents/software/v8/test/mjsunit/mjsunit.js:249:7)
    at TestTypedArray (/home/rtrk/Documents/software/v8/test/mjsunit/es6/typedarray.js:315:3)
    at /home/rtrk/Documents/software/v8/test/mjsunit/es6/typedarray.js:318:1
Command: /home/rtrk/Documents/software/v8/out/mipsel.optdebug/d8 --test --random-seed=-363950349 --stress-opt --always-opt --nohard-abort --nodead-code-elimination --nofold-constants --enable-slow-asserts --debug-code --verify-heap --harmony-tostring /home/rtrk/Documents/software/v8/test/mjsunit/mjsunit.js /home/rtrk/Documents/software/v8/test/mjsunit/es6/typedarray.js
```

**Comment by paul99** [comment]
See https://chromium.googlesource.com/v8/v8/+/fd73cb191c5b7c8a49002d11e0cecd5556df0c58/src/mips/assembler-mips.h#543
And https://chromium.googlesource.com/v8/v8/+/fd73cb191c5b7c8a49002d11e0cecd5556df0c58/src/debug/mips/debug-mips.cc#43

I dont see how this would be causing the bug right now, but the patching should be fixed to use new Call().

**Comment by djpesic** [comment]
I'm not sure this is the cause of the bug, becaue an optimization, until now, is done only for lui-ori-jal/jalr sequences marked with RELOCATE_INTERNAL_REFERENCE

**Comment by paul99** [comment]
A couple issues here, first, RELOCATE_INTERNAL_REFERENCE is not very common in r6. It was previously used for long-branches, and a few other more rare cases. Long-branches are now done via r6 bc() instruction. See the functions `is_near_r6()`, and `BranchShortHelperR6()`. I can see how this is a bit confusing because it defines the previously well-understood: 'near-branch is 16-bit offset', to something more like 'can be encoded in single instruction'. The bc() range is huge, which means that we almost never would use the multi instruction version (which requires lui/jic).

The much more important case for this optimization is Call & Jump to EXTERNAL_REFERENCE or CODE_TARGET. These are the calls to C functions or other JS functions. 

Since there are bugs in this more limited case of RELOCATE_INTERNAL_REFERENCE, you might choose to try to fix these first. But it would also be very reasonable to disable these temporarily, and get the much more common case working.

**Comment by mkaric** [comment]
I found that the problem is in branch delay slots. When the Branch function is called from lithium-codegen-mips.cc with USE_DELAY_SLOT parameter, the instruction after the generated jic instruction is not executed. Interestingly I managed to fix this by modifying only LCodeGen::DoCmpT function so it doesn't use delay slots. With this change all previously failing tests pass, except for mjsunit/div-mod.js which fails only with turbo flag, and also fails with a clean checkout on the same commit with the same error. However, this is probably not the best solution, and as long as we use delay slots it would be safer to remove the optimization and use jr/jalr when a delay slot is used.

**Comment by mkaric** [comment]
I modified the code so jic instruction is used only when the delay slot is unused. There were still some failures when running tests, but with some changes in the diff, now all tests pass. The only thing that is confusing is kInstructionsFor32BitConstant defined in assembler-mips.h, i tried running tests and setting it to 3, 2 and 1 (which should not make any sense), and all tests pass in all cases.

**Comment by mkaric** [comment]
CL with the changes is uploaded here: https://codereview.chromium.org/1573983002/.

The case of 3 for the constant kInstructionsFor32BitConstant was only useful when we had J/JAL optimization (removed in #204). Setting the value back to 2, along with adjustments in the comments in a separate CL: https://codereview.chromium.org/1690133004/.

**Comment by mkaric** [comment]
Changes landed as https://crrev.com/c766f739ddd01b3688cfa94ec295b768f3edadf4.

Separate CL related to J/JAL optimization landed as https://crrev.com/e3453a866d471e27cb0a7bf9c2196b632bda77fc.

**Comment by mkaric** [comment]
New changes have been made to mips32, in Jump, Call and CallSize functions in MacroAssembler, but this caused many failures because of improper code patching. Call and Jump functions now generate one instruction less so this needs to be adjusted for. Several constants in assembler-mips.h and hard coded values in full-codegen-mips.cc affect code patching. After adjusting these constants and values all tests pass except for one which is flaky. The flaky test is cctest/test-api/SetJitCodeEventHandler and fails with the message:
**\* Error in `out/mipsel.optdebug/cctest': double free or corruption (out): 0xf4daa8a8 ***
Aborted (core dumped)

**Comment by mkaric** [comment]
The flaky test is not related to my changes, uploaded the CL:
https://codereview.chromium.org/1807263003

**Comment by mkaric** [comment]
Landed as https://crrev.com/21733b6b5259799ff4042db58473f986fe2e4a43.

Changes ported to mips64, CL uploaded:
https://codereview.chromium.org/1830133002/

**Comment by mkaric** [comment]
Landed as https://crrev.com/a3f941aed4afb475232b2d7d11179720d5e52fd6, closing. We could investigate if it is possible to use JIC/JIALC offset in Jump and Call MacroAssembler functions and reduce the number of used instructions by one, but a new issue can be opened for that.
