### ISSUE TITLE
cctest/test-debug/ProcessDebugMessagesThreaded flaky on MIPS32R6 Release under qemu

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#202]
cctest/test-debug/ProcessDebugMessagesThreaded flaky on MIPS32R6 Release under qemu:
See log:
`https://v8.mips.com/bbv8/builders/Target%20-%20edge%20-%20mipsr6%2Cunder%20qemu/builds/1064/steps/Check%20%28flakes%29/logs/ProcessDebugMessagesT..`

**Comment by ilijapavlovic** [comment]
The test performs 20 iterations and stops with execution when Turbofan compiler is enabled (--turbo).
`qemu-mipsel -R 2147483648 -cpu mips32r6-generic /home/rtrk/MIPS/v8/out/mipsel.release/cctest --random-seed=-1587340061 --turbo test-debug/ProcessDebugMessagesThreaded --nohard-abort --nodead-code-elimination --nofold-constants --testing_serialization_file=/home/rtrk/MIPS/v8/out/.serdes/serdes_ProcessDebugMessagesThreaded__turbo`

There is no rule in which iteration the test will stop.
Following observations are done with qemu in user mode.
- Collection traces from qemu (option: -D <file.log>) cannot reproduce the problem. With this option
  one iteration has duration ~63 ms. Usually, an iteration has duration ~19 ms.
- To keep iteration times small as possible, every trace flag or print flag is used separately.
  It means that ones the test is performed only with --trace_opt, the second time only with --trace_codegen, etc.
- Very often, in moment of blocking the test, the last line in a trace was not completed (like interrupted in the middle of printing).
  In source code, if there are two print statements (in a sequence), the first print is performed but not the following print.
- Traces collected on this way did not give information about cause for blocking test.

Further efforts were directed in investigation the test threads during execution.
Classes Mutex and RecursiveMutex were in focus with methods Lock/Unlock/TryLock.
Following situations are considered:
- For Lock: if the mutex is currently locked by the same thread calling this function, it produces a deadlock (with undefined behavior)
- For Unlock: if the mutex is not currently locked by the calling thread, it causes undefined behavior.

With inserting printf() statements inside Lock/Unlock/TryLock it was possible to see 
outputs similar to the following:

```
...
Mutex::Lock() native_handle_=0x25603c4 
Mutex::Lock() native_handle_=0x25603c4      
Mutex::Unlock() native_handle_=0x25603c4    // <--- 
Mutex::Unlock() native_handle_=0x25603c4    // <---- The 2nd attempt to unlock the same mutex!!
...
```

Soon, after these paired unlocks follows stopping of the test. As it is mentioned above,
this can cause undefined behaviour and therefore stopping the test.

**Comment by paul99** [comment]
Using today's ToT I built for mips32r6, and ran it on Boston board, 1-Core, 2-thread (looks to linux like 2 cpus). So far it's run 515 Iterations of the overall test, and had no failures.

Here is what a single iteration looks like (the capital-I Iteration is the number my looping script prints, the lower-case 'integration' is what the program prints.

```
Iteration 515
iteration 0 took 1168.137000 ms
iteration 1 took 805.911000 ms
iteration 2 took 491.139000 ms
iteration 3 took 700.372000 ms
iteration 4 took 485.567000 ms
iteration 5 took 485.554000 ms
iteration 6 took 484.062000 ms
iteration 7 took 484.548000 ms
iteration 8 took 484.403000 ms
iteration 9 took 538.508000 ms
iteration 10 took 472.166000 ms
iteration 11 took 463.557000 ms
iteration 12 took 458.973000 ms
iteration 13 took 442.551000 ms
iteration 14 took 443.748000 ms
iteration 15 took 441.500000 ms
iteration 16 took 443.815000 ms
iteration 17 took 442.219000 ms
iteration 18 took 442.368000 ms
iteration 19 took 447.554000 ms
```

Command run: 
     out/mipsel.release/cctest --random-seed=-1587340061 --turbo test-debug/ProcessDebugMessagesThreaded --nohard-abort --nodead-code-elimination --nofold-constants --testing_serialization_file=out/.serdes/serdes_ProcessDebugMessagesThreaded__turbo

**Comment by ilijapavlovic** [comment]
Iteration times on Boston board are very interesting here. Iterations 14 to 19 have times ~443 ms. In qemu user mode, these iterations had times from ~19 ms to ~25 ms.

**Comment by ibogosavljevic** [comment]
Issue appears on qemu-userland MIPS32R2 and qemu-userland MIPS32R6. I don't remeber seeing this issue on MIPS32R2 simulator or boards.

**Comment by paul99** [comment]
On the board: Pass: 1500, fail: 0

@ilijapavlovic : the board is fpga running at 25MHz so the execution times are long compared to your x86 workstation.

Seems clear that this is a qemu issue, but not clear to me if these threading related tests _should_ work perfectly. In other words, is it expected that code doing threading and locking (on mips meaning ll/sc) should work flawlessly? I suppose it should.

Do you think it is worth trying an older version qemu for mips32r2, to see if this is some behavior that crept in recently?

**Comment by ilijapavlovic** [comment]
I tried with a commit for qemu from February 2015, and the problem is still reproducible (mips32r2). Because of way how the test finishes (without any error message, writing trace messages interrupted in the middle of a line...) it is possible that qemu somehow gets stuck.

**Comment by ibogosavljevic** [comment]
This is the status up to now: this test has been failing on other architectures as well, it has been listed as flaky in cctest.status

```
  # Fails sometimes.
  'test-debug/ProcessDebugMessagesThreaded': [PASS, FLAKY],
```

We didn't continue the investigation, but until now, it seems that the issue arises here:

```
void Debug::EnqueueCommandMessage(Vector<const uint16_t> command,
                                  v8::Debug::ClientData* client_data) {
  CommandMessage message = CommandMessage::New(
      Vector<uint16_t>(const_cast<uint16_t*>(command.start()),
                       command.length()),
      client_data);
  isolate_->logger()->DebugTag("Put command on command_queue.");
  command_queue_.Put(message);
  command_received_.Signal();

  // Set the debug command break flag to have the command processed.
  if (!in_debug_scope()) isolate_->stack_guard()->RequestDebugCommand();
}
```

The line that might cause the issue is this one: `if (!in_debug_scope()) isolate_->stack_guard()->RequestDebugCommand();`. We believe this line should be executed atomically, but it isn't and it causes test to fail.

**Comment by ilijapavlovic** [comment]
Since Dec 01, 2016 till Jan 02, 2017 this problem is not reproduced on test machines. Therefore this issue will be closed.
