### ISSUE TITLE
Port r6 compact-branch support to mips64

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#203]
The CL to use r6 compact branches on mips32 is _almost_ done https://codereview.chromium.org/1396133002  (https://github.com/paul99/v8m-rb/issues/140)

We need to port this to mips64. Assigning to Ilija.

**Comment by ibogosavljevic** [comment]
PTAL: https://codereview.chromium.org/1534183002/

**Comment by ibogosavljevic** [comment]
Landed, closing issue: https://chromium.googlesource.com/v8/v8/+/2c63060f113bd7a7a40e5aeb895984b8328e7824
