### ISSUE TITLE
Remove mips32 jalr->jal optimization

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#204]
The optimization for jalr->jal and jr->j was very important on some old cores. But those cores are no longer shipping in products using v8.

Recent benchmarks from Djordje https://v8m.slack.com/files/djordje.pesic/F0D6286D9/jalr-_jal-benchmark.txt show that these do not have significan advantage on platforms we care about.

Ákos, please remove this opt. Mostly it's in `Assembler::set_target_address_at()`, but there is also some of this in `Assembler::JumpToJumpRegister()` and `RelocInfo::apply()`.

Please check for other code that should be altered or removed.

**Comment by djpesic** [comment]
I removed optimization. Initial diff is on https://gist.github.com/djpesic/b8a6331f07f574df0435#file-jalr-to-jal-removal-txt. Please, take a look.

**Comment by kilvadyb** [comment]
lgtm (if it passes tests :) ).

**Comment by paul99** [comment]
lgtm, Djordje, please create a CL and add me, Balázs, and Ákos as reviewers. If you have test results, let us know here or on slack. If either of those guys give you lgtm during your work day, go ahead and land it, no need to wait for me.

**Comment by djpesic** [comment]
https://codereview.chromium.org/1419793014/
PTAL

**Comment by djpesic** [comment]
Landed as
https://crrev.com/60b97e802fad47f9f01fbd334717302ba4fb710d
Closing

**Comment by kisg** [comment]
Landed a CL: https://codereview.chromium.org/1690133004/

@mkaric: Close if done

**Comment by mkaric** [comment]
Closing.
