### ISSUE TITLE
Interpreter bug on big-endian

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#207]
Commit 6173d504 [Interpreter] Add wide varients of bytecodes with feedback and constant pool indexes. (https://codereview.chromium.org/1413863010) cause several failures on big-endian including on the bots at Google.

Here is an example failure: https://v8.mips.com/bbv8/builders/Target%20-%20big%20-%20edge%20-%20no%20i18n/builds/4655

Ákos and I looked at this today and found some suspect accesses that may need byte-swap, but initial hacking attempts did not fix the problem.

Assigning to Ákos, but anyone is welcome to take a look! Since this is on the Google bots, the priority is high.

**Comment by paul99** [comment]
There is additional discussion in #bigendian channel....

**Comment by akospalfi** [comment]
Please see my comments in #bigendian channel.

**Comment by palfia** [comment]
Please see my comments in #bigendian channel.

**Comment by palfia** [comment]
Fixed in https://codereview.chromium.org/1431803004/.

Closing...
