### ISSUE TITLE
RunFloat64MulAndFloat64Add[1|2] and RunFloat64MulAndFloat64Sub[1|2] fail on qemu R6 in RELEASE mode

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#208]
Tests RunFloat64MulAndFloat64Add1, RunFloat64MulAndFloat64Add2, RunFloat64MulAndFloat64Sub1 and RunFloat64MulAndFloat64Sub2 fail on qemu R6 with error:

```
#
# Fatal error in .././test/cctest/compiler/codegen-tester.h, line 523
# Check failed: (x)==(y).
#

==== C stack trace ===============================
```

https://v8.mips.com/bbv8/builders/Target%20-%20edge%20-%20mipsr6%2Cunder%20qemu/builds/1149/steps/Check/logs/RunFloat64MulAndFloat..

**Comment by ibogosavljevic** [comment]
The error appears only on R6 with Codescape GNU Tools 2015.01-5 for MIPS IMG Linux 4.9.2 and with compilation flag -O3. It appears both on qemu and R6 FPGA board.

When using -O3, the compiler generates MADDF instruction, which has better precision than separate multiply and add, but the results are different and the test fails.

Fix would be to force compiler to generate separate multiply and add, in the following way

FAILING VERSION

```
  FOR_FLOAT64_INPUTS(i) {
    FOR_FLOAT64_INPUTS(j) {
      FOR_FLOAT64_INPUTS(k) {
        CheckDoubleEq(*i + (*j * *k), m.Call(*i, *j, *k));
      }
    }
  }
```

SUCCESS VERSION

```
  FOR_FLOAT64_INPUTS(i) {
    FOR_FLOAT64_INPUTS(j) {
      FOR_FLOAT64_INPUTS(k) {
        volatile double temp = (*j * *k);
        volatile double expected = *i + temp;
        CheckDoubleEq(expected, m.Call(*i, *j, *k));
      }
    }
  }
```

Using volatile double variables forces the compiler to execute two instructions instead of one

**Comment by paul99** [comment]
While looking for NaN issues related to 206, I found this deleted comment in 9eace97b Use signaling NaN for holes in fixed double arrays.

This may have some relevance to FP precision issues, it certainly does for a32:

```
# All floating-point computations on x87 happens in 80-bit
# precision.  Because the C and C++ language standards allow
# the compiler to keep the floating-point values in higher
# precision than what's specified in the source and doing so
# is more efficient than constantly rounding up to 64-bit or
# 32-bit precision as specified in the source, the compiler,
# especially in the optimized mode, tries very hard to keep
# values in x87 floating-point stack (in 80-bit precision)
# as long as possible. This has important side effects, that
# the real value used in computation may change depending on
# how the compiler did the optimization - that is, the value
# kept in 80-bit is different than the value rounded down to
# 64-bit or 32-bit. There are possible compiler options to
# make this behavior consistent (e.g. -ffloat-store would keep
# all floating-values in the memory, thus force them to be
# rounded to its original precision) but they have significant
# runtime performance penalty.
#
# -mfpmath=sse -msse2 makes the compiler use SSE instructions
# which keep floating-point values in SSE registers in its
# native precision (32-bit for single precision, and 64-bit
# for double precision values). This means the floating-point
# value used during computation does not change depending on
# how the compiler optimized the code, since the value is
# always kept in its specified precision.
#
# Refer to http://crbug.com/348761 for rationale behind SSE2
# being a minimum requirement for 32-bit Linux builds and
# http://crbug.com/313032 for an example where this has "bit"
# us in the past.
```

**Comment by ibogosavljevic** [comment]
One of the ways to fix this issue would be to completely disable generation of fusion MAD instruction. For this we should use -mno-fused-madd. Alas, the compiler IMG 2015.01- is insensitive to this switch, and we get MADDF instruction regardless if this option is or isn't provided to the compiler.

A bug has been reported to the compiler team. Bug is here https://dmz-portal.mips.com/bugz/show_bug.cgi?id=2261. After the missing functionality is implemented by compiler folks , we could enable this switch and have everything working. But, another alas, we don't know when this will happen.

**Comment by ibogosavljevic** [comment]
The bug appears with the version of the compiler 2015.06-05. BTW, in order to compile with this toolchain, here are the settings:

```
CCPATH="/home/ivica/tools/codescape-2015.06-05-mips-img-linux-gnu/2015.06-05/bin/mips-img-linux-gnu-"
export CC=${CCPATH}gcc
export CXX=${CCPATH}g++
export AR=${CCPATH}ar
export RANLIB=${CCPATH}ranlib
export LINK=$CXX
export GDB=${CCPATH}gdb
```

For Mips32R6, you also need to:

```
export LDSO_PATH=/home/ivica/tools/codescape-2015.06-05-mips-img-linux-gnu/2015.06-05/sysroot/mipsel-r6-hard/lib/ld-linux-mipsn8.so.1
export LD_R_PATH=/home/ivica/tools/codescape-2015.06-05-mips-img-linux-gnu/2015.06-05/sysroot/mipsel-r6-hard/lib:/home/ivica/tools/codescape-2015.06-05-mips-img-linux-gnu/2015.06-05/mips-img-linux-gnu/lib/mipsel-r6-hard/lib
```

For Mips64R6, you need to:

```
export LDSO_PATH=/home/ivica/tools/codescape-2015.06-05-mips-img-linux-gnu/2015.06-05/sysroot/mipsel-r6-hard/lib64/ld-linux-mipsn8.so.1
export LD_R_PATH=/home/ivica/tools/codescape-2015.06-05-mips-img-linux-gnu/2015.06-05/sysroot/mipsel-r6-hard/lib64:/home/ivica/tools/codescape-2015.06-05-mips-img-linux-gnu/2015.06-05/mips-img-linux-gnu/lib/mipsel-r6-hard/lib64
```

**Comment by ibogosavljevic** [comment]
It's not possible to disable tests based on arch_variant :( We can either disable it for all or enable it for all

**Comment by kisg** [comment]
Alan: Please also run the Octane and Kraken benchmarks with and without your patch to see if there is a performance effect (hopefully increase).

**Comment by ibogosavljevic** [comment]
We disabled fused multiply-add in both compiled and emitted code, the problem is now solved.

Duplicate of #435. Closing
