### ISSUE TITLE
How to output all functions' running time

### ISSUE THREAD

**Issue by loongson817** [v8mips/v8mips#21]
Hi 
    when I use
     benchmarks> ../out/mipsel.release/d8 --prof run.js
   then it will create a file v8.log.  And  when i am in the mipsel.release directory,
    out/mipsel.release> ../../tools/linux-tick-processor  ../../benchmaks/v8.log > 1.out
  in the 1.out, we can get some code-creation infomation, for example:
  [JavaScript]:
   ticks  total  nonlib   name
    407    7.7%    7.7%  LazyCompile: *montReduce crypto.js:583
    397    7.5%    7.5%  LazyCompile: *lin_solve navier-stokes.js:128
    269    5.1%    5.1%  LazyCompile: *rewrite_nboyer earley-boyer.js:3604
  Now, I want to know the run-time of every functions in *.js .  Such as in  crypto.js, I want to How long the montReduce cost, but don't modify the crypto.js.   I want to do run-time statistics for all functions.
  How can i do？ Thanks!!

**Comment by paul99** [comment]
I am afraid that I do not have good knowledge on this profiling to help you out. The profiling code is not mips-specifc. You might want to post your question on the v8-users list, and see if the other users, or the developers there have info to share.

https://groups.google.com/forum/?fromgroups#!forum/v8-users

**Comment by paul99** [comment]
This has had no input for 7 months, closing. If there is more here, please re-open this issue.
