### ISSUE TITLE
Improve Cvt_d_uw in mips64 and mips32 ports.

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#212]
While doing the uint64_t to FP double and single conversions in https://codereview.chromium.org/1439053003/ and https://codereview.chromium.org/1440133002/
per https://github.com/paul99/v8m-rb/issues/211, it became obvious that our existing Cvt_d_uw() macro-asm sequences are non-optimal (using many more instructions than needed).

Please compare the mips64 Cvt_d_ul() to existing mips64 Cvt_d_uw() and also to mips32 Cvt_d_uw().

Note that the mips32 version can use the existing method of testing MSB, by branching on >=0 (e.g., treating the unsigned integer as signed for the purpose of the branch).

The mips64 Cvt_d_uw() won't be able to do that directly, we will need some slightly different method to detect the b31 set in 64-bit regs. Yet, I still think we can save a lot of instructions over the current version.

**Comment by lialan** [comment]
​here is the CL: https://codereview.chromium.org/1453373002/

**Comment by lialan** [comment]
patch checked in. I will close this issue for now.
