### ISSUE TITLE
Disable signed-compare warning on gcc builds

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#214]
Usually once a week we get all the target bots broken when gcc detects a comparison between signed and unsigned values. Today it was this: 

```
  EXPECT_EQ(task1->id(), 1);
```

id() returns uint32_t, the 1 is interpreted as a signed integer, and this breaks. (the real reason is the macros & templates used for things like EXPECT_EQ() and DCHECK(), and so on. You can review those source of these.)

Breakage does not happen on clang. I spoke with one of our compiler guys, and he did not see that this warning would prevent terrible hard-to-find errors, so in my opinion, this warning is not worth it, given all the false alarms for obviously OK constructs like above.

So, I'd like to have someone remove this check from gcc builds by adding some flag, guessing: -Wno-sign-compare to the GYP files. I do not know if it is OK to pass a flag like this to clang. If it is, that would be easiest. If not, we have do do something only when clang is disabled (clang=0) in GYP.

We should also check that older gcc, like 4.8, and maybe even 4.6 don't choke on this flag. We don't use those older versions, but other folks might.

Other people have submitted gcc signed-compare error fixes, so I don't think it is only MIPS that cares, I think we should do this for all arch's, but I will want to as other folks that might care to review the CL, like the ARM & PPC teams.

Please pull an ARM toolchain and see how it goes there. I think Linaro tools are 4.9.2 or above.

I just compiled on x86 with a gcc 4.9.3, and that generates the same errors that we do.

Ivica, can you please assign this to someone on the team. I'll give it P2, but I would like to see us get this into review next week. If needed, please bump the priority.

**Comment by kilvadyb** [comment]
I did a quick and dirty solution: https://codereview.chromium.org/1476473002/
I started trybots and seems like android chromium debug build has failed.

**Comment by kilvadyb** [comment]
All the failures are some config problems and real builds are fine.

**Comment by paul99** [comment]
This was fixed by Balázs in https://codereview.chromium.org/1476473002 and landed as https://crrev.com/8e54a667b2c812f8a0f2f506af6c644a952d8569
