### ISSUE TITLE
Problems with round operations on mips32

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#216]
Several recent CL's have been adding float conversions and rounding modes to TF.

I just reviewed two pending CLs that add rounding ops:
https://codereview.chromium.org/1444583002/
https://codereview.chromium.org/1440293002/

These look to me like they should be totally broken for mip32, and yet they do seem to work, on mips32r2, and on mips32r1.  [1]

The problem I think I see is in `#define ASSEMBLE_ROUND_DOUBLE_TO_DOUBLE( ... )` on line 428 of code-generator-mips.cc. That macro directly emits `cvt_d_l`, and also `ceil_l_d`, or `trunc_l_d`, or `floor_l_d`.

All those instructions are fine in fp64 mode, but have undefined operation in fp32 mode (e.g. mips32r2 and below). Manual says "For CVT.D.L, the result of this instruction is UNPREDICTABLE if the processor is executing in 16 FP registers mode." Furthermore, this instruction is defined for mips32r2, so it should not even exist on r1 board, and should therefore get illegal instruction exception.

Yet I run the `test-run-machops` on mips32r2 and mips32r1 hardware, and the tests don't fail (other than the different fails in https://github.com/paul99/v8m-rb/issues/215 on r1).

So, either the documentation is wrong [2], or our code is not really emitting these instructions.

We need to debug this (even on the sim) and see what is really getting emitted and executed during these rounding tests.

We _likely_ have to generate alternative macro-assembler functions for r2 and r1.

Notes:
[1] mips64 is fine, since we always use fp64 mode there, per the ABI.
[2] Some of you may remember we had breakage in tests that used these "_l' instructions on some hardware. So we got rid of them on mips32. I think it likely we will have to do same here.

@ibogosavljevic can you either look into this one yourself, or assign it to someone? We should get right on this, due to the recent CL's coming from 'ahaas'.

**Comment by ibogosavljevic** [comment]
The reason why we are not experiencing any failures on MIPS32R1 and MIPS32R2 is because these operations are disabled on these architectures. Namely, there is a list of optional operator in machine-operators.cc:177 (Code 1) which not all architectures implement. On MIPS, we have a setup that we do not implement kFloat64RoundDown and kFloat64RoundTruncate if the architecture doesn't support it instruction-selector-mips.cc:1099 (Code 2). That is the reason why we aren't seeing any failures.

Code 1

```
#define PURE_OPTIONAL_OP_LIST(V)                            \
  V(Word32Ctz, Operator::kNoProperties, 1, 0, 1)            \
  V(Word64Ctz, Operator::kNoProperties, 1, 0, 1)            \
  V(Word32Popcnt, Operator::kNoProperties, 1, 0, 1)         \
  V(Word64Popcnt, Operator::kNoProperties, 1, 0, 1)         \
  V(Float32Max, Operator::kNoProperties, 2, 0, 1)           \
  V(Float32Min, Operator::kNoProperties, 2, 0, 1)           \
  V(Float64Max, Operator::kNoProperties, 2, 0, 1)           \
  V(Float64Min, Operator::kNoProperties, 2, 0, 1)           \
  V(Float64RoundDown, Operator::kNoProperties, 1, 0, 1)     \
  V(Float64RoundTruncate, Operator::kNoProperties, 1, 0, 1) \
  V(Float64RoundTiesAway, Operator::kNoProperties, 1, 0, 1)
```

Code 2

```
MachineOperatorBuilder::Flags
InstructionSelector::SupportedMachineOperatorFlags() {
  MachineOperatorBuilder::Flags flags = MachineOperatorBuilder::kNoFlags;
  if ((IsMipsArchVariant(kMips32r2) || IsMipsArchVariant(kMips32r6)) &&
      IsFp64Mode()) {
    flags |= MachineOperatorBuilder::kFloat64RoundDown |
             MachineOperatorBuilder::kFloat64RoundTruncate;
  }
  return flags | MachineOperatorBuilder::kFloat64Min |
         MachineOperatorBuilder::kFloat64Max |
         MachineOperatorBuilder::kFloat32Min |
         MachineOperatorBuilder::kFloat32Max;
}
```

**Comment by paul99** [comment]
OK, thanks for pointing this out. I should have seen it.

Could you please port the original changes from these 2 referenced CL's for mips32. Sorry I created more work for us, we certainly do not need that.

I do think it would be prudent to put a DCHECK(IsFp64Mode()) in the ASSEMBLE_ROUND_DOUBLE_TO_DOUBLE macro. That makes it self-documenting and helps catch mistakes if someone gets flag mode incorrect.

Might be good to run these tests for mips32r6 & mips64r6 on the fpga board.

**Comment by ibogosavljevic** [comment]
PTAL https://codereview.chromium.org/1448383002

**Comment by ibogosavljevic** [comment]
Patch landed, closing issue
