### ISSUE TITLE
Use DAHI, DATI for mips64r6 li()

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#218]
r6 adds some better instructions for loading constants. Please read the instruction set reference (6.04) for AUI DAUI DAHI DATI.

Our mips64 `li()` implementation takes 6 instructions to load an arbitrary 64-bit constant. It takes 4 instructions to load an address, since addresses are known to be 48-bits. (also please review the li() macro carefully, it uses less instructions whenever possible.)

Using LUI, ORI, DAHI, DATI, we can load 64bits in 4 instructions, and 48 bits in 3.

Please implement this optimization for mips64 `li()`.

Please read the instruction set ref 'Programming Notes:' section carefully. the instructions _should_ be emitted in a particular order, as hardware optimization may be done if this ordering is consistent. [1]

Also, I'm sure there are other places where these instructions could be useful, so keep an eye on that, and suggest ideas in this issue, or create a new one.

Recommendation: do this as 3 CL's:
1. Add simulator support for these instructions, and add thorough test case in test-assembler-mips64.cc, and verify on r6-hardware & qemu, so we know all targets work the same. Please add DCHECKs for `r6` in the assembler.
2. Do a CL to let `li()` macro use these instructions for everything _except_ addresses (see enum LiFlags `ADDRESS_LOAD`). I reccommend  creating macro-asm test case for li() exercising cornercases, and verifying instruction could.
3. Change address load to 3 instructions for r6 -- note that there will be work with patching, likely in multiple locations.

Notes: 
[1] - the stylized ordering/HW-optimization may not work with the 3-instrction address load. I will check this with the HW team when I return to office. It should not affect correctness. But it _might_ be possible that 4 instruction using the recommended ordering could be faster - doubtful, but we should check.

**Comment by lialan** [comment]
The simulator support for those instructions is checked in this CL:
https://codereview.chromium.org/1481493002

**Comment by lialan** [comment]
A prototype of the non-address load change CL is uploaded at:
https://codereview.chromium.org/1522573002

Tests pass on simulator and Qemu mips64r6 mode (there were a lot of Div32/Truncate failures).

I am working on tuning it, and part 3.

**Comment by kisg** [comment]
Landed: https://codereview.chromium.org/1714283002/

@lialan Close if done.

**Comment by lialan** [comment]
In order to optimize address loads, we have to shrink the address load instructions from 4 to at most 3. But I find it quite difficult to use 3 instructions to load some stack pointer in all cases. I think it is even impossible to do that.

For example, consider loading `0x00007fffffffffff` with `LUI`, `ORI` and `DAHI`. the `LUI` would load `ffff` with sign extension, which will result higher 16bits to be 1s. In this case a `DATI` is necessary to fill the top 16bits with 0s. 

To use 3 instructions, `LUI` is necessary because it is the only instruction (in those 3) that flush the bits.

**Comment by kilvadyb** [comment]
There are > 50 failures running mips64el.optdebug.quickcheck on r6 simulator. If I revert
50a394d -- MIPS64: Fix 'MIPS: use DAHI/DATH for li macro on mips64r6.'
1f5b84e -- MIPS: use DAHI/DATH for li macro on mips64r6.
commits then r6 mips64el.optdebug.quickcheck tests are OK. @lialan, please fix it.

**Comment by lialan** [comment]
@kilvadyb I have determined the issue to be the `LUI` instruction sign extending the top 16bits. Resulting invalid memory address accesses.

I am doing a fix for it.

**Comment by lialan** [comment]
fix is at [https://codereview.chromium.org/1763733002](https://codereview.chromium.org/1763733002). PTAL.

This fix specifically fix the LUI instruction. Corresponding tests are added as well.

**Comment by mkaric** [comment]
Fix CL landed, closing the issue.
