### ISSUE TITLE
mips32 target debug breakage, es6/classes tests.

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#220]
See: https://v8.mips.com/bbv8/builders/Target%20-%20Debug%20-%20edge

Of the last few builds as of 2015-11-30, 1484, 1482, 1481 have ~60 fails, all on popcorn-hour-board-4.
(mjsunit/es6/classes-subclass-builtins, mjsunit/es6/classes-subclass-arrays, mjsunit/es6/classes-maps, mjsunit/es6/regexp-constructor, and others)

Builds 1483, 1480, 1479 have single fail on regress-2594 (known issue from https://github.com/paul99/v8m-rb/issues/206). All these were run on Octeon-III boards.

Maybe this is alignment related? (popcorn boards disable alignment fixups, we are not capable of disabling alignment fixes Octeon-III boards currently.)

Also, note to @mkaric : one of the failing tests is same as the BE fail in https://github.com/paul99/v8m-rb/issues/217, maybe related?

To confuse the history more, this overlaps (int time on the BB) with interpreter alignment bugs that Ákos fixed in https://codereview.chromium.org/1423373004 - on Nov 5.

Taking that into account, it appears that after 678a5583d6e15 on Nov 3, every build on popcorn board has the mjsunit/es6/classes-subclass-builtins failure. But most builds are on Rhino, Cavium, etc. all Octeon-III, and this test does not fail, only regress-2594

Note that both this and https://github.com/paul99/v8m-rb/issues/217 fail mjsunit/es6/regexp-constructor as well as classes-subclass-builtins.

I am thinking that someone is allocating an object pointer that is somehow not 32-bit aligned, and the CAST_ACCESSOR for object->IsLayoutDescriptor() is getting (sometimes) unaligned pointer. The octeon-II chip in erpro-8 Big Endian boards also has hardware-alignment support, so that board will NOT fault on alignment, but may get the byte-ordering scrambled in this case.

Assigning first to @palfia  to document how to run this test with the alignment fixups disabled on popcorn boards. 

Then please assign to @mkaric as I think this is same as the other issue.

@mkaric, @ibogosavljevic please try to find a popcorn board to test on, or some other board where alignment fixups in kernel can be disabled. I _think_ you can do that for CI-20 also.

Even on error-8 board, if you can backtrace where the 
# Fatal error in .././src/objects-inl.h, line 3254
# Check failed: !v8::internal::FLAG_enable_slow_asserts || (object->IsLayoutDescriptor()).

fails on EB, you may find that pointer is unaligned.

**Comment by palfia** [comment]
@mkaric, @ibogosavljevic:
You can disable the kernel alignment fixup with the alignment disabler binaries. The disabler binary turns the kernel alignment fixup off via a syscall and executes the binary passed via it's command line  (I've shared the disabler binaries via Slack.)

To run a specific test:

```
out/mipsel.optdebug/disable-kernel-alignment-fixups-mips32r2el out/mipsel.optdebug/d8 --test --random-seed=907002487 --stress-opt --always-opt --nohard-abort --nodead-code-elimination --nofold-constants --enable-slow-asserts --debug-code --verify-heap --harmony-regexp-subclass test/mjsunit/mjsunit.js test/mjsunit/es6/regexp-constructor.js
```

To run a whole test suite you can use the "--command-prefix" flag (please adjust the path to your env):

```
tools/run-tests.py --arch=mipsel --mode=optdebug --no-presubmit --command-prefix="<path-to-repo>/out/mipsel.optdebug/disable-kernel-alignment-fixups-mips32r2el " mjsunit
```

**Comment by mkaric** [comment]
I ran mjsunit/es6/classes-subclass-builtins.js test on a CI-20 board with disabled kernel alignment fixup and it fails with bus error. Then I shortened the test (it still fails with the same error) and what I got is very similar to the short test in the big-endian failure:

```
"use strict";
(function() {
  class A extends String {
  }
  var o = new A("foo");
})();
```

**Comment by mkaric** [comment]
kLayoutDecriptorOffset seems to be causing the misalignment problem, as well as the problem on BE. In objects.h it is defined kLayoutDecriptorOffset = 1, and next to it there is a comment "Must not be ever accessed.". Since it is equal to 1 it causes a misalignment when accessed, but it does point to the correct value. Also on big-endian the correct value for kLayoutDecriptorOffset would be -1, to access the correct value. 

Possible solution for this could be using a different accessor that would access only the correct byte.

**Comment by mkaric** [comment]
GetLayoutDescriptor() function performs FLAG_unbox_double_fields check and calls appropriate function (layout_descriptor() or LayoutDescriptor::FastPointerLayout()). Changing map->layout_descriptor() to map->GetLayoutDescriptor() in objects.cc in Map::CopyInitialMap function fixes both #217 and #220 issues.

**Comment by mkaric** [comment]
PTAL https://codereview.chromium.org/1522203004

**Comment by mkaric** [comment]
Landed as https://crrev.com/291219dafab05f1de26aa39f917f179d8abe44dc, closing.
