### ISSUE TITLE
Further optimize Addu/Subu overflow checks (Pre-R6)

### ISSUE THREAD

**Issue by lialan** [v8mips/v8mips#222]
This idea stems from #201 where we uses branches (BOVC/BNVC) to do the trick. We might be able to do better in some cases (adding immediate values). For the simplicity I just copy and paste my comments here:

Assume incoming immediate is a 32bit unsigned value, and then if we regard it as a signed value, we will have the following observation (extracted from MagicCode source code comments I made a while ago, and op1 is from the "left" register, and op3 is from the "dst" register in V8 AdduAndCheckForOverflow function context. And actually, it works for SubuAndCheckForOverflow as well):

```
using (op1, op2, op3) to represent the MSB of (operand_reg, operand_imm32, result_reg) respecitvely.
when opnd_imm32 >=0 then the calculation of
(op1 ^ op3) & (op2 ^ op3) could be simplified as (op1 ^ op3) & op3

when opnd_imm32 < 0 then it becomes: (op1 ^ op3) & ~op3.
since we only care for the MSB, use a truth table could give us:
op1, op3  => (op1 ^ op3) & ~op3
0 , 0   => 0
0 , 1   => 0
1 , 0   => 1
1 , 1   => 0
```

It can shrink the comparison instructions from 3 to 2 in both cases to calculate the overflow bit, and better, it can avoid restoring immediate value in the "right" operand to a temporary register to use op2 can be used to do an XOR operation, because op2 is omitted in the computation.

**Comment by lialan** [comment]
Another possible, better solution is to use the following structure to identify unsigned overflows:

```
a = b + c
if (a < b) or (a < c) then overflow
```

At this moment our code uses XOR/AND to construct the MSB of the overflow indicator, and test if the indicator is less than zero for overflow. To use this way to detect overflow we will have to change the way of jumping to overflow branches as well.

**Comment by kilvadyb** [comment]
I also copy my thoughts from #201:

If I understand you right then I think if we compare the result `a` with both operands then got something like the following code on pre-r6:

```
addu('a', 'b', 'c');
sltu(at, 'a', 'b');
bne(at, zero_reg, &overflow_label);
nop();
sltu(at, 'a', 'c');
bne(at, zero_reg, &overflow_label);
nop();
```

So we would have more instructions than currently.

on r6 we have `bovc, bnvc` for `add`, for `sub` it may be good:

```
Subu('a', 'b', 'c');
bgtuc('a', 'b', &overflow_label);
nop();
bgtuc('a', 'c', &overflow_label);
```

In the 1st case:
"opnd_imm32 < 0 then it becomes: (op1 ^ op3) & ~op3" also 3 instructions and if we have to do a comparison (opnd_imm32 < 0) then it results two more instructions. So please post working code snipetts or even better: a proposal CL which passes all the tests (to save me from thinking :) ).

**Comment by lialan** [comment]
@kilvadyb Sorry I was talking about pre-r6 cases, actually for the first one it is just:

```
addu('a', 'b', 'c');
sltu(at, 'a', 'b');
bne(at, zero_reg, &overflow_label);
nop();
```

Because if 'a' overflows then it will be smaller than both 'b' and 'c', testing one operand is enough. Of course using BOVC and BNVC on r6 is the best.

Also, in the 1st case, I think we can use 3 instructions (including branches) to do the trick, just look at the truth table, only when tmp2 is greater than tmp1, it will overflow, So I think we can do something like this:

```
slti tmp1, op3, 0x0
slti tmp2, op1, 0x0
blt tmp2, tmp1, &overflow_label
```

**Comment by kilvadyb** [comment]
In  the 1st case I think

```
addu('a', 'b', 'c');
sltu(at, 'a', 'b');
bne(at, zero_reg, &overflow_label);
nop();
```

cannot be enough. For example if b == -1 (0xf..ff) and c == -2 (0xf..fe) then a will be -3 (0xf..fd). 'a' is smaller then b and smaller then c but there is no overflow (a is smaller then b, c both in signed and unsigned comparison). You can compile the following code (even for mips and check the generated asm code):

```
  unsigned b = (unsigned)-1, c = (unsigned)-2, a = b + c;
  if (a < b || a < c) {
    printf("Overflow?\n");
  }
```

Am I misunderstanding something? Please make a proposal CL and run all tests (or at least some working test code) to see/prove that your idea works for corner cases.

And on MIPS we don't have `blt`by my docs and use `slt tmp1, op3, zero_reg' instead of 'slti tmp1, op3, 0`.

**Comment by lialan** [comment]
@kilvadyb Sorry I just realized that I accidentally pick the title to have "Adds/Subs", actually they should be "Addu/Subu". 

In the case of unsigned add and sub, your example is indeed an unsigned overflow.

I will probably come up with a CL of this for you to review.

**Comment by kilvadyb** [comment]
It does not matter if you call it adds or addu. On mips we have only signed add/sub (as no status flags like on arm which could be set differently). We are checking for signed overflows (like `bovc, bnvc` on r6) and -3 == -1 + -2 is not an overflow.
BOVC: Detect overflow for add (signed 32 bits) and branch if overflow.

 Doc says for `addu, addiu`:
"The term “unsigned” in the instruction name is a misnomer; this operation is 32-bit modulo arithmetic that does not trap on overflow. This instruction is appropriate for unsigned arithmetic, such as address arithmetic, or integer arithmetic environments that ignore overflow, such as C language arithmetic."

On ARM:
"Twos complement means there is no difference between signed and unsigned addition." (like on mips, we have only one kind of add) "The (add.)s bit determines whether any flags are modified or not IF modified, then carry is the unsigned overflow/borrow and v is the signed overflow/borrow." On mips we don't have carry or v flags and V8 does not care about unsigned overflow (carry bit).
