### ISSUE TITLE
Enable odd floating point registers on R6

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#226]
Let us try to enable odd floating point registers for MIPS32R6 and MIPS64R6 to Lithium register allocator and see how this affects the performance on Octane benchmark test suites.

Procedure
1) Enable odd floating point registers . Please take care to enable only temporary registers and not saved registers. Also, note that some registers may be used elsewhere (e.g. Lithium scratch register or double compare register)
2) Execute octane benchmark suite on the board before and after the change and notice changes in performance
3) If the performance increase is enough, prepare the CL to land this change

**Comment by paul99** [comment]
This should also be fine for mips64r2, as it is really tied to use of fp64 mode, not r6 specifically. 

Advantage there is we have more good test platforms like octeon-III. 

Also there is a small issue to resolve for fpxx mode, on mips32, lets talk this thru on Monday call.

**Comment by ilijapavlovic** [comment]
Here is the list of main guidelines and system information for this task:
- Adding odd FPU registers into Lithium register allocator is tested with MIPS64 architecture (big endian) and release mode.
- The register allocator list is expanded with temporary registers ($f1, $f3, $f5, $f7, $f9, $f11, $f21, $f23). (File: v8/src/mips64/assembler-mips64.h; macro: ALLOCATABLE_DOUBLE_REGISTERS(V))
- Performances are tested on hardware with CPU Cavium Octeon III V0.2  FPU V0.0 (big endian) and OS Debian GNU/Linux 7.9 (wheezy).
- Performances are measured before and after adding odd FPU registers.

From Octane benchmark, the test with intensive use of FPU registers are NavierStokes, Mandreel and Box2D. As the best candidate, Box2d is selected.

The test Box2D is performed in 50 iterations. Average score values (before and after adding odd FPU registers) are compared and achieved improvement was 1.23%.

Later, complete Octane benchmark test is performed in 10 iterations.
Here is the list of Octane benchmark tests where are shown averagre scores and achieved improvements (or degradations) with odd FPU registers.

```
Richards:      2118.9    -0.12%
DeltaBlue:     2352.6    -1.36%
Crypto:        1686.3    -1.18%
RayTrace:       420.8     0.26%
EarleyBoyer:   2541.2     0.24%
RegExp:         262.6     0.69%
Splay:         1020.5    22.14%
SplayLatency:  2554.4    -2.23%
NavierStokes:  1920.7     0.22%
PdfJS:         1055.3    -0.03%
Gameboy:       2469.3     0.22%
CodeLoad:      1348.1    -0.01%
Box2D:         1104.9    -0.72%
Typescript:     193.4    -1.38%
................................
Score:         1162.2     0.84%
```

Note: Some of tests (as Mandreel and zlib) could not be run on the big endian system.

The tests NavierStokes and Box2D  did not have performance improvements as it was expected, 
and many tests had performance degradations.

Therefore, it can be concluded that adding odd FPU registers in Lithium register allocator list 
will not improve performances.

**Comment by ilijapavlovic** [comment]
The list of Octane benchmark tests with enabled TurboFan compiler (flag: --turbo) where are shown average scores and achieved improvements (or degradations) with odd FPU registers

```
Richards:      790.6        0.08%
DeltaBlue:     541.8        0.09%
Crypto:        350.1       -0.51%
RayTrace:       26.5       -0.15%
EarleyBoyer:  1604.7       -1.52%
RegExp:        105.0        0.67%
Splay:         295.5       19.49%
SplayLatency:  693.4        2.45%
NavierStokes:  348.0        0.12%
PdfJS:         307.6        0.03%
Gameboy:       659.1        0.18%
CodeLoad:     1243.3        0.64%
Box2D:         365.1       -0.14%
Typescript:    160.2        1.78%
..................................
Score:         363.1        1.57%
```

The Splay test has 19.49% improvement with minimal score 199 and maximal score 317.

**Comment by ilijapavlovic** [comment]
Results from Kraken benchmark:

```
                       | Without odd FPUs    | With odd FPUs    | Improvement
.............................................................................
                               [ms]  +/-[%]       [ms]  +/-[%]      
Total:                      19715.4     0.5    19851.8     0.5    -0.69%

ai:                          3120.7     2.4    3251.3      2.5    -4.18%
  astar:                     3120.7     2.4    3251.3      2.5    -4.18%

audio:                       7013.4     0.4    6998.9      0.5     0.21%
  Beat-detection:            1651.3     0.2    1640.5      0.3     0.65%
  dft:                       3504.2     0.9    3500.2      0.9     0.11%
  fft:                        781.5     0.2     781.0      0.1     0.06%
  oscilator:                 1076.3     0.2    1077.2      0.1    -0.08%

imaging:                     4809.3     0.1    4788.9      0.1     0.42%
  Gaussian-blur              1419.5     0.1    1420.2      0.0    -0.05%
  darkroom:                  1403.7     0.1    1384.3      0.1     1.38%
  desaturate:                1986.0     0.1    1984.4      0.1     0.08%

json:                         735.1     0.2     735.6      0.3    -0.07%
  Parse-financial             491.3     0.3     490.8      0.4     0.10%
  Stringify-tinderbox         243.8     0.1     244.8      0.1    -0.41%

stanford:                    4037.0     0.7    4077.2      0.9    -1.00%
  Crypto-aes:                 939.0     0.7     945.6      0.8    -0.70%
  Crypto-ccm:                1076.8     1.8    1092.2      1.7    -1.43%
  Crypto-pbkdf2:             1367.6     0.6    1394.5      1.4    -1.97%
  Crypto-sha256-iterative:    653.5     1.2     644.9      1.1     1.32%
```

With additional odd FPU registers in the Lithium register allocator list, Kraken execution 
is longer for certain time amount (136.4 ms).

**Comment by ibogosavljevic** [comment]
The results show that enabling additional registers doesn't lead to any significant performance increase in any of the tests.

The performance increase can be expected only in those cases where register allocator has already allocated all 16 registers and it requires a 17th one. This is obviously not something that happens often because we don't see any noticable performance increase, except for Box2D test where it is constant around 1%.

This means that this change is not justified. The issue is closed without any changes to the source code.
