### ISSUE TITLE
v8 and fpxx

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#232]
Debian is in process of updating gcc version to >= 5.0 and this bring some news for MIPS. When compiling in this configuration, the compiler implicitly generates code which can execute on both fp32 and fp64. The new switch is called fpxx.

This is a cover issue for enabling v8 to be compiled and working with fpxx compilation flag. Currently, v8 cannot generate fpxx compatible code. This should not be a problem because we can probe at runtime to determine if we are running on fp32 or fp64.  Unfortunately, snapshots are generated during compilation of the v8, and if they are compiled on fp32, the system will not work on fp64.

We need to investigate all possible options on how to deal with this issue. The worst scenario that could happen is that  we would need to rewrite  pieces for v8 so that the code that is generated is fpxx compatible.

**Comment by ibogosavljevic** [comment]
How to check FP mode of your binary:

Dump all sections of you binary, and look for .MIPS.abiflags section. Note the number of the section

$ readelf -S program

Section Headers:
[Nr] Name Type Addr Off Size ES Flg Lk Inf Al
[ 0] NULL 00000000 000000 000000 00 0 0 0
[ 1] .note.ABI-tag NOTE 004000f4 0000f4 000020 00 A 0 0 4
**[ 2] .MIPS.abiflags LOPROC+2a 00400118 000118 000018 18 A 0 0 8**
[ 3] .reginfo MIPS_REGINFO 00400130 000130 000018 18 A 0 0 4
[ 4] .init PROGBITS 00400148 000148 000064 00 AX 0 0 4
[ 5] .text PROGBITS 004001b0 0001b0 06f6e0 00 AX 0 0 16
...

Do a hex dump of the first several bytes of the .MIPS.abiflag section. Number of our section is 2, so we use number 2 to reference it in readelf command.

$ readelf –-hex-dump=2 program (2 is number of .MIPS.abiflags section)

Hex dump of section '.MIPS.abiflags':
0x00400118 00002002 010100**05** 00000000 00000000 .. .............
0x00400128 00000000 00000000 ........

The eighth byte of .MIPS.abiflags section is fp_abi flag, and may have one of following values:

00 MIPS_ABI_FP_ANY /\* FP ABI doesn't matter _/
01 MIPS_ABI_FP_DOUBLE /_ -mdouble-float _/
02 MIPS_ABI_FP_SINGLE /_ -msingle-float _/
03 MIPS_ABI_FP_SOFT /_ -msoft-float _/
04 MIPS_ABI_FP_OLD_64 /_ -mips32r2 -mfp64 _/
05 MIPS_ABI_FP_XX /_ -mfpxx _/
06 MIPS_ABI_FP_64 /_ -mips32r2 -mfp64 _/
07 MIPS_ABI_FP_64A /_ -mips32r2 -mfp64 -mno-odd-spreg */

**Comment by ibogosavljevic** [comment]
We managed to reproduce the issue. If we compile v8 with fpxx, and run it, it will display wrong results since snapshots are assuming that the system is running of fp32, whereas the other JIT code is assuming it is running on fp64.
To reproduce the issue, you will need:
- Board MIPS Malta (MIPS 74Kc V4.9) with kernel 4.1.0.
- You need to use mti toolchain, the version that I am using is mips-mti-linux-gnu-gcc (Codescape GNU Tools 2015.01-7 for MIPS MTI Linux) 4.9.2. The issue doesn't reproduce with mips-linux-gnu-gcc (Sourcery CodeBench Lite 2015.11-32) 5.2.0.
- You need to compile your v8 statically. See patch bellow.
- Export _export GYPFLAGS="-Dmips_arch_variant=r2 -Dmips_fpu_mode=fpxx"_, and compile v8 using _make mipsel.release_
- After the compilation, run the octane test suite. You should see that many benchmarks print weird errors.
- If you recompile without snapshots (make mipsel.release snapshot=off), everything works

```
diff --git a/build/toolchain.gypi b/build/toolchain.gypi
index bcefa78..9c28f90 100644
--- a/build/toolchain.gypi
+++ b/build/toolchain.gypi
@@ -645,8 +645,8 @@
                         'cflags': ['-Wa,-mips32r2'],
                       }],
                     ],
-                    'cflags': ['-mips32r2'],
-                    'ldflags': ['-mips32r2'],
+                    'cflags': ['-mips32r2','-static -static-libgcc'],
+                    'ldflags': ['-mips32r2','-static -static-libgcc'],
                   }],
                   ['mips_arch_variant=="r1"', {
                     'cflags!': ['-mfp64', '-mfpxx'],
```

**Comment by ibogosavljevic** [comment]
After talking a little bit with guys from Valgrind, who are working on similar issue, these are the ways Linux kernel deals with fpxx compiled binaries.
- On kernel version < 3.19, fpxx compiled binaries start in FP32 mode
- On kernel version < 4.1, fpxx compiled binaries start in FP32 or FP64 mode, depending on the kernel configuration
- On kernel version > 4.1, the same thing applies as on < 4.1, with an exception. If all the code until one point in time is FPXX, and the system is running in FP32 , and then we load a library which is compiled for FP64, the dynamic linker will switch from FP32 to FP64 to accommodate the new library. It can also happen vice-versa, that the switching goes from FP64 to FP32

We have two challenges here:
- Allow v8 to be compiled with fpxx and to run correctly
- Allow v8 to switch from FP32 to FP64 and vice-versa

Allow v8 to be compiled with fpxx and to run correctly: we already dealt with this elsewhere, just as a reminder: we could generate two sets of snapshots, regenerate snapshots on the machine, even compile v8 without snapshots (this would probably work for Debian)

Allow v8 to switch from FP32 to FP64 and vice-versa: this case is more interesting. We would either 1) need to generate FPXX code or 2) disable switching mode. First thing is mostly straightforward, requiring  implementation. If we want to disable switching mode, we would need to take advice from @mfortune from #192. If v8 opens a handle to FP32 dummy library and holds it, this will disable switch to FP64.

**Comment by mfortune** [comment]
I agree with the summary from @ibogosavljevic above. (You may find it easier to discuss if you refer to the modes of execution as FR=0 and FR=1 rather than FP32 and FP64.)

Commenting on how to determine which FP mode a binary is built for...

From binutils 2.25 onwards the processor specific dump from both objdump and readelf will show the ABI in human readable form note the FP ABI line. binutils 2.25 is required for any FPXX support so it is undoubtedly at least version 2.25 in debian already.

> readelf -A myobject.o

MIPS ABI Flags Version: 0

ISA: MIPS32r2
GPR size: 32
CPR1 size: 32
CPR2 size: 0
FP ABI: Hard or soft float
ISA Extension: None
ASEs:
        None
FLAGS 1: 00000000
FLAGS 2: 00000000

**Comment by ibogosavljevic** [comment]
The FPXX has been enabled on MIPS32R2, PTAL: https://codereview.chromium.org/1586223004/

Concerning earlier architectures, adding support for FPXX on them would be very difficult, since those architectures do not support MTHC1 and MFHC1 instructions. In that case we would need to use memory to exchange double values between GP registers and FP registers, which poses two problems:
1) We need to allocate memory for this, which needs to be accessible using 1 instruction. Solution is to use the ROOT array, and this requires some workarounds which are not that pretty
2) v8 doesn't align double values on eight bit boundaries, therefore we cannot use LDC1 to load them. Normally we use two LW to load the value to GP registers, and use MTC1 and MTHC1 to transfer this to FP registers. In case of FPXX, we need to
a) load the value using 2 LW to two GP registers
b) store this value to aligned double memory address
c) use LDC1 to load from aligned memory address to FP register as double
This is too complicated so after some consideration we decided not to implement this. Building for MIPS32R1 and LOONGSON requires FP32, otherwise it might not work if process is running in FP=1 mode

We need to make sure that the code we write doesn't mess up with FPXX. Therefore we need to set up an automated builder for this to check for regressions. This has already been dealt in #239

**Comment by ibogosavljevic** [comment]
Patch landed and no regressions: https://chromium.googlesource.com/v8/v8/+/b23d5389e024a85cdc5c7d343fe5cc68a14f4d49

Next stop, running tests on the newly introduced flag. Please see #239
