### ISSUE TITLE
Implement instruction scheduler

### ISSUE THREAD

**Issue by lialan** [v8mips/v8mips#234]
We should implement instruction scheduler as other architectures do. And in fact, it is pretty easy task as the core of the scheduler is already written inside src/compiler/instruction-scheduler.h(.cc).

What we need is to return a flag for each of the MIPS instruction, and there are only 4 flags so far (defined in instruction-scheduler.h).

Maybe the no-so-obvious thing is how we handle delay slots -- do the 4 flags sufficient to describe the scenario of utilizing a delay slot?

**Comment by lialan** [comment]
first patch is checked in at:

https://codereview.chromium.org/1610433002

**Comment by lialan** [comment]
I have implemented the instruction latency model inside the same CL.

**Comment by ibogosavljevic** [comment]
Instruction scheduler is not used yet. This is duplicate of #419. CLosing issue
