### ISSUE TITLE
Remove mips64 unused ABI cruft

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#241]
There are a lot of // TODO(plind) regarding ABI in mips64. This should all be removed. We support only the `n64` ABI.

Early in the development of the mips64 port, I had thought we might create a unified mips32/mips64 port (kind of like x32/x64). That would have required different compilation directives for O32 and n64 ABI, and many other things (dealing with loading pointers appropriately thru Macros, etc.) The plan was abandoned -- and we should clean up the unused artifacts.

Search for `kMipsAbi`and you will find most things that need to be removed.

Here are some other places that I can see in a quick search.

```
code-stubs-mips64.cc: JSEntryStub::Generate():  mostly in comments.
regexp-macro-assembler-mips64.cc: big comment block at start,
```

**Comment by ilijapavlovic** [comment]
CL is uploaded and ready for review: https://codereview.chromium.org/1638303005/

**Comment by ilijapavlovic** [comment]
The patch landed as https://crrev.com/dd64a6d8a1ead06a67490c869ab4fdd13ac80b00
