### ISSUE TITLE
upgrade google's big-endian boards on bots

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#243]
Google has two erpro-8 boards - running old 3.4 kernels. (FYI, they do not use qemu for builds, and there fore run with snapshot=off).

Issues are that these are quite slow, and old. NOT a showstopper, but we should improve this.

Options are to replace them with Rhino UTM-4 running big-endian -- which has FPU and would be faster. But we have a lame outdated kernel on those boards right now, and should not do that update until we get to a modern kernel.

We could also update the erpro-8's that they have to a recent kernel.

This is low pri for now, I think we should wait and buy new UTM-4's once we get the kernel updated there.

Whatever is done would have to be coordinated with google infrastructure team in Mountain View (the boards physically reside there). I can dig up the name of the contact person I used, but maybe best to just get a name from Michael Achenbach, since the person handling this may have changed.

Raghu or some other Santa Clara person should be the contact with the Mountain View folks.

**Comment by kwan0xfff** [comment]
Boards are now running kernel v4.1.20, Debian 8.4. Git version is 2.x. (The buildbot slave info, which is manually updated, is obsolete.)

On-site visit was done on Apr 22. There was a bit remote follow-up required for one of the machines, completed by Google engineer. New manager of area is Vince Hang.
