### ISSUE TITLE
mjsunit/setters-on-elements crashes on MIPS32

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#246]
mjsunit/setters-on-elements crashes on MIPS32 on v8 simulator. Currently many ignition tests are failing and are expected to fail (see mjsuint.status) for the list of tests. But even though they are expected to fail, they are not expected to crash.

Please see here: https://v8.mips.com/bbv8/builders/Sim%20-%20edge/builds/9899/steps/Mjsunit%20-%20ignition/logs/setters-on-elements

**Comment by marijantic** [comment]
This issue does not repro on the board. It is limited to v8 simulator, mips32.

**Comment by marijantic** [comment]
The issue was fixed as of build 10117. Values of ra register were not preserved for the elided frames in turbofan. https://v8.mips.com/bbv8/builders/Sim%20-%20edge/builds/10117
