### ISSUE TITLE
Use lsa/dlsa in TF

### ISSUE THREAD

**Issue by kilvadyb** [v8mips/v8mips#248]
Other architectures are using special Operand()s to use shifted values/operands in TurboFan. We should use lsa/dlsa on r6 for the same purpose, I hope.

**Comment by lialan** [comment]
Here is a small opt for Multiplication using LSA/DLSA:

https://codereview.chromium.org/1664583002

**Comment by kilvadyb** [comment]
The patch looks promising, please check the nits I posted on the review page.

I also think about if it is possible use kMipsLsa in TF where left-shifted operands like Operand(.., LSL, ...) is used on ARM (and on Intel architectures, I guess).

**Comment by lialan** [comment]
DLSA/LSA can also be used in combining the follow code sequence:

```
__ SmiScale(at, code_, kPointerSizeLog2);
__ Daddu(result_, result_, at);
```

when criteria matches.

**Comment by kilvadyb** [comment]
SmiScale is available only on mips64 and shifts to right with:
dsra(dst, src, kSmiShift - scale);
while lsa/dlsa supports only unsigned 'sa' parameter for shifting to left. So

```
__ SmiScale(at, code_, kPointerSizeLog2);  // dsra(at, code_,  kSmiShift - kPointerSizeLog2);
__ Daddu(result_, result_, at); 
```

Cannot be replaced with Dlsa(), only with

```
__ SmiUntag(at, code_);  // dsra32(at, _code, 0);
__ Dlsa(result_, result_, at, kPointerSizeLog2);  // dlsa(result_, result_, at, kPointerSizeLog2);
```

And no win with it. Please feel free to read the implementations of MacroAssembler instructions.

**Comment by lialan** [comment]
@kilvadyb You are right, there is no win on that.

**Comment by lialan** [comment]
Patchset 5 adds a small opt of selecting DLSA/LSA in the case of operations of:

`(x << imm) + y) or (x + (y << imm))`

**Comment by kilvadyb** [comment]
Sounds good. Where can I find the code? Could you tell line numbers? I could not find it in the patchset (I guess with a rebase a lot of other code was added.)

**Comment by lialan** [comment]
@kilvadyb You can find the newly changed code in `instruction-selector-mips64.cc` and `instruction-selector-mips.cc`. The changes are in the `VisitInt32Add` and `VisitInt64Add` functions.

**Comment by kilvadyb** [comment]
After a hard fight I managed to fix typos in the CL. Now it is OK for both ignition snapshot and mjsunit/wasm/embenchen/zlib. new CL: https://codereview.chromium.org/1859143002

I also created some TF Add... tests for possible lsa/dlsa. I don't know where to add those tests:
- In test-macro-assembler-mips\* we don't use (and include headers for) turbofan tests.
- Im test-run-machops a MIPS specific test is not so good (although those tests should be passed on other architectures).

The tests:

```
diff --git a/test/cctest/compiler/test-run-machops.cc b/test/cctest/compiler/test-run-machops.cc
index 2bfe124..fc37c52 100644
--- a/test/cctest/compiler/test-run-machops.cc
+++ b/test/cctest/compiler/test-run-machops.cc
@@ -4,6 +4,7 @@

 #include <cmath>
 #include <functional>
+#include <iostream>
 #include <limits>

 #include "src/base/bits.h"
@@ -28,6 +29,43 @@ TEST(RunInt32Add) {
   CHECK_EQ(1, m.Call());
 }

+static int Int32AddLsaHelper(bool is_left) {
+  RawMachineAssemblerTester<int32_t> m;
+  Node* shift = m.Word32Shl(m.Int32Constant(4), m.Int32Constant(2));
+  Node* add = m.Int32Add(m.Int32Constant(20), m.Int32Constant(22));
+  Node* lsa = is_left ? m.Int32Add(shift, add) : m.Int32Add(add, shift);
+  m.Return(lsa);
+  Handle<Code> code = m.GetCode();
+  code->Print(std::cout);
+  return m.Call();
+}
+
+TEST(RunInt32AddLsa) {
+  // Shift at right.
+  CHECK_EQ(58, Int32AddLsaHelper(false));
+
+  // Shift at left.
+  CHECK_EQ(58, Int32AddLsaHelper(true));
+}
+
+static int64_t Int64AddDlsaHelper(bool is_left) {
+  RawMachineAssemblerTester<int64_t> m;
+  Node* shift = m.Word64Shl(m.Int64Constant(4), m.Int64Constant(2));
+  Node* add = m.Int64Add(m.Int64Constant(20), m.Int64Constant(22));
+  Node* dlsa = is_left ? m.Int64Add(shift, add) : m.Int64Add(add, shift);
+  m.Return(dlsa);
+  Handle<Code> code = m.GetCode();
+  code->Print(std::cout);
+  return m.Call();
+}
+
+TEST(RunInt64AddDlsa) {
+  // Shift at right.
+  CHECK_EQ(58, Int64AddDlsaHelper(false));
+
+  // Shift at left.
+  CHECK_EQ(58, Int64AddDlsaHelper(true));
+}

 TEST(RunWord32ReverseBits) {
   BufferedRawMachineAssemblerTester<uint32_t> m(MachineType::Uint32());
```

**Comment by kilvadyb** [comment]
I got respone to the test question so am working on a followup test CL.

**Comment by kilvadyb** [comment]
CL: https://codereview.chromium.org/1859143002 and followup test CL: https://codereview.chromium.org/1867923002/ landed.

**Comment by kilvadyb** [comment]
We should investigate https://codereview.chromium.org/1972103002/ and https://codereview.chromium.org/1974263002/ to check if we could use (d)lsa for the same cases.

**Comment by kilvadyb** [comment]
I debugged and studied the two arm CLs and all the LSL operand occurrences in turbofan arm code and I think there is no more place to use `lsa/dlsa` at the moment.
