### ISSUE TITLE
Fix compilation for mac / clang

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#25]
There are some compilation errors  on v8 when using Mac with Mountain Lion / Xcode 4. 

to be precise, I am using OS-X 10.8.1, xcode 4.4.1 / i686-apple-darwin11-llvm-gcc-4.2 (GCC) 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00)

These errors are unused variable warnings that clang is more picky about than gcc.

I have fixed this in https://github.com/paul99/v8m-rb/commit/dcb7847b9175739094be99a743c81397b2a250ee

I think I will do OS upgrade to 10.8.2, and Xcode 4.5.1 and re-test, and if that is good, I will ask you to submit. Leaving issue with me until testing is complete.

**Comment by paul99** [comment]
I updated the mac to latest 10.8.2, Xcode 4.5.1. The gcc revision is the same as in above comment.

The fix in https://github.com/paul99/v8m-rb/commit/dcb7847b9175739094be99a743c81397b2a250ee still works fine.

Assigning to Akos to submit upstream to Google.

**Comment by palfia** [comment]
Submitted to Google and cherry-picked to bleeding_edge as 4e3d5814f7
