### ISSUE TITLE
Fix -0/+0 handling in simulator FPU min, max

### ISSUE THREAD

**Issue by kilvadyb** [v8mips/v8mips#250]

**Comment by kilvadyb** [comment]
I am working on (testing) a fix CL which also decreases copy-paste code a bit. I plan tol use the same technique for mina, maxa if the solution is expected.

**Comment by kilvadyb** [comment]
Proposal CL uploaded: https://codereview.chromium.org/1668143002/
I also added +/-inf to the cctest assembler tests. Would be fine to run tests on a real HW.

**Comment by kisg** [comment]
Landed.
