### ISSUE TITLE
Optimize Instruction class usage in simulator

### ISSUE THREAD

**Issue by kilvadyb** [v8mips/v8mips#251]
With introducing a new subclass of Instruction which is able to store type info the tests on simulator got 10% improvement and we don't loose the full usage of DCHECK()s.

Proposal CL:
https://codereview.chromium.org/1349403003/

![instruction_3](https://cloud.githubusercontent.com/assets/1742387/12824252/9a0701bc-cb70-11e5-9235-b4f1c6940bc8.png)

**Comment by kilvadyb** [comment]
Ping

**Comment by lialan** [comment]
I think this effectively changes the data locality of the instruction, and makes LLVM able to inline the various field member functions called in simulator, which both in conjunction boost the sim performance.

It is a good idea to do so, but just wondering, do we really need a SimInstruction class?

**Comment by kilvadyb** [comment]
I don't understand you, Alan. It's not about LLVM, it's about avoiding many re-calculation of InstructionType().
Function members of Instruction class contain type checking DCHECK()s (which slows down the simulator in debug mode):

```
  inline int32_t ImmValue(int bits) const {
    DCHECK(InstructionType() == kImmediateType);
    return Bits(bits - 1, 0);
  }
```

InstructionType() is computed again and again from the pointed bits of the instr (Instruction object's *this). As simulator works sequentially, it reads the next instruction, processes it then read the next and so on. So simulator can compute the type of the currently processed instruction only once and store it. To store/cache the type info, I introduced a new (almost) sub-class: SimInstruction. I used templates to "inherit" functions and avoid code duplication. Virtual functions cannot be used as an Instruction object never allocated (just a 4 bytes memory area casted with Instruction::At(addr) and an Instruction object's this points to that 4-byte instruction. No place for virtual table or data members).

**Comment by lialan** [comment]
@kilvadyb Thanks for the explanation, I didn't know that there was such as complicated structure that computes type info every time. 

In that case, I think you made a good point to cache those info.

**Comment by kilvadyb** [comment]
Sure, I should have started with the description. Paul has chosen to use a quick and not so reliable InstructionType(NORMAL | EXTRA) parameter/implementation. My solution is even quicker and no info lost. Anyway InstructionType() uses a big switch (which is evaluated 2 or 3 times per each instruction executed by the simulator). I measured 10% execution time improvement on simulator optdebug.(quick)check.

**Comment by kilvadyb** [comment]
Rebased to Tot and fixed for 32-bit.

**Comment by kilvadyb** [comment]
Fixed and rebased CL published.

**Comment by kilvadyb** [comment]
optdebug.quickcheck time is improved from 5:46 to 5:19 on the same, otherwise idle machine.

**Comment by kilvadyb** [comment]
32 bits CL landed.

**Comment by kilvadyb** [comment]
32-bit CL https://codereview.chromium.org/1349403003/ landed.

**Comment by kilvadyb** [comment]
64-bit proposal CL: https://codereview.chromium.org/2375673002, PTAL.

The main point of this modification was to avoid the quick instruction type check for simulator and be even quicker with a deep check. Paul introduced a check type enum with NORMAL (deep check) and EXTRA (quick check for simulator). But now it seems to be messed up and simulator run fails with NORMAL instruction type check. I  am going to investigate this problem.

**Comment by kilvadyb** [comment]
InstructionType(EXTRA, NORMAL) removed on 64-bit but I cannot upload a separated CL yet. I plan to make a 32-bit CL and add 64-bit patchset when the https://codereview.chromium.org/2375673002/ landed. PTAL

**Comment by kilvadyb** [comment]
To remove 32-bit EXTRA|NORMAL for InstructionType(): https://codereview.chromium.org/2374013004

PTAL. If 64-bit proposal CL: https://codereview.chromium.org/2375673002 landed then I can upload the 64-bit patchset for this CL (I hope).

**Comment by kilvadyb** [comment]
https://codereview.chromium.org/2375673002 landed.

**Comment by kilvadyb** [comment]
InstructionType checking fix CL: https://codereview.chromium.org/2374013004/ landed.
