### ISSUE TITLE
Use max_d, min_d in LCodeGen::DoMathMinMax.

### ISSUE THREAD

**Issue by kilvadyb** [v8mips/v8mips#257]
Jakob's suggestion:

> MIPS folks: FYI. I noticed that there are max_d/min_d instructions in
> assembler-mips{,64}.h. If those do what their name suggests, then the
> MIPS/MIPS64 implementations of the representation.IsDouble() branch of
> LCodeGen::DoMathMinMax could be as simple as it is on arm64. I'm leaving this up
> to you to improve in a follow-up CL if you want. (Crankshaft is deprecated so
> it's not worth putting a whole lot of effort into.)

**Comment by lialan** [comment]
Just wild guesses: `max.fmt` on MIPS performs differently than the V8 convention, perhaps we should wait until NaN handling is implemented in #247 ?

**Comment by kilvadyb** [comment]
NaN handling has been added to the CL of #247 already. That issue is waiting for a review for a while :)

**Comment by kilvadyb** [comment]
Proposal CL uploaded: https://codereview.chromium.org/1876223003/

**Comment by kilvadyb** [comment]
The usage of macro instructions removed the old implementation of the following algorithm:
      // The algorithm is: -((-L) + (-R)), which in case of L and R being
      // different registers is most efficiently expressed as -((-L) - R).
I cannot see why the old code block would be better then simple comparison but it should be reviewed, discussed.

**Comment by kilvadyb** [comment]
Improved CL landed: https://codereview.chromium.org/1876223003/
