### ISSUE TITLE
mips_arch_variant bug in gyp build

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#26]
There is a small bug that causes us to build mips32r2 version of v8 as mips32 (r1). This effects only the compiled code. Our generated code is correctly set for mips32r2.

In the default case of building for mips32r2, we get these compiler flags:

```
-EL -mhard-float -mips32r2 -Wa,-mips32r2 -mips32 -Wa,-mips32
```

Since the "last flag wins" the object files are compiled as mips32. In a funny twist, the code sourcery lite compilers do not have multi-lib support, and there is a bug that if you tell it to link mips32, it will silently link your object files with mips32r2 libraries, and then the resulting binary is mips32r2.

We do get this define also: -D_MIPS_ARCH_MIPS32R2' which controls our generated code.

Now this probably does not hurt us too bad, but it would be interesting to run benchmarks on a r2 platform, and see if there is any noticeable performance difference. (I doubt there will be, but that would be useful to decide if we ant to fix this only on bleeding_edge, or backport to some branches.)

I tested this on https://github.com/v8/v8/commit/34c172e79aa870156db237c334ebb89cc9fef805
(as the next commit breaks our build today)

**Comment by paul99** [comment]
The problem is this sequence in build/common.gypi:

```
              ['mips_arch_variant=="mips32r2"', {
                'cflags': ['-mips32r2', '-Wa,-mips32r2'],
              }],
              ['mips_arch_variant=="loongson"', {
                'cflags': ['-mips3', '-Wa,-mips3'],
              }, {
                'cflags': ['-mips32', '-Wa,-mips32'],
              }],
```

GYP has kind of limited if/else syntax, but it does not support if (cond1) { A } else if (cond2 { B } else { C }, which is what we are asking it to do here. So if we are using mips32r2, the we get the cflags for both A & C (mips32r2 AND mips32)

One fix is this:

```
diff --git a/build/common.gypi b/build/common.gypi
index dc5456b..566a21c 100644
--- a/build/common.gypi
+++ b/build/common.gypi
@@ -200,10 +200,11 @@
                   ['mips_arch_variant=="mips32r2"', {
                     'cflags': ['-mips32r2', '-Wa,-mips32r2'],
                   }],
+                  ['mips_arch_variant=="mips32r1"', {
+                    'cflags': ['-mips32', '-Wa,-mips32'],
+                 }],
                   ['mips_arch_variant=="loongson"', {
                     'cflags': ['-mips3', '-Wa,-mips3'],
-                  }, {
-                    'cflags': ['-mips32', '-Wa,-mips32'],
                   }],
                 ],
               }],
```

Dusan, can you review this, and either approve, or suggest something better? I did limited testing of this, and did not test on the simulator (where this section should be skipped.). But please do test this thoroughly.

**Comment by dusmil** [comment]
The patch is fine,  I have tested it both for simulator build,  and cross compilation,  but with gyp revision 1228.
The problem is that I cannot force CodeSourcery 4.4 toolchain with appropriate flags to generate pure mips32 revision 1 object files, so I use Broadcom toolchain  for testing instead.   

The cross compilation with gyp build system is broken even for ARM after updating gyp to revision 1501 in commit:  1a561f1

**Comment by palfia** [comment]
We also had problems, when we tried to compile V8 with the new gyp. The new gyp tries to link the d8 binary with ld, but it fails, because it seems from the command line parameters, that it should use g++. Therefore as a quick fix we changed the LINK environment variable to g++. 
So the actual mips_env.sh looks like this:

```
# Flag for SConstruct to set flags needed for gcc 4.4, including -fno-strict-alias
export GCC_VERSION=44

# Sets up aliases for gcc & binutils, to support cross-compilation
CCPATH=/data/CodeSourcery/mips-4.4-303/bin
export CC=$CCPATH/mips-linux-gnu-gcc
export CXX=$CCPATH/mips-linux-gnu-g++
export AR=$CCPATH/mips-linux-gnu-ar
export RANLIB=$CCPATH/mips-linux-gnu-ranlib
export LINK=$CCPATH/mips-linux-gnu-g++

```

**Comment by paul99** [comment]
Akos - Thanks for the input. On the our gpy wiki page, Dusan had written this, which is same as you say, and I had been doing that with r1228 also:

Also, it is needed for cross build to export one additional environment variable as: export LINK=$CXX

Is there something else broken with r1501 gyp?

Dusan, you said it is broken for Arm as well. Can you provide more details? We should at least submit a bug report to google team, in case they are not aware....

**Comment by dusmil** [comment]
I see errors for ARM cross-compiling, and I am sure I set LINK variable properly:

Here is the error message:

/scratch/scratch/v8mips/dusan/opt/arm-2010q1/bin/arm-none-linux-gnueabi-ld: unrecognized option '-Wl,--start-group'
/scratch/scratch/v8mips/dusan/opt/arm-2010q1/bin/arm-none-linux-gnueabi-ld: use the --help option for usage information
make[1]: **\* [/scratch/scratch/v8mips/dusan/quick/v8m-rb/out/arm.release/preparser] Error 1

The new gyp calls ld directly instead of calling g++ for linking, but problem is that it passes flags as it would call g++, and that is wrong.

**Comment by palfia** [comment]
We had exactly the same problem on both MIPS and ARM, but with the modified ccenv sh above, it works fine (using CodeSourcery toolchain 4.4 and gyp r1501).

**Comment by dusmil** [comment]
The actual cause of the problem is exported LD environment variable.
Be advised,  unset LD variable , or remove it from script when build with new version of gyp.

**Comment by paul99** [comment]
Dusan, thanks for figuring that out, I removed LD var, and am using r1501, and it works fine.

I updated the wiki page to add a bit more detail on building. Please take a look.

**Comment by paul99** [comment]
Akos, can you please upstream this fix (the diff in comment 2 above)?

**Comment by paul99** [comment]
Akos, please hold off on upstreaming. I have having doubts that this is the "final" change, and we might want to do some more work before upstreaming.

(I think you are on Holiday for Tuesday, but I want to discuss this with Dusan before we move forward. I will either update this issue, or let Gergely know the resolution here. Just FYI, the issue is that I am having problems getting v8 build options like arch_variant to work properly in Chromium)

**Comment by paul99** [comment]
Akos, please go ahead and submit this one. There may be more GYP changes coming, but this one is necessary and does work correctly. We can close this issue when the change is landed at google.

**Comment by palfia** [comment]
I've submitted this change to Google in this CL: https://chromiumcodereview.appspot.com/11289003/

**Comment by paul99** [comment]
Fixed and landed 4 months ago. Closing
