### ISSUE TITLE
Disallow usage of Assembler instructions which has better/safer MacroAssembler version.

### ISSUE THREAD

**Issue by kilvadyb** [v8mips/v8mips#261]
For example 'sa' parameter handling in Lsa/Dlsa macro instructions slightly differ from the MIPS assembler definitions and we have cctests only for the MacroAssembler functions and only the MacroAssembler functions are allowed to be used. We could make the Assembler::[d]lsa() functions private. I plan to make a proposal CL for that. Every team member is invited to discuss our possibilities.

**Comment by kilvadyb** [comment]
Proposal Lsa/Dlsa CL:
https://codereview.chromium.org/1749263002/

**Comment by ibogosavljevic** [comment]
The patch has landed so we are closing this issue
