### ISSUE TITLE
Bughunting: cctest/test-serialize/SerializeInternalReference

### ISSUE THREAD

**Issue by kilvadyb** [v8mips/v8mips#262]
New test failure in the buildbots: cctest/test-serialize/SerializeInternalReference

https://dmz-portal.mips.com/bbv8/builders/Sim%20-%20edge/builds/10318

**Comment by marijantic** [comment]
Issue started appearing after the change 
https://chromium.googlesource.com/v8/v8/+/d1df58e8d734ceb7d475b9c83263466f6ccd9031

**Comment by kilvadyb** [comment]
Seems to be fixed with
a3a583dbaa79f22c1f9a8ad1dfd846c43d6ce9e2 -- [turbofan] Re-enables the jump table emission in the mips instruction selector.

**Comment by kilvadyb** [comment]
The CL looks good. We could fix it earlier if we catch the CL where the comment appeared about the ra issue :(

**Comment by marijantic** [comment]
Yes, simply re-enabling th EmitTableSwitch in instruction selector fixed the failing test, but other tests started failing due to problem with ra value. I was just working on modifying GenerateSwitchTable method.

**Comment by kilvadyb** [comment]
Fixed by
a3a583dbaa79f22c1f9a8ad1dfd846c43d6ce9e2 -- [turbofan] Re-enables the jump table emission in the mips instruction selector.
