### ISSUE TITLE
Bughunting: mjsunit/wasm/params

### ISSUE THREAD

**Issue by kilvadyb** [v8mips/v8mips#269]

**Comment by marijantic** [comment]
https://v8.mips.com/bbv8/builders/Target%20-%20edge/builds/6639/steps/Check/logs/params

**Comment by marijantic** [comment]
The first build to experience the issue: https://v8.mips.com/bbv8/builders/Target%20-%20edge/builds/6506

**Comment by marijantic** [comment]
The issue does not repro on the ci20 board. Tests are running on the Popcorn board, so this seems to be the hardware issue.

**Comment by ibogosavljevic** [comment]
This issue does not reproduce for a very long time, so closing it.
