### ISSUE TITLE
Bughunting: Several MIPS64 debug failures.

### ISSUE THREAD

**Issue by palfia** [v8mips/v8mips#273]
There are several test failures on MIPS64 in debug mode.

I didn't go through the whole list, but most of them fails on both sim and target, however they fail in a different way, on sim it reads nullptr, but on target they fail at a DCHECK.

Sim: https://v8.mips.com/bbv8/builders/Sim%20-%20MIPS64%20-%20Debug%20-%20edge/builds/7039
Target: https://v8.mips.com/bbv8/builders/Target%20-%20MIPS64%20-%20Debug%20-%20edge/builds/1020

Please bisect and debug the failures.

**Comment by marijantic** [comment]
Issues on simulator started appearing after https://v8.mips.com/bbv8/builders/Sim%20-%20MIPS64%20-%20Debug%20-%20edge/builds/7005

**Comment by marijantic** [comment]
On the board, the first build with failures is https://v8.mips.com/bbv8/builders/Target%20-%20MIPS64%20-%20Debug%20-%20edge/builds/1019
Common change in both of the builds is https://chromium.googlesource.com/v8/v8/+/9dcd0857d64a117801bf91cb6caf7d6578809cb1

**Comment by marijantic** [comment]
atomics-exchange.js: Problem is in MacroAssembler::CheckAccessGlobalProxy, the changes introduced to context loading are not preserving the value of at during JumpIfNotSmi call. Also, two consecutive branch instructions are introduced. Local fix is available, testing in progress.

**Comment by marijantic** [comment]
PTAL: https://codereview.chromium.org/1812463002/

**Comment by palfia** [comment]
Looks good, nice find!

**Comment by marijantic** [comment]
Patchset landed as https://crrev.com/b64bcb41b13747a5f7a1a221397990efa1f4fcc4
