### ISSUE TITLE
Bughunting: unittests/Bytecodes.DecodeBytecodeAndOperands

### ISSUE THREAD

**Issue by mkaric** [v8mips/v8mips#281]
https://v8.mips.com/bbv8/builders/Target%20-%20big%20-%20edge%20-%20no%20i18n/builds/6849
https://v8.mips.com/bbv8/builders/Target%20-%20big%20-%20Debug%20-%20edge%20-%20no%20i18n/builds/4888
https://v8.mips.com/bbv8/builders/Target%20-%20MIPS64%20-%20big%20-%20Debug%20-%20edge%20-%20no%20i18n/builds/927

**Comment by joransiu** [comment]
We are also seeing the same failure on s390x.  @john-yan is investigating, and in the meantime, he has requested the test be skipped on Big Endian platforms: https://codereview.chromium.org/1858793002/

**Comment by mkaric** [comment]
Thanks. So far I concluded that the problem is in the call to ReadUnalignedUInt16 and ReadUnalignedUInt32 functions in interpreter/bytecodes.cc which return a different value for big endian (byte reversed). Simply reversing the byte order of this value for big endian makes this test pass, but the change causes new failures. Here is the diff:

```
diff --git a/src/interpreter/bytecodes.cc b/src/interpreter/bytecodes.cc
index 136e280..701e84a 100644
--- a/src/interpreter/bytecodes.cc
+++ b/src/interpreter/bytecodes.cc
@@ -456,9 +456,17 @@ int32_t Bytecodes::DecodeSignedOperand(const uint8_t* operand_start,
     case OperandSize::kByte:
       return static_cast<int8_t>(*operand_start);
     case OperandSize::kShort:
+#if V8_TARGET_BIG_ENDIAN
+      return static_cast<int16_t>(__builtin_bswap16(ReadUnalignedUInt16(operand_start)));
+#else
       return static_cast<int16_t>(ReadUnalignedUInt16(operand_start));
+#endif
     case OperandSize::kQuad:
+#if V8_TARGET_BIG_ENDIAN
+      return static_cast<int32_t>(__builtin_bswap32(ReadUnalignedUInt32(operand_start)));
+#else
       return static_cast<int32_t>(ReadUnalignedUInt32(operand_start));
+#endif
     case OperandSize::kNone:
       UNREACHABLE();
   }
@@ -474,9 +482,17 @@ uint32_t Bytecodes::DecodeUnsignedOperand(const uint8_t* operand_start,
     case OperandSize::kByte:
       return *operand_start;
     case OperandSize::kShort:
+#if V8_TARGET_BIG_ENDIAN
+      return __builtin_bswap16(ReadUnalignedUInt16(operand_start));
+#else
       return ReadUnalignedUInt16(operand_start);
+#endif
     case OperandSize::kQuad:
+#if V8_TARGET_BIG_ENDIAN
+      return __builtin_bswap32(ReadUnalignedUInt32(operand_start));
+#else
       return ReadUnalignedUInt32(operand_start);
+#endif
     case OperandSize::kNone:
       UNREACHABLE();
   }
```

**Comment by john-yan** [comment]
Hello @mkaric , thanks for the information and yes that's exactly where the problems are! Given that 5.1 branch are cut in this Friday, introducing new failures is definitely not a good idea. :)

**Comment by mkaric** [comment]
@john-yan Hello, have you been looking at this problem? I noticed your commit comment where you disabled the test for BE. Do you think the problem is in the test (input data should be different for BE machines) or in the interpreter code (data should be corrected on BE)?

**Comment by john-yan** [comment]
@mkaric Let me show you why it's failing:

In the 2nd test, which is 
`{{B(Wide), B(LdaSmi), 0xe8, 0x03}, 4, 0, "      LdaSmi.Wide [1000]"},`
1000 is represented by 0x03e8 in hex. In LE, it's stored as 0xe8, 0x03 as shown. In BE natively, it should be the reverse 0x03, 0xe8.

It could be fixed by reversing the input or fixed by doing reversed load in the interpreter code.

**Comment by mkaric** [comment]
@john-yan Thanks, yes I was aware reversing input data like that would fix the problem, but wasn't sure that would be the correct solution. My understanding of the interpreter is not at a high level at this point. So basically the test input data values should be reversed for BE and that would fix the issue.

**Comment by john-yan** [comment]
@mkaric I don't understand why v8 needs a interpreter either. :( Given 5.1 source is cut today, I just disabled it on BEs.

**Comment by mkaric** [comment]
Uploaded a CL, PTAL: https://codereview.chromium.org/1881423002/

**Comment by john-yan** [comment]
LGTM!

**Comment by mkaric** [comment]
Landed as https://crrev.com/3b416c67f5c5294ffb937110478baf6048c0c39a, closing.

**Comment by mkaric** [comment]
Test is failing again for big endian.

**Comment by john-yan** [comment]
I asked Orion about the matter and here is the reply:

> It looks like I missed adding a macro for a case in the test - so much for making the test easier to maintain :-)
> 
> Can you try replacing:
> {B(Wide), B(LdaSmi), 0x18, 0xfc}, 4, 0, "      LdaSmi.Wide [-1000]"}
> 
> with:
> 
> {B(Wide), B(LdaSmi), U16(-1000)}, 4, 0, "      LdaSmi.Wide [-1000]"}
> 
> Hopefully this helps. I'm offline from now until Thursday so can't land anything from here.
> 
> Best regards
> 
> Orion

Looks like we need to add the U16 macro.

**Comment by mkaric** [comment]
@john-yan U16 macro is already there, he just missed one spot where is should be used. Actually there is another one where U8 should be used. I will prepare the CL.

**Comment by mkaric** [comment]
Uploaded a CL: https://codereview.chromium.org/2024123002/

**Comment by john-yan** [comment]
@mkaric your fix is LGTM, thanks! Could you also port it to 5.2-lkgr, which is also failing on this issue?

**Comment by mkaric** [comment]
Landed as https://crrev.com/b8786b35fcbf4cec390cf22a0c5da42e690df77b.

**Comment by mkaric** [comment]
Test is still failing on builders, there seems to be another error in the test causing the failure for big endian.

**Comment by mkaric** [comment]
@john-yan I uploaded a CL for 5.2, can you have a look: https://codereview.chromium.org/2032493003

**Comment by john-yan** [comment]
@mkaric That looks good to me. Thanks!

**Comment by mkaric** [comment]
Uploaded a fix CL: https://codereview.chromium.org/2030063002/, it turns out one value in the test should be U8 instead of U16.

**Comment by mkaric** [comment]
Landed as https://crrev.com/16dda2152f4823e7557e76fe993199703d872227.

**Comment by mkaric** [comment]
@john-yan Landed another CL for 5.2 (https://codereview.chromium.org/2031283002).

Test now passes. Closing.

**Comment by john-yan** [comment]
Could you please also backport to 5.2?

**Comment by john-yan** [comment]
Thanks!
