### ISSUE TITLE
Overflow not detected by AddBranchOvf and SubBranchOvf 

### ISSUE THREAD

**Issue by marijantic** [v8mips/v8mips#283]
Apply the attached patch (modify Mips AddPair and SubPair to use AddBranchOvf and SubBranchOvf).

[addBranchOvf.txt](https://github.com/v8mips/v8mips/files/195518/addBranchOvf.txt)

Run the  RunInt32PairAdd and RunInt32PairSub tests 
out/mipsel.optdebug/cctest --random-seed=1089846861 --stress-opt --always-opt test-run-machops/RunInt32PairAdd --nohard-abort --nodead-code-elimination --nofold-constants --enable-slow-asserts --debug-code --verify-heap
out/mipsel.optdebug/cctest --random-seed=1089846861 --stress-opt --always-opt test-run-machops/RunInt32PairSub --nohard-abort --nodead-code-elimination --nofold-constants --enable-slow-asserts --debug-code --verify-heap

Result: The tests are failing. Overflow is not detected correctly.
Simulator trace for RunInt32PairAdd, for input FFFFFFFF and 00000001:
0x5d112ff4  8c820000       lw      v0, 0(a0)               00000001 <-- [ff92cd98](34551)
 0x5d112ff8  8ca30000       lw      v1, 0(a1)               00000000 <-- [ff92ce2c](34552)
 0x5d112ffc  8cc40000       lw      a0, 0(a2)               ffffffff <-- [ff92ce28](34553)
 0x5d113000  8ce50000       lw      a1, 0(a3)               00000000 <-- [ff92ce24](34554)
 0x5d113004  00653821       addu    a3, v1, a1              00000000
 0x5d113008  00823021       addu    a2, a0, v0              00000000
 0x5d11300c  00c4c826       xor     t9, a2, a0              ffffffff
 0x5d113010  00c29826       xor     s3, a2, v0              00000001
 0x5d113014  0279c824       and     t9, s3, t9              00000001
 0x5d113018  07210002       bgez    t9, 2 -> 0x5d113024  
 0x5d113024  3c02ff92       lui     v0, 0xff92              ff920000
 0x5d113028  3442cde8       ori     v0, v0, 0xcde8          ff92cde8
 0x5d11302c  ac460000       sw      a2, 0(v0)               00000000 --> [ff92cde8]
 0x5d113030  3c02ff92       lui     v0, 0xff92              ff920000
 0x5d113034  3442cdec       ori     v0, v0, 0xcdec          ff92cdec
 0x5d113038  ac470000       sw      a3, 0(v0)               00000000 --> [ff92cdec]
 0x5d11303c  8fc30018       lw      v1, 24(fp)              ff92ce54 <-- [f3b81fc0](34567)
 0x5d113040  2402004a       addiu   v0, zero_reg, 74        0000004a

The condition   0x5d113018  07210002       bgez    t9, 2 -> 0x5d113024 will always be satisfied, as the overflown bit actually carries the sign of the result

**Comment by kilvadyb** [comment]
In Sub|AddPair we need unsigned overflow while Add|SubBranchOvf() functions handles signed overflow. For example -1 + 1 == 0 is correct in signed case, no overflow. In unsigned case -1 is `0xffffffff` and `0xffffffff + 1` is `0x100000000` which is greater then MAX_UINT32. The question is that we should add unsigned overflow functions to MacroAssembler (Add|SubBranchUOvf()) or not. IMO we should move `Add|SubPair` ops to MacroAssembler and put comment into the source of them about unsigned overflow handling. And if we need unsigned overflow once more then we can create functions for them.

**Comment by ibogosavljevic** [comment]
I'm going to write tests for these two functions and and possibly rename them if ok with you yo AddBranchOvfSigned / SubBranchOvfSigned

**Comment by kilvadyb** [comment]
Rename is a good idea as these functions caused many misunderstanding already. I would prefer AddBranchSignedOvf but does not matter. There are quite many overflow checking tests already, please check them to find out what we need.

**Comment by ibogosavljevic** [comment]
CL: https://codereview.chromium.org/1857193002/

**Comment by ibogosavljevic** [comment]
We added tests that verify behavior of Branch functions

Patch landed:
https://crrev.com/d4403b172f357e6e44e4571a3332c437d3ce08c9

tests are passing on mipsr2 and mipsr6, 32 and 64
