### ISSUE TITLE
SmiTag()/SmiUntag() around stub calls

### ISSUE THREAD

**Issue by kilvadyb** [v8mips/v8mips#284]
I had to do a fix CL where

```
__ SmiTag(a0);
__ SmiTag(a3);
...
ToNumberStub stub(masm->isolate());
__ CallStub(&stub);
...
__ SmiUntag(a3);
__ SmiUntag(a0);
```

was added to a call of a stub function. From our point of view the tagging/untagging is quite useless (a0 and a3 is not used inside the tagging block -- v8 tests were passed without those instructions). But there was a chromium failure when GC was activated from the code of the ToNumber stub (I guess). The chromium bug:
https://bugs.chromium.org/p/chromium/issues/detail?id=598651

The bugreport:
"This is (without tagging) not GC save. There exists a path (at least on the simulator) to trigger
a GC from ToNumberStub which expects values on the stack to be properly tagged."

A call trace can be found in the last message from Michael Lippautz at
https://codereview.chromium.org/1694833002/

**Comment by kisg** [comment]
This is an important information, and should be added to the wiki.
@kilvadyb: Please add this information to the wiki. I think we should create a developer info page for infos like this. Suggestions for the name of the page welcome. (e.g. V8MIPS Developer Guide ? )
After it has been added to the wiki, the issue can be closed

**Comment by kilvadyb** [comment]
Proposal page added: https://github.com/v8mips/v8mips/wiki/V8MIPS-Developer-Guide
