### ISSUE TITLE
Bughunting: multiple test failures on MIPS64

### ISSUE THREAD

**Issue by palfia** [v8mips/v8mips#286]
Since build: https://v8.mips.com/bbv8/builders/Sim%20-%20MIPS64%20-%20edge/builds/7395

**Comment by marijantic** [comment]
One of the failures was present before the above mentioned build, opened #288  to track it.

**Comment by marijantic** [comment]
Local fix available for Builtins::Generate_ResumeGeneratorTrampoline, testing in progress.

**Comment by marijantic** [comment]
PTAL: https://codereview.chromium.org/1869343003/

**Comment by marijantic** [comment]
Patch landed as https://chromium.googlesource.com/v8/v8/+/a39544b674e9392d25fe7f6f82f27dbf8d0f9267
