### ISSUE TITLE
Bughunting: failing Run_Wasm_I64Binops for MIPS64

### ISSUE THREAD

**Issue by marijantic** [v8mips/v8mips#288]
https://v8.mips.com/bbv8/builders/Sim%20-%20MIPS64%20-%20edge/builds/7408/steps/Check/logs/Run_Wasm_I64Binops

The test is failing for Ror/Rol operations. These have a fall-back to Sub, needs investigation.

**Comment by marijantic** [comment]
This is a simulator issue. Basically, drotr and drotr32 are not implemented, i.e DSRL and DSRL32 are missing the rotate part.

**Comment by marijantic** [comment]
PTAL: https://codereview.chromium.org/1880953002/

**Comment by palfia** [comment]
Closing issue, fixed by https://codereview.chromium.org/1880953002/ .
