### ISSUE TITLE
Bughunting: Failing Run_WasmCall_Int64Sub and Run_Wasm_MemI64_Sum for big endian

### ISSUE THREAD

**Issue by marijantic** [v8mips/v8mips#289]
Failing since build https://v8.mips.com/bbv8/builders/Target%20-%20big%20-%20edge%20-%20no%20i18n/builds/6996/

**Comment by marijantic** [comment]
Debugging of Run_WasmCall_Int64Sub for MIPS32 on a big-endian board reveals the following: 
On a 32-bit platform, the subtraction operation is lowered to SubPair.  
Assume that the test is run with the values 00000001 FFFFFFFF and 1B09788B FFFFFFFF. The SubPair method in macro-assembler-mips.cc is given the values of left_low = 00000001, left_high = FFFFFFFF, right_low 1B09788B and right_high = FFFFFFFF. The order of high and low words in the operands is wrong.

**Comment by palfia** [comment]
Skipped for big-endian by: https://codereview.chromium.org/1948053002

**Comment by palfia** [comment]
Put this on hold until we resolve #276.

**Comment by marijantic** [comment]
Solved by https://codereview.chromium.org/2034093002/. Closing the issue.
