### ISSUE TITLE
Port new CL: https://codereview.chromium.org/1759383003

### ISSUE THREAD

**Issue by palfia** [v8mips/v8mips#293]
Please port this CL to MIPS.

Since build: https://v8.mips.com/bbv8/builders/Target%20-%20edge/builds/6909

**Comment by ilijapavlovic** [comment]
CL with solution is uploaded and ready for review. https://codereview.chromium.org/1886723003/
Tested with architectures mips, mips64, mipsel, mips64el and variant r2 in release mode.

**Comment by ilijapavlovic** [comment]
Solution is tested for following tests (in different flag combinations):
- test-run-wasm-machops/RunLoadStoreRelocationOffset
- test-run-wasm-machops/RunLoadStoreRelocation
- test/mjsunit/wasm/module-memory.js

**Comment by ilijapavlovic** [comment]
Landed as https://crrev.com/ec5995a1049375dcd0df1fb9bb7d7351edb98112
