### ISSUE TITLE
Bughunting: Simulator MIPS64 edge: failing mjsunit/harmony/futex

### ISSUE THREAD

**Issue by ilijapavlovic** [v8mips/v8mips#295]
The following test fails:
https://v8.mips.com/bbv8/builders/Sim%20-%20MIPS64%20-%20edge/builds/7475/steps/Mjsunit%20-%20ignition/logs/futex

**Comment by ilijapavlovic** [comment]
Related with following commit: https://chromium.googlesource.com/v8/v8/+/5e9ddf6ce4b698cb3112bd349ca5206cfada1437

**Comment by kilvadyb** [comment]
I think it is related to #294 issue.

**Comment by ilijapavlovic** [comment]
Yes. This is only subset of the problem described in #294. We suppose that the solution for both will be the same.

**Comment by ilijapavlovic** [comment]
The problem is solved with commit efadbfc458519848509136014e4b9e8435d379ea 
"MIPS: [Atomics] Remove Atomics code stubs; use TF ops."
