### ISSUE TITLE
Port new CL to MIPS: https://codereview.chromium.org/1892533004/

### ISSUE THREAD

**Issue by palfia** [v8mips/v8mips#298]

**Comment by kilvadyb** [comment]
Port uploaded: https://codereview.chromium.org/1896963002/

**Comment by kilvadyb** [comment]
Port done: https://codereview.chromium.org/1896963002/
Merged to original CL, landed.

**Comment by kilvadyb** [comment]
Some cctest like test-js-typed-lowering/Int32AddNarrowing failed on a board while it passed on simulators. The author of the original CL fixed the problem in https://codereview.chromium.org/1901423002/ -- 8960600 And the failures disappeared from the boards.

**Comment by kilvadyb** [comment]
Still some optimization in stack handling is possible, I work on a followup CL.

**Comment by kilvadyb** [comment]
Followup optimization CL: https://codereview.chromium.org/1903973003/

**Comment by kilvadyb** [comment]
PTAL, ping

**Comment by palfia** [comment]
LGTM'ed.

**Comment by kilvadyb** [comment]
https://codereview.chromium.org/1899423003/ landed.
