### ISSUE TITLE
runaway mjsunit/d8-worker-sharedarraybuffer

### ISSUE THREAD

**Issue by kwan0xfff** [v8mips/v8mips#301]
Several test runs have `mjsunit/d8-worker-sharedarraybuffer.js` running for an exceedingly long time until they are manually terminated.  This has happened both on physical boards and simulators.

Example tests include:
- cavoct3-board-1: [Target - MIPS64 - Debug - edge Build #1105](https://dmz-portal.mips.com/bbv8/builders/Target%20-%20MIPS64%20-%20Debug%20-%20edge/builds/1105)
- rhino-board-1: [Target - Debug - edge Build #1843](https://dmz-portal.mips.com/bbv8/builders/Target%20-%20Debug%20-%20edge/builds/1843)
- mips-sim-3: [Sim - Debug - edge - mipsr6 Build #2383](https://dmz-portal.mips.com/bbv8/builders/Sim%20-%20Debug%20-%20edge%20-%20mipsr6/builds/2383)
- mips-sim-10: [Sim - Debug - edge Build #10933](https://dmz-portal.mips.com/bbv8/builders/Sim%20-%20Debug%20-%20edge/builds/10933)
- mips-sim-9: [Sim - Debug - edge - mipsr6 Build #2382](https://dmz-portal.mips.com/bbv8/builders/Sim%20-%20Debug%20-%20edge%20-%20mipsr6/builds/2382)

On the last one, the offending process showed the following in 'ps':
`bbv8     16710 99.9  0.4 673668 18104 ?        Rl   04:28 173:32                          |   \_ /bbv8-slaves/cavoct3-board-1/build/slave/v8-linux-mips64el-debug-target-edge/build/v8/out/Debug/d8 --test --random-seed=1773649175 --stress-opt --always-opt --nohard-abort --nodead-code-elimination --nofold-constants --enable-slow-asserts --debug-code --verify-heap --harmony-sharedarraybuffer /bbv8-slaves/cavoct3-board-1/build/slave/v8-linux-mips64el-debug-target-edge/build/v8/test/mjsunit/mjsunit.js /bbv8-slaves/cavoct3-board-1/build/slave/v8-linux-mips64el-debug-target-edge/build/v8/test/mjsunit/d8-worker-sharedarraybuffer.js`

These particular tests keep the simulator or board occupied at load avg 1.00 (or 2.00 when 2 sims run on one server) until manually terminated.  That is, they cause the test queue to back up severely.

**Comment by mkaric** [comment]
There has been several changes related to atomics in the last few days which affect d8-worker-sharedarraybuffer test, after finally fixing atomics code it seems this problem is resolved now. There has been several test runs on all builders you listed and these were quite fast, sim builders are green now too. I see the problem only with Target - Debug - edge which completed only one test run quickly and currently is running for over 2 hours. This seems to be related to a different problem and I am looking into that in #300.

**Comment by kwan0xfff** [comment]
Today, I'm not seeing this particular problem come up. I'll downgrade the priority to pri2. If I don't see this again for another day, I'll close this.

**Comment by kwan0xfff** [comment]
Found "mjsunit/d8-worker-sharedarraybuffer" passed in https://dmz-portal.mips.com/bbv8/builders/Target%20-%20Debug%20-%20edge/builds/1848 in "Check" step.  Have not seen problem show up on other tests. (But those tests are not completing.) For now, will mark this as resolved.
