### ISSUE TITLE
Bughunting: mjsunit/harmony/futex times out in various tests

### ISSUE THREAD

**Issue by kwan0xfff** [v8mips/v8mips#309]
Various individual tests have timed out while running test/mjsunit/harmony/futex.js  In some cases, processes running this test were killed after accumulating 60 minutes of CPU time.

Below are some representative timeouts:

---

_Case 1_:
Test: mjsunit/harmony/futex
Flags: --stress-opt --always-opt
Command: out/Release/d8 --test --random-seed=-1 --stress-opt --always-opt --nohard-abort --nodead-code-elimination --nofold-constants --allow-natives-syntax --harmony-sharedarraybuffer test/mjsunit/mjsunit.js test/mjsunit/harmony/futex.js

Run #1
Exit code: -9
Result: TIMEOUT
Expected outcomes: PASS

Taken from:
https://v8.mips.com/bbv8/builders/Target%20-%20big%20-%20edge%20-%20no%20i18n/builds/7403/steps/Check/logs/futex
Was run on ER Pro-8 kernel v 4.1.20, big endian.

---

_Case 2:_
Test: mjsunit/harmony/futex
Flags: --stress-opt --always-opt
Command: out/Release/d8 --test --random-seed=298856 --stress-opt --always-opt --nohard-abort --nodead-code-elimination --nofold-constants --allow-natives-syntax --harmony-sharedarraybuffer test/mjsunit/mjsunit.js test/mjsunit/harmony/futex.js

Run #1
Exit code: -9
Result: TIMEOUT
Expected outcomes: PASS
Duration: 26:40:151

Taken from:
https://v8.mips.com/bbv8/builders/Target%20%281%29%20-%20edge%20-%20fpxx/builds/337/steps/Check/logs/futex
Was run on ER Pro-8 kernel v 4.1.20, little endian.

---
- Case 3:*
  Test: mjsunit/harmony/futex
  Flags: --turbo
  Command: out/Debug/d8 --test --random-seed=-1 --turbo --nohard-abort --nodead-code-elimination --nofold-constants --enable-slow-asserts --debug-code --verify-heap --allow-natives-syntax --harmony-sharedarraybuffer test/mjsunit/mjsunit.js test/mjsunit/harmony/futex.js

Run #1
Exit code: -9
Result: TIMEOUT
Expected outcomes: PASS

Taken from:
https://v8.mips.com/bbv8/builders/Target%20-%20Debug%20-%20edge/builds/1879/steps/Check/logs/futex
Was run on Rhino UTM-4 kernel v3.10.20, little endian.

**Comment by palfia** [comment]
Thanks for reporting, I hope porting the atomics store CL (https://codereview.chromium.org/1938213002) to MIPS will solve this issue.

**Comment by palfia** [comment]
Landed the MIPS port of the atomic store: https://codereview.chromium.org/1957463002/

**Comment by palfia** [comment]
Fixed by e11eb9a7d7fa6a1adccfc8c25c8655f0b106f966.
