### ISSUE TITLE
MIPS softfloat bug fixes

### ISSUE THREAD

**Issue by kisg** [v8mips/v8mips#31]
Soft float MIPS builds have test failures. This issue will act as a synchronization point for these failures and fixes.

**Comment by kilvadyb** [comment]
In progress: fixing bug: test/mjsunit/bit-not.js
Simplified js:
function testBitNot(x, name) {
  actual = ~(x - 0.01);
  print("actual: " + actual);
}

//testBitNot(0x7fffffff, "0x7fffffff");
testBitNot(0x80000000, "0x80000000");

Bad result comes up  in soft-float mode when testBitNot is called with 0x80000000 and only both of the calls are in the js file. A lonely testBitNot(0x80000000, "0x80000000"); succeeds.

**Comment by paul99** [comment]
Dusan, can you please post the current failing tests, and the areas that you are investigating, even if they are just hypothesis at this point.

**Comment by dusmil** [comment]
I am working on: mjsunit/mul-exhaustive-part9.

It fails as:
=== mjsunit/mul-exhaustive-part9 ===
/home/dusan/v8mips/check/v8m-rb/test/mjsunit/mjsunit.js:166: Failure: expected <-1125900980584448> found <-1125900980584448.2>
    throw new MjsUnitAssertionError(message);

It looks to me it is minor precision issue in code for double to integer conversion. Still, searching for spot where tiny error is made. It could be that rounding routines for soft-float code path have a bug for large numbers.

**Comment by dusmil** [comment]
Hi guys, I fixed my bug I was hunting, and the rest of them.

Interestingly, We had hidden bug in integer to double  conversion routine.

The patch will be submitted, and pushed to dm-dev branch.

**Comment by paul99** [comment]
Dusan, thanks for the fix. It is committed, I even got the the patch attribution right this time!

Please update the CL https://codereview.chromium.org/13455006/ with the commit info in the description, and close that CL and this issue.

**Comment by paul99** [comment]
This is completed. Closing.
