### ISSUE TITLE
Bughunting: Allocation folding test failures on MIPS64 debug

### ISSUE THREAD

**Issue by palfia** [v8mips/v8mips#313]
There are new test failures on MIPS64 Debug mode since: https://v8.mips.com/bbv8/builders/Sim%20-%20MIPS64%20-%20Debug%20-%20edge/builds/7637

The tests are failing with the following msg:

```
#
# Fatal error in ../src/crankshaft/mips64/lithium-codegen-mips64.cc, line 5287
# Check failed: !instr->hydrogen()->IsAllocationFolded().
#
```

Please investigate this problem.

**Comment by marijantic** [comment]
In https://codereview.chromium.org/1972553002 (above mentioned build), the failing debug check in line 5287 was added. Most of the actual changes were introduced by https://codereview.chromium.org/1899813003

**Comment by marijantic** [comment]
PTAL: https://codereview.chromium.org/1977833002/
Changes introduced to lithium-mips.cc were missing from lithium-mips64.cc.

**Comment by marijantic** [comment]
Fix landed as https://crrev.com/ced0f49763ef18e874902e3f33b81d75f5a3b2ae
