### ISSUE TITLE
Bughunting: mjsunit/wasm/embenchen/box2d failure on boards

### ISSUE THREAD

**Issue by kilvadyb** [v8mips/v8mips#321]

**Comment by kilvadyb** [comment]
Cannot reproduce compiling the same revision that the buildbot failure shows. I run the test on popcorn, ci-20 and er8 boards without any failure. I hope fix for #318 would help on this also.

**Comment by ibogosavljevic** [comment]
Fixed from #318 solved the issue:

https://v8.mips.com/bbv8/builders/Target%20-%20edge/builds/7361/steps/Check/logs/stdio

Closing...
