### ISSUE TITLE
Bughunting: Various word32 tests failing for MIPS64 target

### ISSUE THREAD

**Issue by marijantic** [v8mips/v8mips#322]
https://v8.mips.com/bbv8/builders/Target%20-%20MIPS64%20-%20edge/builds/5139
Failing tests: RunWord32OrP, RunWord32AndAndWord32ShrP, RunWord32XorP, RunWord32ShrP

**Comment by palfia** [comment]
This is a duplicate of #310.

**Comment by marijantic** [comment]
Missed that one when checking. Closing.
