### ISSUE TITLE
Bughunting: several test failures on big-endian.

### ISSUE THREAD

**Issue by palfia** [v8mips/v8mips#323]
Several tests are failing on big-endian since: https://codereview.chromium.org/1990923002

cctest/test-run-wasm-64/RunWasmCompiled_F64ReinterpretI64
cctest/test-run-wasm-64/RunWasmCompiled_LoadMemI64
cctest/test-run-wasm/RunWasmCompiled_MemF64_Mul
cctest/test-run-wasm-64/RunWasmCompiled_StoreMemI64_alignment
cctest/test-run-wasm/RunWasmInterpreted_Float64SubMinusZero
cctest/test-run-wasm/RunWasmInterpreted_Int32LoadInt16_zeroext
cctest/test-run-wasm-64/RunWasmInterpreted_LoadStoreI64_sx
cctest/test-run-wasm/RunWasmInterpreted_MixedGlobals

**Comment by palfia** [comment]
I think the only problem here is that the name of the tests were changed by this CL, but the *.status files weren't updated accordingly.

**Comment by john-yan** [comment]
I asked Orion about the matter and here is the reply:

> It looks like I missed adding a macro for a case in the test - so much for making the test easier to maintain :-)
>
>Can you try replacing:
>{B(Wide), B(LdaSmi), 0x18, 0xfc}, 4, 0, "      LdaSmi.Wide [-1000]"}
>
>with:
>
>{B(Wide), B(LdaSmi), U16(-1000)}, 4, 0, "      LdaSmi.Wide [-1000]"}
>
>Hopefully this helps. I'm offline from now until Thursday so can't land anything from here.
>
>Best regards
>
>Orion

Looks like we need to add the U16 macro.

**Comment by john-yan** [comment]
sorry, was commenting to another thread.

**Comment by palfia** [comment]
Fixed by #276
