### ISSUE TITLE
recipe for target mipsel.release failed

### ISSUE THREAD

**Issue by FuddingtonBear** [v8mips/v8mips#328]
Hi, I have a CI20 board and trying to install V8 for this.  I have followed the instructions here https://github.com/v8mips/v8mips/wiki/Building-v8-for-MIPS however I am getting an error as specified in the title.  Here is the console output:

`make[1]: Entering directory '/home/johnathon332/downloads/v8/out'
  CXX(target) /home/johnathon332/downloads/v8/out/mipsel.release/obj.target/v8_base/src/accessors.o
  CXX(target) /home/johnathon332/downloads/v8/out/mipsel.release/obj.target/v8_base/src/address-map.o
  CXX(target) /home/johnathon332/downloads/v8/out/mipsel.release/obj.target/v8_base/src/allocation.o
/home/johnathon332/downloads/mips-mti-linux-gnu/2015.01-7/bin/mips-mti-linux-gnu-g++: 1: /home/johnathon332/downloads/mips-mti-linux-gnu/2015.01-7/bin/mips-mti-linux-gnu-g++: Syntax error: "(" unexpected
src/v8_base.target.mipsel.release.mk:618: recipe for target '/home/johnathon332/downloads/v8/out/mipsel.release/obj.target/v8_base/src/accessors.o' failed
make[1]: *** [/home/johnathon332/downloads/v8/out/mipsel.release/obj.target/v8_base/src/accessors.o] Error 2
make[1]: *** Waiting for unfinished jobs....
  CXX(target) /home/johnathon332/downloads/v8/out/mipsel.release/obj.target/v8_base/src/allocation-site-scopes.o
/home/johnathon332/downloads/mips-mti-linux-gnu/2015.01-7/bin/mips-mti-linux-gnu-g++: 1: /home/johnathon332/downloads/mips-mti-linux-gnu/2015.01-7/bin/mips-mti-linux-gnu-g++: Syntax error: "(" unexpected
src/v8_base.target.mipsel.release.mk:618: recipe for target '/home/johnathon332/downloads/v8/out/mipsel.release/obj.target/v8_base/src/address-map.o' failed
make[1]: *** [/home/johnathon332/downloads/v8/out/mipsel.release/obj.target/v8_base/src/address-map.o] Error 2
/home/johnathon332/downloads/mips-mti-linux-gnu/2015.01-7/bin/mips-mti-linux-gnu-g++: 1: /home/johnathon332/downloads/mips-mti-linux-gnu/2015.01-7/bin/mips-mti-linux-gnu-g++: Syntax error: "(" unexpected
src/v8_base.target.mipsel.release.mk:618: recipe for target '/home/johnathon332/downloads/v8/out/mipsel.release/obj.target/v8_base/src/allocation.o' failed
make[1]: *** [/home/johnathon332/downloads/v8/out/mipsel.release/obj.target/v8_base/src/allocation.o] Error 2
/home/johnathon332/downloads/mips-mti-linux-gnu/2015.01-7/bin/mips-mti-linux-gnu-g++: 1: /home/johnathon332/downloads/mips-mti-linux-gnu/2015.01-7/bin/mips-mti-linux-gnu-g++: Syntax error: "(" unexpected
src/v8_base.target.mipsel.release.mk:618: recipe for target '/home/johnathon332/downloads/v8/out/mipsel.release/obj.target/v8_base/src/allocation-site-scopes.o' failed
make[1]: *** [/home/johnathon332/downloads/v8/out/mipsel.release/obj.target/v8_base/src/allocation-site-scopes.o] Error 2
make[1]: Leaving directory '/home/johnathon332/downloads/v8/out'
Makefile:318: recipe for target 'mipsel.release' failed
make: *** [mipsel.release] Error 2`

I followed through till after exporting the paths and then did the make on v8

Here is my cpu info if needed and it is little endian

system type             : JZ4780
machine                 : imgtec,ci20
processor               : 0
cpu model               : Ingenic JZRISC V4.15  FPU V0.0
BogoMIPS                : 1196.85
wait instruction        : yes
microsecond timers      : no
tlb_entries             : 32
extra interrupt vector  : yes
hardware watchpoint     : yes, count: 1, address/irw mask: [0x0fff]
isa                     : mips1 mips2 mips32r1 mips32r2
ASEs implemented        :
shadow register sets    : 1
kscratch registers      : 0
package                 : 0
core                    : 0
VCED exceptions         : not available
VCEI exceptions         : not available

processor               : 1
cpu model               : Ingenic JZRISC V4.15  FPU V0.0
BogoMIPS                : 1202.58
wait instruction        : yes
microsecond timers      : no
tlb_entries             : 32
extra interrupt vector  : yes
hardware watchpoint     : yes, count: 1, address/irw mask: [0x0fff]
isa                     : mips1 mips2 mips32r1 mips32r2
ASEs implemented        :
shadow register sets    : 1
kscratch registers      : 0
package                 : 0
core                    : 1
VCED exceptions         : not available
VCEI exceptions         : not available`

**Comment by ibogosavljevic** [comment]
Please paste all of the relevant information:
- values in relevant system variables
- version of GCC toolchain you are using
- command you used to start the compilation
- Git commit ID of v8 you are using

**Comment by ibogosavljevic** [comment]
Also, are you compiling on board or on your native X64/X86 system?

**Comment by ilijapavlovic** [comment]
If you are trying to build/compile V8 on MIPS board, than you have to do native compiling:

```
cd <PROJECT>/v8
make native -jN
or
make mipsel.release
or
make mipsel.debug
```

With this you will get automatically build in release mode for host architecture.
https://github.com/v8/v8/wiki/Building%20with%20Gyp

**Comment by ilijapavlovic** [comment]
Updated previous comment.

**Comment by ilijapavlovic** [comment]
In case native compiling you should not perform steps described for cross compiling.
