### ISSUE TITLE
Bughunting: async-debug test failures.

### ISSUE THREAD

**Issue by palfia** [v8mips/v8mips#329]
Several test failures since: https://build.chromium.org/p/client.v8.ports/builders/V8%20Linux%20-%20mipsel%20-%20sim/builds/684

**Comment by kilvadyb** [comment]
Fix CL uploaded: https://codereview.chromium.org/2045553002/

**Comment by kilvadyb** [comment]
Still mjsunit/harmony/async-debug-step-next fails sometimes on mips64el simulator.

**Comment by kilvadyb** [comment]
Followup/Fix CL for addressing a MIPS64 typo: https://codereview.chromium.org/2045923002/

**Comment by kilvadyb** [comment]
CL landed, 64-bit simulator Buildbot got green.
