### ISSUE TITLE
Bughunting: mjsunit/regress/regress-int32-truncation

### ISSUE THREAD

**Issue by mkaric** [v8mips/v8mips#336]
The test started failing on several builders:

https://v8.mips.com/bbv8/builders/Sim%20-%20MIPS64%20-%20edge/builds/8018
https://v8.mips.com/bbv8/builders/Sim%20-%20MIPS64%20-%20Debug%20-%20edge%20-%20mipsr6/builds/2943
https://v8.mips.com/bbv8/builders/Sim%20-%20MIPS64%20-%20Debug%20-%20edge/builds/7975
https://v8.mips.com/bbv8/builders/Sim%20-%20MIPS64%20-%20edge%20-%20mipsr6/builds/3013

**Comment by mkaric** [comment]
The test failure started with this CL:
https://codereview.chromium.org/2059403003

**Comment by mkaric** [comment]
Also fails on mips64 board and under qemu:
https://v8.mips.com/bbv8/builders/Target%20-%20MIPS64%20-%20edge/builds/5379
https://v8.mips.com/bbv8/builders/Target%20-%20MIPS64%20-%20edge%20-%20mipsr6%2Cunder%20qemu/builds/3129

**Comment by mkaric** [comment]
It seems the problem occurs when turbofan Mips64Dadd operation is generated with equal input and output registers (e.g. v0=v0+v0) and then have deoptimization when the generated code is executed. The input values are overwritten with the output value and then deoptimized code uses the wrong value as input.

**Comment by kilvadyb** [comment]
Bug appeared with commit 00889cc29c1489a8d00b4bfbef47b48efc45af5d -- https://codereview.chromium.org/2082993002

**Comment by mkaric** [comment]
Uploaded a fix CL:
https://codereview.chromium.org/2102063002
Can you PTAL and give me your opinion?

**Comment by mkaric** [comment]
The above fix CL fixes only MIPS64, the test starting failing also for MIPS32 since https://codereview.chromium.org/2082993002, as @kilvadyb commented.

**Comment by kilvadyb** [comment]
On MIPS64 the critical dadd is generated from
instruction-selector-mips64.cc:
VisitBinop()->EmitDeoptimize()->Emit()->…
The allocated virtual registers for operand nodes: output[0] == 4, input[0|1] == 5 so the ARM `add w0, w1, w1` seems to be logical and the MIPS `dadd v0, v0, v0` looks to be buggy. I continue to investigate virtual_register -> register mapping/translation.

backtrace:

```
    #0: 0x00000001004d84a8 d8`v8::internal::compiler::Instruction::Instruction(this=0x000000010304ff80, opcode=2768948, output_count=1, outputs=0x00007fff5fbfc0f0, input_count=13, inputs=0x000000010304f820, temp_count=0, temps=0x0000000000000000) + 472 at instruction.cc:289
    #1: 0x00000001004d863c d8`v8::internal::compiler::Instruction::Instruction(this=0x000000010304ff80, opcode=2768948, output_count=1, outputs=0x00007fff5fbfc0f0, input_count=13, inputs=0x000000010304f820, temp_count=0, temps=0x0000000000000000) + 92 at instruction.cc:277
    #2: 0x00000001004b4989 d8`v8::internal::compiler::Instruction::New(zone=0x0000000102805c80, opcode=2768948, output_count=1, outputs=0x00007fff5fbfc0f0, input_count=13, inputs=0x000000010304f820, temp_count=0, temps=0x0000000000000000) + 601 at instruction.h:827
  * #3: 0x00000001004b4073 d8`v8::internal::compiler::InstructionSelector::Emit(this=0x00007fff5fbfcea8, opcode=2768948, output_count=1, outputs=0x00007fff5fbfc0f0, input_count=13, inputs=0x000000010304f820, temp_count=0, temps=0x0000000000000000) + 115 at instruction-selector.cc:210
    #4: 0x00000001004c0943 d8`v8::internal::compiler::InstructionSelector::EmitDeoptimize(this=0x00007fff5fbfcea8, opcode=2768948, output_count=1, outputs=0x00007fff5fbfc0f0, input_count=2, inputs=0x00007fff5fbfc100, frame_state=0x0000000103012ee0) + 1379 at instruction-selector.cc:1805
    #5: 0x0000000100f84d16 d8`v8::internal::compiler::VisitBinop(selector=0x00007fff5fbfcea8, node=0x0000000103087858, opcode=671796, cont=0x00007fff5fbfc220) + 2550 at instruction-selector-mips64.cc:124
    #6: 0x0000000100f83a8e d8`v8::internal::compiler::(anonymous namespace)::VisitWordCompareZero(selector=0x00007fff5fbfcea8, user=0x0000000103087920, value=0x00000001030878a8, cont=0x00007fff5fbfc220) + 1102 at instruction-selector-mips64.cc:1729
    #7: 0x0000000100f83dd3 d8`v8::internal::compiler::InstructionSelector::VisitDeoptimizeIf(this=0x00007fff5fbfcea8, node=0x0000000103087920) + 99 at instruction-selector-mips64.cc:1769
    #8: 0x00000001004baf1e d8`v8::internal::compiler::InstructionSelector::VisitNode(this=0x00007fff5fbfcea8, node=0x0000000103087920) + 638 at instruction-selector.cc:902
```

**Comment by kilvadyb** [comment]
On mips64le the following register allocation happens:

```
----- Instruction sequence before register allocation -----
...
v4(R) = Mips64Dadd && deoptimize if overflow v5(R) v5(R) #0 v6(S) v7(-) v8(-) v9(-) v10(S) [immediate:2] [immediate:3] [immediate:4] v5(-) v5(-)
...
----- Instruction sequence after register allocation -----
...
[v0|R|w64] = Mips64Dadd && deoptimize if overflow [v0|R|w32] [v0|R|w32] #0 [stack:3|t] [stack:-3|t] [v1|R|t] [stack:-1|t] [stack:2|t] [immediate:2] [immediate:3] [immediate:4] [v0|R|w32] [v0|R|w32]
...
```

And the register allocation is committed by

```
PipelineImpl::AllocateRegisters() {
...
  Run<CommitAssignmentPhase>();
...
```

Both v4 and v5 virtual registers are translated to v0 register.

**Comment by mkaric** [comment]
Added a mips32 fix to the CL (https://codereview.chromium.org/2102063002), PTAL.

**Comment by mkaric** [comment]
Landed as https://crrev.com/99385e8e4bcef1f333ede61c936528bfc0c8ecfa. The test now passes on buildbots.

**Comment by kilvadyb** [comment]
```
PipelineImpl::AllocateRegisters(} {
...
  Run<AllocateGeneralRegistersPhase<LinearScanAllocator>>();
...
```

does the register allocation. On MIPS64:

```
#### (destination of dadd) v5: interval 5:0 start=130, end=134
Register v1 is free until pos 0 (1)
Assigning free reg v0 to live range 5:0

#### (source reg of dadd) v4: interval 4:0 start=134, end=137
Assigning free reg v0 to live range 4:0
```

v0 is allocated for virtual reg. 5 because v1 is allocated already. On ARM64 all the x0 and x1 regs are free at the same point.

**Comment by mkaric** [comment]
It seems I found the solution for this, I stumbled upon this CL:
https://codereview.chromium.org/2109153002
Implementing the same thing on mips fixed the failure. I checked the generated code and now another register is used to store the result of addition (a0 in this case). I didn't test mips64 but I expect it to fix the failure there as well.

**Comment by kilvadyb** [comment]
Looks promising. I guess that what I was looked for meny days :) Could you make a MIPS port of it? And revert your workaround?

**Comment by mkaric** [comment]
The same change fixes mips64 as well.

**Comment by mkaric** [comment]
Uploaded a fix CL:
https://codereview.chromium.org/2133503004/
PTAL

**Comment by mkaric** [comment]
Fix CL landed as https://crrev.com/91f63b2ee42307bb5566b60e2d6deb0bc7c795ce.

Previous fix is no longer needed, landed a revert CL (https://codereview.chromium.org/2129083003/).
