### ISSUE TITLE
Bughunting: cctest/test-gap-resolver/FuzzResolver

### ISSUE THREAD

**Issue by kilvadyb** [v8mips/v8mips#338]

**Comment by kilvadyb** [comment]
The problematic CL: fc59eb8a7a1eb45edd2d4ff7910e66fab3093030 -- https://codereview.chromium.org/2060273003

**Comment by ibogosavljevic** [comment]
Reported also on https://bugs.chromium.org/p/chromium/issues/detail?id=622619

**Comment by kilvadyb** [comment]
Proposal CL uploaded: https://codereview.chromium.org/2090993002/ and lgtm'ed.

**Comment by kilvadyb** [comment]
CL landed: https://codereview.chromium.org/2090993002/
