### ISSUE TITLE
Bughunting: Sim - edge: mjsunit/regress/regress-int32-truncation

### ISSUE THREAD

**Issue by ilijapavlovic** [v8mips/v8mips#339]
The test mjsunit/regress/regress-int32-truncation fails on simulator
TARGET_ARCH=mipsel
MODE=release
VARIANT=r2
Other details: https://v8.mips.com/bbv8/builders/Sim%20-%20edge/builds/11467/steps/Check/logs/regress-int32-truncat..

**Comment by palfia** [comment]
Duplicate of #336.
