### ISSUE TITLE
Port soft-float removal patch to MIPS on Google bleeding_edge

### ISSUE THREAD

**Issue by kisg** [v8mips/v8mips#34]
CL: https://codereview.chromium.org/13560007/
SVN commit id: r14159

Apart from the port, we have to make sure that we remove all MIPS-only soft-float code that is not found in the ARM commit.

The commit first should be submitted to our github as a separate branch, reviewed by Paul and Dusan, then submitted upstream.

**Comment by paul99** [comment]
Dusan, could please take the lead on getting this soft-float removal ported. There has been porting work each day, and likely to be more tomorrow, so Ákos has not been able to get to this yet.

**Comment by dusmil** [comment]
Soft-float removal commit is ported and pushed to dm-dev. Calling for a review.
The patch is successfully tested on simulator in both modes, release and debug.

**Comment by paul99** [comment]
Initial code review has been done on http://github.com/paul99/v8m-rb/commit/c201cb426037b97b7779e54e6e46b85cacb220ec

Dusan pushed an update to dm-dev-soft-removal and upstreamed to Reitveld:
https://codereview.chromium.org/14113011/.

I will do a 2nd review on reitveld today, and I would ask that Ákos or Gergely also review. Let's look to land this tomorrow, 16-April.

Dusan, what testing has been done on this on your side, on your revised CL?

**Comment by paul99** [comment]
This has landed as r 14275 on google bleeding edge. Closing.
