### ISSUE TITLE
Bughunting: intl/general/case-mapping.js failing on r6

### ISSUE THREAD

**Issue by marijantic** [v8mips/v8mips#358]
Fails since https://v8.mips.com/bbv8/builders/Sim%20-%20edge%20-%20mipsr6/builds/2812

**Comment by marijantic** [comment]
Also fails under qemu https://v8.mips.com/bbv8/builders/Target%20-%20edge%20-%20mipsr6%2Cunder%20qemu/builds/3335
Failed first time for https://v8.mips.com/bbv8/builders/Target%20-%20edge%20-%20mipsr6%2Cunder%20qemu/builds/3202

**Comment by marijantic** [comment]
CL that caused the problem: https://chromium.googlesource.com/v8/v8/+/6f920d7d59915e970a7d09bb6596605015c3bedd
This CL changes simplified operator reducer, and js typed lowering. The reducer behaves the same way on r2 and r6, but the test fails only on r6. Failure message indicates that the problem is probably just revealed by these changes, but not caused by them.

```
Fatal error in ../../src/mips/assembler-mips.cc, line 934
Check failed: trampoline_pos != kInvalidSlotPos.
```

**Comment by marijantic** [comment]
Cause of the problem is the BOVC instruction emitted in AddOvfBranch. BOVC and BNVC are the branching instructions not passing through Branch() macro, thus not being handled correctly if the trampoline is emitted.

**Comment by kilvadyb** [comment]
Theoretically buffer growing, trampoline pool and compact branch guarding are handled at assembler level not in MacroAssembler so emitting `bovc` (or whatever `b*c()` branch) without Branch() should not be a problem. I am going to check this issue. If you can reproduce it then a test-assembler case in cctest would be nice.

**Comment by kilvadyb** [comment]
Finally I managed to reproduce the failure. Trampoline entry is not created for a (far) label. The test is a regexp test and I have some uncertain memories about a problem with regexp. Regexp can emit a lot of branch ops and the `CheckTrampolinePool()` and trampoline generation is blocked (I guess it is blocked by trampoline_pool_blocked_nesting_).

**Comment by marijantic** [comment]
Branch macro will check both whether there is already a trampoline emitted and whether the label is bound, and depending on this either call BranchShort, or BranchLong. These macros will then issue the appropriate assm branching instructions, and let assembler level methods handle the rest. 

The problem occurs when the label is created and linked before the trampoline is emitted, but we attempt to bind after the trampoline emission. This issue is fixed by the introduced Bovc and Bnvc macros in macro assembler, that mimic the Branch macro used for other branching instructions.
I wrote a test that is causing the trampoline to be emitted, prior to binding AddBranchOvf label. Before the fix, it fails with the same error message as case-mapping.js (Check failed: trampoline_pos != kInvalidSlotPos.)

**Comment by marijantic** [comment]
PTAL: https://codereview.chromium.org/2225323002

**Comment by marijantic** [comment]
CL landed as https://crrev.com/93809055aa7d58585d73cfa9fbf18b82340db2a1
