### ISSUE TITLE
Bughunting: ConvertDToI test fails on BE boards

### ISSUE THREAD

**Issue by mkaric** [v8mips/v8mips#359]
The test fails for mips32 and mips64, only on BE boards:
cctest/test-code-stubs-mips/ConvertDToI
cctest/test-code-stubs-mips64/ConvertDToI

Log:
https://v8.mips.com/bbv8/builders/Target%20-%20big%20-%20Debug%20-%20edge%20-%20no%20i18n/builds/6176/steps/Check/logs/ConvertDToI
https://v8.mips.com/bbv8/builders/Target%20-%20MIPS64%20-%20big%20-%20Debug%20-%20edge%20-%20no%20i18n/builds/1178/steps/Check/logs/ConvertDToI

**Comment by ibogosavljevic** [comment]
Sent to review:
https://codereview.chromium.org/2157373002/

**Comment by ibogosavljevic** [comment]
Patch landed, but there are many failures on big-endian currently dealt in #361.

**Comment by ibogosavljevic** [comment]
Fixed https://v8.mips.com/bbv8/builders/Target%20-%20MIPS64%20-%20big%20-%20Debug%20-%20edge%20-%20no%20i18n/builds/1201

Closing issue
