### ISSUE TITLE
v8 doesn't compile under CLANG on MIPS32

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#365]
Currently there is a compilation failure on MIPS32 with CLANG:
https://v8.mips.com/bbv8/builders/Target%20-%20edge%20-%20clang%20-%20builder/builds/2930
https://v8.mips.com/bbv8/builders/Target%20-%20edge%20-%20clang%2Cmipsr1%20-%20builder
https://v8.mips.com/bbv8/builders/Target%20-%20Debug%20-%20edge%20-%20clang%20-%20builder

**Comment by ibogosavljevic** [comment]
The issue is related to sysroot. MIPS uses debian_wheezy_mips-sysroot sysroot, and the failure happens. If no sysroot is provided (which is default on MIPS64) we are not seeing any failure.

To fix, compile v8 with use_sysroot=0.

@MIPSbkirby Could you change the configuration of the CLANG builders not to use sysroot on MIPS32, like this:
`export GYP_DEFINES='clang=1 target_arch=mipsel v8_target_arch=mipsel use_sysroot=0'`

In the meantime, I will try to figure out what is the problem with the sysroot.

**Comment by MIPSbkirby** [comment]
I've added the `use_sysroot=0` GYP flag to the Clang compiler builders.  I tested one and its passing now.

**Comment by ibogosavljevic** [comment]
The reason why we are seeing failures when compiling with CLANG and sysroot is that wrong parameters are used for the compilation.

Since we have wheezy sysroot and gold linker as part of the third_pardy, this makes GCC toolchain unused. Here are the new parameters for the compilation. @MIPSbkirby:  They should be used with MIPS32R1EL and MIPS32R2EL. We don't use them with MIPS32R6 because this architecture is not binary compatible with debian wheezy libraries, so please have this compiled as it was until now (use_sysroot = 0)

export ARCH_VAR=r2 or export ARCH_VAR=r1
export ARCH=mipsel
export CLANG_BASE=/home/ivica/src/o_main/v8/third_party/llvm-build
export CLANG_BINDIR=$CLANG_BASE/Release+Asserts/bin
export CLANG_ARGS="--target=$ARCH-linux-gnu"
export CLANG=$CLANG_BINDIR/clang
export CLANGXX=$CLANG_BINDIR/clang++
export CC="$CLANG $CLANG_ARGS"
export CXX="$CLANGXX $CLANG_ARGS"
export CPP="$CLANG $CLANG_ARGS -E"
export LINK="$CLANGXX $CLANG_ARGS"
export CC_host="$CLANG"
export CXX_host="$CLANGXX"
export CPP_host="$CLANG -E"
export LINK_host="$CLANGXX"
export GYP_DEFINES="clang=1 target_arch=$ARCH v8_target_arch=$ARCH mips_arch_variant=$ARCH_VAR"

export LD_R_PATH="/home/ivica/src/o_main/v8/build/linux/debian_wheezy_mips-sysroot/lib/mipsel-linux-gnu:/home/ivica/src/o_main/v8/build/linux/debian_wheezy_mips-sysroot/usr/lib/mipsel-linux-gnu"
export LDSO_PATH="/home/ivica/src/o_main/v8/build/linux/debian_wheezy_mips-sysroot/lib/mipsel-linux-gnu/ld-2.13.so"

**Comment by ibogosavljevic** [comment]
Updated documentation with the newest info:
https://github.com/v8mips/v8mips/wiki/Cross-compile-V8-with-Clang-that-comes-with-V8

Closing issue.

**Comment by MIPSbkirby** [comment]
@ibogosavljevic It looks like the only change you made was you removed the `-stdlib=libstdc++` and `--gcc-toolchain=$TCBASE` flags from the `CLANG_ARGS` variable.  Is that correct?  If so, I'm still not able to get this compile. I've left off the `use_sysroot=0` GYP flag and both of those compiler arguments.  Then, when I build I see lots of errors like `fatal error: 'string' file not found`.  I get the same results with and without the `-stdlib=libstdc++` flag too.  Here is a bit of the compile output:

```
[3/1455] CXX obj/third_party/icu/source/i18n/icui18n.bocsu.o
FAILED: obj/third_party/icu/source/i18n/icui18n.bocsu.o 
/net/mipssw051/export/tmp/bkirby/v8-rebase/build/slave/fake_slave/build/v8/third_party/llvm-build/Release+Asserts/bin/clang++ --target=mipsel-mti-linux-gnu -st
dlib=libstdc++ -MMD -MF obj/third_party/icu/source/i18n/icui18n.bocsu.o.d -DU_USING_ICU_NAMESPACE=0 -DHAVE_DLOPEN=0 -DUCONFIG_ONLY_HTML_CONVERSION=1 -DU_CHARSE
T_IS_UTF8=1 -DU_STATIC_IMPLEMENTATION -DCR_CLANG_REVISION=274369-1 -DV8_TARGET_ARCH_MIPS -DCAN_USE_FPU_INSTRUCTIONS -D__mips_hard_float=1 -DU_I18N_IMPLEMENTATI
ON -DU_ENABLE_DYLOAD=0 -DU_NOEXCEPT= -D_MIPS_TARGET_HW -D_MIPS_ARCH_MIPS32R2 -DFPU_MODE_FP32 -I../../third_party/icu/source/common -I../../third_party/icu/sour
ce/i18n -Wno-unused-parameter -pthread -Wmissing-field-initializers -Wno-gnu-zero-variadic-macro-arguments -fvisibility=hidden -fcolor-diagnostics -Wno-undefin
ed-var-template -Wno-nonportable-include-path -Wno-deprecated-declarations -Wno-logical-op-parentheses -Wno-tautological-compare -Wno-parentheses -Wno-deprecat
ed-declarations -Wno-deprecated-register -Wno-deprecated-declarations -Wno-logical-op-parentheses -Wno-tautological-compare -Wno-switch --sysroot=/net/mipssw05
1/export/tmp/bkirby/v8-rebase/build/slave/fake_slave/build/v8/build/linux/debian_wheezy_mips-sysroot -integrated-as -EL -Wno-error=array-bounds -mhard-float -m
ips32r2 -mfp32 -m32 -fdata-sections -ffunction-sections  -O3 -fno-exceptions -std=gnu++11 -frtti  -c ../../third_party/icu/source/i18n/bocsu.cpp -o obj/third_p
arty/icu/source/i18n/icui18n.bocsu.o
In file included from ../../third_party/icu/source/i18n/bocsu.cpp:22:
In file included from ../../third_party/icu/source/common/unicode/bytestream.h:40:
../../third_party/icu/source/common/unicode/std_string.h:33:10: fatal error: 'string' file not found
#include <string>
         ^
1 error generated.
```

Did I miss another change you made?
