### ISSUE TITLE
Bughunting: mjsunit/regress/regress-599717 fails occasionally on MIPS64 BE

### ISSUE THREAD

**Issue by mkaric** [v8mips/v8mips#366]
The test fails occasionally on MIPS64 BE buildbot. Here are the builds where it failed:
https://v8.mips.com/bbv8/builders/Target%20-%20MIPS64%20-%20big%20-%20Debug%20-%20edge%20-%20no%20i18n/builds/1207
https://v8.mips.com/bbv8/builders/Target%20-%20MIPS64%20-%20big%20-%20Debug%20-%20edge%20-%20no%20i18n/builds/1205
https://v8.mips.com/bbv8/builders/Target%20-%20MIPS64%20-%20big%20-%20Debug%20-%20edge%20-%20no%20i18n/builds/1193
https://v8.mips.com/bbv8/builders/Target%20-%20MIPS64%20-%20big%20-%20Debug%20-%20edge%20-%20no%20i18n/builds/1188

**Comment by mkaric** [comment]
This test crashes when it runs out of memory, this is similar to issue #303. @MIPSbkirby Maybe the same solution will help here as well, can you add more swap space to this board?

**Comment by MIPSbkirby** [comment]
@kwan0xfff Can you add swap to this board?

**Comment by kwan0xfff** [comment]
This board (cavium-board-1) already has 2 GB of swap.  It's also been up for 191 days.  (Last mod of /etc/fstab was on Jan 20, 2016.)
Other board stats: has 2 GB of RAM.  Kernel version 4.1.4.
We could add more swap out of a file system on the same device (MMC card). Do we think that will help??

**Comment by ibogosavljevic** [comment]
@kwan0xfff The test fails because OOM Killer gets activated. You can check this if you type `dmesg` right after the test fails, it will appear in the system log.

**Comment by mkaric** [comment]
Last time I see this test failed is in build https://v8.mips.com/bbv8/builders/Target%20-%20MIPS64%20-%20big%20-%20Debug%20-%20edge%20-%20no%20i18n/builds/1246, this was more than 10 days ago. Since then several other tests started failing, this might be somehow related. Lets wait for these to be fixed and see if the failure appears again. If it does maybe we could try increasing swap space.

**Comment by mkaric** [comment]
Here are the links to the logs from the builds mentioned in the first post:
https://v8.mips.com/bbv8/builders/Target%20-%20MIPS64%20-%20big%20-%20Debug%20-%20edge/builds/1207/steps/Check%20%28flakes%29/logs/regress-599717
https://v8.mips.com/bbv8/builders/Target%20-%20MIPS64%20-%20big%20-%20Debug%20-%20edge/builds/1205/steps/Check%20%28flakes%29/logs/regress-599717
https://v8.mips.com/bbv8/builders/Target%20-%20MIPS64%20-%20big%20-%20Debug%20-%20edge/builds/1193/steps/Check%20%28flakes%29/logs/regress-599717
https://v8.mips.com/bbv8/builders/Target%20-%20MIPS64%20-%20big%20-%20Debug%20-%20edge/builds/1188/steps/Check%20%28flakes%29/logs/regress-599717

And here is a few more recent ones:
https://v8.mips.com/bbv8/builders/Target%20-%20MIPS64%20-%20big%20-%20Debug%20-%20edge/builds/1397/steps/Check%20%28flakes%29/logs/regress-599717
https://v8.mips.com/bbv8/builders/Target%20-%20MIPS64%20-%20big%20-%20Debug%20-%20edge/builds/1393/steps/Check%20%28flakes%29/logs/regress-599717
https://v8.mips.com/bbv8/builders/Target%20-%20MIPS64%20-%20big%20-%20Debug%20-%20edge/builds/1392/steps/Check%20%28flakes%29/logs/regress-599717
https://v8.mips.com/bbv8/builders/Target%20-%20MIPS64%20-%20big%20-%20Debug%20-%20edge/builds/1390/steps/Check%20%28flakes%29/logs/regress-599717

So the test still fails occasionally. It seems the test no longer crashes, but it still sometimes timeouts on the first run. Also interesting to note that in these last four logs, in the second run the execution times differ greatly: 0.4s, 2s, 44s and 13m23s.

**Comment by mkaric** [comment]
Also fails on mips64 little endian, and also with large variance in duration in the second, successful run:
https://v8.mips.com/bbv8/builders/Target%20-%20MIPS64%20-%20Debug%20-%20edge/builds/1451/steps/Check%20%28flakes%29/logs/regress-599717
https://v8.mips.com/bbv8/builders/Target%20-%20MIPS64%20-%20Debug%20-%20edge/builds/1450/steps/Check%20%28flakes%29/logs/regress-599717
https://v8.mips.com/bbv8/builders/Target%20-%20MIPS64%20-%20Debug%20-%20edge/builds/1448/steps/Check%20%28flakes%29/logs/regress-599717
https://v8.mips.com/bbv8/builders/Target%20-%20MIPS64%20-%20Debug%20-%20edge/builds/1443/steps/Check%20%28flakes%29/logs/regress-599717

However, in the first run the test crashes after running for a long time, while on big endian it timeouts.

**Comment by mkaric** [comment]
This flaky test has not failed in a very long time. I think it is safe to close this issue, if the problem comes up again we can open a new one.
