### ISSUE TITLE
Compilation failure on v8 using GCC 5

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#369]
v8 doesn't compile with GCC 5, investigate:
https://v8.mips.com/bbv8/builders/Target%20-%20big%20-%20edge%20-%20gcc5%20-%20builder/builds/124
https://v8.mips.com/bbv8/builders/Target%20-%20Debug%20-%20edge%20-%20gcc5%20-%20builder/builds/124
https://v8.mips.com/bbv8/builders/Target%20-%20MIPS64%20-%20big%20-%20Debug%20-%20edge%20-%20gcc5%20-%20builder/builds/124
https://v8.mips.com/bbv8/builders/Target%20-%20MIPS64%20-%20edge%20-%20gcc5%20-%20builder/builds/124

**Comment by ilijapavlovic** [comment]
"Target - big - edge - gcc5 - builder" is successful now: https://v8.mips.com/bbv8/builders/Target%20-%20big%20-%20edge%20-%20gcc5%20-%20builder/builds/125

**Comment by ilijapavlovic** [comment]
Only difference for "Target - big - edge - gcc5 - builder" build 125 (compared with 124) is successful execution the step 1: "running steps via annotated script".

**Comment by ilijapavlovic** [comment]
"Target - MIPS64 - edge - gcc5 - builder " is also successful since build 125: https://v8.mips.com/bbv8/builders/Target%20-%20MIPS64%20-%20edge%20-%20gcc5%20-%20builder/builds/125
Step 1  "running steps via annotated script" successfully executed in build 125.

**Comment by ilijapavlovic** [comment]
This is from log for "Target - Debug - edge - gcc5 - builder". (Variables `${TC_PATH}` and `${BUILD_PATH}` are here only because of log readability.)

```
TC_PATH=/mips/arch/overflow/codesourcery/mips-linux-gnu/lite/release/2015.11-32/Linux
BUILD_PATH=/bbv8-slaves/mips-sim-13/build/slave/v8-linux-mipsel-debug-target-edge-gcc5-builder/build
```

Execution of the following command makes problems:

```
${TC_PATH}/bin/mips-linux-gnu-g++ -B/bbv8-slaves/mips-sim-13/build/slave/v8-linux-mipsel-debug-target-edge-gcc5-builder/build/v8/third_party/binutils/Linux_x64/Release/bin -pthread -B/bbv8-slaves/mips-sim-13/build/slave/v8-linux-mipsel-debug-target-edge-gcc5-builder/build/v8/third_party/binutils/Linux_x64/Release/bin -Wl,--dynamic-linker=${TC_PATH}/mips-linux-gnu/libc/el/lib/ld.so.1 -Wl,--rpath=${TC_PATH}/mips-linux-gnu/libc/el/lib:${TC_PATH}/mips-linux-gnu/libc/el/usr/lib -EL -mhard-float -mips32r2 -o inspector_protocol_parser_test -Wl,--start-group obj/third_party/WebKit/Source/platform/inspector_protocol/inspector_protocol_parser_test.ParserTest.o obj/test/inspector_protocol_parser_test/inspector_protocol_parser_test.RunTests.o obj/src/inspector/libinspector_protocol.a obj/testing/libgmock.a obj/testing/libgtest.a -Wl,--end-group  
```

The command finishes with error messages `could not load plugin library: ... wrong ELF class: ELFCLASS32`.

```
${BUILD_PATH}/v8/third_party/binutils/Linux_x64/Release/bin/ld: 
error: ${TC_PATH}/bin/../libexec/gcc/mips-linux-gnu/5.2.0/liblto_plugin.so: 
could not load plugin library: ${TC_PATH}/bin/../libexec/gcc/mips-linux-gnu/5.2.0/liblto_plugin.so: 
wrong ELF class: ELFCLASS32

collect2: error: ld returned 1 exit status
```

Usually, this error message appears in cases when 64-bit ELF class is needed.

For "Target - MIPS64 - big - Debug - edge - gcc5 - builder" there is very similar error message:

```
${TC_PATH}/bin/../lib/gcc/mips-linux-gnu/5.2.0/../../../../mips-linux-gnu/bin/ld: 
BFD (Sourcery CodeBench Lite 2015.11-32) 2.25.51 internal error, aborting at 
/scratch/cmoore/mips-linux-gnu-lite-2015.11-32/obj/binutils-src-2015.11-32-mips-linux-gnu-i686-pc-linux-gnu/bfd/merge.c:909 in _bfd_merged_section_offset

${TC_PATH}/bin/../lib/gcc/mips-linux-gnu/5.2.0/../../../../mips-linux-gnu/bin/ld: Please report this bug.

collect2: error: ld returned 1 exit status
```

According these error messages, possible cause of the problem is in internal error of the toolchain.

**Comment by ilijapavlovic** [comment]
Both error messages for Debug build targets are reproduced locally.
Steps for reproducing error messages:

1) Common part for all build targets:

```
TC_BASE=${PROJECT}/toolchains/CodeBench/mips-2015.11
TC_BASE_REMOTE=${REMOTE_DIR}/toolchains/CodeBench/mips-2015.11
PREFIX=${TC_BASE}/bin/mips-linux-gnu-

export CC=${PREFIX}gcc-5.2.0
export CXX=${PREFIX}g++
export AR=${PREFIX}ar
export RANLIB=${PREFIX}ranlib
export LINK=$CXX

export GYP_CROSSCOMPILE=1
export GYP_GENERATORS=ninja
```

2) Target specific parts:
- Target - big - edge - gcc5 - builder

```
export LD_R_PATH="${TC_BASE_REMOTE}/mips-linux-gnu/libc/lib:${TC_BASE_REMOTE}/mips-linux-gnu/libc/usr/lib"
export LDSO_PATH="${TC_BASE_REMOTE}/mips-linux-gnu/libc/lib/ld.so.1"
export GYP_DEFINES="target_arch=mips v8_target_arch=mips v8_use_snapshot=false"
```
- Target - MIPS64 - edge - gcc5 - builder

```
export LD_R_PATH="${TC_BASE_REMOTE}/mips-linux-gnu/libc/el/lib64:${TC_BASE_REMOTE}/mips-linux-gnu/libc/el/usr/lib64"
export LDSO_PATH="${TC_BASE_REMOTE}/mips-linux-gnu/libc/el/lib64/ld.so.1"
export GYP_DEFINES="target_arch=mips64el v8_target_arch=mips64el"
```
- Target - Debug - edge - gcc5 - builder

```
export LD_R_PATH="${TC_BASE_REMOTE}/mips-linux-gnu/libc/el/lib:${TC_BASE_REMOTE}/mips-linux-gnu/libc/el/usr/lib"
export LDSO_PATH="${TC_BASE_REMOTE}/mips-linux-gnu/libc/el/lib/ld.so.1"
export GYP_DEFINES="target_arch=mipsel v8_enable_slow_dchecks=1 v8_optimized_debug=1 v8_target_arch=mipsel"
```
- Target - MIPS64 - big - Debug - edge - gcc5 - builder

```
export LD_R_PATH="${TC_BASE_REMOTE}/mips-linux-gnu/libc/lib64:${TC_BASE_REMOTE}/mips-linux-gnu/libc/usr/lib64"
export LDSO_PATH="${TC_BASE_REMOTE}/mips-linux-gnu/libc/lib64/ld.so.1"
export GYP_DEFINES="target_arch=mips64 v8_enable_slow_dchecks=1 v8_optimized_debug=1 v8_target_arch=mips64 v8_use_snapshot=false"
```

3) Steps for build

```
cd ${PROJECT}/v8
gypfiles/gyp_v8
${PROJECT}/depot_tools/ninja -v -w dupbuild=err -C ./out/<Release|Debug>
```

For Debug build targets will be generated identical error messages as on buildbots.

**Comment by ilijapavlovic** [comment]
mipsel.r2.debug was possible to compile if GYP flag `linux_use_bundled_gold` is set on `0`:

```
export GYP_DEFINES="target_arch=mipsel v8_enable_slow_dchecks=1 v8_optimized_debug=1 v8_target_arch=mipsel linux_use_bundled_gold=0"
```

In `v8/gypfiles/standalone.gypi` is following:

```
        # linux_use_bundled_gold: whether to use the gold linker binary checked
        # into third_party/binutils.  Force this off via GYP_DEFINES when you
        # are using a custom toolchain and need to control -B in ldflags.
        # Do not use 32-bit gold on 32-bit hosts as it runs out address space
        # for component=static_library builds.
```

**Comment by ilijapavlovic** [comment]
During building mips64.r2.debug, linker `ld`reports an error as internal, but if the command is executed separately, error message is `out of memory`:

```
cd ./out/Debug

<TC_PATH>/mips-2015.11/bin/mips-linux-gnu-g++ -pthread -Wl,--dynamic-linker=<REMOTE_TC_PATH>/mips-2015.11/mips-linux-gnu/libc/lib64/ld.so.1, -Wl,--rpath=<REMOTE_TC_PATH>/mips-2015.11/mips-linux-gnu/libc/lib64:<REMOTE_TC_PATH>/mips-2015.11/mips-linux-gnu/libc/usr/lib64 -EB -mhard-float -mips64r2 -mabi=64 -Wl,--dynamic-linker=<REMOTE_TC_PATH>/mips-2015.11/mips-linux-gnu/libc/lib64/ld.so.1, -Wl,--rpath=<REMOTE_TC_PATH>/mips-2015.11/mips-linux-gnu/libc/lib64:<REMOTE_TC_PATH>/mips-2015.11/mips-linux-gnu/libc/usr/lib64 -EB -mhard-float -mips64r2 -mabi=64 -o cctest -Wl,--start-group ... -Wl,--end-group  -ldl -lrt
```

Command output:

```
<TC_PATH>/mips-2015.11/bin/../lib/gcc/mips-linux-gnu/5.2.0/../../../../mips-linux-gnu/bin/ld: 
out of memory allocating 262084 bytes after a total of 472076288 bytes
collect2: error: ld returned 1 exit status
```

According documentation for linker `ld`, it can run out of memory space while linking a large executable. For preventing such behaviour for linker, the option `-no-keep-memory` should be used.

The patch:

```
index 95eb1d9..16e8158 100644
--- a/gypfiles/toolchain.gypi
+++ b/gypfiles/toolchain.gypi
@@ -374,7 +374,7 @@
                 },
                 'conditions': [
                   ['ldso_path!=""', {
-                    'ldflags': ['-Wl,--dynamic-linker=<(ldso_path)'],
+                    'ldflags': ['-Wl,--dynamic-linker=<(ldso_path),-no-keep-memory'],
                   }],
                   ['ld_r_path!=""', {
                     'ldflags': ['-Wl,--rpath=<(ld_r_path)'],
```

With this patch, build for mips64.r2.debug will succeed.

**Comment by ilijapavlovic** [comment]
Additional comparing is done between builds for mips64.r2.debug and mips64el.r2.debug. For mips64el.r2.debug the build finishes with error message `Memory exhausted`:

```
<TC_PATH>/mips-2015.11/bin/../lib/gcc/mips-linux-gnu/5.2.0/../../../../mips-linux-gnu/bin/ld: 
final link failed: Memory exhausted
collect2: error: ld returned 1 exit status
```

For successful build, the same patch as for mips64.r2.debug should be applied.

**Summary**
For successful build with GCC 5.2.0 following should be done:
- For mipsel.r2.debug in `GYP_DEFINES` must be defined `linux_use_bundled_gold=0`.
- For mips64.r2.debug and mips64el.r2.debug must be applied the patch from previous comment.

**Comment by ibogosavljevic** [comment]
Related to failure when linking v8 for MIPS32R2 and the error we see

```
/home/ivica/src/o_main2/v8/third_party/binutils/Linux_x64/Release/bin/ld: error: /home/ivica/tools/mips-2016.05/bin/../libexec/gcc/mips-linux-gnu/5.3.0/liblto_plugin.so: could not load plugin library: /home/ivica/tools/mips-2016.05/bin/../libexec/gcc/mips-linux-gnu/5.3.0/liblto_plugin.so: wrong ELF class: ELFCLASS32
```

The reason for this error is that gold linker itself is x64, whereas `Sourcery CodeBench Lite` toolchain exists in 32bit version only.
Bottom line, if you want to link v8 with gold using `Sourcery CodeBench Lite` toolchain, you will need either to have 32bit Linux or you need to overwrite gold linker with the 32bit version of gold.

You can download the gold linker using:
`download_from_google_storage --no_resume --no_auth --bucket chromium-binutils -s /home/ivica/src/merging/01/v8/third_party/binutils/Linux_ia32/binutils.tar.bz2.sha1`

**Comment by ibogosavljevic** [comment]
Nothing to be done here, closing issue...
