### ISSUE TITLE
Fix 3.17 test failure on hw

### ISSUE THREAD

**Issue by palfia** [v8mips/v8mips#37]
The following test fails on the 3.17 branch on the sigma8654:

v8tests.--stress-opt_--always-opt_--nobreak-on-abort_--nodead-code-elimination_--nofold-constants_test/mjsunit/mjsunit.js_test/mjsunit/stack-traces-overflow.js

Stacktrace

stdout:
============ Stress 1/5 ============
/data/jenkins/slave-sigma-8654/workspace/v8-3.17-mips24k-release/TESTMODE/release/TESTTYPE/mjsunit/slave/v8-mips24k/test/mjsunit/mjsunit.js:166: Failure: expected <1> found <20968>
    throw new MjsUnitAssertionError(message);
          ^
undefined

**Comment by dusmil** [comment]
This is fixed in r13900. We missed to merge this one.

**Comment by palfia** [comment]
I've created a merge CL to fix this bug: https://codereview.chromium.org/14161005/

**Comment by palfia** [comment]
Landed as r14317.

Closing issue.
