### ISSUE TITLE
Porting: InstructionSelector::VisitFloat32Add, InstructionSelector::VisitFloat64Add, InstructionSelector::VisitFloat32Sub and InstructionSelector::VisitFloat64Sub

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#379]
Port InstructionSelector::VisitFloat32Add, InstructionSelector::VisitFloat64Add, InstructionSelector::VisitFloat32Sub and InstructionSelector::VisitFloat64Sub from ARM to use MADD and MSUB instructions in case of Multiplication with Addition/Substraction.

**Comment by ilijapavlovic** [comment]
As precondition for the porting, it is necessary to implement following MIPS32/64 instructions:
- MADD.S
- MSUB.fmt
- MADDF.fmt
- MSUBF.fmt

**Comment by kilvadyb** [comment]
Might be related to an old issue from Alen: #249

**Comment by kilvadyb** [comment]
I uploaded a rebased port of Alan's CL: https://codereview.chromium.org/2297173002 disasm is missing and madd.fmt's precision also must be checked and find an r6 implementation. Also the r1 an Longsoon support. are opened.

**Comment by ilijapavlovic** [comment]
Following instructions and their results are compared for MIPS32 (r2 board and r6 FPGA board):
- MADD.S (r2) with MADDF.S (r6)
- MSUB.S (r2) with MSUBF.S (r6)
- MADD.D (r2) with MADDF.D (r6)
- MSUB.D (r2) with MSUBF.D (r6)

As input data is used following set of numbers:

```
    // fr, fs, ft
    {11.11, 22.22, 33.33},
    {11.11, 22.22, -33.33},
    {11.11, -22.22, 33.33},
    {11.11, -22.22, -33.33},
    {-11.11, 22.22, 33.33},
    {-11.11, 22.22, -33.33},
    {-11.11, -22.22, 33.33},
    {-11.11, -22.22, -33.33}
```

MADD.S vs. MADDF.S
- There are differences in received results.

```
MADD_S=751.702576   MADDF_S=751.702637   // ***
MADD_S=-729.482605  MADDF_S=-729.482605
MADD_S=-729.482605  MADDF_S=-729.482605
MADD_S=751.702576   MADDF_S=751.702637   // ***
MADD_S=729.482605   MADDF_S=729.482605
MADD_S=-751.702576  MADDF_S=-751.702637   // ***
MADD_S=-751.702576  MADDF_S=-751.702637   // ***
MADD_S=729.482605   MADDF_S=729.482605
```

MSUB.S vs. MSUBF.S
- There are differences in received results.
- Note that MSUB.S = - MSUBF.S. Further analysis takes this fact in results consideration.

```
MSUB_S=729.482605   MSUBF_S=-729.482605 
MSUB_S=-751.702576  MSUBF_S=751.702637 // ***
MSUB_S=-751.702576  MSUBF_S=751.702637 // ***
MSUB_S=729.482605   MSUBF_S=-729.482605 
MSUB_S=751.702576   MSUBF_S=-751.702637 // ***
MSUB_S=-729.482605  MSUBF_S=729.482605 
MSUB_S=-729.482605  MSUBF_S=729.482605 
MSUB_S=751.702576   MSUBF_S=-751.702637 // ***
```

MADD.D vs. MADDF.D
- Recevied results are the same.

```
MADD_D=751.702600   MADDF_D=751.702600 
MADD_D=-729.482600  MADDF_D=-729.482600 
MADD_D=-729.482600  MADDF_D=-729.482600 
MADD_D=751.702600   MADDF_D=751.702600 
MADD_D=729.482600   MADDF_D=729.482600 
MADD_D=-751.702600  MADDF_D=-751.702600 
MADD_D=-751.702600  MADDF_D=-751.702600 
MADD_D=729.482600   MADDF_D=729.482600 
```

MSUB.D vs. MSUBF.D
- The results are the same (MSUB.D = -MSUBF.D)

```
MSUB_D=729.482600   MSUBF_D=-729.482600 
MSUB_D=-751.702600  MSUBF_D=751.702600 
MSUB_D=-751.702600  MSUBF_D=751.702600 
MSUB_D=729.482600   MSUBF_D=-729.482600 
MSUB_D=751.702600   MSUBF_D=-751.702600 
MSUB_D=-729.482600  MSUBF_D=729.482600 
MSUB_D=-729.482600  MSUBF_D=729.482600 
MSUB_D=751.702600   MSUBF_D=-751.702600 
```

**Comment by ilijapavlovic** [comment]
Several test cases are done where are used `sqrtf(2.0), sqrtf(3.0), sqrtf(5.0)` as input data for single formats and `sqrt(2.0), sqrt(3.0), sqrt(5.0)` as input data for double formats.
Results:
- There is no difference between results single and double formats.
- There is no difference between results r2 and r6 instructions.

In previous comment is shown that different results can be calculated if used numbers are with small number of digits after decimal point (different representation decimal numbers and rounding).

**Comment by ilijapavlovic** [comment]
The 1st CL with implementation MADD.S, MSUB, MADDF and MSUBF:
https://codereview.chromium.org/2313623002/

**Comment by ilijapavlovic** [comment]
The 1st CL landed as https://crrev.com/65fd5e1165104e387edf7348661c5f43ac954a52

**Comment by ilijapavlovic** [comment]
The 2nd CL uploaded and ready for review: https://codereview.chromium.org/2341303002/

**Comment by ilijapavlovic** [comment]
The 2nd CL landed: https://crrev.com/502b9aa71b1b28578579083f11f8bc67e4cd3430
This CL contains implementation for porting.
