### ISSUE TITLE
Test failure on hw: mjsunit/regress/regress-crbug-160010.js

### ISSUE THREAD

**Issue by palfia** [v8mips/v8mips#38]
The following test always fails on hw with out of memory error:

v8tests.--nobreak-on-abort_--nodead-code-elimination_--nofold-constants_--allow-natives-syntax_test/mjsunit/mjsunit.js_test/mjsunit/regress/regress-crbug-160010.js

Stacktrace

stderr:
#
# Fatal error in CALL_AND_RETRY_2
# Allocation failed - process out of memory
#

**Comment by dusmil** [comment]
This test fails due to a insufficient memory on system. it uses more than 512mb  On mips HW with enough RAM memory or enabled swap memory it passes.  I confirm this.

**Comment by kisg** [comment]
Fixed with the addition of swap, and moving to boards with more available memory.
