### ISSUE TITLE
Big endian builds failing to run gclient runhooks

### ISSUE THREAD

**Issue by MIPSbkirby** [v8mips/v8mips#382]
As of commit fcc8399d, `gclient runhooks` isn't running for big endian builds.  It fails with the message:

```
Error running GYP
Error: Command '/usr/bin/python v8/gypfiles/gyp_v8' returned non-zero exit status 1 in /bbv8-slaves/mips-sim-13/build/slave/v8-linux-mips-target-edge-builder/build
step returned non-zero exit code: 2
```

It's failing for both Codescape GCC and Clang builders:
https://v8.mips.com/bbv8/builders/Target%20-%20big%20-%20edge%20-%20builder/builds/10527
https://v8.mips.com/bbv8/builders/Target%20-%20big%20-%20edge%20-%20clang%20-%20builder/builds/3272

**Comment by palfia** [comment]
Uploaded and landed a fix: https://codereview.chromium.org/2296473002/

Waiting for the bots to verify the fix.

**Comment by MIPSbkirby** [comment]
Our bots are now working again after this fix landed.  Closing the bug.
