### ISSUE TITLE
Bughunting: mjsunit/generated-transition-stub and mjsunit/regress/regress-542823 failures.

### ISSUE THREAD

**Issue by kilvadyb** [v8mips/v8mips#387]
Both of the tests fail with

```
#
# Fatal error in ../../src/runtime/runtime-internal.cc, line 372
# Check failed: size <= Page::kMaxRegularHeapObjectSize.
#
```

Since https://dmz-portal.mips.com/bbv8/builders/Sim%20-%20edge/builds/12232
on 32-bit, regress-542823 fails on 64-bit simulator also.

**Comment by kilvadyb** [comment]
bad since d27f7f7 -- https://codereview.chromium.org/2301883002

**Comment by kilvadyb** [comment]
bad since 3b8ad45 - https://codereview.chromium.org/2289683002

**Comment by kilvadyb** [comment]
We are out of the limit:
Runtime_AllocateInTargetSpace is called from generated code with size to allocate: `630912` while the limit is: `kMaxRegularHeapObjectSize = 512 * KB - Page::kHeaderSize;` and I don't think the google guys should rise the limit as the comment of the constant says:

```
  // Maximum object size that gets allocated into regular pages. Objects larger
  // than that size are allocated in large object space and are never moved in
  // memory. This also applies to new space allocation, since objects are never
  // migrated from new space to large object space. Takes double alignment into
  // account.
  // TODO(hpayer): This limit should be way smaller but we currently have
  // short living objects >256K.
```

**Comment by kilvadyb** [comment]
The 'too big' allocation happens calling the code generated in `LCodeGen::DoDeferredAllocate()` (from snapshot code if it is turned on).

**Comment by kilvadyb** [comment]
`kMaxRegularHeapObjectSize` was moved to globals.h and also a static_assert added for it: `kMaxRegularHeapObjectSize <= MemoryChunk::kAllocatableMemory`
`MemoryChunk::kAllocatableMemory` is computed from kPageSize. I try to figure out why the object size is OK on arm and bigger on MIPS.

**Comment by palfia** [comment]
Uploaded & landed the fix CL: https://codereview.chromium.org/2386673002/
