### ISSUE TITLE
Test failure on hw: mjsunit/debug-evaluate-locals-optimized-double.js

### ISSUE THREAD

**Issue by palfia** [v8mips/v8mips#39]
The following test always crashes on hw:

v8tests.--nobreak-on-abort_--nodead-code-elimination_--nofold-constants_--expose-debug-as_debug_--expose-gc_--allow-natives-syntax_--inline-construct_test/mjsunit/mjsunit.js_test/mjsunit/debug-evaluate-locals-optimized-double.js

Stacktrace

--- CRASHED ---

**Comment by kisg** [comment]
This is no longer relevant, was fixed in r14828
