### ISSUE TITLE
Bughunting: test/mjsunit/harmony/generators.js failure 

### ISSUE THREAD

**Issue by marijantic** [v8mips/v8mips#391]
https://v8.mips.com/bbv8/builders/Sim%20-%20edge/builds/12381/steps/Mjsunit%20-%20ignition/logs/generators

**Comment by marijantic** [comment]
Problem with out-of-line code generation, first occurred after https://codereview.chromium.org/2320473003/ 
The label that is causing the issue is unused when bind_to() is called, and is generated when assembling kArchStoreWithWriteBarrier

**Comment by marijantic** [comment]
Bug not appearing after https://chromium.googlesource.com/v8/v8/+/27fe988b85e9b0b77eb5c376d4bdd1350dfc3e17

**Comment by simicicd** [comment]
Patch landed, closing the issue: https://codereview.chromium.org/2530143002/
