### ISSUE TITLE
Bughunting: mjsunit/wasm/start-function

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#402]
https://v8.mips.com/bbv8/builders/Sim%20-%20Debug%20-%20edge/builds/12541/steps/Mjsunit%20-%20ignition/logs/start-function

**Comment by simicicd** [comment]
Start function test fails in heap verification check, only in debug mode. HeapVerify() function requires address in return register v0, but WASM start function should not return any value.

After some time spent in investigation, we came with conclusion that this is not only MIPS related problem. Small change which produce the same error on ARM architecture is created, and bug is reported to V8 team (https://bugs.chromium.org/p/v8/issues/detail?id=5599)

**Comment by simicicd** [comment]
Issue is fixed with this CL: https://codereview.chromium.org/2483193002

**Comment by ibogosavljevic** [comment]
Fixed on buildbots: https://v8.mips.com/bbv8/builders/Sim%20-%20Debug%20-%20edge/builds/12797

Issue closed!
