### ISSUE TITLE
Bughunting: cctest/test-scanner-streams/CharacterStreams on mipsel

### ISSUE THREAD

**Issue by mkaric** [v8mips/v8mips#406]
This test is the only remaining failure after the fix in #396. It also fails with bus error. 

Log:
https://v8.mips.com/bbv8/builders/Target%20-%20edge/builds/8355/steps/Check/logs/CharacterStreams

**Comment by ibogosavljevic** [comment]
Uploaded fix: https://codereview.chromium.org/2415093002/

**Comment by ibogosavljevic** [comment]
Fixed: https://v8.mips.com/bbv8/builders/Target%20-%20edge%20-%20mipsr1/builds/8576

Closing
