### ISSUE TITLE
Push multitest.sh to github

### ISSUE THREAD

**Issue by palfia** [v8mips/v8mips#41]

**Comment by paul99** [comment]
I don't understand this. Isn't this file particular to Jenkins builder? (basing my comment off of the mention in issue 40)

Why would we need this in our github repo (assuming you meant v8m-rb).

Or does this have some other use than Jenkins?

**Comment by kisg** [comment]
I planned to push all our test scripts to a github repo, but separate from v8m-rb. We don't have to put it under your account, if you don't want, just wanted to keep track of this track. Internally we already use a git repo to store this tool, so I just thought it would make sense to make it public.

**Comment by paul99** [comment]
Gergely, I have no trouble at all putting another repo in my account. If you'd like it there, please suggest a repo name, and I will set it up for you. I can certainly see wanting to version control the files, makes perfect sense.

As I said above, I did not think it belonged in v8m-rb, that's all.

**Comment by kisg** [comment]
This is no longer relevant.
