### ISSUE TITLE
Infrastructure: Testing MIPS32R6 and MIPS64R6 compiled wtih CLANG

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#412]
We need to introduce the testing of MIPS32R6 and MIPS64R6 compiled using CLANG. 
- Tests should be executed using qemu-user upstream (same configuration as other qemu testing environemnts)
- We need to test both Optdebug and Release configurations
- It is ok if the tests are executed on a daily basis if we have resource issues, but preferably we would like to execute them after every commit

Assigning to @MIPSbkirby

**Comment by MIPSbkirby** [comment]
Added eight builders to build with clang and test MIPSr6.  The clang compiler builders are in the "Clang Builders" category and the testers are in the "Clang Targets" category.  They run at the lowest priority.  So, they'll only run if there's no other jobs running on the x86 mips-sim slaves.
