### ISSUE TITLE
Target - edge - shared library builder not linking unittests against libicui18n.so correctly

### ISSUE THREAD

**Issue by MIPSbkirby** [v8mips/v8mips#415]
The builder fails to compile with errors like the following:

```
/bbv8-slaves/cavoct3-board-1/build/slave/v8-linux-mipsel-target-edge-shared-library/build/v8/out/Release/unittests: error while loading shared libraries: libicui18n.so: cannot open shared object file: No such file or directory
```

After looking at what is being built, it looks like the `unittests` isn't being linked to the correct `libicui18n.so` and `libicuuc.so` libraries which are part of the ICU package.  Running `ldd` against the `d8` binary shows it linking against the correct `libicui18n.so` and `libicuuc.so` libraries:

```
$ ldd slave/fake_slave/build/v8/out/Release/d8 | egrep 'libicuuc.so|libicui18n.so'
        libicui18n.so => /net/mipssw051/export/tmp/bkirby/v8-shared-library-failure/src/build/slave/fake_slave/build/v8/out/Release/lib/libicui18n.so (0x77b17000)
        libicuuc.so => /net/mipssw051/export/tmp/bkirby/v8-shared-library-failure/src/build/slave/fake_slave/build/v8/out/Release/lib/libicuuc.so (0x77989000)
```

Compared to running `ldd` against the `unittests` binary, it tries to link against the version of `libicui18n.so` and `libicuuc.so` that is on the board:

```
$ ldd slave/fake_slave/build/v8/out/Release/unittests  | egrep 'libicuuc.so|libicui18n.so'
        libicui18n.so => /usr/lib/mipsel-linux-gnu/libicui18n.so (0x75cc4000)
        libicuuc.so => /usr/lib/mipsel-linux-gnu/libicuuc.so (0x75b2d000)
```

Linking `unittests` against the correct libraries should fix this.  Note that these libraries are both part of the ICU package which V8 builds internally.

**Comment by mkaric** [comment]
This has been failing since the CL https://codereview.chromium.org/2416243002 landed, more precisely, since these changes in unittests.gyp landed: https://codereview.chromium.org/2416243002/diff/60001/test/unittests/unittests.gyp.

**Comment by mkaric** [comment]
Fixed this by adding icu libraries to dependencies in unittests.gyp when i18n support is on. Also fixed gn build. CL uploaded:
https://codereview.chromium.org/2479863002/

**Comment by mkaric** [comment]
This is pretty much done but the reviewer went on a two week long vacation so putting on hold until I can land the fix.

**Comment by mkaric** [comment]
Fix CL landed, unittests are green on the buildbot, closing.
