### ISSUE TITLE
New test failure on the 3.17 stable branch

### ISSUE THREAD

**Issue by palfia** [v8mips/v8mips#42]
A new backport merge breaks the MIPS build: http://code.google.com/p/v8/source/detail?r=14276

**Comment by paul99** [comment]
This change merges bleeding_edge r13898 to 3.17. 

We have the MIPS port of this fix in r13906. Can you merge that to the branch?

**Comment by palfia** [comment]
I've created a merge CL to fix this bug: https://codereview.chromium.org/14161005/

**Comment by palfia** [comment]
Landed as r14317.

Closing issue.
