### ISSUE TITLE
Optimization: optimize load/store with large offset on MIPSR2 and less

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#424]
Currently, we are using the following sequence for load/store with large offset. Let's say the offset is 0x12345678 and that we want to load the value to register a0 with base register s0. 

```
lui at, 0x1234
ori at, at, 0x5678
add at, s0, at
lw a0, 0(at)
```

This sequence can be optimized in the following way:

```
lui at, 0x1234
add at, s0, at
lw 0x5678(at)
```

**Comment by simicicd** [comment]
Sent to code review: https://codereview.chromium.org/2486283003/

**Comment by simicicd** [comment]
Patch for mips32 landed: https://codereview.chromium.org/2503493002/

**Comment by marijantic** [comment]
Patch for mips64: https://codereview.chromium.org/2505923002/

**Comment by marijantic** [comment]
Patch landed, closing the issue. https://crrev.com/daedefd3fc117754eaaa1b961880fff07d84852c
