### ISSUE TITLE
Bughunting: With Clang, build V8 fails for R6.

### ISSUE THREAD

**Issue by ilijapavlovic** [v8mips/v8mips#433]
When clang is used for building V8 with release 6, building fails on different targets.
The common error message for all failed builds:
```
...
clang: /b/build/slave/linux_upload_clang/build/src/third_party/llvm/lib/Target/Mips/MipsHazardSchedule.cpp:98: Iter getNextMachineInstr(Iter): Assertion `I != E' failed
...
```

**Comment by ilijapavlovic** [comment]
The problem is reproduced locally for mips64el.release.r6.
All relevant commands and files are collected and delivered/reported to the Clang team.

**Comment by ilijapavlovic** [comment]
The last appearance of this error message was in build 
https://v8.mips.com/bbv8/builders/Target%20-%20MIPS64%20-%20edge%20-%20clang%2Cmipsr6%2Cunder%20qemu%20-%20builder/builds/309/steps/compile/logs/stdio

After this build, new error messages are visible in logs.

**Comment by ilijapavlovic** [comment]
Build system for V8 uses Clang version 289944-2.
To Clang developers are delivered logs, cpp files and scripts which are generated by unsuccessful build.
The problems are reproduced with this version, but it is not the newest version of the Clang.
Clang version, where reproducing the problem is stopped at Clang developers, is  **290361**.
This fact should be checked.

**Comment by ilijapavlovic** [comment]
Build is successful since 
https://v8.mips.com/bbv8/builders/Target%20-%20MIPS64%20-%20edge%20-%20clang%2Cmipsr6%2Cunder%20qemu%20-%20builder/builds/865

New Clang version:
```
$ ${PROJECT}/v8/third_party/llvm-build/Release+Asserts/bin/clang++ --version
clang version 5.0.0 (trunk 295793)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: ${PROJECT}/v8/third_party/llvm-build/Release+Asserts/bin
```
Local build was also successful.

**Comment by ilijapavlovic** [comment]
The build again fails:
 https://v8.mips.com/bbv8/builders/Target%20-%20MIPS64%20-%20edge%20-%20clang%2Cmipsr6%2Cunder%20qemu%20-%20builder/builds/880

**Comment by ilijapavlovic** [comment]
All builds with Clang for Release 6 have problems with compiling `v8/src/heap/mark-compact.cc`.

Clang version:
```
$ ${PROJECT}/v8/third_party/llvm-build/Release+Asserts/bin/clang++ --version
clang version 5.0.0 (trunk 296320)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: ${PROJECT}/v8/third_party/llvm-build/Release+Asserts/bin
```

**Comment by ibogosavljevic** [comment]
I am closing this issue because it got resolved. The new failures are related to the new version of CLANG, please open the new issue with adequate description
