### ISSUE TITLE
Infrastracture: Enable watchdog timer on CI20 boards

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#434]
We are having problems with CI20 baords. The boards freeze from time to time and need to be manually reset. If we enable watchdog timer, the boards will reset themselves so there won't be any need for this.

**Comment by simicicd** [comment]
Steps for enabling watchdog timer on CI20 boards:

1. Check if watchdog module is loaded:
`ls -l /dev/watchdog*`
(Should be able to see /dev/watchdog and /dev/watchdog0 device files)

2. Install watchdog deamon if it is not already installed:
`sudo apt-get install watchdog`

3. Create dir for watchdog logs files (in case dir doesn't exist):
`sudo mkdir -p /var/log/watchdog`

4. Change the default watchdog configuration (file /etc/default/watchdog): 
- add following line to the end of file:
   `watchdog_options="-s -v -c /etc/watchdog.conf"`

5. Change /etc/watchdog.conf file: 
- uncomment following lines in this file:
```
   watchdog-device = /dev/watchdog    
   admin              = root
   interval            = 1
   logtick             = 1
   log-dir             = /var/log/watchdog    
   realtime           = yes
   priority            = 1 
```
- add following line to the end of file:
   `watchdog-timeout        = 60`

6. Start watchdog service at boot:
 - create a symbolic link to the watchdog.service file:
`sudo ln /lib/systemd/system/watchdog.service /etc/systemd/system/multi-user.target.wants/watchdog.service`

7. Reboot ci20 board

8. Verify watchdog service in running correctly:
`systemctl status watchdog.service`
