### ISSUE TITLE
Bughunting: Failing floating point tests on mipsr6 simulator

### ISSUE THREAD

**Issue by marijantic** [v8mips/v8mips#435]
https://v8.mips.com/bbv8/builders/Sim%20-%20Debug%20-%20edge%20-%20mipsr6/builds/4704/steps/Check/logs/RunFloat64MulAndFloat..
https://v8.mips.com/bbv8/builders/Sim%20-%20Debug%20-%20edge%20-%20mipsr6/builds/4689/steps/Check/logs/math-expm1
https://v8.mips.com/bbv8/builders/Sim%20-%20Debug%20-%20edge%20-%20mipsr6/builds/4689/steps/Check/logs/math-fround
https://v8.mips.com/bbv8/builders/Sim%20-%20Debug%20-%20edge%20-%20mipsr6/builds/4689/steps/Check/logs/multiply-add

Failures occurring since CL: https://chromium.googlesource.com/v8/v8/+/11f0a0e8196b71c6d6f6374f741111e7a8fde0a1

**Comment by marijantic** [comment]
Error when running 

> out/mipsel.debug/cctest --random-seed=1616162405 --ignition-staging test-run-machops/RunFloat64MulAndFloat64Add2 --nohard-abort --nodead-code-elimination --nofold-constants

> Fatal error in .././test/cctest/compiler/value-helper.h, line 350
  Check failed: x == y (4.29497e+75 vs. 4.29497e+75).

 Occurs for bit patterns x= 4fa2fdbb0e1d7eaf, y= 4fa2fdbb0e1d7eae

**Comment by marijantic** [comment]
CL that fixes the test-run-machops issue. https://codereview.chromium.org/2553073002 
Issues from mjsunit suite cannot be reproduced locally.

**Comment by marijantic** [comment]
We decided to skip the following tests for simulator runs:
'test-run-machops/RunFloat64MulAndFloat64Add1'
'test-run-machops/RunFloat64MulAndFloat64Add2'
'test-run-machops/RunFloat64MulAndFloat64Sub2'
'mjsunit/es6/math-expm1.js'
'mjsunit/es6/math-fround.js'
'mjsunit/compiler/multiply-add.js'

**Comment by ibogosavljevic** [comment]
Decided to disable fusion multiply add in both emitted and compiled code. A patch has been sent to review: https://codereview.chromium.org/2569683002/

**Comment by ibogosavljevic** [comment]
Patch landed, issue closeed
