### ISSUE TITLE
Improvement: Add supprot for FP register content in simulator trace.

### ISSUE THREAD

**Issue by ilijapavlovic** [v8mips/v8mips#439]
For instructions which manipulate with floating point (FP) registers, contents of FP registers are not visible in simulator trace. Several examples from simulator trace:
```
...
0x2a486730  46202306       mov.d   f12, f4
0x2a486768  46003386       mov.s   f14, f6
0x2a4867b4  44181000       mfc1    t8, f2
```
It is necessary to implement that content of destination registers is displayed in simulator trace.

**Comment by ilijapavlovic** [comment]
CL uploaded and ready for review: https://codereview.chromium.org/2603083002/

**Comment by ilijapavlovic** [comment]
Committed as https://chromium.googlesource.com/v8/v8/+/dac1327596c31e8348cd5163dae50860f763647f

**Comment by ibogosavljevic** [comment]
Closing
