### ISSUE TITLE
Bughunting: mjsunit/array-functions-prototype-misc falky failure

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#440]
https://v8.mips.com/bbv8/builders/Target%20-%20edge/builds/8870/steps/Check%20%28flakes%29/logs/array-functions-proto..

**Comment by p-rudic** [comment]
It has been found that tests occasionally fail because these tests need 400MB of RAM to run, and buildbots usually run several kind of tests at the same time. When system is low on memory it calls Out Of Memory killer which kills most memory hungry tests.

**Comment by ibogosavljevic** [comment]
Execute only one instance of the test on buildbots. The patch has been uploaded and landed and the issue doesn't appear anymore
https://codereview.chromium.org/2653603002/
