### ISSUE TITLE
cctest/test-api/IndependentWeakHandle fails on mips64

### ISSUE THREAD

**Issue by kwan0xfff** [v8mips/v8mips#444]
This is a test failure on the "build24-b3" (ER Pro--8) board at Google:
https://build.chromium.org/p/client.v8.ports/builders/V8%20Mips%20-%20big%20endian%20-%20nosnap%20-%202/builds/2290

The above build (# 2290) is the first occurrence found in logs for that builder.  Build # 2289 did not show this error.  From the test log:
```
Test: cctest/test-api/IndependentWeakHandle
Flags: 
Command: out/Release/cctest --random-seed=1778233961 test-api/IndependentWeakHandle --nohard-abort --nodead-code-elimination --nofold-constants

Build environment:

Run #1
Exit code: -6
Result: FAIL
Expected outcomes: PASS
Duration: 00:01:878

Stderr:


#
# Fatal error in ../../test/cctest/test-api.cc, line 7833
# Check failed: (CcTest::heap()->SizeOfObjects())<(big_heap_size - 20000).
#

==== C stack trace ===============================

    /b/build/slave/V8_Mips_-_big_endian_-_nosnap_-_2/build/v8/out/Release/cctest() [0x8d249c]
```

**Comment by p-rudic** [comment]
Can't reproduce this issue on our buildbots.  According to our observations problem arises because Garbage Collector don't free up enough space, but we didn't notice reason.

**Comment by kwan0xfff** [comment]
It seems this error is no longer reported by the board at Google. As of build #2366 on Jan 19, the error has gone away. (It was still in #2365.)
https://build.chromium.org/p/client.v8.ports/builders/V8%20Mips%20-%20big%20endian%20-%20nosnap%20-%202/builds/2366

I assume it is safe to close this.
