### ISSUE TITLE
Bughunting: mjsunit/regress/regress-crbug-514081 flaky failure on MIPS64 big-endian debug

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#446]
https://v8.mips.com/bbv8/builders/Target%20-%20MIPS64%20-%20big%20-%20Debug%20-%20edge/builds/1674/steps/Check%20%28flakes%29/logs/regress-crbug-514081

assign to @prudic

**Comment by p-rudic** [comment]
Those tests are using a lot of memory, and our boards have only up to 2GB of RAM. Therefore they are frequently failing because Out Of Memory killer terminates them.

**Comment by ibogosavljevic** [comment]
Execute only one instance of the test on buildbots. The patch has been uploaded and landed and the issue doesn't appear anymore
https://codereview.chromium.org/2653603002/
