### ISSUE TITLE
Infrastructure Maintanance: Explore possibilites for /tmp cleanup of unused files

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#448]
Assigning to @prudic

**Comment by p-rudic** [comment]
@MIPSbkirby Found program "tmpreaper" that can be used for periodical cleanup of unused files in /tmp folder. You can downoload instructions for using tmpreaper: https://docs.google.com/document/d/1Kg_7k99XrgCfE6sdtafpv1bEK7eKfD9YZsflC_DgJm0/edit?usp=sharing

**Comment by ibogosavljevic** [comment]
Done
