### ISSUE TITLE
Bughunting: With Clang, build V8 fails for R6.

### ISSUE THREAD

**Issue by ilijapavlovic** [v8mips/v8mips#461]
When V8 is build for Release 6 with Clang version 5.0.0 (trunk 296320), compiling `v8/src/heap/mark-compact.cc` fails.

https://v8.mips.com/bbv8/builders/Target%20-%20MIPS64%20-%20Debug%20-%20edge%20-%20clang%2Cmipsr6%2Cunder%20qemu%20-%20builder/builds/920/steps/compile/logs/stdio
https://v8.mips.com/bbv8/builders/Target%20-%20Debug%20-%20edge%20-%20clang%2Cmipsr6%2Cunder%20qemu%20-%20builder/builds/851/steps/compile/logs/stdio
https://v8.mips.com/bbv8/builders/Target%20-%20MIPS64%20-%20edge%20-%20clang%2Cmipsr6%2Cunder%20qemu%20-%20builder/builds/905/steps/compile/logs/stdio
https://v8.mips.com/bbv8/builders/Target%20-%20edge%20-%20clang%2Cmipsr6%2Cunder%20qemu%20-%20builder/builds/895/steps/compile/logs/stdio

This problem is reported to the Clang team: https://dmz-portal.mips.com/bugz/show_bug.cgi?id=2504

**Comment by ibogosavljevic** [comment]
Issue resolved on buildbots, closing...
