### ISSUE TITLE
Compilation failure: Failure on Target debug builders

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#462]
Following builders do not compile with following error:
https://v8.mips.com/bbv8/builders/Target%20-%20Debug%20-%20edge%20-%20builder/builds/13327/steps/compile/logs/stdio

Target - Debug - edge - builder
Target - big - Debug - edge - builder
Target - Debug - edge - mipsr1 - builder
Target - MIPS64 - Debug - edge - builder
Target - Debug - edge - mipsr6,under qemu,quick - builder
Target - MIPS64 - Debug - edge - mipsr6,under qemu,quick - builder
Target - MIPS64 - big - Debug - edge - builder

The reason for the failure is change introduced here: https://chromium.googlesource.com/v8/v8/+/7f68cbbffa14376006226a427d1b42081b109d46%5E%21/#F2

The problem appears only on GCC 4.9.2, it is absent in GCC 4.9.4. It is related to inlining of function Vector<T> SubVector(int from, int to) const into RegExpBuilder::AddQuantifierToAtom. When this happens, a warning occurs with message `../../src/vector.h: In member function ‘bool v8::internal::RegExpBuilder::AddQuantifierToAtom(int, int, v8::internal::RegExpQuantifier::QuantifierType)’:
../../include/v8config.h:357:67: error: assuming signed overflow does not occur when assuming that (X - c) > X is always false [-Werror=strict-overflow]`

This is a problem in GCC and it has been fixed in later versions. Unfortunately, the version that fixed it is not available for the MIPS target. We could workaround on this by disabling slow asserts.

@MIPSbkirby : Could you please disable slow asserts on target debug buildbots by setting v8_enable_slow_dchecks to false?

**Comment by MIPSbkirby** [comment]
`v8_enable_slow_dchecks` is set to false for all builders that had it turned on.  I've run a [build](https://v8.mips.com/bbv8/builders/Target%20-%20Debug%20-%20edge%20-%20builder/builds/13370) and it compiled successfully.  So, the work around is in place.

**Comment by ibogosavljevic** [comment]
Done
