### ISSUE TITLE
Try to optimize mov(a0, vo) instructions

### ISSUE THREAD

**Issue by palfia** [v8mips/v8mips#47]
Recently, I have added a few new mov instructions to move a "function"'s result to the first argument of another "function".

We should try to get rid of these extra moves, if possible.

Examples:
FullCodeGenerator::DoTest(...)
FullCodeGenerator::VisitYield(...)

**Comment by kisg** [comment]
It was investigated by Ákos, and he does not see a way to optimize these mov() instructions.
