### ISSUE TITLE
Bughunting: Builders fail when inspector is enabled in gyp.

### ISSUE THREAD

**Issue by ilijapavlovic** [v8mips/v8mips#470]
Following builders fail:
https://v8.mips.com/bbv8/builders/Target%20-%20Debug%20-%20edge%20-%20builder/builds/13637
https://v8.mips.com/bbv8/builders/Target%20-%20edge%20-%20builder/builds/14203
https://v8.mips.com/bbv8/builders/Target%20-%20edge%20-%20mipsr1%20-%20builder/builds/12417
https://v8.mips.com/bbv8/builders/Target%20-%20MIPS64%20-%20edge%20-%20builder/builds/14343
https://v8.mips.com/bbv8/builders/Target%20-%20edge%20-%20mipsr6%2Cunder%20qemu%20-%20builder/builds/3468
https://v8.mips.com/bbv8/builders/Target%20-%20MIPS64%20-%20edge%20-%20mipsr6%2Cunder%20qemu%20-%20builder/builds/3695

Common thing for these problems is that they started after commit:
`9bc1eb5ecee0b1859db4baa262c5eff53cfe8b18       Enable inspector in gyp`

**Comment by ilijapavlovic** [comment]
Content of the error message:
```
ninja: error: obj.host/src/inspector/protocol_compatibility.ninja:13: multiple rules generate gen/src/js_protocol.stamp [-w dupbuild=err]
```

**Comment by ilijapavlovic** [comment]
In file `v8/src/inspector/inspector.gyp` are following lines:
```
    { 'target_name': 'protocol_compatibility',
     ...
      'actions': [
        {
          'action_name': 'protocol_compatibility',
          'inputs': [
            'js_protocol.json',
          ],
          'outputs': [
            '<@(SHARED_INTERMEDIATE_DIR)/src/js_protocol.stamp',
          ],
          'action': [
            'python',
            '<(protocol_path)/CheckProtocolCompatibility.py',
            '--stamp', '<@(_outputs)',
            'js_protocol.json',
          ],
          'message': 'Generating inspector protocol sources from protocol json definition',
        },
      ]
    },
```
In file `build.ninja` are many lines with `subninja`keywords which include another `.ninja` files.
These included files are searched for lines with `js_protocol.stamp` and most of them contain rules with `gen/src/js_protocol.stamp`.

**Comment by ilijapavlovic** [comment]
Reported error: https://bugs.chromium.org/p/v8/issues/detail?id=6176

**Comment by ilijapavlovic** [comment]
Build for MIPS32 big endian is successful while it is not case for little endian.
In file `v8/src/inspector/inspector.gyp`, all targets have following condition:
```
      'conditions': [
        ['want_separate_host_toolset==1', {
          'toolsets': ['host', 'target'],
        }, {
          'toolsets': ['target'],
        }]
      ],
```
For MIPS big endian targets, `want_separate_host_toolset` is set to `0` while for little endian targets this parameter has value `1`. These settings are regulated in file `v8/gypfiles/standalone.gypi`:
```
    'conditions': [
      ['(v8_target_arch=="arm" and host_arch!="arm") or \
        (v8_target_arch=="arm64" and host_arch!="arm64") or \
        (v8_target_arch=="mipsel" and host_arch!="mipsel") or \
        (v8_target_arch=="mips64el" and host_arch!="mips64el") or \
        (v8_target_arch=="x64" and host_arch!="x64") or \
        (OS=="android" or OS=="qnx")', {
        'want_separate_host_toolset': 1,
      }, {
        'want_separate_host_toolset': 0,
      }],
```

**Comment by ilijapavlovic** [comment]
When toolset is `target`, as output directory is used `SHARED_INTERMEDIATE_DIR`. Value for this variable is defined as `$!PRODUCT_DIR/gen`. For `host` toolset, as output will be used the same `gen` directory and this fact leads to conflict where rules for `target` and `host` try to create/build the same files.

To avoid this problem, following is applied:
- If toolset is `host`, as output directory will be used `INTERMEDIATE_DIR`.
- If toolset is `target`, as output directory will be used `SHARED_INTERMEDIATE_DIR`.

This approach was successful for building `mipsel.r2`.

**Comment by ilijapavlovic** [comment]
CL: https://codereview.chromium.org/2819283005/

**Comment by ibogosavljevic** [comment]
CL sent to review and landed. Issue closed
