### ISSUE TITLE
Bughunting: Failure of test mjsunit/wasm/grow-memory 

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#472]
https://v8.mips.com/bbv8/builders/Sim%20-%20MIPS64%20-%20Debug%20-%20edge/builds/10690/steps/Check/logs/grow-memory

**Comment by ibogosavljevic** [comment]
assigning to @p-rudic

**Comment by p-rudic** [comment]
Resolved by this commit: https://chromium-review.googlesource.com/463006
