### ISSUE TITLE
Bughunting: mjsunit/array-feedback and mjsunit/array-constructor failure

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#475]
A few test started failing on MIPS64 after following commit:

https://chromium.googlesource.com/v8/v8/+/751e89359123df4f6e5f0b28b89fcdf63ed16a77

https://v8.mips.com/bbv8/builders/Target%20-%20MIPS64%20-%20edge/builds/8362/steps/Check/logs/array-feedback
https://v8.mips.com/bbv8/builders/Target%20-%20MIPS64%20-%20edge/builds/8362/steps/Check/logs/array-constructor
https://v8.mips.com/bbv8/builders/Target%20-%20MIPS64%20-%20edge/builds/8362/steps/Check/logs/md5
https://v8.mips.com/bbv8/builders/Target%20-%20MIPS64%20-%20edge/builds/8362/steps/Check/logs/packed-elements

Assign to @p-rudic

**Comment by p-rudic** [comment]
Resolved in patch: https://codereview.chromium.org/2816733004/#

**Comment by ibogosavljevic** [comment]
Issue closed
