### ISSUE TITLE
cctest/test-cpu-profiler/SampleWhenFrameIsNotSetup bug for MIPS.

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#49]
This test was put on the SKIP list for mips only by Yuri S. when it failed. I had missed that. 

It seems that if it is passing for arm, then it should be passing for MIPS also, so I think we should look deeper at this.

Let's get to this when we have some time.

```
https://codereview.chromium.org/16329004
http://code.google.com/p/v8/issues/detail?id=2628
```

**Comment by dusmil** [comment]
Fix for this is submitted.
https://codereview.chromium.org/17265004/

**Comment by paul99** [comment]
Thanks for the fix! The CL is landed as r15213, and v8 bug http://code.google.com/p/v8/issues/detail?id=2628 is also updated. 

Closing this issue.
