### ISSUE TITLE
sunspider-1.0.2 failed on chromium 60

### ISSUE THREAD

**Issue by xwafish** [v8mips/v8mips#497]
I build chromium 60 with mips64r2, v8 version is 6.0.186
but sun spider test failed:
https://webkit.org/perf/sunspider/sunspider.html

chromium 58 failed too, but chromium 52 pass.

**Comment by ClarkWang-2013** [comment]
chromium58：
http://www.linuxfromscratch.org/blfs/view/svn/xsoft/chromium.html

build on mips64el platform with mips64r2，but sunspider test failed。

**Comment by ClarkWang-2013** [comment]
get v8 code and build from：
https://github.com/v8/v8/wiki/Building-with-GN

fetch v8
gclient sync

gn gen out.gn/mips64el.release --args='use_sysroot=false is_clang=fasle is_debug=false use_goma=true'
ninja -C out.gn/mips64el.release d8

d8 test sunspider-1.0.2，results as follows：
1、out.gn/mips64el.release/d8 3d-raytrace.js 
3d-raytrace.js:446: Error: bad result: expected length 20970 but got 20716
    throw "Error: bad result: expected length " + expectedLength + " but got " + testOutput.length;
    ^
2、out.gn/mips64el.release/d8 access-nbody.js 
access-nbody.js:173: ERROR: bad result: expected -1.3524862408537381 but got -1.3524862408537377
    throw "ERROR: bad result: expected " + expected + " but got " + ret;
3、out.gn/mips64el.release/d8 3d-cube.js 
3d-cube.js:340: Error: bad vector sum for CubeSize = 40; expected 2889.0000000000055 but got 2889.0000000000023
    throw "Error: bad vector sum for CubeSize = " + CubeSize + "; expected " + validation[CubeSize] + " but got " + sum;
    ^

Same with chromium58 sunspider-1.0.2 test, and also 3d-cube,3d-raytrace and nboby test failed.

**Comment by ibogosavljevic** [comment]
Please try to cherry pick following change to your V8 source code and recompile V8 and try again:

commit ID: 601f1fdf8d4b9e527ab1e5c061803ef548ecfd93

MIPS[64]: Fix deoptimizer generate table for large deoptimization tables

With the introduction of upfront deopt table generation, case where
deoptimization tables have more than 8000 entries become much more common
and bugs started to appear.

This CL fixes the issue, but it is far from perfect. We had to
increase number of instruction per table entry from 2 to 3 in
order to accommodate larger tables.

TEST=mjsunit/array-sort,mjsunit/json,mjsunit/md5
BUG=

Review-Url: https://codereview.chromium.org/2901393003
Cr-Commit-Position: refs/heads/master@{#45531}

**Comment by ClarkWang-2013** [comment]
I checkout commit ID: 601f1fdf8d4b9e527ab1e5c061803ef548ecfd93
MIPS[64]: Fix deoptimizer generate table for large deoptimization tables.

and build again,but also test failed unfortunatly.

**Comment by ibogosavljevic** [comment]
Please provide some more information about the environment:
are you cross compiling?
what version of gcc are you using?

**Comment by ClarkWang-2013** [comment]
Not cross compiling, I'm compiling on loongson3A mips64el platform.

$ gcc -v
COLLECT_GCC=/usr/bin/gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/mips64el-redhat-linux/4.9.3/lto-wrapper
target：mips64el-redhat-linux
configure：../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-arch=loongson3a --enable-languages=c,c++,objc,obj-c++,fortran,go,lto --enable-plugin --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.9.3/obj-mips64el-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.9.3/obj-mips64el-redhat-linux/cloog-install --enable-gnu-indirect-function --with-long-double-128 --build=mips64el-redhat-linux
gcc version 4.9.3 20150626 (Red Hat 4.9.3-5) (GCC)

**Comment by ClarkWang-2013** [comment]
Same platform environment, I compiling chromium52 with v8-5.2.36.49 test sunspider-1.0.2 passed all.

**Comment by ibogosavljevic** [comment]
I need to try to reproduce the issue in my environment. Can you please try the following:
* execute Octante test suite as described here https://github.com/v8mips/v8mips/wiki/Benchmarking-V8. Please let me know if there are any failures.
* use the same binary but execute it on some other mips64r2 architecture. This would help me determine if the problem is related to V8 in general or is it specific to Longsoon.

**Comment by ClarkWang-2013** [comment]
V8 benchmark octance2.0 test all passed.  i'm sorry I only have loongson mips64r2 architecture, but i guess can be related to v8 in general mips64r2.

**Comment by ibogosavljevic** [comment]
Hi!

I am having problems running SunSpider test suite. There is no version that can be executed offline. Can you send me the files and instructions on how to run?

**Comment by ibogosavljevic** [comment]
Also, I compiled V8 for MIPS32R6 statically using cross compile toolchain Codescape GNU Tools 2015.01-7 for MIPS MTI Linux and linked it statically. commit ID 2325ef535f895529c3d705b20ef0a0e552232652

It can be downloaded from this address: https://dl.rt-rk.com/?t=34fcd3802784c7cf3cf2a061607ebcd1

Could you please try it out and tell me if the problem is reproduced with this version. This should help me establish if the problem is with the compiler/architecture or V8.

**Comment by ClarkWang-2013** [comment]
https://github.com/WebKit/webkit/tree/master/PerformanceTests/SunSpider/tests/sunspider-1.0.2

you can only test three js files:3d-cube.js 3d-raytrace.js and access-nbody.js

test method: /you-path/d8 3d-cube.js

Tests whether to make a problem?

**Comment by ClarkWang-2013** [comment]
I downloaded d8 from this address: 
https://dl.rt-rk.com/?t=34fcd3802784c7cf3cf2a061607ebcd1

test three js files:3d-cube.js 3d-raytrace.js and access-nbody.js in sunspider-1.0.2 and occur errors as follows:
$ ./d8 ../../wangqing/SunSpider/tests/sunspider-1.0.2/3d-cube.js 
#
# Fatal error in ../src/heap/heap.cc, line 1205
# Check failed: static_cast<size_t>(size) <= MemoryAllocator::PageAreaSize( static_cast<AllocationSpace>(space)) (499872 vs. 475136).
#

==== C stack trace ===============================

    [0x120e3cfcc]
Trace/breakpoint trap (核心已转储)

Three test failed error as same.

**Comment by ibogosavljevic** [comment]
The problem is that your Linux uses non standard page size. V8 uses 4 kB by default. Can you please execute following command in the console so we get the correct number

getconf PAGE_SIZE

I will recompile V8 and send you the version that works

**Comment by ClarkWang-2013** [comment]
loongson page size is 16KB by default.
$ getconf PAGE_SIZE
16384

**Comment by ibogosavljevic** [comment]
Can you please try with this version: https://dl.rt-rk.com/?t=01c02f15291807935fb4862105cc0ba1

It has fixed the page size for your system

**Comment by ClarkWang-2013** [comment]
I test the v8_3/d8, 3d-cube.js and access-nbody.js test passed, but 3d-raytrace.js still test failed。

$ ./d8 ../../wangqing/SunSpider/tests/sunspider-1.0.2/3d-raytrace.js 
../../wangqing/SunSpider/tests/sunspider-1.0.2/3d-raytrace.js:446: Error: bad result: expected length 20970 but got 20866
    throw "Error: bad result: expected length " + expectedLength + " but got " + testOutput.length;
    ^

**Comment by ibogosavljevic** [comment]
I managed to reproduce the issue, but it reproduces on Loongson only. It doesn't reproduce on other architectures.

I am on vacation until the end of this week and will be back to debug it on Monday

**Comment by ibogosavljevic** [comment]
Hi Wang!

I managed to find the cause of the failure of 3d-raytrace.js test. It seems that Loongson 3A either uses fused MADD or has some problem with MADD instruction. Between Chromium 52 and Chromium 60 we enabled MADD instruction instead of MUL/ADD and this is the reason why you see the failure.

Below is the patch that will make test 3d-raytrace.js pass on Loongson 3A. Please notice that this is just a workaround and we will need to fix this better, but this will be done later.
```
diff --git a/src/mips64/macro-assembler-mips64.cc b/src/mips64/macro-assembler-mips64.cc
index 59e7f21..faf6632 100644
--- a/src/mips64/macro-assembler-mips64.cc
+++ b/src/mips64/macro-assembler-mips64.cc
@@ -2618,7 +2618,9 @@ void MacroAssembler::Trunc_ul_s(FPURegister fd, Register rs,
 void MacroAssembler::Madd_s(FPURegister fd, FPURegister fr, FPURegister fs,
                             FPURegister ft, FPURegister scratch) {
   if (kArchVariant == kMips64r2) {
-    madd_s(fd, fr, fs, ft);
+    DCHECK(!fr.is(scratch) && !fs.is(scratch) && !ft.is(scratch));
+    mul_s(scratch, fs, ft);
+    add_s(fd, fr, scratch);
   } else {
     DCHECK(!fr.is(scratch) && !fs.is(scratch) && !ft.is(scratch));
     mul_s(scratch, fs, ft);
@@ -2629,7 +2631,9 @@ void MacroAssembler::Madd_s(FPURegister fd, FPURegister fr, FPURegister fs,
 void MacroAssembler::Madd_d(FPURegister fd, FPURegister fr, FPURegister fs,
     FPURegister ft, FPURegister scratch) {
   if (kArchVariant == kMips64r2) {
-    madd_d(fd, fr, fs, ft);
+    DCHECK(!fr.is(scratch) && !fs.is(scratch) && !ft.is(scratch));
+    mul_d(scratch, fs, ft);
+    add_d(fd, fr, scratch);
   } else {
     DCHECK(!fr.is(scratch) && !fs.is(scratch) && !ft.is(scratch));
     mul_d(scratch, fs, ft);
```

**Comment by ClarkWang-2013** [comment]
Thanks !!!   I modify as follows and all sunspider-1.0.2 tests passed:

diff --git a/BUILD.gn b/BUILD.gn
index e732957..f7834e1 100644
--- a/BUILD.gn
+++ b/BUILD.gn
@@ -383,6 +383,9 @@ config("toolchain") {
       defines += [ "_MIPS_ARCH_MIPS64R6" ]
     } else if (mips_arch_variant == "r2") {
       defines += [ "_MIPS_ARCH_MIPS64R2" ]
    +} else if (mips_arch_variant == "loongson3") {
    +defines += [ "_MIPS_ARCH_LOONGSON" ]
    +defines += [ "FPU_MODE_FP64" ]
     }
   }
   if (v8_current_cpu == "s390" || v8_current_cpu == "s390x") {
diff --git a/src/mips64/macro-assembler-mips64.cc b/src/mips64/macro-assembler-mips64.cc
index 769cd7f..0410534 100644
--- a/src/mips64/macro-assembler-mips64.cc
+++ b/src/mips64/macro-assembler-mips64.cc
@@ -2493,7 +2493,13 @@ void MacroAssembler::Trunc_ul_s(FPURegister fd, Register rs,
 void MacroAssembler::Madd_s(FPURegister fd, FPURegister fr, FPURegister fs,
                             FPURegister ft, FPURegister scratch) {
   if (kArchVariant == kMips64r2) {
+#ifdef _MIPS_ARCH_LOONGSON
    +DCHECK(!fr.is(scratch) && !fs.is(scratch) && !ft.is(scratch));
    +mul_s(scratch, fs, ft);
    +add_s(fd, fr, scratch);
+#else
     madd_s(fd, fr, fs, ft);
+#endif
   } else {
     DCHECK(!fr.is(scratch) && !fs.is(scratch) && !ft.is(scratch));
     mul_s(scratch, fs, ft);
@@ -2504,7 +2510,13 @@ void MacroAssembler::Madd_s(FPURegister fd, FPURegister fr, FPURegister fs,
 void MacroAssembler::Madd_d(FPURegister fd, FPURegister fr, FPURegister fs,
     FPURegister ft, FPURegister scratch) {
   if (kArchVariant == kMips64r2) {
+#ifdef _MIPS_ARCH_LOONGSON
    +DCHECK(!fr.is(scratch) && !fs.is(scratch) && !ft.is(scratch));
    +mul_d(scratch, fs, ft);
    +add_d(fd, fr, scratch);
+#else
     madd_d(fd, fr, fs, ft);
+#endif
   } else {
     DCHECK(!fr.is(scratch) && !fs.is(scratch) && !ft.is(scratch));
     mul_d(scratch, fs, ft);

And,  gn gen out.gn/mips64el.release --args='use_sysroot=false is_clang=false is_debug=false use_goma=true mips_arch_variant="loongson3"', I add "mips_arch_variant="loongson3"" to args.

**Comment by ibogosavljevic** [comment]
So here is the verdict: Loongson 3A has fused multiply-add instruction instead of the regular (this is not according to instruction manual for R2 architecture). This is what is causing problem in this test.

Having this in mind, we will remove MADD optimizations for MIPS64R2 since they don't give proper results on MIPS64R2

**Comment by ClarkWang-2013** [comment]
@ibogosavljevic  I‘m Sorry to trouble you, listen to you before V8 has pagesize problem on loongson platform. 
Now，I have a problem that local compiling on loongson is ok, but cross compiling on x64 and run in loongson is error。I want to know how you modify pagesize in V8?

Thanks.
