### ISSUE TITLE
Test with softfloat on sim and mips hardware

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#5]
I have not tested soft-float build of v8 for a long time, and I do not think it is on one of our builders.

Can you please test, both sim & hw, and document status here, and fix any issues that arise.

I know without float that we will not use crankshaft, and that's fine, but it should work. Maybe you can also run & publish v8 and sunspider benchmarks in softfloat mode.

**Comment by dusmil** [comment]
Here are the results on mips simulator for soft-float in release mode:

cctest:  [06:27|% 100|+ 2763|-   0]

mjsunit: [12:35|% 100|+ 2781|-   0]

mozilla: [43:27|% 100|+ 5787|-   0]

sputnik: [14:55|% 100|+ 15861|-   0]

Current  version from head of our bleeding_edge branch.

**Comment by paul99** [comment]
Please see https://github.com/paul99/v8m-rb/issues/6: sputnik is gone. Please do test with test262.

Also, can you please run at least a sim test on the google repo HEAD, so we know nothing from our repo got missed in submissions.

**Comment by dusmil** [comment]
Results on HW Sigma8656 soft-float release:

mjsunit: [96:17|% 100|+ 2781|-   0]

mozilla: [334:08|% 100|+ 5787|-   0]

test262: [606:43|% 100|+ 34734|-   0]

**Comment by dusmil** [comment]
Benchmarks on Sigma 8656 soft-float release mode:

V8 benchmark:

Richards: 385
DeltaBlue: 295
Crypto: 429
RayTrace: 177
EarleyBoyer: 721
RegExp: 97.4
Splay: 244

---

Score (version 6): 284

Sputnik:

# 

 RESULTS (means and 95% confidence intervals)

---

Total:                 11750.8ms +/- 0.2%

---

  3d:                   3003.8ms +/- 0.4%
    cube:                563.3ms +/- 0.6%
    morph:              1999.8ms +/- 0.9%
    raytrace:            440.8ms +/- 1.1%

  access:                525.8ms +/- 0.2%
    binary-trees:         46.0ms +/- 0.0%
    fannkuch:            209.0ms +/- 0.6%
    nbody:               181.5ms +/- 0.5%
    nsieve:               89.3ms +/- 0.9%

  bitops:                360.5ms +/- 0.4%
    3bit-bits-in-byte:    24.8ms +/- 3.2%
    bits-in-byte:         55.0ms +/- 0.0%
    bitwise-and:         111.3ms +/- 1.4%
    nsieve-bits:         169.5ms +/- 0.5%

  controlflow:            61.0ms +/- 0.0%
    recursive:            61.0ms +/- 0.0%

  crypto:                647.3ms +/- 1.0%
    aes:                 283.3ms +/- 1.2%
    md5:                 240.8ms +/- 1.0%
    sha1:                123.3ms +/- 0.6%

  date:                 1105.5ms +/- 1.0%
    format-tofte:        539.0ms +/- 0.9%
    format-xparb:        566.5ms +/- 2.0%

  math:                 3318.0ms +/- 0.1%
    cordic:              128.5ms +/- 0.7%
    partial-sums:       3084.3ms +/- 0.2%
    spectral-norm:       105.3ms +/- 0.8%

  regexp:                281.3ms +/- 0.7%
    dna:                 281.3ms +/- 0.7%

  string:               2447.8ms +/- 0.5%
    base64:              141.0ms +/- 0.9%
    fasta:               210.0ms +/- 0.6%
    tagcloud:           1017.3ms +/- 1.4%
    unpack-code:         888.8ms +/- 0.8%
    validate-input:      190.8ms +/- 1.4%

**Comment by paul99** [comment]
Gergely, can you verify that softfloat is on our builders periodically, both release and debug modes for all suites?

If so (or once it is done) please close this issue.

**Comment by kisg** [comment]
Ákos: please set up a softfloat build slave in jenkins with the SF malta board. Add this board to the v8-mips74k-softfloat group. Set up the following softfloat build jobs:
- v8-gbl-simulator-release-softfloat
- v8mips-bleeding-edge-simulator-release-softfloat
- v8-gbl-mips74k-release-softfloat (started if the gbl simulator is at least unstable
- v8mips-bleeding-edge-mips74k-release-softfloat (started if the bleeding-edge simulator is at least unstable)

Close the issue when ready.

**Comment by kisg** [comment]
We no longer support softfloat in GBL, 3.17 branch is the last, we have jobs set up for that.
