### ISSUE TITLE
Test failures on sim with snapshot=off

### ISSUE THREAD

**Issue by kilvadyb** [v8mips/v8mips#50]
The following tests fail on MIPS simulator when cctest compiled with snapshot=off and they pass on ARM simulator:

cctest/test-serialize/DeserializeFromSecondSerialization --nobreak-on-abort --nodead-code-elimination --nofold-constants

cctest/test-serialize/DeserializeFromSecondSerialization --nobreak-on-abort --nodead-code-elimination --nofold-constants --stress-opt --always-opt

cctest/test-serialize/DeserializeFromSecondSerialization --nobreak-on-abort --nodead-code-elimination --nofold-constants --nocrankshaft

cctest/test-serialize/DeserializeFromSecondSerializationAndRunScript2 --nobreak-on-abort --nodead-code-elimination --nofold-constants --nocrankshaft

cctest/test-serialize/DeserializeFromSecondSerializationAndRunScript2 --nobreak-on-abort --nodead-code-elimination --nofold-constants

cctest/test-serialize/DeserializeFromSecondSerializationAndRunScript2 --nobreak-on-abort --nodead-code-elimination --nofold-constants --stress-opt --always-opt

cctest/test-api/OutOfMemory --nobreak-on-abort --nodead-code-elimination --nofold-constants --stress-opt --always-opt

cctest/test-api/HugeConsStringOutOfMemory --nobreak-on-abort --nodead-code-elimination --nofold-constants --stress-opt --always-opt

cctest/test-api/OutOfMemoryNested --nobreak-on-abort --nodead-code-elimination --nofold-constants --stress-opt --always-opt

**Comment by kilvadyb** [comment]
OutOfMemory problems can be solved adding 4 \* K to constraints.set_max_old_space_size values in test/cctest/test-api.cc.

**Comment by dusmil** [comment]
I have noticed those tests are skipped for ARM. Does this increase of old space size resolve all tests?

**Comment by kilvadyb** [comment]
cctest/test-api/HugeConsStringOutOfMemory is solved by the commit: https://codereview.chromium.org/18688002/
The OutOfMemory and OutOfMemoryNested can be solved with the same way: adding 4 \* K to constraints.set_max_old_space_size values in test/cctest/test-api.cc

cctest/test-serialize/\* tests aren't solved this way, they should be SKIPed as on ARM.

**Comment by dusmil** [comment]
That's good. The real question is now whether we can do the same for the test from "test-serialize", or skip them as it is done for ARM.
