### ISSUE TITLE
Porting: [arm] Introduce UseScratchRegisterScope

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#501]
Port https://chromium-review.googlesource.com/c/544956/ to MIPS32 and MIPS64 if applicable

**Comment by sretenkovacevic** [comment]
CL uploaded and landed. Link to codereview: [https://chromium-review.googlesource.com/c/574923/](https://chromium-review.googlesource.com/c/574923/)

**Comment by ibogosavljevic** [comment]
Closed.
