### ISSUE TITLE
Bughunting: cctest/test-spaces/SizeOfInitialHeap

### ISSUE THREAD

**Issue by ilijapavlovic** [v8mips/v8mips#502]
The test cctest/test-spaces/SizeOfInitialHeap fails on following test builders:
https://v8.imgtec.com/bbv8/builders/Sim%20-%20edge/builds/14832
https://v8.imgtec.com/bbv8/builders/Sim%20-%20MIPS64%20-%20edge/builds/11231
https://v8.imgtec.com/bbv8/builders/Target%20-%20edge/builds/10589
https://v8.imgtec.com/bbv8/builders/Target%20%281%29%20-%20edge/builds/9080
https://v8.imgtec.com/bbv8/builders/Target%20-%20edge%20-%20shared%20library/builds/7277
https://v8.imgtec.com/bbv8/builders/Target%20-%20edge%20-%20fpxx/builds/3777
https://v8.imgtec.com/bbv8/builders/Target%20%281%29%20-%20edge%20-%20fpxx/builds/4404
https://v8.imgtec.com/bbv8/builders/Target%20-%20edge%20-%20mipsr1/builds/10788
https://v8.imgtec.com/bbv8/builders/Target%20-%20big%20-%20edge/builds/13269
https://v8.imgtec.com/bbv8/builders/Target%20-%20MIPS64%20-%20edge/builds/9097
https://v8.imgtec.com/bbv8/builders/Target%20-%20edge%20-%20clang/builds/2637
https://v8.imgtec.com/bbv8/builders/Target%20-%20MIPS64%20-%20edge%20-%20clang/builds/2598

Common error message for all of them:
```
#
# Fatal error in ../../test/cctest/heap/test-spaces.cc, line 474
# Check failed: heap->paged_space(i)->CommittedMemory() <= kMaxInitialSizePerSpace.
#
```

**Comment by ilijapavlovic** [comment]
The problem appears after following commit:
```
commit 0d833cb94f882e28054ea1fcff7de1d6dafe302a

    [deoptimizer] Remove support for code-stub "deopt".
    
    This removes support for code-stub to tail-call into the runtime via the
    deoptimizer. The Hydrogen code-stubs would trigger a deopt in order to
    materialize a trampoline frame, which would then continue execution in a
    runtime function associated with each stub. This is no longer needed for
    code-stubs built with the CSA.
```
Reviewed-on: https://chromium-review.googlesource.com/548375

**Comment by p-rudic** [comment]
The bug is fixed by this CL : https://chromium-review.googlesource.com/c/593950/

**Comment by ibogosavljevic** [comment]
Closed
