### ISSUE TITLE
Port: ` [arm][arm64] Delete unused code from the macro assembler `

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#509]
Port https://chromium-review.googlesource.com/c/571011/

**Comment by ilijapavlovic** [comment]
From `macro-assembler-mips64.*` will not be removed ` void StubPrologue(StackFrame::Type type);`.
See following CL: https://codereview.chromium.org/2467513002
In this CL, `StubPrologue()` is removed from ARM64 implementation, but in MIPS64 are done another corrections.

**Comment by ilijapavlovic** [comment]
CL uploaded: https://chromium-review.googlesource.com/c/591127/

**Comment by ilijapavlovic** [comment]
CL landed as 
https://chromium.googlesource.com/v8/v8/+/d721a9d40627a80acc27a0b856e82a2b20d8d834

**Comment by ibogosavljevic** [comment]
Closed
