### ISSUE TITLE
Bughunting: Failure of mjsunit/optimized-foreach-holey, mjsunit/optimized-foreach-holey-3 on big endian

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#512]
There are a few tests failing on BIG endian

https://v8.imgtec.com/bbv8/builders/Target%20-%20big%20-%20Debug%20-%20edge/builds/10137/steps/Check/logs/optimized-foreach-holey
https://v8.imgtec.com/bbv8/builders/Target%20-%20big%20-%20Debug%20-%20edge/builds/10137/steps/Check/logs/optimized-foreach-hol..
https://v8.imgtec.com/bbv8/builders/Target%20-%20big%20-%20Debug%20-%20edge/builds/10137/steps/Check/logs/regress-6526
https://v8.imgtec.com/bbv8/builders/Target%20-%20big%20-%20Debug%20-%20edge/builds/10137/steps/Check/logs/regress-747075

**Comment by p-rudic** [comment]
Bug was because of bad union initialization.
This CL fixed the issue: https://chromium-review.googlesource.com/c/613266

**Comment by ibogosavljevic** [comment]
Issue closed
