### ISSUE TITLE
Porting: `Fix code generator for load and store data`

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#516]
Port https://chromium-review.googlesource.com/c/608975 to MIPS32

**Comment by ilijapavlovic** [comment]
CL uploaded:
https://chromium-review.googlesource.com/c/v8/v8/+/699998

**Comment by ilijapavlovic** [comment]
CL landed: https://chromium.googlesource.com/v8/v8/+/419edddad3fe7fc55cee47738d31582e192a0162
