### ISSUE TITLE
New feature: Add support for MSA 2RF instructions to simulator

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#517]
Add support for MSA 2RF instructions to simulator

This CL add support for MSA 2R instructions to simulator: https://chromium-review.googlesource.com/c/538654

Similarly, please add support for MSA 2RF instructions to simulator. Please add tests for the new instructions if they are not already present.

Information about MIPS MSA can be found here: http://cdn2.imgtec.com/documentation/MD00866-2B-MSA32-AFP-01.12.pdf

**Comment by p-rudic** [comment]
Instructions and corresponding test are added for V8 builtin simulator in this CL: https://chromium-review.googlesource.com/c/v8/v8/+/657677

**Comment by ibogosavljevic** [comment]
Functionality implemented, closing.
