### ISSUE TITLE
Skip cctest/test-run-wasm-atomics/* for big endian architecture.

### ISSUE THREAD

**Issue by ilijapavlovic** [v8mips/v8mips#526]
For big endian architecture, cctest/test-run-wasm-atomics/* should be skipped.

**Comment by ilijapavlovic** [comment]
The CL uploaded: https://chromium-review.googlesource.com/c/v8/v8/+/671010
The CL tested on MIPS32 and MIPS64 big-endian boards.

**Comment by ilijapavlovic** [comment]
The CL landed: https://chromium.googlesource.com/v8/v8/+/ce76dd60c8c879e5528558096517331c4ac66794

**Comment by ibogosavljevic** [comment]
Closed.
