### ISSUE TITLE
Bughunting: A handfull of tests fail under MIPS64BE with same error

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#527]
There is a handfull of test that fail with the following error on MIPS64BE:

```
--- stderr ---
#
# Fatal error in ../../src/deoptimizer.cc, line 3413
# Check failed: !iterator->HasNext() || static_cast<Translation::Opcode>(iterator->Next()) == Translation::BEGIN.
#

==== C stack trace ===============================
```

The list is available here:
https://v8.imgtec.com/bbv8/builders/Target%20-%20MIPS64%20-%20big%20-%20Debug%20-%20edge/builds/2263/steps/Check/logs/stdio

**Comment by sretenkovacevic** [comment]
CL landed [https://chromium-review.googlesource.com/#/c/700680/](https://chromium-review.googlesource.com/#/c/700680/). 367 tests are fixed.

**Comment by ibogosavljevic** [comment]
As of https://v8.imgtec.com/bbv8/builders/Target%20-%20MIPS64%20-%20big%20-%20Debug%20-%20edge/builds/2325 there is no failures except for three tests that are covered in this bug. Issue closed.

**Comment by ibogosavljevic** [comment]
Commit that solves the issues: https://v8.imgtec.com/bbv8/builders/Target%20-%20MIPS64%20-%20big%20-%20Debug%20-%20edge/builds/2319
