### ISSUE TITLE
Bughunting: mjsunit/asm/int32div fails with Clang 313786-1.

### ISSUE THREAD

**Issue by ilijapavlovic** [v8mips/v8mips#530]
The test fails when build V8 is performed with the Clang:

https://v8.imgtec.com/bbv8/builders/Target%20-%20MIPS64%20-%20edge%20-%20clang/builds/3046
https://v8.imgtec.com/bbv8/builders/Target%20-%20MIPS64%20-%20edge%20-%20clang%2Cmipsr6%2Cunder%20qemu/builds/989
https://v8.imgtec.com/bbv8/builders/Target%20-%20Debug%20-%20edge%20-%20clang%2Cmipsr6%2Cunder%20qemu/builds/894
https://v8.imgtec.com/bbv8/builders/Target%20-%20MIPS64%20-%20Debug%20-%20edge%20-%20clang%2Cmipsr6%2Cunder%20qemu/builds/814
https://v8.imgtec.com/bbv8/builders/Target%20-%20MIPS64%20-%20Debug%20-%20edge%20-%20clang/builds/1006

The tests started to fail with following CL:
https://chromium-review.googlesource.com/c/v8/v8/+/691834
`Reland "[build] Switch windows default compilation to MSVS 2017"`

This CL introduces new Clang: version `312679-1` is substituted with version `313786-1`.

When a later CL is build with Clang version `312679-1` (for example: `"MIPS: [wasm] Allow traps in tests with many parameters in cctests"`), the test was successful.

Error message in Release mode:
```
=== mjsunit/asm/int32div ===
--- stderr ---
Received signal 11 SEGV_MAPERR 0000ffffffff
```

Error message for Debug mode:
```
=== mjsunit/asm/int32div ===
--- stderr ---
#
# Fatal error in ../../src/compiler/register-allocator-verifier.cc, line 42
# Check failed: Immediately after CommitAssignmentPhase..
#
```

**Comment by ilijapavlovic** [comment]
The error message is created in function `VerifyAllocatedGaps(const Instruction* instr, const char* caller_info)`. 
Content of instruction `instr` is printed for both Clang versions. The checking fails for instruction `Mips64Dsar`.

Instruction's contents:
- successful case:
```
gap () ([t0|R|w32] = [a3|R|t];) 
          [t0|R|w32] = Mips64Dsar [t0|R|w32] [immediate:369]
```
- unsuccessful case:
```
gap () (v6(R) = [a3|R|t];) 
          [t0|R|w32] = Mips64Dsar [a3|R|t] [immediate:369]
```

In unsuccessful case, the test fails in checking a `MoveOperands` object which is not allocated.

**Comment by ilijapavlovic** [comment]
With `--trace-turbo-graph` are collected instruction sequences before register allocations:
```
----- Instruction sequence before register allocation -----   // OK case
...
      16: gap () (v18(R) = v6(-);) 
          v18(1) = Mips64Dsar v18(R) [immediate:369]
...
```
```
----- Instruction sequence before register allocation -----  // Error case
...
      16: gap () (v6(R) = v6(-);) 
          v18(1) = Mips64Dsar v6(R) [immediate:369]
...
```
In error case is used virtual register `v6(R)` instead `v18(R)`.

With flag `--trace-alloc` are collected following logs:

OK case:
```
...
Add to live range 18 use position 70
Add to live range 18 interval [56 70[
Shorten live range 18 to [66
Add to live range 18 use position 66
Add to live range 18 use position 66
Add to live range 18 interval [56 66[
Shorten live range 18 to [65
Add to live range 18 use position 65
Add to live range 6 use position 65
Add to live range 6 interval [56 65[
...
```
Error case:
```
...
Add to live range 282 use position 70
Add to live range 18 use position 70
Add to live range 18 interval [56 70[
Shorten live range 18 to [66
Add to live range 18 use position 66
Add to live range 6 use position 66      // <---- virtual register 6 instead 18!
Add to live range 6 interval [56 66[      // <---- virtual register 6 instead 18!
// ------- no message "Shorten live range ..."; no call to TopLevelLiveRange::ShortenTo()
// ------- no message "Add to live range ..." ; no call to TopLevelLiveRange::AddUseInterval()
Add to live range 6 use position 65
Add to live range 6 interval [56 65[
Shorten live range 278 to [62
Add to live range 278 use position 62
...
```
In error case:
* From some reason is used virtual register `v6` instead `v18`.
* There are no calls ` TopLevelLiveRange::ShortenTo()` and `TopLevelLiveRange::AddUseInterval()`

**Comment by sretenkovacevic** [comment]
These tests are working now, since
 [https://v8.imgtec.com/bbv8/builders/Target%20-%20MIPS64%20-%20edge%20-%20clang/builds/3230](https://v8.imgtec.com/bbv8/builders/Target%20-%20MIPS64%20-%20edge%20-%20clang/builds/3230)

Commit that fixed the failures: [https://chromium-review.googlesource.com/c/v8/v8/+/784472](https://chromium-review.googlesource.com/c/v8/v8/+/784472)

This issue can be closed now.
