### ISSUE TITLE
Bughunting: mjsunit/wasm/multi-value fails on simulator

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#538]
https://v8.imgtec.com/bbv8/builders/Sim%20-%20edge/builds/15714/steps/Check/logs/multi-value

**Comment by IvoMarkovic** [comment]
https://chromium-review.googlesource.com/#/c/v8/v8/+/774286

**Comment by ibogosavljevic** [comment]
Issue fixed https://v8.imgtec.com/bbv8/builders/Sim%20-%20edge/builds/15766
