### ISSUE TITLE
Remove alignment fix ups on builder target boards.

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#54]
Update the kernels on target boards so that alignment fix ups are not done. We do want to have alignment exceptions generated so that tests hard-fail.

This applies to mips buildbot boards, and HJ Jenkins target boards.

**Comment by kilvadyb** [comment]
We can turn off alignment fix ups with a simple wrapper:

```
#include <stdio.h>
#include <unistd.h>
#include <string.h>
#include <errno.h>
#include <sys/sysmips.h>


int main(int argc, char *argv[])
{
    if (argc < 2) {
        printf("usage:\n\t%p <cmd with args>\n", argv[0]);
        return 1;
    }

    sysmips(MIPS_FIXADE, 0);

    execvp(argv[1], argv + 1);
    printf("execvp failed: %d - %s\n", errno, strerror(errno));
    return 1;
}
```

**Comment by kisg** [comment]
@kwan0xfff : Could you please compile a list of the builders that are running without alignment fixups?

**Comment by ibogosavljevic** [comment]
This has been done long time ago. Those test that fail because of unaligned issues will display message "BUS due to misalignment". Closed
