### ISSUE TITLE
Using GN to build MIPS32r6 won't run under QEMU

### ISSUE THREAD

**Issue by MIPSbkirby** [v8mips/v8mips#544]
Using the following script, I'm able to build V8 as a MIPS32r6 binary:
[build-MIPS32r6-with-GN.sh.txt](https://github.com/v8mips/v8mips/files/1493099/build-MIPS32r6-with-GN.sh.txt)

However, when I try to run it under QEMU, it fails to run:
```
$ COMP_BASE=/mips/proj/build-compiler/Codescape-SDK/CentOS/x86_64/IMG/Linux-gnu/2017.10-05
$ LDSO_PATH="${COMP_BASE}/sysroot/mipsel-r6-hard/lib/ld-2.20.so"
$ LD_R_PATH="${COMP_BASE}/sysroot/mipsel-r6-hard/lib:${COMP_BASE}/mips-img-linux-gnu/lib/mipsel-r6-hard/lib"
$ echo 'console.log("hello world")' | /mips/tools/mips/swpkgs/bin/qemu-mipsel-V8-mipsr6-upstream-master-a008535b-with-upstream-patch -cpu mips32r6-generic $LDSO_PATH --library-path $LD_R_PATH  $PWD/fromscratch-MIPS32r6-with-GN/v8/out/Release/d8 
/export/tmp/bkirby/v8-gn-testing/fromscratch-MIPS32r6-with-GN/v8/out/Release/d8: error while loading shared libraries: /export/tmp/bkirby/v8-gn-testing/fromscratch-MIPS32r6-with-GN/v8/out/Release/d8: cannot open shared object file: No such file or directory
```

When building it with the following script using GYP, the rpath and dynamic linker are embedded into the `d8` binary:
[build-MIPS32r6-with-GYP.sh.txt](https://github.com/v8mips/v8mips/files/1493134/build-MIPS32r6-with-GYP.sh.txt)

So, running under QEMU just works as long as no dynamic linker or rpath are specified:
```
$ echo 'console.log("hello world")' | /mips/tools/mips/swpkgs/bin/qemu-mipsel-V8-mipsr6-upstream-master-a008535b-with-upstream-patch -cpu mips32r6-generic $PWD/fromscratch-MIPS32r6-with-embedded-ldso-and-rpath/v8/out/Release/d8           
V8 version 6.4.0 (candidate)
d8> hello world
undefined
d8>
```
I tried a recent version of QEMU (version 2.10.1) as well, but it won't run the GYP version with the embedded rpath and dynamic linker.
```
$ echo 'console.log("hello world")' | qemu/qemu-2.10.1/mipsel-linux-user/qemu-mipsel -cpu mips32r6-generic $LDSO_PATH  $PWD/fromscratch-MIPS32r6-with-embedded-ldso-and-rpath/v8/out/Release/d8
/export/tmp/bkirby/v8-gn-testing/fromscratch-MIPS32r6-with-embedded-ldso-and-rpath/v8/out/Release/d8: error while loading shared libraries: /export/tmp/bkirby/v8-gn-testing/fromscratch-MIPS32r6-with-embedded-ldso-and-rpath/v8/out/Release/d8: cannot open shared object file: No such file or directory
```

**Comment by sretenkovacevic** [comment]
As far as I know, there is no use in exporting LDSO_PATH and LD_R_PATH when compiling using GN, since GN has no mechanism of using them.

In issue #466 there is an example of compiling with specified linker and library path. gcc_rpath is something that is regular part of GN and has same role as LD_R_PATH in GYP, while ldso_path is currently on codereview and for now it can only be used if separate patch is implemented (it can be found in mentioned issue) and it should replace LDSO_PATH from GYP.

Hope I got Your problem right and this was helpful.

**Comment by ibogosavljevic** [comment]
There was a problem with GN and MIPS32R6. The problem was fixed with this patch https://chromium-review.googlesource.com/c/v8/v8/+/806494.

This issue is duplicate of #548. @MIPSbkirby , after confirming that the patch resolved the issue, i.e. number of failures on MIP32R6 GN is comparable to MIPS32R6 GYP, close the issue.

**Comment by MIPSbkirby** [comment]
The issue is that the compiled `d8` binary won't run under QEMU.  The following command fails:
```
echo 'console.log("hello world")' | /mips/tools/mips/swpkgs/bin/qemu-mipsel-V8-mipsr6-upstream-master-a008535b-with-upstream-patch -cpu mips32r6-generic $PWD/fromscratch/v8/out/Release/d8
```

This assumes you've built the `d8` binary with the above attached script.  The patch that @ibogosavljevic mentions doesn't fix this either.  

You can get the same QEMU binary at the URL:
https://dmz-portal.mips.com/dl/qemu-mipsel-V8-mipsr6-upstream-master-a008535b-with-upstream-patch

**Comment by ibogosavljevic** [comment]
@MIPSbkirby : I downloaded and executed the qemu binary, and I had no problems.

Here is what commands I used to compile the program:

```
export PATH=$PATH:/home/ivica/tools/codescape-2016.05-3-mips-img-linux-gnu/2016.05-03/bin
gn gen out.gn/mipsel_debug_clang --args='is_debug=false target_cpu="mipsel" v8_target_cpu="mipsel" mips_arch_variant="r6" is_clang=false target_os="linux" use_sysroot=false use_gold=true  treat_warnings_as_errors=false'
ninja -C out.gn/mipsel_debug_clang/

/home/ivica/Downloads/qemu-mipsel-V8-mipsr6-upstream-master-a008535b-with-upstream-patch -cpu mips32r6-generic -L /home/ivica/tools/codescape-2016.05-3-mips-img-linux-gnu/2016.05-03/sysroot/mipsel-r6-hard -E LD_LIBRARY_PATH=/home/ivica/tools/codescape-2016.05-3-mips-img-linux-gnu/2016.05-03/mips-img-linux-gnu/lib/mipsel-r6-hard/lib out.gn/mipsel_debug_clang/d8
```

**Comment by MIPSbkirby** [comment]
Using the `-L` flag with the sysroot and `-E LD_LIBRARY_PATH` with the rpath set gets it to run correctly.
