### ISSUE TITLE
Bughunting: Add -WUnreachable-code on MIPS 

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#547]
https://chromium-review.googlesource.com/c/v8/v8/+/800291/10/BUILD.gn#508

This flag should be added and all the warnings fixes.

**Comment by ilijapavlovic** [comment]
When `-Wunreachable` flag is used for compilation, the Clang will try to detect a code which will not be executed at all.
In MIPS implementation, it is mostly related in the control flow statements where function `IsMipsArchVariant()` is used. On such places there will be always a block of the code which will not be executed at all.

For fixing this issue it would be necessary to use macro-definitions instead `IsMipsArchVariant()` function.

Example:
```
if (IsMipsArchVariant(kMips32r6)) {
  ...
} else {
  ...
}

```
Previous control flow structure would be replaced with macro-definitions:
```
#ifdef _MIPS_ARCH_MIPS32R6
...
#else
...
#endif
```

Definition of `IsMipsArchVariant()` function:
```
#ifndef _MIPS_ARCH_MIPS32RX
#define IsMipsArchVariant(check) \
  (kArchVariant == check)
#else
#define IsMipsArchVariant(check) \
  (CpuFeatures::IsSupported(static_cast<CpuFeature>(check)))
#endif
```
Function `IsMipsArchVariant()` uses function `CpuFeatures::IsSupported()`, and it's purpose is described in following:
```
// CpuFeatures keeps track of which features are supported by the target CPU.
// Supported features must be enabled by a CpuFeatureScope before use.
// Example:
//   if (assembler->IsSupported(SSE3)) {
//     CpuFeatureScope fscope(assembler, SSE3);
//     // Generate code containing SSE3 instructions.
//   } else {
//     // Generate alternative code.
//   }
```
Using macro-definitions is in conflict with this guideline. Therefore, `IsMipsArchVariant()` will not be substituted with corresponding macro-definitions, and for MIPS32 it will not be possible to use `-Wunreachable` flag with the Clang.
