### ISSUE TITLE
Port:  Support testing Simd128 moves and swaps

### ISSUE THREAD

**Issue by sretenkovacevic** [v8mips/v8mips#551]
Extend the code-generator tests to cover AssembleMove and AssembleSwap with
Simd128 registers and stack slots, for targets that support them.

Link to original CL:
[https://chromium-review.googlesource.com/c/v8/v8/+/728599](https://chromium-review.googlesource.com/c/v8/v8/+/728599)

Porting this might make it easier to locate bugs that prevent these tests from working correctly for other data types, as it was the case on ARM.

**Comment by prudic** [comment]
Porting done in this CL: https://chromium-review.googlesource.com/c/v8/v8/+/906469

**Comment by sretenkovacevic** [comment]
Issue closed.
