### ISSUE TITLE
Cleanup: Prevent trampolines in Ldc1 and Sdc1 in macro-assembler-mips.cc

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#555]
Ldc1 and Sdc1 are complex macro instructions that use temporary registers on MIPS32. Prevent trampolines!

**Comment by ilijapavlovic** [comment]
CL uploaded and ready for review:
https://chromium-review.googlesource.com/c/v8/v8/+/897422

**Comment by ilijapavlovic** [comment]
CL landed.
https://chromium.googlesource.com/v8/v8/+/79645fefd90bdba2d62ceb3c2ce6edf7b68f9b80
