### ISSUE TITLE
Bughunting: inspector/runtime/get-properties fails on MIPS32BE

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#558]
https://v8.imgtec.com/bbv8/builders/Target%20-%20big%20-%20Debug%20-%20edge/builds/11703/steps/Check/logs/get-properties

**Comment by IvoMarkovic** [comment]
After adding expected results for BE and modifying script to parse it:
https://chromium-review.googlesource.com/c/v8/v8/+/880946

Test was changed in order to be byte independent:
https://chromium-review.googlesource.com/c/v8/v8/+/881883

**Comment by ibogosavljevic** [comment]
Resolved.
