### ISSUE TITLE
Bughunting: cctest/test-run-machops/RunWord32EqualAndWord32ShrP fails on MIPS64 simulator

### ISSUE THREAD

**Issue by sretenkovacevic** [v8mips/v8mips#560]
This test started failing with commit [https://chromium-review.googlesource.com/850873](https://chromium-review.googlesource.com/850873)

**Comment by ibogosavljevic** [comment]
After rewriting of simulator code for all architectures, this test started failing on MIPS64. The reason for the failure is that MIPS64 requires that arguments passed by stack needs to be signed-extended even if they are unsigned type

Proposed a CL: https://chromium-review.googlesource.com/c/v8/v8/+/866845, but owners wanted to do the patch themselves: https://chromium-review.googlesource.com/c/v8/v8/+/868651

After the patch landed, issue doesn't appear on build bots anymore: https://v8.imgtec.com/bbv8/builders/Sim%20-%20MIPS64%20-%20edge/builds/12471

Issue closed
