### ISSUE TITLE
Bughunting: Compilation failure on CLANG MIPS64R6 builder

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#565]
https://v8.imgtec.com/bbv8/builders/Target%20-%20MIPS64%20-%20Debug%20-%20edge%20-%20clang%2Cmipsr6%2Cunder%20qemu%20-%20builder/builds/2564/steps/compile/logs/stdio

**Comment by IvoMarkovic** [comment]
Compiler issue reported:
https://dmz-portal.mips.com/bugz/show_bug.cgi?id=2828

**Comment by ibogosavljevic** [comment]
Not reproducible on buildbot anymore: https://v8.imgtec.com/bbv8/builders/Target%20-%20MIPS64%20-%20Debug%20-%20edge%20-%20clang%2Cmipsr6%2Cunder%20qemu%20-%20builder/builds/2802
