### ISSUE TITLE
Bughunting: Test wasm-spec-tests/tests/br_table fails

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#568]
Test wasm-spec-tests/tests/br_table fails

Link to the failure on buildbot: https://v8.imgtec.com/bbv8/builders/Target%20-%20MIPS64%20-%20edge/builds/11002

The failure started to appear after this commit:
https://chromium.googlesource.com/v8/v8/+/2778b46081c6db1090fad409923ec34089bfb910

**Comment by sretenkovacevic** [comment]
CL uploaded and landed [https://chromium-review.googlesource.com/c/v8/v8/+/901883](https://chromium-review.googlesource.com/c/v8/v8/+/901883)

Problem was with AssembleArchLookupSwitch function in code-generator-mips.cc and wrong delay slot usage in it. Same change was made in mips64.

Test passes on buildbots now and this issue can be closed.

[https://v8.imgtec.com/bbv8/builders/Sim%20-%20Debug%20-%20edge%20-%20GYP/builds/1327](https://v8.imgtec.com/bbv8/builders/Sim%20-%20Debug%20-%20edge%20-%20GYP/builds/1327)

**Comment by ibogosavljevic** [comment]
Issue closed
