### ISSUE TITLE
Building r15785 with gcc 4.7 fails.

### ISSUE THREAD

**Issue by kilvadyb** [v8mips/v8mips#57]
In file included from ../src/typing.h:38:0,
                 from ../src/typing.cc:28:
../src/effects.h: In instantiation of ‘void v8::internal::EffectsMixin<Var, Base, Effects>::Seq(Var, v8::internal::Effect) [with Var = int; Base = v8::internal::NestedEffectsBase<int, -2147483648>; Effects = v8::internal::Effects<int, -2147483648>]’:
../src/typing.cc:413:68:   required from here
../src/effects.h:121:5: error: ‘Insert’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]

**Comment by paul99** [comment]
Thanks for getting this on GH issues so quickly. Per my recent email, 4.6.3 works OK.

The error was not introduced with 15785, it came earlier. Per the mips buildbot, 15771 works fine, 15783 fails with this error. Revs in between were broken (or untested) for the port of 15773 that Balázs submitted in 15783.

**Comment by kilvadyb** [comment]
We reproduced the failure with CodeSourcery 4.7.2 and emdebian's mipsel-linux-gnu-g++-4.7 and with g++ 4.7.2 sim build also so it seems from the logs that gcc 4.7 is more sensitive, produces a warning which doesn't come up using earlier versions.

**Comment by paul99** [comment]
Can you guys isolate it to the commit, and see if we can find a fix that will eliminate the warning?

> g++ 4.7.2 sim build also

Does that mean that it will fail to build ia32 or x64 with gcc 4.7? That should raise the priority ;-)

**Comment by palfia** [comment]
The commit

30f09208 r15776 Implement simple effect typing for variables

introduces this failure. The failure is exists on all platforms with gcc 4.7.

Unfortunately, we can't fix this failure ourself, because it is introduced by an arch indep change, so we have to wait for the upstream to fix this failure (or we can try to create a fix and submit to upstream).

**Comment by palfia** [comment]
FYI: This commit is reverted on gbl due to compiler failures.

**Comment by paul99** [comment]
This is no longer an issue, closing.
