### ISSUE TITLE
Bughunting: cctest/test-run-wasm-simd/RunWasm_I32x4AddHoriz_simd_lowered fails on MIPS32 big endian

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#574]
https://v8.imgtec.com/bbv8/builders/Target%20-%20big%20-%20Debug%20-%20edge/builds/12024/steps/Check/logs/RunWasm_I32x4AddHoriz..

**Comment by prudic** [comment]
Added support for big endian for simd lowering for I32x4AddHoriz.
CL: https://chromium-review.googlesource.com/c/v8/v8/+/915064
Issue fixed.

**Comment by ibogosavljevic** [comment]
Closed
