### ISSUE TITLE
Bughunting: cctest/test-isolate-independent-builtins/VerifyBuiltinsIsolateIndependence fails on MIPS32 big endian

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#575]
cctest/test-isolate-independent-builtins/VerifyBuiltinsIsolateIndependence fails on MIPS32 big endian

Link to buildbot: https://v8.imgtec.com/bbv8/builders/Target%20-%20edge%20-%20no%20snapshot/builds/9371/steps/Check/logs/VerifyBuiltinsIsolate..

**Comment by IvoMarkovic** [comment]
After commit:
https://chromium-review.googlesource.com/c/v8/v8/+/923729/11/
test stopped failing.
After that, same test was executed on ARM and result showed that the test fails there as well, so the problem is not MIPS-specific.
