### ISSUE TITLE
How to run mips64 on the loongson3a

### ISSUE THREAD

**Issue by sosohu** [v8mips/v8mips#58]
I tried to compile the v8 with mips64 on the loongson3a in release mode. And the result is the compile is ok, but when I run the v8's benchmark , such errors occurred:
Richards: Error: Error during execution: queueCount = 149, holdCount = 59.
DeltaBlue: ReferenceError: alert is not defined
....
Is not I also need to change some files to support mips64? ( I succeeded in mips3 way)

**Comment by kisg** [comment]
Currently V8 on MIPS only supports MIPS32 OABI and the variation of the MIPS3 OABI used by Loongson. We currently don't support any MIPS64 ABI. As far as I know there are no current plans to support MIPS64 in V8 in the near future.

**Comment by sosohu** [comment]
Ok Thank your for your respond

**Comment by paul99** [comment]
We now have full support for mips64el, which runs fine on the Loongson 3A, and much of that code was contributed by Yuyin at Loongson. Closing this.

Fyi, we also now support mips64 big endian. AKAIK, loongson 3a only runs little endian, but i have onlu used the 3a laptop.
