### ISSUE TITLE
Bughunting: Few tests related to wasm serialization fail on bots without unaligned memory access

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#583]
Few tests related to wasm serialization fail on bots without unaligned memory access:

These are:
mjsunit/regress/regress-430201b
mjsunit/regress/regress-430201
mjsunit/regress/wasm/regress-808012
mjsunit/regress/regress-crbug-781583
mjsunit/regress/wasm/regress-808980
mjsunit/regress/short-circuit
mjsunit/wasm/compiled-module-serialization

Link to failure on buildbots: https://v8.imgtec.com/bbv8/builders/Target%20-%20edge/builds/12631/steps/Check/logs/stdio

**Comment by IvoMarkovic** [comment]
https://chromium-review.googlesource.com/c/v8/v8/+/975547
https://chromium-review.googlesource.com/c/v8/v8/+/939172

**Comment by IvoMarkovic** [comment]
https://chromium-review.googlesource.com/c/v8/v8/+/1013929
