### ISSUE TITLE
Bughunting: cctest/test-isolate-independent-builtins/ByteInRodata fails on BE

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#592]
Link to failure on buildbots: https://logs.chromium.org/v/?s=chromium%2Fbb%2Fclient.v8.ports%2FV8_Mips_-_big_endian_-_nosnap_-_2%2F5186%2F%2B%2Frecipes%2Fsteps%2FCheck%2F0%2Flogs%2FByteInRodata%2F0

https://v8.imgtec.com/bbv8/builders/Target%20-%20big%20-%20edge/builds/16324/steps/Check/logs/ByteInText

**Comment by prudic** [comment]
Issue fixed in this CL: https://chromium-review.googlesource.com/c/v8/v8/+/966287
