### ISSUE TITLE
Bughunting: cctest/test-debug/BreakPointConditionBuiltin fails on all bots

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#593]
https://v8.imgtec.com/bbv8/builders/Sim%20-%20Debug%20-%20edge/builds/16301/steps/Check/logs/BreakPointConditionBu..

**Comment by mkaric** [comment]
The CL https://chromium-review.googlesource.com/c/v8/v8/+/970467 fixed this issue as well.

**Comment by mkaric** [comment]
This is not a mips issue, as discussed in https://bugs.chromium.org/p/v8/issues/detail?id=7449.
