### ISSUE TITLE
Bughunting: mjsunit/harmony/bigint/typedarray fails on Google MIPS32BE buildbot

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#596]
Link to failure on buildbot:
https://logs.chromium.org/v/?s=chromium%2Fbb%2Fclient.v8.ports%2FV8_Mips_-_big_endian_-_nosnap_-_2%2F5227%2F%2B%2Frecipes%2Fsteps%2FCheck%2F0%2Flogs%2Ftypedarray%2F0

**Comment by prudic** [comment]
Fixed bug with this CL: https://chromium-review.googlesource.com/c/v8/v8/+/995455

**Comment by ibogosavljevic** [comment]
Issue not reproduced on buildbot anymore, closed 

https://luci-milo.appspot.com/buildbot/client.v8.ports/V8%20Mips%20-%20big%20endian%20-%20nosnap%20-%202/5324
