### ISSUE TITLE
Bughunting: A few wasm related tests are crashing on all buildbots

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#599]
Link to the failure on buildbot:
https://v8.imgtec.com/bbv8/builders/Sim%20-%20edge/builds/16311

mjsunit/wasm/asm-wasm-stack
mjsunit/regress/wasm/regress-763439
mjsunit/regress/wasm/regress-752423
mjsunit/wasm/table-grow
mjsunit/wasm/indirect-tables
mjsunit/wasm/indirect-calls
mjsunit/wasm/import-memory

**Comment by IvoMarkovic** [comment]
https://chromium-review.googlesource.com/c/v8/v8/+/995435

**Comment by ibogosavljevic** [comment]
Confirmed on buildbot: https://v8.imgtec.com/bbv8/builders/Sim%20-%20edge/builds/16347

Closed
