### ISSUE TITLE
Deprecate sputnik, add test262

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#6]
We have been adding test262 to the builders, but I have just learned that Sputnik test suite is deprecated, and the tests have been incorporated into test262.

So please remove sputnik from your builders and test harnesses.

Info on shutdown is here: http://en.wikipedia.org/wiki/Sputnik_(JavaScript_conformance_test). (I noticed that Google buildbot was not running it, and found this)

See test/test262 in the source tree, and here: http://test262.ecmascript.org/

One issue: test262 revision in v8 source tree changed rev post-3.9 release branch. Depending on your setup, that can complicate regression testing 3.9. 

test.py has an option to grab the test data: --download-data. It seems broken for me on the older rev of test262 in 3.9 branch.

For now, assigned to Gergely to update the Jenkins tester at HJ.

**Comment by paul99** [comment]
I think this was all handled for the HJ Jenkins builder. Gergely, please confirm, and close this issue if appropriate.

Per recent discussions, please sure test262 is also run in debug mode, at least once a week.

**Comment by kisg** [comment]
Ákos: please confirm and close if done.

**Comment by kisg** [comment]
Done.
