### ISSUE TITLE
Performance regression alerts from Jenkins

### ISSUE THREAD

**Issue by kisg** [v8mips/v8mips#60]
Set up performance regression alerts from Jenkins.

One feasible solution is:
- Import performance graph data from Jenkins to Google Spreadsheet by a Google Script
- Use a Google Script to check for regressions and send out alerts
- Create a shell script that can be run from cron to download the spreadsheet periodically for backup
- Track only trunk and stable branches

**Comment by palfia** [comment]
- The importer and updater part of this is done.
- Auto-backup and regression checker is still missing.
