### ISSUE TITLE
Bughunting: A few SIMD related buildbots fail on BE bots

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#602]
https://build.chromium.org/p/client.v8.ports/builders/V8%20Mips%20-%20big%20endian%20-%20nosnap%20-%202/builds/5296

List of tests that fail:
Done running cctest/test-run-wasm-simd/RunWasm_S16x8Dup_simd_lowered: FAIL
Done running cctest/test-run-wasm-simd/RunWasm_S16x8UnzipLeft_simd_lowered: FAIL
Done running cctest/test-run-wasm-simd/RunWasm_S16x8TransposeLeft_simd_lowered: FAIL
Done running cctest/test-run-wasm-simd/RunWasm_S16x8ZipLeft_simd_lowered: FAIL
Done running cctest/test-run-wasm-simd/RunWasm_S32x4Irregular_simd_lowered: FAIL
Done running cctest/test-run-wasm-simd/RunWasm_S32x4TransposeRight_simd_lowered: FAIL
Done running cctest/test-run-wasm-simd/RunWasm_S32x4ZipRight_simd_lowered: FAIL
Done running cctest/test-run-wasm-simd/RunWasm_S32x4UnzipRight_simd_lowered: FAIL
Done running cctest/test-run-wasm-simd/RunWasm_S8x16Dup_simd_lowered: FAIL
Done running cctest/test-run-wasm-simd/RunWasm_S8x16UnzipLeft_simd_lowered: FAIL
Done running cctest/test-run-wasm-simd/RunWasm_S8x16TransposeLeft_simd_lowered: FAIL
Done running cctest/test-run-wasm-simd/RunWasm_S8x16ZipLeft_simd_lowered: FAIL

**Comment by prudic** [comment]
Fixed issue with this CL: https://chromium-review.googlesource.com/c/v8/v8/+/988012

**Comment by ibogosavljevic** [comment]
Issue does not reproduce on buildbotd anymore: https://build.chromium.org/p/client.v8.ports/builders/V8%20Mips%20-%20big%20endian%20-%20nosnap%20-%202/builds/5325

Closed.
