### ISSUE TITLE
Bughunting: unittests/InterpreterAssemblerTest.BytecodeOperand fails everywhere

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#604]
Link to failure on buildbots:
https://v8.imgtec.com/bbv8/builders/Sim%20-%20Debug%20-%20edge/builds/16366/steps/Unittests/logs/InterpreterAssemblerT..

**Comment by mkaric** [comment]
Fixed by https://chromium-review.googlesource.com/c/v8/v8/+/1018902, closing.
