### ISSUE TITLE
Bughunting: unittests/ValueSerializerTest.DecodeBigInt fails on all buildbots

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#607]
https://v8.imgtec.com/bbv8/builders/Target%20-%20big%20-%20edge/builds/16564/steps/Check/logs/stdio

**Comment by prudic** [comment]
Issue fixed by adding big endian support for BigInts serialization.
CL: https://chromium-review.googlesource.com/c/v8/v8/+/1023418
