### ISSUE TITLE
Bughunting: FuzzAssembleMove[AndSwap] fail on all buildbots

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#609]
Link to the first time failure appeared on buildbots:
https://v8.imgtec.com/bbv8/builders/Sim%20-%20MIPS64%20-%20edge/builds/12794/steps/Check/logs/stdio

Done running cctest/test-code-generator/FuzzAssembleMoveAndSwap: FAIL
Done running cctest/test-code-generator/FuzzAssembleMove: FAIL

**Comment by IvoMarkovic** [comment]
https://chromium-review.googlesource.com/c/v8/v8/+/1013925

**Comment by IvoMarkovic** [comment]
After this commit, there is no more issues with this two tests.
https://v8.imgtec.com/bbv8/builders/Sim%20-%20MIPS64%20-%20edge/builds/12836/
