### ISSUE TITLE
Bughunting: mjsunit/constant-folding-2 fails on bigendian bots

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#613]
https://v8.imgtec.com/bbv8/builders/Target%20-%20big%20-%20edge/builds/16686/steps/Check/logs/constant-folding-2

**Comment by mkaric** [comment]
This has been fixed in https://chromium-review.googlesource.com/c/v8/v8/+/1012460.

**Comment by ibogosavljevic** [comment]
Closed
