### ISSUE TITLE
Performance: Call to C runtime instead of bailing out on MIPS32 Floor_d_d, Ceil_d_d, Trunc_d_d and Round_d_d implementations

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#615]
In https://chromium-review.googlesource.com/c/v8/v8/+/1009908/2/src/wasm/baseline/mips/liftoff-assembler-mips.h#699, we bail out to turbofan if the FPU is in FP32 mode. Better solution would be to calculate this value using C function, similar as it is done here:  (see e.g. EmitI32UnOpWithCFallback in liftoff-compiler.cc).

**Comment by prudic** [comment]
Implemented C runtime function call for  Floor_d_d, Ceil_d_d, Trunc_d_d and Round_d_d on mips32 fp32:
https://chromium-review.googlesource.com/c/v8/v8/+/1044187

**Comment by ibogosavljevic** [comment]
Issue closed
