### ISSUE TITLE
easy landing script

### ISSUE THREAD

**Issue by kisg** [v8mips/v8mips#62]
If a non-commiter's CL is approved by one of the MIPS owners, the CL has to be landed by a committer or the owner itself. Currently this is a manual process. 

A script should be created which (given a CL URL) can land a CL automatically.

**Comment by palfia** [comment]
I think, we can close this ticket, since git cl patch does this job well. What do you think?

**Comment by kisg** [comment]
Let's document git cl patch usage in our wiki, and I think it can be closed as well after that.

Do you agree Paul?

**Comment by paul99** [comment]
Agreed. Please update the wiki and we can close this.

**Comment by palfia** [comment]
Done.
