### ISSUE TITLE
Bughunting: mjsunit/skipping-inner-functions fails on BE

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#623]
Link to failure on buildbot:

https://v8.imgtec.com/bbv8/builders/Target%20-%20big%20-%20Debug%20-%20edge/builds/12618/steps/Check/logs/skipping-inner-functi..

**Comment by prudic** [comment]
Issue fixed:
https://chromium-review.googlesource.com/c/v8/v8/+/1029954
