### ISSUE TITLE
Bughunting: RunWasmLiftoff_I64ShrUOnDifferentRegisters fails on all buildbots

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#629]
Link to the failure on bildbot: https://v8.imgtec.com/bbv8/builders/Sim%20-%20edge/builds/16444

cctest/test-run-wasm/RunWasmLiftoff_I64ShrUOnDifferentRegisters
cctest/test-run-wasm/RunWasmLiftoff_I64ShlOnDifferentRegisters

**Comment by mkaric** [comment]
The problem occurs when getting an unused register causes spilling, but the generated code is not executed because of a branch, resulting in loss of data.

Uploaded a fix CL:
https://chromium-review.googlesource.com/c/v8/v8/+/1060213

**Comment by mkaric** [comment]
Landed, closing.
