### ISSUE TITLE
Bughunting: cctest/test-orderedhashtable/SmallOrderedHash* fails on MIPS32BE

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#631]
Link to failure on buildbot:

https://v8.imgtec.com/bbv8/builders/Target%20-%20big%20-%20Debug%20-%20edge/builds/12722

**Comment by IvoMarkovic** [comment]
After commit:
https://chromium-review.googlesource.com/c/v8/v8/+/1047957
tests are not failing any more.
Solution is in file:
https://chromium-review.googlesource.com/c/v8/v8/+/1047957/5/src/objects-body-descriptors-inl.h
Offset and iteration through the table were changed.

**Comment by ibogosavljevic** [comment]
Not reproduced on buildbot anymore, issue closed: https://v8.imgtec.com/bbv8/builders/Target%20-%20big%20-%20Debug%20-%20edge/builds/12786
