### ISSUE TITLE
Bughunting: cctest/test-code-generator/FuzzAssembleMove fails on MIPS64BE in debug mode

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#636]
Link to failure on buildbot: https://v8.imgtec.com/bbv8/builders/Target%20-%20MIPS64%20-%20big%20-%20Debug%20-%20edge/builds/2651/steps/Check/logs/FuzzAssembleMove

**Comment by prudic** [comment]
Issue fixed: https://chromium-review.googlesource.com/c/v8/v8/+/1078755
