### ISSUE TITLE
Bughunting: Compilation failure on MIPS64R6 with CLANG

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#649]
Link to failure on buidlbot: https://v8.imgtec.com/bbv8/builders/Target%20-%20MIPS64%20-%20Debug%20-%20edge%20-%20clang%2Cmipsr6%2Cunder%20qemu%20-%20builder/builds/2903/steps/compile/logs/stdio

**Comment by mkaric** [comment]
This is caused by a problem in CLANG, and it has been fixed in a newer version ([r332977](https://reviews.llvm.org/rL332977)). I will leave this open until a fixed version of CLANG is rolled into v8 and we confirm the builder is working properly.

**Comment by mkaric** [comment]
New version of CLANG rolled, closing.
