### ISSUE TITLE
Porting: Port "[wasm] Introduce jump table"

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#654]
Port https://chromium.googlesource.com/v8/v8/+/733b7c8258872dbbb44222831694c5f6b69424ab

**Comment by prudic** [comment]
Porting landed: https://chromium-review.googlesource.com/c/v8/v8/+/1107630

**Comment by prudic** [comment]
Fixed port for MIPS r6 : https://chromium-review.googlesource.com/c/v8/v8/+/1120182

**Comment by ibogosavljevic** [comment]
Closed
