### ISSUE TITLE
Bughunting: Builder failures with Print function

### ISSUE THREAD

**Issue by sretenkovacevic** [v8mips/v8mips#655]
Builders failing since commit [https://chromium-review.googlesource.com/c/v8/v8/+/1112001](https://chromium-review.googlesource.com/c/v8/v8/+/1112001).

All builders are failing.

**Comment by ibogosavljevic** [comment]
Issue resolved with CL: https://chromium-review.googlesource.com/c/v8/v8/+/1116965

Doesn't reproduce on buildbots anymore
