### ISSUE TITLE
Bughunting: Compilation failure on MIPS32 BE buildbots

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#657]
Link to failure on buildbots: https://v8.imgtec.com/bbv8/builders/Target%20-%20big%20-%20Debug%20-%20edge%20-%20builder/builds/18560

**Comment by prudic** [comment]
This failure is related to #652. Just extended solution for MIPS32: https://chromium-review.googlesource.com/c/v8/v8/+/1117186
