### ISSUE TITLE
New Feature: Make BranchLong PIC

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#661]
Currently, BranchLong macro instructions are not PIC. We use J on MIPS64 and LUI/ORI/JR on MIPS32 in order to save instructions. However, we need to have BranchLong position independent in order to enable PIC code in builtins.

Similar code has already been implemented in trampolines: https://chromium-review.googlesource.com/c/v8/v8/+/1128964/5/src/mips/assembler-mips.cc#3838

**Comment by prudic** [comment]
List of CLs that made BranchLong PIC and optimized:
https://chromium-review.googlesource.com/c/v8/v8/+/1152810
https://chromium-review.googlesource.com/c/v8/v8/+/1165082
https://chromium-review.googlesource.com/c/v8/v8/+/1163513
https://chromium-review.googlesource.com/c/v8/v8/+/1170777
