### ISSUE TITLE
failing mozilla test ecma/Array/15.4.4.2.js

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#68]
This test fails on HW only in debug mode. The failure is NaN related.

Ákos or Balázs, can you please take a look?

```
out/mipsel.debug/d8 --test --stress-opt --always-opt --nobreak-on-abort --nodead-code-elimination --nofold-constants --enable-slow-asserts --debug-code --verify-heap --expose-gc test/mozilla/mozilla-shell-emulation.js test/mozilla/data/shell.js test/mozilla/data/ecma/shell.js test/mozilla/data/ecma/Array/shell.js test/mozilla/data/ecma/Array/15.4.4.2.js


....
# 
# Fatal error in ../src/objects-debug.cc, line 442
# CHECK(!std::isnan(value) || (BitCast<uint64_t>(value) == BitCast<uint64_t>(canonical_not_the_hole_nan_as_double())) || ((BitCast<uint64_t>(value) & Double::kSignMask) != 0)) failed
#
```

**Comment by kilvadyb** [comment]
The problem is that an Intel (0x8000....0) NaN is used in the test not a MIPS (0x7ff...) one. Usually errors like this comes from C++ code when it generates the NaN value although I haven't found the guilty function yet.

**Comment by kilvadyb** [comment]
I found the problem. When the snapshot is made then
LCodeGen::DoStoreKeyedFixedDoubleArray(LStoreKeyed\* instr) is "precompiled" by the tools_gyp_v8_gyp_v8_snapshot_host_run_mksnapshot command. The following NaN values are compiled in:
nan: nan, 0x7ff80000:0
(I added a short print code:
    double nan = FixedDoubleArray::canonical_not_the_hole_nan_as_double();
    uint64_t c = BitCast<uint64_t>(nan);
    fprintf(stderr, "nan: %f, 0x%x:%x\n", nan, (uint32_t)(c >> 32), (uint32_t)(c & 0xffffffff));
)

When the objects-debug.cc's verify code is executed it compares the NaN to FixedDoubleArray::canonical_not_the_hole_nan_as_double() also but that function returns with:
nan: nan, 0x7ff7ffff:ffffffff

I try to find out why tools_gyp_v8_gyp_v8_snapshot_host_run_mksnapshot is used and not tools_gyp_v8_gyp_v8_snapshot_target_run_mksnapshot or how could be the NaN value of the target being used.

**Comment by kilvadyb** [comment]
I found the problem. When the snapshot is made then
LCodeGen::DoStoreKeyedFixedDoubleArray(LStoreKeyed\* instr) is "precompiled" by the tools_gyp_v8_gyp_v8_snapshot_host_run_mksnapshot command. The following NaN values are compiled in:
nan: nan, 0x7ff80000:0
(I added a short print code:
    double nan = FixedDoubleArray::canonical_not_the_hole_nan_as_double();
    uint64_t c = BitCast<uint64_t>(nan);
    fprintf(stderr, "nan: %f, 0x%x:%x\n", nan, (uint32_t)(c >> 32), (uint32_t)(c & 0xffffffff));
)

When the objects-debug.cc's verify code executed it compares the NaN to FixedDoubleArray::canonical_not_the_hole_nan_as_double() also but it returns with:
nan: nan, 0x7ff7ffff:ffffffff

**Comment by kilvadyb** [comment]
I added the following patch to src/platform-posix.cc.

```
double OS::nan_value() {
#if defined(V8_TARGET_ARCH_MIPS) && !defined(V8_HOST_ARCH_MIPS)
    union conversion {
      double d;
      uint32_t u[2];.
    } c;
    c.u[0] = 0x7ff7ffff;
    c.u[1] = 0xffffffff;
    return c.d;
#else
  // NAN from math.h is defined in C99 and not in POSIX.
  return NAN;
#endif
}
```

The ecma/Array/15.4.4.2.js test passes with it.

**Comment by paul99** [comment]
Thanks Balázs! Can you find out when this bug was introduced, because we "used to" pass Mozilla debug builds. I fear that we have been negligent in our testing recently. But I am pretty sure this used to work for MIPS with snapshots.

**Comment by kilvadyb** [comment]
This bug was introduced with r14692 (510fcef). That CL set the default of FLAG_optimize_constructed_arrays to true:

```
--- a/src/flag-definitions.h
+++ b/src/flag-definitions.h
@@ -258,7 +258,7 @@ DEFINE_bool(unreachable_code_elimination, false,
             "eliminate unreachable code (hidden behind soft deopts)")
 DEFINE_bool(track_allocation_sites, true,
             "Use allocation site info to reduce transitions")
-DEFINE_bool(optimize_constructed_arrays, false,
+DEFINE_bool(optimize_constructed_arrays, true,
             "Use allocation site info on constructed arrays")
 DEFINE_bool(trace_osr, false, "trace on-stack replacement")
 DEFINE_int(stress_runs, 0, "number of stress runs")
```

If FLAG_optimize_constructed_arrays is true then

```
LCodeGen::DoStoreKeyedFixedDoubleArray(LStoreKeyed* instr)
```

 is compiled into the snapshot lib with a host (x64) specified nan value.

I found the following solution only although it seems to be a hack and later might cause problems on simulator:

Using MIPS specific NaN when we compile for target (mksnapshot uses the simulator and I did not find a way to check if we compile for simulator or HW at that point):

```
#if defined(V8_TARGET_ARCH_MIPS)
  union conversion {
    double d;
    uint32_t u[2];
  } c;
  c.u[0] = 0x7ff7ffff;
  c.u[1] = 0xffffffff;
  return c.d;
#else
  // NAN from math.h is defined in C99 and not in POSIX.
  return NAN;
#endif
```

This patch can be added to FixedDoubleArray::canonical_not_the_hole_nan_as_double() or OS::nan_value(). This solution might cause a problem if during the mksnapshot compilation a C math function of the host is called with a MIPS NaN parameter. I could not run full tests in debug mode on our board as it quits at 84% of mjsunits after half a day or so.

**Comment by paul99** [comment]
Balazs had sent the following by email on 2014-01-24:

I made an initial patch to solve the NaN problem. Please take a look:
https://codereview.chromium.org/146953002/

So the problem is: mksnapshot links in libs compiled in simulator mode and they uses host (ia32) specific NaN value while the v8 running on a target board needs a MIPS specific NaN.

I will check why v8.host/libsnapshot.a is linked instead of v8.target/libsnapshot.a. That would be a better solution then this patch.

**Comment by dusmil** [comment]
Here is the simple and elegant fix for this:

https://codereview.chromium.org/150663009

We really do want to have embedded constants in code that comes from snapshot.
As I have described we can use global Nan that is by its definition same as canonical NaN, and which is set up to be MIPS QNaN during bootstrap phase when snapshot is de-serialized and builtins are installed.

**Comment by paul99** [comment]
The fix was landed as r19118. It does seem to fix the Mozilla NaN problem. But there are others.

See: https://dmz-portal.mips.com/bbv8/builders/Target%20-%20Debug%20-%20edge%20-%20test262/builds/98/steps/Test262/logs/stdio

One example:

```
=== test262/15.4.4.15-8-b-ii-4 ===
============ Stress 1/2 ============
============ Stress 2/2 ============
======== Full Deoptimization =======
#
# Fatal error in ../src/objects-debug.cc, line 398
# CHECK(!std::isnan(value) || (BitCast<uint64_t>(value) == BitCast<uint64_t>(canonical_not_the_hole_nan_as_double())) || ((BitCast<uint64_t>(value) & Double::kSignMask) != 0)) failed
#

==== C stack trace ===============================

 1: ??
 2: ??
Command: /export/bbv8-slave-target-6/bbv8/build/slave/v8-linux-mipsel-debug-target-edge-test262/build/v8/out/Debug/d8 --test --stress-opt --always-opt --nobreak-on-abort --nodead-code-elimination --nofold-constants --enable-slow-asserts --debug-code --verify-heap /export/bbv8-slave-target-6/bbv8/build/slave/v8-linux-mipsel-debug-target-edge-test262/build/v8/test/test262/data/test/harness/sta.js /export/bbv8-slave-target-6/bbv8/build/slave/v8-linux-mipsel-debug-target-edge-test262/build/v8/test/test262/data/test/harness/testBuiltInObject.js /export/bbv8-slave-target-6/bbv8/build/slave/v8-linux-mipsel-debug-target-edge-test262/build/v8/test/test262/data/test/harness/testIntl.js /export/bbv8-slave-target-6/bbv8/build/slave/v8-linux-mipsel-debug-target-edge-test262/build/v8/test/test262/harness-adapt.js /export/bbv8-slave-target-6/bbv8/build/slave/v8-linux-mipsel-debug-target-edge-test262/build/v8/test/test262/data/test/suite/ch15/15.4/15.4.4/15.4.4.15/15.4.4.15-8-b-ii-4.js
```

There are also about 30 NaN related failures in debug make check:
https://dmz-portal.mips.com/bbv8/builders/Target%20-%20Debug%20-%20edge/builds/151/steps/Check/logs/stdio

Both of these revs should have the fix that landed yesterday.

**Comment by kilvadyb** [comment]
During the test writing I found that in

```
void MacroAssembler::StoreNumberToDoubleElements(Register value_reg,
                                                 Register key_reg,
                                                 Register elements_reg,
                                                 Register scratch1,
                                                 Register scratch2,
                                                 Register scratch3,
                                                 Label* fail,
                                                 int elements_offset) {
```

function there is a suspicious code part:

```
  // Load canonical NaN for storing into the double array.
  uint64_t nan_int64 = BitCast<uint64_t>(
      FixedDoubleArray::canonical_not_the_hole_nan_as_double());
  li(mantissa_reg, Operand(static_cast<uint32_t>(nan_int64)));
  li(exponent_reg, Operand(static_cast<uint32_t>(nan_int64 >> 32)));
  jmp(&have_double_value);
```

If this function is used by a function which is "precompiled" to the snapshot lib then the same problem might come up.

**Comment by paul99** [comment]
Nice find! Do you have the time to try adapting Dusan's change in r19118 (using LoadRoot) to this spot, and try some of the failing tests?

**Comment by kilvadyb** [comment]
Like this backtrace:

```
(gdb) bt
#0  v8::internal::MacroAssembler::StoreNumberToDoubleElements (this=0x7fff62b8, value_reg=..., key_reg=..., 
    elements_reg=..., scratch1=..., scratch2=..., scratch3=..., fail=0x7fff404c, elements_offset=0)
    at ../src/mips/macro-assembler-mips.cc:3436
#1  0x01003aa8 in v8::internal::KeyedStoreGenerateGenericHelper (masm=0x7fff62b8, fast_object=0x7fff41b8, 
    fast_double=0x7fff41c8, slow=0x7fff41b0, check_map=v8::internal::kCheckMap, 
    increment_length=v8::internal::kDontIncrementLength, value=..., key=..., receiver=..., receiver_map=..., 
    elements_map=..., elements=...) at ../src/mips/ic-mips.cc:937
#2  0x01004600 in v8::internal::KeyedStoreIC::GenerateGeneric (masm=0x7fff62b8, strict_mode=v8::internal::kNonStrictMode)
    at ../src/mips/ic-mips.cc:1083
#3  0x00ac2660 in v8::internal::Generate_KeyedStoreIC_Generic (masm=0x7fff62b8) at ../src/builtins.cc:1394
#4  0x00ac57a4 in v8::internal::Builtins::SetUp (this=0x29343c4, isolate=0x2931988, create_heap_objects=true)
    at ../src/builtins.cc:1642
#5  0x00d12f98 in v8::internal::Isolate::Init (this=0x2931988, des=0x0) at ../src/isolate.cc:2006
#6  0x00f90044 in v8::internal::V8::Initialize (des=0x0) at ../src/v8.cc:87
#7  0x00a44c7c in v8::InitializeHelper (isolate=0x2931988) at ../src/api.cc:239
#8  0x00a44cd8 in v8::EnsureInitializedForIsolate (isolate=0x2931988, location=0x1db82a4 "v8::Context::New()")
    at ../src/api.cc:246
#9  0x00a60dd4 in v8::Context::New (external_isolate=0x2931988, extensions=0x0, global_template=..., global_object=...)
    at ../src/api.cc:5136
```

As I remember the last functions of the trace are called from the mksnapshot code also.

Yes, I'm going to try out Dusan's solution for this function.

**Comment by kilvadyb** [comment]
I uploaded a CL which seems to work, at least it fixes the fail of the test262/15.4.4.15-8-b-ii-4:
https://codereview.chromium.org/156803003/
To run all the test262 tests on a board in debug and release mode takes some time.

**Comment by paul99** [comment]
Thanks Balázs, I suspect this is correct. But I'd like to have you guys do just a bit more testing before we land this. I suspect you are done for the day, but Ákos, do you think you could run a few of the tests manually in debug mode on a board?

If you look at these two log files, you can find many NaN related errors. Can you run 10 or so of those as a sample to be certain this is working? If so, I will approve and land this CL.

https://dmz-portal.mips.com/bbv8/builders/Target%20-%20Debug%20-%20edge/builds/151/steps/Check/logs/stdio

https://dmz-portal.mips.com/bbv8/builders/Target%20-%20Debug%20-%20edge%20-%20test262/builds/98/steps/Test262/logs/stdio

**Comment by kilvadyb** [comment]
I started the test262 tests in debug mode on our broadcom board, hopefully tomorrow we will see a full log. If Ákos can do a few test manually that is quicker.

**Comment by paul99** [comment]
Yes, I am hoping to land this change today, so running a few manual tests would be very helpful.

I don't have a board available to me right now, they are all on the bots ;-)

**Comment by palfia** [comment]
I've extracted the failing tests from the logfiles with a grep/sed command and created a shell script which executes only these tests. Now the tests are running on the popcorn board. It's good so far.

**Comment by palfia** [comment]
Every test failure (mjsunit&test262) is fixed by Balázs's patch.

**Comment by paul99** [comment]
Committed https://codereview.chromium.org/156803003/ as r19175. This should fix everything. Closing issue (will reopen if some tests fail.) Thanks everyone!!
