### ISSUE TITLE
Investigate ARM deopt jump table

### ISSUE THREAD

**Issue by kalmard** [v8mips/v8mips#7]
Commit ab8e3bd924 added the LCodeGen::GenerateDeoptJumpTable() on ARM. This is _very_ similar to our trampoline pool. What it essentially does is creating a jump table after crankshaft code has been generated specifically for deoptimization jumps. Since it uses pc-relative loads it cannot be easily translated to MIPS.

I never fully understood how this is an optimization. Here are a few guesses (with the assumption that deoptimizer jumps are not taken far more often than they are taken):
1. it may save a few instructions by not pre-loading the target address
2. it may save a few instructions and possibly utilize the I-cache slightly better by removing the pointer constant from the executed code and placing it elsewhere
3. related to the previous point, it may save memory by re-using jump addresses

An optimization similar to 1. is active on MIPS in MacroAssembler::Jump.
As for 2. and 3. these are valid points but I'm not sure they would create an actual, measureable difference in speed. The memory saved by re-using addresses is most likely lost because of the need for a separate jump table.

Obviously I could have missed something, an other benefit or technique that MIPS could use.

**Comment by paul99** [comment]
I think the ideas here, though good at the time, are well out of date. The deopt jump tables have changed a few times, and I know Dusan did some optimizations there. 

I will close this now, but feel free to reopen, or create new issue, if better ideas come up.
