### ISSUE TITLE
Small improvement to r19040, unroll push loop

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#71]
The argument pushing loop of static void GenerateFastApiCall() should be unrolled, since our push includes a stack adjust as separate instruction:

```
for (int i = 0; i < argc; i++) {
  Register arg = values[argc-1-i];
  ASSERT(!receiver.is(arg));
  ASSERT(!scratch_in.is(arg));
  __ push(arg);
}
```

Maybe you can take a look thru this file for similar optimization opportuntiies.

Normally I would request this via code-review, but r19040 fixed the build, works as is, and I thought we might lose a day due to timezone diffs.

**Comment by palfia** [comment]
I've quickly gone through all files and I've uploaded a CL: https://codereview.chromium.org/145973015/

**Comment by paul99** [comment]
Committed patchset #5 manually as r19042. Thanks Ákos!! Closing.
