### ISSUE TITLE
investigate webkit & test262 failures

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#73]
There are a couple fails on the bot, when running on boards:

=== webkit/dfg-ensure-non-array-array-storage-on-window ===
=== test262/15.2.3.6-4-178 ===

Here are logs for the failing revs, can you guys please investigate? It's possible these are intermittent.

https://dmz-portal.mips.com/bbv8/builders/Target%20-%20edge%20-%20webkit/builds/683/steps/WebKit/logs/stdio

https://dmz-portal.mips.com/bbv8/builders/Target%20-%20edge%20-%20test262/builds/543/steps/Test262/logs/stdio

**Comment by palfia** [comment]
I tried to reproduce the test262/15.2.3.6-4-178 failure on several boards but it always passes. It even works when I start the test in an infinite loop.

**Comment by paul99** [comment]
It may be that we have a flaky board or boards. Here is another make check run that has 3 failures, can you also compare those to running on your board?

https://dmz-portal.mips.com/bbv8/builders/Target%20-%20Debug%20-%20edge/builds/157/steps/Check/logs/stdio

Also, assuming that these pass for you, can you look thru the buildbot logs and see if you can correlate these seemingly random failures with a particular board, or other configuration?

**Comment by palfia** [comment]
Short summary:
- The mjsunit/d8-performance-now also fails on our side with the same error, it needs investigation.
- The mjsunit/regress/regress-2790 failure is a timeout, it runs veeery long, but it passes.
- The cctest/test-cpu-profiler/CollectCpuProfile is slow, but passes on our side, this may be a flaky test, I will try to reproduce it.

**Comment by kisg** [comment]
We have not seen these issues for a long time, closing for now. A new issue will be opened if the problem pops up again.
