### ISSUE TITLE
Release tests trigger trace-sim in cctest, and possibly also in mjsunit

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#77]
Release mode tests trigger a bug where --trace-sim mode is erroneously enabled in a long-running test, resulting in millions of extra lines (traced instructions) in the log file. It wastes time and log space. We cannot enable release mode on the bots, until this fixed.

It does not happen in debug mode. 

I've seen this several times on cctest, and thought I saw it happen on mjsunit test, but I cannot repro, so I may have been mistaken. I am not certain if this happens every time that cctest is run in release sim mode.

**Comment by paul99** [comment]
It did happen on mjsunit when tests were 99% done, waiting for the last few slow ones to finish:

```
=== mjsunit/regress/regress-2185-2 ===                                 
============ Stress 1/5 ============
Short 2826ms
random 3195ms
up 3263ms
down 3010ms
saw 1000 1749ms
saw 500 1417ms
saw 200 1222ms
saw 200 symmetric 1391ms
saw 200 down 1161ms
up, down 9220ms
up, up 9810ms
down, down 10518ms
down, up 9081ms
============ Stress 2/5 ============
Short 2095ms
random 2454ms
up 2360ms
down 2326ms
saw 1000 1914ms
saw 500 1756ms
saw 200 1786ms
saw 200 symmetric 1579ms
saw 200 down 1442ms
up, down 9432ms
up, up 10375ms
down, down 8083ms
down, up 4666ms
============ Stress 3/5 ============
Short 1417ms
random 1516ms
up 1556ms
down 1564ms
saw 1000 1005ms
saw 500 859ms
saw 200 878ms
saw 200 symmetric 750ms
saw 200 down 687ms
up, down 4480ms
up, up 5080ms
down, down 5600ms
down, up 4408ms
============ Stress 4/5 ============
Short 1279ms
random 1405ms
up 1390ms
down 1395ms
saw 1000 887ms
saw 500 763ms
saw 200 777ms
saw 200 symmetric 686ms
saw 200 down 631ms
  0x5261a588  0014a438       dsll    s4, s4, 16              0000ffffffff0000
  0x5261a58c  36948000       ori     s4, s4, 0x8000          0000ffffffff8000
  0x5261a590  0014a438       dsll    s4, s4, 16              ffffffff80000000
  0x5261a594  36940000       ori     s4, s4, 0x0             ffffffff80000000
  0x5261a598  0134082a       slt     at, t1, s4              0000000000000000
  0x5261a59c  142005e9       bne     at, zero_reg, 1513      
  0x5261a5a4  ffc9fea0       sd      t1, -352(fp)            000000000000575c --> [00007fb545adf8e8]    (6)
  0x5261a5a8  11270206       beq     t1, a3, 518             
  0x5261a5b0  dcd3ffff       ld      s3, -1(a2)              000000002d51adc9 <-- [0000000041029f38]    (8)
  0x5261a5b4  3c010000       lui     at, 0x0                 0000000000000000
  0x5261a5b8  34210000       ori     at, at, 0x0             0000000000000000
  0x5261a5bc  00010c38       dsll    at, at, 16              0000000000000000

 .... and this goes on for what seems like millions of instructions ..... 
```

**Comment by xwafish** [comment]
This did not happen when I run mjsunit/regress/regress-2185-2 with mips64.release/d8, but it happened when I run benchmark/run.js. both use mips64.release/d8 and mips64.debug/d8. Looks like trace_sim is enabled at simulator-mips64.cc: 3033, icount_ overflowed, if I changed
if (icount_ == ::v8::internale::FLAG_trace_sim_at) to
if ((icount_ == ::v8::internale::FLAG_trace_sim_at) && (icount_ !=0))
mips64.release/d8 run.js will work ok.  mips64.debug/d8 run.js also work ok, but it takes so long time.

so we shounld fix the implemention of FLAG_trace_sim_at.
maybe we shounld take icount_  as a long long type, and also ::v8::internale::FLAG_trace_sim_at?

**Comment by paul99** [comment]
Thanks for the analysis. Yes, I will change count_ and the flag to 64-bit.

**Comment by paul99** [comment]
Fixed in https://github.com/paul99/v8m-rb/commit/ad66b81c97f3fdd53f0cba4c3e7e07b48246de6f

As mentioned in commit message, I just changed `icount_` to int64_t and cast the flag to int64 on use. That limits the trace-sim-at value to be < 2^31, since it is an int. That fits OK, with my use-cases. Please let me know if you need a bigger number. If we need to increase it, we can reopen this issue.

Closing.
