### ISSUE TITLE
Fix compiler warnings for mips64

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#78]
There are a lot of warnings generated. Most are due to two things:
1. Dodgy use of __int128 in the simulator, to support multiplication using hi/lo regs.

That should be re-worked, as I don't think its necessary. But if it is, we should find a way to do it in C that won't be complained about. Or, at the last resort, if this cannot be fixed properly, turn off the warning.
1. Some cctest usage of 'LL' constants, which gcc complains about for some reason:
   
    ../test/cctest/test-assembler-mips64.cc:1406:12: warning: use of C++0x long long integer constant [-Wlong-long]
    CHECK_EQ(0x0000000099aabbccLL, t.r6);
2. Some printf/scanf format string problems.

**Comment by paul99** [comment]
Warnings in sim are fixed with 2008ee4c, MIPS64: Silence all warnings in simulator.

Still need to fix warnings in test/cctest/test-assembler-mips64.cc

**Comment by dusmil** [comment]
Fixed.
