### ISSUE TITLE
Different cache-flush code for glibc and bionic

### ISSUE THREAD

**Issue by kalmard** [v8mips/v8mips#8]
In cpu-mips.cc:
# if defined(ANDROID)

  // Bionic cacheflush can typically run in userland, avoiding kernel call.
  char *end = reinterpret_cast<char *>(start) + size;
  cacheflush(reinterpret_cast<intptr_t>(start), reinterpret_cast<intptr_t>(end), 0);
# else  // ANDROID

  int res;
  // See http://www.linux-mips.org/wiki/Cacheflush_Syscall.
  res = syscall(**NR_cacheflush, start, size, ICACHE);
  if (res) {
    V8_Fatal(__FILE**, **LINE**, "Failed to flush the instruction cache");
  }
# endif  // ANDROID

This is obviously not a huge issue, but perhaps unifying these may make future maintenance easier.
A comment on this from Paul:

"syscall will work on all sub-arch, but is slower (by a little) than using userland mips32r2 "isync" instruction to flush, which gcc has buildtin for"

Also note an issue on the website referenced in the comment: "The current implementation ignores the addr and nbytes parameters. Therefore always the whole cache is flushed. ".

**Comment by paul99** [comment]
I don't think its worth unifying these for seveal reasons: previous measurements did not show significant diff between kernel call, and userland isync. (Of course it might make sense to re eval on current hardware). 

On android we ran into several hardware devices that did not support isync correctly, for at least a couple different reasons.  This was conrollable on android system builds, but would be very difficult to modify or even test properly with random different toolchains being used on different vendors hardware.

I dont think its worth the risk, unless we find compelling perf diff in some situation. Closing.
