### ISSUE TITLE
Fix & optimize li()

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#80]
The li() macro needs both bug-fixing and optimization.
### Bugs

li() sometimes loads an incorrect value, if we just use li(reg, Operand(value)). We do not fully understand all the failure scenarios, but some are definitely related to sign-extension. (I suspect some issues are related just to improper C++ data types, where sign information may get dropped thru bad casting or assignment.)

In specific cases, we use `CONSTANT_SIZE` to force li() to emit all 6 (!) instructions. We noted all these special cases with TODO comments in the code. Examples: 

from code-stubs-mips64.cc:5478

```
  // TODO(plind): Fix li() so we can use constant embedded inside And().
  // __ And(regs_.scratch0(), regs_.object(), Operand(~Page::kPageAlignmentMask));
  __ li(at, Operand(~Page::kPageAlignmentMask), CONSTANT_SIZE);
  __ And(regs_.scratch0(), regs_.object(), Operand(at));
```

The problem there is that the constant `~Page::kPageAlignmentMask` must sign-extend and it does not do that correctly by default.

Similar from full-codegen-mips64.cc:

```
  __ li(scratch1, Operand(~kSmiTagMask), CONSTANT_SIZE);
```

Similar from lithium-code-gen-mips64.cc:

```
  __ li(result_reg, Operand(kMinInt), CONSTANT_SIZE);  // TODO(yy)
```

I think there is something incorrect with the size-based test routines, like `is_int64_32()`, `is_int64_16()` not detecting negative numbers properly.

When fixing this, please include a set of li() test cases in cctest/test-macro-assembler-mips64.cc with all these cases covered.

The names themselves `is_int64_32()`, `is_int64_16()`, etc.,  are not good and these should be renamed.
### Optimization

Six instruction li() seems insane, but I've not found a better sequence of instructions.

```
lui(rd, (j.imm64_ >> 48) & kImm16Mask);
ori(rd, rd, (j.imm64_ >> 32) & kImm16Mask);
dsll(rd, rd, 16);
ori(rd, rd, (j.imm64_ >> 16) & kImm16Mask);
dsll(rd, rd, 16);
ori(rd, rd, j.imm64_ & kImm16Mask);
```

However, one optimization is that addresses in mips64 (and in x64 for use with simulator) have only 48 significant bits. The upper 16 bits are always zero.

So when the above _bug_ is fixed we can change the legitimate use of `CONSTANT_SIZE` (for patchable pointers) to the 4-instruction sequence:

```
lui(rd, (j.imm64_ >> 32) & kImm16Mask);
ori(rd, rd, (j.imm64_ >> 16) & kImm16Mask);
dsll(rd, rd, 16);
ori(rd, rd, j.imm64_ & kImm16Mask);
```

That change will require changing _all_ the code patching sequences.

Also, please note the non-constant-size versions of li() often degenerate to 4 instructions, due to two instructions seemingly required just to sign-extend a value!!

It would sure be awesome for someone to find some better ways of doing these common operations. Maybe we should study some gcc-generated code, as those folks must know all the tricks.

**Comment by paul99** [comment]
A bit more: in macro-assembler-mips.cc in MacroAssembler::EnsureNotWhite() at line 5679 I have a workaround to move `~kObjectAlignmentMask` out of a And() Operand(), but that li() works without needing `CONSTANT_SIZE`.

Later in the file in MacroAssembler::AllocateTwoByteString() there is a usage of 

```
  And(scratch1, scratch1, Operand(~kObjectAlignmentMask));
```

I do not know if that works, or if it is a bug that was not found yet.

My notes have the hypothesis that maybe `li(t8, Operand(~kObjectAlignmentMask));` works since the signed number fits in int16_t. However that does not make sense with the presumably broken example of ~kSmiTagMask from above.

I think the right answer is to create lots of test cases in cctest/test-macro-assembler-mips64.cc and look a code generated.

(And, test-macro-assembler-mips64.cc does not exist yet, so you will need to create that and add it to build system)

**Comment by dusmil** [comment]
The bug in li() macro fixed. New test added.
The commit a44c6d8 is on dm-mips64 branch.

The next commit will be optimization for address loading.

**Comment by dusmil** [comment]
Optimization is done. The patch is on the branch,
Tested thoroughly on simulator in debug mode, and HW release (cctest, mjsunit).

**Comment by paul99** [comment]
This is long-completed, closing.
