### ISSUE TITLE
Which mipsbe branch would you suggest?

### ISSUE THREAD

**Issue by ffissore** [v8mips/v8mips#82]
I see `dm-dev-mipsbe`, `dm-mipsbe-3.14` and `dm-mipsbe-rebase`. Which one would you suggest to pack nodejs using v8 as a shared library?

**Comment by dusmil** [comment]
Hi Frederico,
I suggest stable and older version that is upstreamed to Debian community in case you need soft-float support for running on MIPS routers without FPU. It can be found on dm-mipsbe-3.14 branch. Also recently the BE support has been officially upstreamed to Google branch, and now BE support is part of all future versions of v8. So, if you need latest code you can get it from google bleeding_edge,  "gbl" branch on our github repo.

**Comment by ffissore** [comment]
Thank you! I'll use 3.14 then
