### ISSUE TITLE
Deserializing snapshot crash on MIPS64

### ISSUE THREAD

**Issue by dusmil** [v8mips/v8mips#83]
Running d8 with snapshot crashes for MIPS64 in bootstrap phase.
The problem is d8 cannot even be started when snapshot is on.

```
#
# Fatal error in ../src/spaces.cc, line 2664
# CHECK(CountTotalPages() > 1 || size_in_bytes <= free_list_.available()) failed
#

==== C stack trace ===============================

 1: V8_Fatal
 2: v8::internal::PagedSpace::SlowAllocateRaw(int)
 3: v8::internal::PagedSpace::AllocateRaw(int)
 4: v8::internal::Heap::ReserveSpace(int*, unsigned char**)
 5: v8::internal::Deserializer::Deserialize(v8::internal::Isolate*)
 6: v8::internal::Isolate::Init(v8::internal::Deserializer*)
 7: v8::internal::V8::Initialize(v8::internal::Deserializer*)
 8: v8::internal::Snapshot::Initialize(char const*)
 9: ??
10: v8::V8::Initialize()
11: v8::Locker::Initialize(v8::Isolate*)
12: v8::Locker::Locker(v8::Isolate*)
13: v8::Shell::InitializeDebugger(v8::Isolate*)
14: v8::Shell::Main(int, char**)
15: main
16: __libc_start_main
17: ??
```

It appears problem is in snapshot size which exceeds 1MB, which is strange.
Data of required memory from snapshot.cc:

const byte\* Snapshot::context_raw_data_ = Snapshot::context_data_;
const int Snapshot::context_new_space_used_ = 0;
const int Snapshot::context_pointer_space_used_ = 140744;
const int Snapshot::context_data_space_used_ = 688;
const int Snapshot::context_code_space_used_ = 0;
const int Snapshot::context_map_space_used_ = 12816;
const int Snapshot::context_cell_space_used_ = 0;
const int Snapshot::context_property_cell_space_used_ = 19040;
const int Snapshot::new_space_used_ = 0;
const int Snapshot::pointer_space_used_ = 350600;
const int Snapshot::data_space_used_ = 390288;
const int Snapshot::code_space_used_ = 627936;
const int Snapshot::map_space_used_ = 6120;
const int Snapshot::cell_space_used_ = 3360;
const int Snapshot::property_cell_space_used_ = 0;
const int Snapshot::size_ = 1264772;
const byte\* Snapshot::raw_data_ = Snapshot::data_;
const int Snapshot::raw_size_ = Snapshot::size_;

**Comment by paul99** [comment]
Here is the data for a mips32.debug build at mips64:eea7dfe10

```
const byte* Snapshot::context_raw_data_ = Snapshot::context_data_;
const int Snapshot::context_new_space_used_ = 0;
const int Snapshot::context_pointer_space_used_ = 70372;
const int Snapshot::context_data_space_used_ = 344;
const int Snapshot::context_code_space_used_ = 0;
const int Snapshot::context_map_space_used_ = 7120;
const int Snapshot::context_cell_space_used_ = 0;
const int Snapshot::context_property_cell_space_used_ = 9520;
const int Snapshot::new_space_used_ = 0;
const int Snapshot::pointer_space_used_ = 189112;
const int Snapshot::data_space_used_ = 260992;
const int Snapshot::code_space_used_ = 464480;
const int Snapshot::map_space_used_ = 3400;
const int Snapshot::cell_space_used_ = 1680;
const int Snapshot::property_cell_space_used_ = 0;
const int Snapshot::size_ = 916748;
const byte* Snapshot::raw_data_ = Snapshot::data_;
const int Snapshot::raw_size_ = Snapshot::size_;
```

The surprising one to me is the code size expansion. We would expect the data sizes to be double. The code-size issue that I'm aware of is li() now generating 6-instructions, where mips32 generates only 2. But the code_size expanded by 35%!

**Comment by xwafish** [comment]
Looks like fixed with https://github.com/paul99/v8m-rb/commit/734fd31b749d7eb4541db4e5928e883c6c069ba1

**Comment by paul99** [comment]
I confirm the fix so far on simulator runs. This is great news! 

I just ran release mode mjsunit on sim, with snapshots on. 5 failures, 1 was timeout.

I probably won't get this pushed to mips64 until tomorrow.

**Comment by paul99** [comment]
Fix is in mips64 branch, and verified. Closing.
