### ISSUE TITLE
Failure on pidigits benchmark

### ISSUE THREAD

**Issue by dusmil** [v8mips/v8mips#84]
The pidigits benchmark  fails on mips32 HW and simulator for arguments larger than 840, which is number of digits of PI number that is calculated in benchmark.

The benchmark is part of web-shoutout benchmark group used in chromium project.
https://code.google.com/p/web-shootout/

On other architectures including the ARM simulator this benchmark executes correctly for arguments more than 2000.

Here is the failure log.

```
5346908302      :820

6425223082      :830

5334468485      :840

biginteger.js:76: TypeError: Cannot read property 's' of undefined
function abs(o) { return (o.s<0)?negate(o):o; }
                             ^
TypeError: Cannot read property 's' of undefined
    at abs (biginteger.js:76:28)
    at bnpMultiplyTo (biginteger.js:190:23)
    at multiply (biginteger.js:310:49)
    at pidigits (pidigits.js:29:38)
    at unnamed:1:1
```

The benchmark can be extracted as standalone JS files:
The required files to run with d8 shell from source are pidigits.js and biginteger.js.
Function  "PidigitsBenchmark" should be put under comments.

Command to run it with d8 shell:

out/mipsel.release/d8 pidigits.js  biginteger.js  -e "pidigits(850)"

**Comment by dusmil** [comment]
This bug is somehow GC related and the behavior indicates it is in crankshafted code.
When benchmark is run with gc_global or nocrankshaft flag, it always passes.

All versions for 3.21 to 3.26 of v8 are affected by this bug.
Interestingly, The 3.20.17.23 version works.

I managed to narrow the search when d8 stopped working between 3.21.4 and 3.21.5.
Even better I have single commit after which the failure occurs. 
it is 8b76a60c7857de8e34d7e7be5fa35cfd7b0676cf.

Unfortunately, in this commit there is no single line of MIPS specific code. Everything has been done in hydrogen, so I believe this only triggers the bug in MIPS code that is somewhere else.

**Comment by dusmil** [comment]
The last findings showed me the problem is related to ICs, this can be proved if flag --nouse-ic is passed. Then the benchmark passes every time.  I narrow it by disabling ICs one by one, and came to the point that only if usage of UpdateCaches is disabled everything is working.

```
index a8d3527..066bfb0
--- a/src/ic.cc
+++ b/src/ic.cc
@@ -1718,7 +1718,7 @@ MaybeObject* StoreIC::Store(State state,
              IsUndeclaredGlobal(object)) {
     // Strict mode doesn't allow setting non-existent global property.
     return ReferenceError("not_defined", name);
-  } else if (FLAG_use_ic &&
+  } else if (0 &&
              (lookup.IsNormal() ||
               (lookup.IsField() && lookup.CanHoldValue(value)))) {
     Handle<Code> stub = strict_mode == kStrictMode
@@ -1746,7 +1746,10 @@ void StoreIC::UpdateCaches(LookupResult* lookup,
```

I traced it further and saw the JS stack was corrupted on MIPS after 840 iteration of bench or after 15670 multiply calls. Considering the fact, the stack layout for JS almost does not depend on arch specifics, the difference in stack frames is clearly a problem.

The MIPS stack at the point when multiply is called:

```
  0xf7496db0:  0x42b16ec9 1118924489 (0x42b16ec9 <JS Global Object>)
  0xf7496db4:  0x42b2e125 1119019301 (0x42b2e125 <JS Function stop_fun (SharedFunctionInfo 0x42b18a35)>)
  0xf7496db8:  0x42b25d2d 1118985517 (0x42b25d2d <JS Function multiply (SharedFunctionInfo 0x42b18acd)>)
  0xf7496dbc:  0x22bccc39  582798393 (0x22bccc39 <JS Array[0]>)
  0xf7496dc0:  0x42b25d2d 1118985517 (0x42b25d2d <JS Function multiply (SharedFunctionInfo 0x42b18acd)>)
  0xf7496dc4:  0x42b25c91 1118985361 (0x42b25c91 <FixedArray[28]>)
  0xf7496dc8:  0xf7496ef0 -146182416 (smi -73091208)
  0xf7496dcc:  0x2955df54  693493588 (smi 346746794)
  0xf7496dd0:  0x42b25d71 1118985585 (0x42b25d71 <JS Array[1]>)
  0xf7496dd4:  0x22b5da09  582343177 (0x22b5da09 <JS Array[1099]>)
  0xf7496dd8:  0x42b16ec9 1118924489 (0x42b16ec9 <JS Global Object>)
  0xf7496ddc:  0xbeeddead -1091707219
  0xf7496de0:  0x22b19159  582062425 (0x22b19159 <String[2]: 10>)
  0xf7496de4:  0x22b19159  582062425 (0x22b19159 <String[2]: 10>)
  0xf7496de8:  0x22b080a1  581992609 (0x22b080a1 <JS Array[1098]>)
  0xf7496dec:  0x22bc40c9  582762697 (0x22bc40c9 <JS Array[1099]>)
  0xf7496df0:  0x000015d0       5584 (smi 2792)
  0xf7496df4:  0x00005744      22340 (smi 11170)
  0xf7496df8:  0x22b6f9c9  582416841 (0x22b6f9c9 <JS Array[1099]>)
  0xf7496dfc:  0x22b5da09  582343177 (0x22b5da09 <JS Array[1099]>)

```

Arm stack:

```
 0xf7437e74:  0x57d16ec9 1473343177 (0x57d16ec9 <JS Global Object>)
  0xf7437e78:  0x57d2c67d 1473431165 (0x57d2c67d <JS Function stop_fun (SharedFu
  0xf7437e7c:  0x57d2a2cd 1473422029 (0x57d2a2cd <JS Function multiply (SharedFu
  0xf7437e80:  0x2df9f7e9  771356649 (0x2df9f7e9 <JS Array[0]>)
  0xf7437e84:  0x57d2a2cd 1473422029 (0x57d2a2cd <JS Function multiply (SharedFu
  0xf7437e88:  0x57d24171 1473397105 (0x57d24171 <FixedArray[28]>)
  0xf7437e8c:  0xf7437ef4 -146571532 (smi -73285766)
  0xf7437e90:  0x49349d80 1228184960 (smi 614092480)
  0xf7437e94:  0x2df9f775  771356533 (0x2df9f775 <JS Array[1]>)
  0xf7437e98:  0x2df482f5  770999029 (0x2df482f5 <JS Array[1099]>)
  0xf7437e9c:  0x57d16ec9 1473343177 (0x57d16ec9 <JS Global Object>)
  0xf7437ea0:  0x00000014         20 (smi 10)
  0xf7437ea4:  0x54e08091 1423999121 (0x54e08091 <undefined>)
  0xf7437ea8:  0x2df964c9  771318985 (0x2df964c9 <JS Array[1]>)
  0xf7437eac:  0x0000574c      22348 (smi 11174)
  0xf7437eb0:  0x2df9f775  771356533 (0x2df9f775 <JS Array[1]>)
  0xf7437eb4:  0x000015d2       5586 (smi 2793)
  0xf7437eb8:  0x57d24255 1473397333 (0x57d24255 <JS Array[10]>)
  0xf7437ebc:  0x2df87cd1  771259601 (0x2df87cd1 <JS Array[1099]>)
  0xf7437ec0:  0x2df7950d  771200269 (0x2df7950d <JS Array[1099]>)

```

This ''beaddead" value of stack slot worries me, and it indicates the frame is corrupted somewhere before. 
Interestingly, executing without crankshaft the stack layout at exact same point is correct and matches one on ARM. The only thing that might logically connect GC related behavior, StoreIC usage, and no crankshaft behavior at the moment is possible bug in write barriers from the optimized code.

**Comment by dusmil** [comment]
All  writer barriers checked and they are correct. In fact  the observed behavior is opposite to expected behavior with failures caused by missing write barriers. The more GC interval I reduce the test is passing, instead of provoking failure sooner.

Also I got other contradicting or inconclusive information. I have forced  generic stub for all StoreICs, and the test still fails.  When set  ICs to use uninitialized or megamorphic stub it passes.  This can be connected to GC dependent behavior and explained by the fact the ICs are flushed after full GC cycle and their state is returned to uninitialized again. It looks like the bug should be in optimized code since  there is no failure with nocrankshaft flag, and this tells me only it is not a bug in IC MIPS specific code. But, if I force always-opt flag the benchmark executes without failure.

From the stuff above it might be concluded that registers used in optimized function are clobbered in IC code which is called from optimized code. Unfortunately, the code for generic stub and uninitialized stub is the same and it ends into call of a runtime function. 

All concurrency related stuff as cause is excluded ( --noparallel-sweeping disabled,, etc ).
Also disabling IC flushing does not prove the theory, because the failure still occurs.

Furthermore,  forcing de-optimization  every 40 GC cycles makes the benchmark executed correctly. It seems we do not deoptimize somewhere we should for the specific set of collected types in unoptimized code .

**Comment by dusmil** [comment]
The bug was introduced in 9d0b7165.

The fix for this is submitted.
https://codereview.chromium.org/300853002/

**Comment by paul99** [comment]
Could you elaborate a bit on how the 'at' register was corrupted? It's not obvious at a glance, and be nice for us all to learn from this pattern.....

**Comment by paul99** [comment]
I committed this as r21540. But I would like to understand additional details before we close this issue. Thanks!

**Comment by dusmil** [comment]
Obviously, this is not obvious as it is simple.

If the right operand of MinMax lithium instruction is stack slot or argument the EmitLoadRegister(right, at) will load right value into 'at' register which may be returned as operation result. In the next step Branch is performed with conditions which will force `slt at, left_reg, at`  to be emitted, where right operand is overwritten  which would be returned as the result.

**Comment by paul99** [comment]
this was landed upstream and merged to mips64. Thanks! closing.
