### ISSUE TITLE
x64 is broken on our mips64 branch

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#88]
x64 compiles, but segfaults on running d8.

x64 was fine on our base commit 48e0ff6eb91ed598c8339da2be663e2e6e64c3c2.

Please find the bad commit, and let's fix it. We should run the tests on all arch's after fixing this.

Also, while cleaning up, arm no longer builds due to 1fe50472899ae1131c3790ea1fa9b05b864e8ad1. When back porting changes from ahead of us in gbl, we should port the code to all arch's. Please fix this also.

Two reasons: 1). It keeps the code working if we need to compare something on another arch, 2) more importantly, it will make the work for the porting team easier if we merge entire commits from upstream. Otherwise they will  have to piece things together, slowing their work.

**Comment by xwafish** [comment]
why segfaults on running x64/d8:
here is the cause commit:
https://github.com/paul99/v8m-rb/commit/d658872c13f05297d4ca5a39b84f3c91bc691ea4

in src/flag-definitions.h, I changed code_comments flag to true, and never change it back later.

change it to false, x64/d8 works ok. and x64/d8 --code_comments --prin_all_code also works ok.

**Comment by xwafish** [comment]
Fixed ：
https://github.com/paul99/v8m-rb/commit/734fd31b749d7eb4541db4e5928e883c6c069ba1

**Comment by paul99** [comment]
This is fixed in 1d2f82c4 on mips64 branch. Closing.
