### ISSUE TITLE
argc is corrupted on simulator entry

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#92]
When Simulator::Call() is entered and we collect the arguments off the stack, the argc value is valid bits in the lower 32-bits, but garbage in the upper 32-bits.

Yuyin provided a workaround for this in builtins Generate_JSEntryTrampolineHelper(), and I've updated the TODO there:

```
Label loop, entry;
// TODO(plind): At least on simulator, argc in a3 is an int32_t with junk
//    in upper bits. Should fix the root cause, rather than use below
//    workaround to clear upper bits.
__ dsll32(a3, a3, 0);  // int32_t -> int64_t.
__ dsrl32(a3, a3, 0);
```

But I do not see this kind of thing on the other arch's nor any special handling in the Simulator::Call().

I have not checked real hardware on this, but I suspect that per the ABI we would have a valid int64 value in the a3 register (for argc param)

Priority 3, since we have a workaround in place.

**Comment by dusmil** [comment]
Fixed in https://codereview.chromium.org/695933002/.

**Comment by paul99** [comment]
Landed as r25043. Closing.
