### ISSUE TITLE
Save non-obj values as pairs of Smi's in debugger

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#93]
In debug-mips64.cc, Generate_DebugBreakCallHelper(), we use the 32-bit code for saving non-obj values, and we should save them per the other 64-bit arch's as pairs of Smi's.

I added a new TODO in my working branch, pl-mips64-gbl.

**Comment by xwafish** [comment]
done, https://github.com/paul99/v8m-rb/commit/6420f0eb4b03053b9c86223bef64a83b0d4b85a6
Please take a look at it.

**Comment by xwafish** [comment]
sorry, there has a mistake in the pacth, I have re-push.:https://github.com/paul99/v8m-rb/commit/c98b552a7d4bff964232307c3cd92abe9502d9b7
thanks dusmil.
