### ISSUE TITLE
Cpu core revision and FPU mode detection

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#97]
Dusan, thanks for your CL https://codereview.chromium.org/618193005/. I have LGTM'd this, however, there are some additional steps we should take **before** landing it. 

**Item 1: CPU core revision id.**

The FP NaN type is not a good way to differentiate r6 from pre-r6. One reason is that r5, including in-development Apache core, uses IEEE 2008 NaN encoding. Also, as you pointed out, Qemu uses 2008 NaN everywhere, and it would be ideal to differentiate r6 and < r6 in qemu directly.

Rich F suggested a nice trick:

The new r6 branch-on-overflow instruction (BOVC) _re-uses_ the major opcode for the pre-r6 ADDI instruction (add-immediate and trap on overflow). Note that the BOVC internally does the add, but discards the result, whereas the ADDI writes the result to `rt` register.

```
         +------+-----+-----+----------------+
 ADDI    |001000|  rs |  rt |  16b immediate |   rt = rs + immediate
         +------+-----+-----+----------------+
 BOVC    |001000|  rs |  rt |  16b offset    |   rs & rt are unmodified
         +------+-----+-----+----------------+
```

This code will set v0 = 0 on r6 cpu, and will set v0 = 1, on rev 1 .. 5, and on MIPS-II:

```
__ mov(v0, zero_reg);
__ addi(v0, v0, 1);  // In r6 this encoding is: bovc(v0, v0, 1).
```

We guarantee by the inputs to never trap (< r6), or never take the branch (r6).

An important issue is to find the right way to encode this so the inline-assembler does not complain, even when the -mips32r6 flag is passed to it.

**Item 2: Identify FPU mode: fp32 or fp64.**

There is a longer-term problem with doing the FP mode ID using `mtc1` to `f1` register, as in your current CL.

Apparently, there is enough cause for concern about backwards compatibility of O32 software that may not be recompiled, that there is work underway to have r6 cores **trap** on single-precision read/write to odd numbered registers, and kernel FP emulation to do fixups. For example, an `mtc1 t0, f1` could be trapped and kernel could do the operations to move that 32-bit value to the high half of `f0`, via `mthc1` instruction.

None of this is in place today, but the plans are developing, including definite support for trapping these instructions in hardware. If this was in place, then your mode ID as written would fail. (Note that there will be some way to defeat this trapping on a per-process basis, via the kernel, but it is all fuzzy in details right now.) And sorry for all this new information, I just learned about this stuff myself today.

Another mechanism that should work fine on all MIPS cores is to read the FP Implementation Register (FIR), using the `cfc1` instruction, and check bit 22, which is the `F64` bit. This is fully readable from user-land.

The potential problem here is I do not know if this register is implemented in Broadcom r1 cores, or Loongson cores. I suspect it _is_ in the 3A chip, but we would need to verify this.

If the register is _not_ implemented, it might always return 0, which would be ideal, as we would then treat this as fp32. This needs testing.

It is _also_ possible to combine this with the NaN testing you did, since any core that returns 2008 NaN is _guaranteed_ to be new enough to also have the FIR register. (I hope this is not necessary.)

**Item 3: other notes on the existing CL.**

I was concerned that use of the assembler directive `.set oddspreg` would fail with older toolchains. It does actually fail, for example with 4.7.2 (Mentor/Code Sourcery 2012.09-43 release), prints error messages from the assembler, but ignores the operation and goes on (even though we set -Werror, I guess assembler warnings don't count):

```
/tmp/ccqM5Wi1.s: Assembler messages:
/tmp/ccqM5Wi1.s:25: Warning: Tried to set unrecognized symbol: oddspreg
/tmp/ccqM5Wi1.s:314: Warning: Tried to set unrecognized symbol: oddspreg
```

Steve Ellcey thought that this was probably OK to use, but he emphasized that we should test all combinations of -mfp32, -mfp64, and -mfpxx on systems with fp32 and fp64 modes in hardware. This seems like a good idea for any scheme we use.

**Timing**

A final item to think about is timing of changes. If all of this is easy to implement and test, then let's update the CL soon, and land it. If this will take some time, should we land some/all of the existing CL as an interim step? Right now, I cannot think of what is critically dependent on this in the short term. Other than our desire to test fpxx C++ code in issue 95, which can be done with local changes.

**Comment by dusmil** [comment]
**Regarding item 1:** Great idea, we could implement this.

**Regarding item 2**:  Sadly, these problems come from our desire and requirement to implement runtime detection in v8 in advance even before final spec are finished, available HWCAP feature support and  final decisions about compatibility handling in kernel are made.

We had same warnings during testing with older toolchains. The problem is they do not recognize set oddspreg directive, but they do not complain about odd single FPU register usage either. The good part is that compilation is not broken.

**Regarding timing:** There is no rush for submitting CL, we should wait and implement proposed idea and do further improvements and testing.

**Comment by paul99** [comment]
Dusan updated the CL (r 24486 ) to use the r6 detector (above), and to keep the same fp64 detector using f1 register (which can be fooled by FRE traps, but still works). This will need to be updated again in the future when all the HWCAPs and FRE stuff is finalized. But this is good for now. Closing.
