### ISSUE TITLE
Fix multiple MIPS64 fails due to r 24737

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#99]
From Ákos today on slack: https://v8m.slack.com/archives/bugs/p1413995881000013

There's a lot of (about 210) new test failures in buildbot in the MIPS64 target release job. I was able to reproduce these failures on our side, so I've started investigate. The tests fail with bus error and it is introduced by r24737 (https://codereview.chromium.org/663023002).

**Comment by palfia** [comment]
Fixed by https://codereview.chromium.org/682673002

**Comment by paul99** [comment]
Fixed. Closing.
